### ISSUE TITLE
Some PostgreSQL weirdness on my end

### ISSUE THREAD

**Issue by srcr** [idno/Known#1001]
I just pulled the latest version to get PostgreSQL support working and be able to stop myMySQL instance, but trying to get this running (and the data across) was kinda tricky and in the end I keep banging into the following error: 
--- from messages
Aug  5 21:46:14  postgres[]: [2-1] ERROR:  syntax error at or near "update" at character 17
Aug  5 21:46:14  postgres[]: [2-2] STATEMENT:  with upsert as (update config
Aug  5 21:46:14  postgres[]: [2-3]                                 set uuid=$1, entity_subtype=$2, owner=$3,
Aug  5 21:46:14  postgres[]: [2-4]                                 contents=$4, search=$5 where _id=$6 returning *)
Aug  5 21:46:14  postgres[]: [2-5]                                                     insert into config
Aug  5 21:46:14  postgres[]: [2-6]                                 (uuid, _id, owner, entity_subtype, contents, search)
Aug  5 21:46:14  postgres[]: [2-7]                                 select $1, $6, $3, $2, $4, $5 where not exists (select * from upsert)

--- from php-fpm.log
[05-Aug-2015 21:46:14] WARNING: [pool www] child  said into stderr: "NOTICE: PHP message: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "update""
[05-Aug-2015 21:46:14] WARNING: [pool www] child  said into stderr: "LINE 1: with upsert as (update config"
[05-Aug-2015 21:46:14] WARNING: [pool www] child  said into stderr: "                        ^"

**Comment by kylewm** [comment]
What version of Postgres are you running? The CTE syntax ("with ...") is apparently only available in 9.1 and up.

**Comment by srcr** [comment]
psql (PostgreSQL) 9.0.22
So what you say Is i need to move to a higher version ?

**Comment by kylewm** [comment]
I'll defer to @mapkyca, if you want to support the PG 9.0 branch, we probably just need to revert https://github.com/idno/Known/commit/c23a136a8a1bd4c810980b69d5f3aabad54af040

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1001" class="u-in-reply-to"></a>According to their release table (http://www.postgresql.org/support/versioning/) 9.0 is EOL as of next month, so I'm tempted to say we keep it as is.

@srcr I'd suggest updating, for multiple reasons. If that isn't possible, try one of the other engines (mysql is the "blessed" engine, and mongo and sqlite are there and fairly low maintenance). 

Or, you could revert the branch in your fork to replace the UPSERT with separate insert/update calls.

**Comment by srcr** [comment]
Thanks for the response, I'm currently in the process of upgrading to version 9.4.4 (latest and greatest) which is a challenge all on it's own. I think when this is done I'll try to do the migration again. I'll keep you posted on the progress.

**Comment by mapkyca** [comment]
Closing for now, since I assume that the upgrade went ok :)
