### ISSUE TITLE
Error while attempting to edit a post.

### ISSUE THREAD

**Issue by andrejstefanovski** [idno/Known#1003]
I pulled the Known-master.zip a few days ago and since then '../IdnoPlugins/Text/' has not been changed.

I attempted to edit a post and got "Fatal Error: /var/www/IdnoPlugins/Text/templates/default/entity/Entry/edit.tpl.php:24 - "Call to a member function getURL() on a non-object", on page social.andrejstefanovski.com/entry/edit/13ce8d8ce32ca26070331d867ddc68af"

Screenshot, if needed:
![screen shot 2015-08-06 at 5 21 20 am](https://cloud.githubusercontent.com/assets/6420626/9108414/e845a784-3bfb-11e5-9b9a-3acee8f253fe.png)
Let me know if I screwed something up on my end or anyone needs more info.

andrej

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1003" class="u-in-reply-to"></a>Seems to work for me, but let me know if this is still a problem for you.

Try updating with the latest packages if so.
