### ISSUE TITLE
Post Privacy Settings don't change on update

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1012]
So I was going through my posts manually changing them from Public to Members-Only so that I can switch my site from Members-Only to Public when I noticed that some post types do not update.

'Locations' and 'Tracks' (plugin) do not update and remain Public.
'Photos' and 'Status Updates' do update and become Members-Only.

**Comment by benwerd** [comment]
I'm not sure about the tracks plugin! Where is that from?

Locations is now fixed though.

On Thu, Aug 13, 2015 at 1:05 AM, Mark Waters <notifications@github.com>
wrote:

> So I was going through my posts manually changing them from Public to
> Members-Only so that I can switch my site from Members-Only to Public when
> I noticed that some post types do not update.
>
> 'Locations' and 'Tracks' (plugin) do not update and remain Public.
> 'Photos' and 'Status Updates' do update and become Members-Only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1012>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by markwaters** [comment]
I found the Tracks plugin here - http://docs.withknown.com/en/latest/plugins/community/
I'll put a bug report in for it too.
The Location / Checkin fix is working for me , thanks @benwerd
