### ISSUE TITLE
Post : html code in <code> block

### ISSUE THREAD

**Issue by danito** [idno/Known#1024]
I try to post some php code in a post. The code is surrounded by < code > < /code > tags but when displayed it is retransformed into real html and does funny things to the page.
See  http://nixis.me/2g
My code : 

``` php
echo "<pre>";
$boite1 = 345; 
$boite2 = 199;
$resultat = $boite1 + $boite2;
echo "Notre calcul: ".$boite1." + ".$boite2." = ".$resultat;
echo '</pre>';
```

The source code in the editor shows this : 

``` html
<blockquote>
<p><code>echo "&lt;pre&gt;";</code><br /><code>$boite1 = 345; </code><br /><code>$boite2 = 199;</code><br /><code>$resultat = $boite1 + $boite2;</code><br />
<code>echo "Notre calcul: ".$boite1." + ".$boite2." = ".$resultat;</code><br />
<code>echo '&lt;/pre&gt;';</code></p>
</blockquote>
```

But on the site it is finally : 

``` html
<blockquote><p>
<code>echo "<pre>";</pre></code><br /><code>$boite1 = 345; </code><br />
<code>$boite2 = 199;</code><br />
<code>$resultat = $boite1 + $boite2;</code><br />
<code>echo "Notre calcul: ".$boite1." + ".$boite2." = ".$resultat;</code><br /><code>echo '';</code>
</p></blockquote>
```

Somewhere the htmlentities are reversed.
##

**Comment by obra** [comment]
I'm still seeing this on 0.8.5.  https://s.ly/2014/how-to-reboot-an-arduino-leonardo-micro-into-the-bootloader demonstrates the issue.

**Comment by benwerd** [comment]
This is frustrating: both TinyMCE (the current editor) and our previous editor automatically convert HTML entities. Looking at a fix now. It may be that we jam this open specifically for HTML within <code> tags.

**Comment by physcocode** [comment]
Bump! this hasn't fix  yet?

**Comment by sctincman** [comment]
I wonder if this occurs when it is read from the database: I inserted HTML tags that were encoded using the basic text editor and it still was rendered in the final post. I also used the Markdown editor with Markdown source that was properly escaped, but this gives the same result.

Markdown:
```
'''
<section class="slide referenced">
    <h2>A slide</h2>
    <p>This sentence makes a reference to some thing<cite id="key" /></p>
    <footer class="bibliography"></footer>
</section>
'''
```

Manually using cmark generates this HTML output:
```
<pre><code>&lt;section class=&quot;slide referenced&quot;&gt;
    &lt;h2&gt;A slide&lt;/h2&gt;
    &lt;p&gt;This sentence makes a reference to some thing&lt;cite id=&quot;key&quot; /&gt;&lt;/p&gt;
    &lt;footer class=&quot;bibliography&quot;&gt;&lt;/footer&gt;
&lt;/section&gt;
</code></pre>
```

Loading this raw HTML in a browser renders as expected. However, if this same text is inserted as basic input into a Known post, the encoded tags are interpreted as raw HTML upon loading.

**Comment by mapkyca** [comment]
Old ticket, but seems to have been resolved.
