### ISSUE TITLE
Annotation breakage of unknown origin on Mongo

### ISSUE THREAD

**Issue by misuba** [idno/Known#1025]
Ooops! MongoCursorException

localhost:27017: The dotted field 'http://theha.us/2015/untitled-1/annotations/90f36d222a02574abb5e5faded0be7a8' in 'annotations.like.http://theha.us/2015/untitled-1/annotations/90f36d222a02574abb5e5faded0be7a8' is not valid for storage.

This is on clicking "like" on anything, or submitting a comment. 

It doesn't count on the title, I've tried it with several things.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1025" class="u-in-reply-to"></a>Looks like this might be a dupe of #447

**Comment by misuba** [comment]
![featured-tableflip](https://cloud.githubusercontent.com/assets/25656/9526379/d72a1176-4c9d-11e5-80c8-66aef6d77c25.png)

**Comment by kylewm** [comment]
Could we close this one and rename the other one something that indicates the problem is with dotted fields in newer versions of Mongo?

**Comment by kylewm** [comment]
Merged with #447
