### ISSUE TITLE
Editing Post Privacy Settings

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1026]
When I click edit on a 'Status' the privacy setting is shown as Public or Members only correctly.

When I do the same on a 'Photo' it defaults back to Public no matter what its original setting.

**Comment by benwerd** [comment]
Are you on the latest photo plugin code? This was an issue but was corrected before the most recent release.

**Comment by markwaters** [comment]
I think so , I am using the latest git release , currently 76129e3

**Comment by funwhilelost** [comment]
I'm having the same issue with bookmarks on v0.8.5 - every time I edit the privacy setting goes back to "Public"
