### ISSUE TITLE
Default Post Privacy

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1027]
It would be nice to be able to set the default post privacy value for each type , e.g.
 * Status = Public
 * Location = Private
 * Photos = Members Only

Perhaps this could be merged with the 'Homepage Content' page as a table ?

**Post**.............**Privacy**..................**FrontPage**
*Status*..........Public....................Yes
*Location*......Private...................No
*Photos*........MembersOnly........Yes

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1027" class="u-in-reply-to"></a>Agree.

**Comment by benwerd** [comment]
I'm inclined to say this should be a plugin - or that each content type should remember its last privacy setting. The alternative is an unreasonably complicated configuration screen.

**Comment by benwerd** [comment]
Closing this - I don't think we'll do it in core, but it would still make a great plugin.
