### ISSUE TITLE
XSS issues with Known API

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1028]
There are a number of issues with how the api currently works that exposes XSS vulnerabilities:

* [x] After a successful HMAC auth, the user is logged in, this session must be destroyed after page has been processed, otherwise subsequent calls from embedded pages could be processed
 * [x] We need an after page hook which we can log out and destroy the session for api users
* [x] Due to the way the API forwards rather than returns in a single page (#595) we currently have to short circuit hmac validation otherwise the 302 to the new object will fail. This means all subsequent HMAC validation is bypassed. We should stop doing that.
 * Additionally, 302 is also an ambiguous message to send, since it doesn't state success or failure, just "go here". My current thinking is that forward() should be disabled in API, and instead return 200 (or an error), and forward() sets a special header, e.g. 'X-KNOWN-API-NEXT' which lets the api retrieve the newly created object with a new set of hmacs.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1028" class="u-in-reply-to"></a>I'm actually pondering whether using a header, and so sending the next object out of band, is a good way.

Wondering whether we should return a json value for api forwards, e.g. {forward: *url*}

What are your thoughts @benwerd?

**Comment by benwerd** [comment]
I'm actually wondering if the API shouldn't swallow the redirect itself internally, and just return the object. It'd require some changes, but in effect, you'd just simulate the GET call.

**Comment by mapkyca** [comment]
I'd rather not, since you're not necessarily going to be in a create->redirect. For example, retrieving a post via a short url but being redirected to the long - this case you'd want to preserve the forward so we can keep the canonical URL.

**Comment by mapkyca** [comment]
Also seemingly the api was implemented to be as close to "web" behaviour as possible...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1028#issuecomment-135818179" class="u-in-reply-to"></a>Additionally:

1) Swallowing the redirect and returning the object will create a behavioural exception for creation events (vs. other api calls)

2) You'd create a case where an object will have URL of https://example.com/status/edit, rather than it's canonical address

3) You'd lose any parameters on forward

4) If you implemented it by literally simulating the GET via web services, you'd lose the session - i.e. you'd get a 403 when accessing a protected object.
