### ISSUE TITLE
Flag abuse

### ISSUE THREAD

**Issue by mapkyca** [idno/known#1033]
There needs to be an abuse reporting tool to flag and report abusive/inappropriate/spam content and accounts.

Although we're not meant to discuss the hosted solution here, this tool needs to handle the hosted solution and report to some central authority when run in multitennant.

Basically, *.withknown.com is being spammed to buggery..
##

**Comment by tantek** [comment]
See research into existing "report abuse" methods / UIs: http://indiewebcamp.com/report_abuse 

And recent 2015-08-28 spam example from Freenode # knownchat:

``` https://opportunityforseoexpert.withknown.com/ ```

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1033" class="u-in-reply-to"></a>Further, the report tool should allow for links and screenshots to be attached as evidence.

Further further (although not necessarily in this ticket) - report post/account is a good start, especially to handle spam accounts, however it might not handle gaters and similar hate campaigns, so I'm starting to think that shareable blocklists might be a way to go.

withknown.com could publish publicly a database of accounts it blocks, and individual knowns can publish similar, either publicly or with friends through access controls.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1033" class="u-in-reply-to"></a>Further further further, it'd be cool if there was some MF2 available for "blocked account", which we could use to automate the process. 

Perhaps we could riff off the existing user markup...

**Comment by mapkyca** [comment]
Going to close this for now. I think this is probably a plugin thing...
