### ISSUE TITLE
Tags from Instagram broken

### ISSUE THREAD

**Issue by davidmead** [idno/Known#1042]
Seems the latest updates have "broken" tags being passed from Instagram. They are being put back into the title, instead of the caption.

<img width="778" alt="screen shot 2015-09-10 at 9 46 59 pm" src="https://cloud.githubusercontent.com/assets/1266930/9805291/86167716-5805-11e5-94fe-262270e490f4.png">

http://blog.davidjohnmead.com/2015/washed-rosie-campbowwow-vscocam-365daysofme-x6-dog

**Comment by davidmead** [comment]
Added my code from https://github.com/davidmead/IndiePub/commit/04d66b8e160c26dbe5e71643db6dcc4ec1e4ea42, back into endpoint.php. Seems to have added back the `u-syndication` links from Instagram posts.

**Comment by kylewm** [comment]
fixed by #1193!
