### ISSUE TITLE
Markdown not respecting backslash escape

### ISSUE THREAD

**Issue by davidmead** [idno/Known#1043]
Now I have to cut & paste tags from the title of [syndicated Instagram posts](https://github.com/idno/Known/issues/1042), I noticed the markdown editor isn't respecting the [backslash escape](http://daringfireball.net/projects/markdown/syntax#backslash) for the '#' when posting.

<img width="456" alt="screen shot 2015-09-10 at 9 52 48 pm" src="https://cloud.githubusercontent.com/assets/1266930/9805372/4f9c4ba6-5806-11e5-82eb-5285f0249934.png">

Though it looks fine when editing and using the preview.

<img width="434" alt="screen shot 2015-09-10 at 9 53 50 pm" src="https://cloud.githubusercontent.com/assets/1266930/9805386/72e6edfa-5806-11e5-8b25-0acca9504063.png">

**Comment by physcocode** [comment]
which markdown editor are you talking about ?

**Comment by kylewm** [comment]
That's a good point, @physcocode. There's no markdown editor in core. Maybe this was an issue with https://github.com/mapkyca/IdnoMarkdown? Closing for now. Feel free to reopen if I've misunderstood.

**Comment by benwerd** [comment]
More likely this editor: https://github.com/idno/markdown

I suspect it's in the parsing rather than the editing. But will take conversation over there.
