### ISSUE TITLE
Thought: Break out tags

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1044]
So, entities used to have a tags field, which is no longer used, in favour of #tags .

Thought: Make use of this field and populate it on save with all #tags found in the post (optionally modify output template to not display this field).

Reason; for folk who like tag clouds etc, this'll make such a query possible to run.

**Comment by rhiaro** [comment]
Coming at posting with a wordpress mindset, totally wasn't obvious to use #tags to tag posts (even though I'm a heavy twitter user) and had to find this issue to realise! So for people who aren't used to tagging this way, it might also be useful to have a separate tags field in the UI.

**Comment by benwerd** [comment]
We actually had a tags field for a while. I'm wondering if it could be an option.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1044#issuecomment-164331281" class="u-in-reply-to"></a>All the code is there, it's just removed from the form. 

My first point is that we also populate this field by mining #tags from the body to populate this as well. Splitting these makes it a little easier to query.

**Comment by mapkyca** [comment]
Seems to have been closed by 1f70e0a
