### ISSUE TITLE
Bookmarks to Facebook : accents not decoded in FB post

### ISSUE THREAD

**Issue by danito** [idno/Known#1045]
When sharing an url as bookmark, if you put some text with french accents in quote, accents are decoded.
See https://nxd4n.nixekinder.be/2015/dans-un-carnet-la-journe-sans-voiture-a-nexiste-pas and https://www.facebook.com/DanielNix/posts/10206917959204942

**Comment by danito** [comment]
BTW if you syndicate a bookmark to FB, the link to your FB post doesn't show up under your known post.

**Comment by benwerd** [comment]
This is a larger problem, which I've filed as #1062.

**Comment by benwerd** [comment]
This is fixed in the latest Facebook plugin code.
