### ISSUE TITLE
Handle split replies toggle in UX rather than data model

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1056]
From comments on 7e8e546bc004002b2f869101291c796e2a1c6832, the ability to hide the fact that replies and updates are split should be handled in the UI, not the data model (which causes some rather nasty problems).

Suggestions would be to have the ability to group content types in dropdown and homepage management (with the ability to toggle separately in the management console), and then have the search pull out based on that.

**Comment by mapkyca** [comment]
Thought... 

How about having the homepage management "types", as they currently are, be entirely abstract and user defined (with sensible defaults)? These groups would be what appears on the dropdown.

You could then have the Content Types as they're provided by the plugins be little widgets that you'd drag and drop into each of these type groups.

So, in this scenario, you could have a type group "Short message", which would default to containing "status messages" and "replies to other sites", but a power user could split these off into their own "status" and "reply" type groups (bonus points if you could drag a Content Type to an empty spot and it create a new type group based on that for you.

The Homepage search would then just work pretty much as it currently does - all it'd need to do is flatten the array of enabled content groups, run a Unique over it and render the result.

Thoughts?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1056" class="u-in-reply-to"></a>Any thoughts on this @benwerd? Might have a crack at implementing it if you think this is a good approach....

**Comment by mapkyca** [comment]
This is being commented on in the wild, I think we definitely need to revert 7e8e546

**Comment by tinokremer** [comment]
+1 on mapkyca's suggestion
