### ISSUE TITLE
Images uploaded by Rich Text Editor in Content Type "Post" are not responsive.

### ISSUE THREAD

**Issue by drkokandy** [idno/Known#1058]
Expected behavior: I expected images in text posts to resize as the containers they are embedded within resize, which is something Bootstrap supports.

Actual behavior: Images in text posts are squished and warped by the containers.

Simple fix: Add Bootstrap class "img-responsive" to each image.

Example post with one non-responsive image and two responsive images: http://known.trdaisuke.com/2015/unexpected-image-behavior-in-known-content-type-post

The first image has not been touched from the rich text editor's defaults: 

    <p><img src="http://known.trdaisuke.com/file/acb51e2155bae0d58e50608e05132956" alt="Illya runs" width="1423" height="800" /></p>

The second image has removed width & height and just added class="img-responsive"

    <p><img class="img-responsive" src="http://known.trdaisuke.com/file/acb51e2155bae0d58e50608e05132956" alt="Illya runs" /></p>

On thee third image, I added the img-responsive class but didn't even bother to remove the height & width, but my browser nevertheless intelligently resizes the image:

    <p><img class="img-responsive" src="http://known.trdaisuke.com/file/acb51e2155bae0d58e50608e05132956" alt="Illya runs" width="1423" height="800" /></p>

So, even if you change nothing about how Known's rich text editor handles images in posts except adding class="img-responsive" to the image, images will resize within Content Type "Post" entries just like they do in Content Type "Photo" entries.

**Comment by benwerd** [comment]
This _should_ be fixed in the latest code. Thanks for highlighting though - this is probably a more elegant solution.

**Comment by drkokandy** [comment]
Thanks for the quick response - I will try this again on the next release & see if it works
