### ISSUE TITLE
Creating and editing slugs

### ISSUE THREAD

**Issue by ssundell** [idno/Known#1059]
Hi.

I've been testing a Known installation for a few days, and decided to import my Blogger data into Known database. Everything went fine apart from one thing: out of 140 posts, 60 had an URL that ended with "untitled-XXX".

After digging it a little bit, it seems that at least on my environment, `mb_strtolower` used in `Entity->prepare_slug` ended up doing some kind of a double encoding with incoming accented characters, which then resulted in unaccepted bytes in the input string for the following functions and the whole thing falling back to *untitled*.

This seems to be caused by a fail in detecting the internal encoding (I haven't yet checked what the application/PHP thinks the incoming string is), I just quick-fixed it by adding *UTF-8* as the character encoding for `mb_strtolower`.

Going forward, though, that only partly fixes the problem, since slug preparation just harshly removes non-ASCII characters. At best this results in unpronouncable URLs, but it may also result with confusion or, in some cases, another untitled post.

So, how about normalizing the accented characters into ASCII? Changing ä to a and ö to o is pretty standard practice for us Scandinavians, and there are tools to do that in PHP. Unfortunately it seems `iconv` transliteration depends on locale of the machine and may result with question marks. StackExchange suggests using Patchwork\UTF8 which does the transliteration properly. It would be very nice to get something like that for creating slugs.

... or at least default slugs. It would be even better if it was possible to edit the slug when creating a new post (or even better, also after posting, but it seems to be used stored in multiple places).

**Comment by benwerd** [comment]
+1 to this. This sounds like a really good idea, and I wasn't previously aware of Patchwork\UTF8. Thanks for the pointer!

**Comment by Chouchen** [comment]
+1, I got the same problem. URIs with "untitled" are pretty ugly and not SEO friendly.

**Comment by benwerd** [comment]
Slugs now allow unicode characters.

**Comment by Chouchen** [comment]
Can you point out the commit which manages it ?
