### ISSUE TITLE
share : missing indieWebContentType for reply

### ISSUE THREAD

**Issue by danito** [idno/Known#1061]
Hi,
since I pulled, in Idno/Pages/Entity/Share.php
$content_type = \Idno\Common\ContentType::getRegisteredForIndieWebPostType($share_type);
returns empty when $share_type == 'reply'.
The only change I could find is commit https://github.com/idno/Known/commit/78987851653bd59d53b203b8a71c339835cad468
Is this linked?

**Comment by benwerd** [comment]
Likely. This will be fixed soon.

**Comment by benwerd** [comment]
This should now be corrected. Can you confirm?

**Comment by danito** [comment]
Fixed
