### ISSUE TITLE
Bookmarklet not saving bookmark

### ISSUE THREAD

**Issue by leogaggl** [idno/Known#1074]
I've been using the bookmarklet previously and it seems to have stopped working after the most recent update. The issue seems to be related to the changed handling of the "Page Title" field.

When you create a bookmark using the "New Bookmark" function the "Page Title" field appears when entering a URL. When you supply this value the bookmark saves fine.

When trying the same via the Bookmarklet (/share?share_url=) and choosing bookmark the  "Page Title" field does not get exposed. When trying to save the bookmark the button shows a dotted outline and does not allow submit. I assume this is due to the  "Page Title" field being mandatory and not being sent. 

No error messages are shown.

Let me know if you need any screenshots or further explanations.

**Comment by leogaggl** [comment]
This has been resolved in one of the latest revisions. Closing

**Comment by leogaggl** [comment]
I have been able to replicate the issue again - it turns out the bookmarklet works fine with well-formed HTML pages. However if the page being bookmarked does not supply a HTML title the bookmarklet does not show the "Page Title" field.

**Comment by mapkyca** [comment]
Looks like it's actually a fault with the website itself being misconfigured; it's either a malformed chunked encoding or incorrect content-length.

Browsers tend to be rather liberal with what they accept, but libCurl is less so.

Also explains why it takes so long to retrieve...
