### ISSUE TITLE
Is PHP 5.6 Supported? Known throws errors or cannot function on Dreamhost (shared) with PHP 5.6

### ISSUE THREAD

**Issue by drkokandy** [idno/Known#1075]
Greetings,
As I've been working on writing up a guide to the Dreamhost shared hosting setup process, I'm noticing big snags getting set up if the domain/subdomain is configured to use PHP 5.6, and I'm not sure if this is a Known issue or a Dreamhost issue, or something else.

Using the latest official release
------------------------------------

Using 0.8.4, the installation halts completely after entering MySQL database information - saying "Oops! Can't connect to database"

On domains powered by PHP 5.4 or PHP 5.5, this error does not occur - registration proceeds normally.

Additionally, if you take a working Known installation on PHP 5.4 or 5.5 and set it to use PHP 5.6 in Dreamhost's Panel - **don't try this in production like I did :smile:** - many PHP errors will pop up, and all images will fail to display as if broken links. (I was able to recover by changing the PHP version back and replacing all Known files from the release zip.)

Using the live development build from github
------------------------------------------------

I also encountered errors on PHP 5.6 using the freshest bits cloned today with `git clone`.  On today's bits on 5.6, I can register, but after creating a user account, I arrive at a page full of nothing but errors before I get to the "write your bio" page. It also fails to function and displays only errors if I try to log in.

Using the same fresh bits from git, I encounter absolutely no errors on a fresh install using PHP 5.5.

For the purpose of the guide I'm writing, I'll recommend using PHP 5.4 or 5.5, but this might be something that you'll need to look for in troubleshooting if lots of folks start using Dreamhost, because Dreamhost will install PHP 5.6 by default now, unless you change that setting (I'll try to make it clear in the guide)

**Comment by benwerd** [comment]
PHP 5.6 is definitely supported - I'm using it right now! Checking into this as a priority, though.

**Comment by benwerd** [comment]
Could it be that some modules are missing in the PHP 5.6 configuration?

**Comment by drkokandy** [comment]
I figured it was most likely on their side. It's possible that Dreamhost is missing some modules on that configuration... but Known's auto checker reports all green on the PHP requirements on the warmup screen. Is there another way to test for missing modules?

**Comment by benwerd** [comment]
No, that should be it. Sorry for the inconvenience - I'll do some testing at my end with a new localhost site on 5.6.

**Comment by benwerd** [comment]
This should be fixed in 0.8.5. Please reopen if it's still not working for you.
