### ISSUE TITLE
Idno photo post not posting to twitter due to filesize (feature request / issue)

### ISSUE THREAD

**Issue by srcr** [idno/Known#1076]
As you can see in the attached picture an upload of a iPhone picture to known with forward posting to twitter fails due to filesize I think known should check this and resize the image accordingly.

![2015-09-23 09 37 36](https://cloud.githubusercontent.com/assets/1507320/10291134/4d7d63b8-6ba8-11e5-8603-d634d9da9027.png)
##

**Comment by benwerd** [comment]
It's actually pretty hard for us to resize images in-browser, particularly on mobile devices. This is, unfortunately, the kind of thing we need an app for.

**Comment by srcr** [comment]
Well I'm not stopping you :) Is there no possibility to do this in the PHP back-end?

**Comment by benwerd** [comment]
Apologies: I misread! It absolutely should be resizing the image on the back-end to send to Twitter. Please disregard my previous comment.

**Comment by benwerd** [comment]
Usually this means that the thumbnail couldn't be generated (that's what we sent to Twitter). Do you have the gd library enabled on your server? I'll test and make sure the mechanism is working in general.

**Comment by srcr** [comment]
Will do :)

**Comment by tinokremer** [comment]
I noticed the same issue the other day. It was with the latest Known (0.8.4). As I'm running on a shared server and I do not have shell access I do not think I can see the libraries available. I share photos from my phone regularly. I never saw that issue pop up before.

**Comment by danito** [comment]
I just tested it with a 6.2mb (4,208px × 3,120px) photo and it works for me (https://twitter.com/nxD4n/status/651413313952325632 - https://nxd4n.nixekinder.be/2015/souvenirs-dt). 
The error message might not be accurate as it just triggers when twitter refuses to accept the image for any reason. I'll check if I can update the plugin so we can have more info about the error message from twitter.

**Comment by srcr** [comment]
I haven't been able to check yet if the issue is solved or not. I did an update of the php-gd library to make sure that is working..

**Comment by funwhilelost** [comment]
It looks like the Twitter plug-in might be sending the raw original file, not a GD-resized version: `$bytes = \Idno\Entities\File::getFileDataFromAttachment($attachment)`.  Just a shot in the dark from browsing the code.

**Comment by kylewm** [comment]
I think the issue is that `Photo::thumbnail_id` changed to `Photo::thumbnail_large_id` in https://github.com/idno/Known/commit/7f666ad647f6cc2b7b0c8cb9e16496c8252bf0b5

I can't try it right this second, but I think it would just need to be changed around here https://github.com/idno/Twitter/blob/1306c50d4f877547766d1468c6b3ede9b3c65aeb/Main.php#L249

**Comment by kylewm** [comment]
Images on Twitter seem to be in the 1024 range (could somebody with a higher resolution confirm?) The largest thumbnail is 800px; maybe it's worth resizing the image specifically for upload?

**Comment by mapkyca** [comment]
Stale issue, is this still a problem?

**Comment by srcr** [comment]
I think the issues is fixed, can't recall that I hit this issue recently.. Sorry should have updated this earlier.

**Comment by mapkyca** [comment]
No worries!
