### ISSUE TITLE
Managing imported data in bulk? Or best to drop it all and start fresh? (possible ER)

### ISSUE THREAD

**Issue by emory** [idno/Known#1085]
This may be an enhancement request, but I imported a Wordpress export and realized that I had a lot of cruft from several years ago that I didn't really want around in my Known installation, but now I'm not sure how to best cull it because individually clicking 'delete' on hundreds? thousands? of posts seems like a good way to spend my time.

I looked in the database but realized I didn't know how consistency could be impacted.

It's a new installation but I did sign up for Convoy and I don't know if dropping and reinitializing my database would screw anything up there.
##

**Comment by akuckartz** [comment]
Suggestion: A bulk format using Activity Streams 2.0 might be useful.

**Comment by kylewm** [comment]
@akuckartz out of curiosity, import or export? what would you use it for?

**Comment by davidmead** [comment]
I need something like this sorted out.

I have a Wordpress blog that I've tried importing through Known and it just
never does anything. An old hosted version of Known that I can't find any
method of importing. and my current self-hosted Known site.

I'd love to move them all into one.


On Mon, Oct 26, 2015 at 1:37 PM, Kyle Mahan <notifications@github.com>
wrote:

> @akuckartz <https://github.com/akuckartz> out of curiosity, import or
> export? what would you use it for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1085#issuecomment-151220182>.
>



-- 
David Mead

http://twitter.com/davidmead
http://davidjohnmead.com
http://dmwebsites.com

**Comment by akuckartz** [comment]
@kylewm Both! The use case would be migrations between Social Web platforms.

**Comment by kylewm** [comment]
@emory the database schema is pretty resilient -- pretty much every object (users, posts, etc.) is stored in the `entities` table, as a JSON blob.

Each post will actually have two entities: an ActivityStreamsPost activity, and the object containing the content of the post.

If you are comfortable hacking around in SQL, you should be fine to just delete older rows from this table (after making a backup of course!)

**Comment by emory** [comment]
I lived dangerously and cleaned up without much hassle. Def should be something addressed in the UI for users at some point though, I can re-open as an ER or you can flag/change appropriately.

**Comment by benwerd** [comment]
Yes. I agree that bull posts in all contexts should have a better
interface.

Ben


On Tuesday, December 8, 2015, emory <notifications@github.com> wrote:

> I lived dangerously and cleaned up without much hassle. Def should be
> something addressed in the UI for users at some point though, I can re-open
> as an ER or you can flag/change appropriately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1085#issuecomment-163091520>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
