### ISSUE TITLE
feature request: auto update

### ISSUE THREAD

**Issue by jpcaruana** [idno/Known#1087]
Hi,

every time I update known, I have issues and have to rollback to previous version (see https://github.com/idno/Known/issues/979) (and I am very sad).

I also use piwik (https://piwik.org/, the open-source analytics plateform), and for each new release, I receive an email with an auto-update link. It works very fine every time. (I also remeber using wordpress with the same auto update feature)

This feature would be a great improvement in user experience.
##

**Comment by benwerd** [comment]
I agree with this. I'm not familiar with Piwik's system, but WordPress remotely logins in and updates files via FTP. We'll look into the possibilities - but I'd love community suggestions here.

**Comment by physcocode** [comment]
> But WordPress remotely logins in and updates files via FTP.

Little sceptical abut it my wordpress server has the FTP port firewalled can you plz elaborate?

**Comment by physcocode** [comment]
isn't this related to #256

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1087" class="u-in-reply-to"></a>Personally, I'm against auto-update in code. Basically, anything that lets you write files on the webserver which will be interpreted as executable is basically asking for pwnage.

That said we should investigate hooking into whatever package manager is on the system - apt or similar.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1087" class="u-in-reply-to"></a>... btw, that's one of the main reasons for having the data directory outside of the web root.

**Comment by mapkyca** [comment]
Calling time. 

Not sure this is something anyone has time to properly evaluate and build. 

Pull requests will of course be considered.
