### ISSUE TITLE
Search - AND not OR

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1091]
When I perform a search with two or more words the results are all the posts where any of the words are used.

I have tried queries like - 'word1 and word2' and '+word1 +word2'

Is there a way to perform an AND search and not the default OR search ?

**Comment by kylewm** [comment]
You're sort of subject to the whims of MySQL's full text search here. By default the full text search uses "natural language mode". If you're curious to try out [boolean mode](https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html) which seems more like what you're after, you could modify `Idno\Data\MySQL::build_where_from_array`

(I haven't tried this but) I think you'd just need to change the line

```php
$subwhere[] = "match (`search`) against (:nonmdvalue{$non_md_variables})";
```
to 

```php
$subwhere[] = "match (`search`) against (:nonmdvalue{$non_md_variables} in boolean mode)";
```

If you try it out and it's better or worse, let me know :)

**Comment by markwaters** [comment]
Thanks so much @kylewm for explaining that so clearly , that works perfectly!

**Comment by kylewm** [comment]
Oh awesome! This might be a cool thing to make configurable in config.ini

**Comment by benwerd** [comment]
@kylewm Indeed :) Added, and set by default.

**Comment by markwaters** [comment]
Great , thanks guys!
