### ISSUE TITLE
Photo posting is broken

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#1092]
Attempts to post a photo on desktop Chrome and Android fail with a message: "We couldn't access your image. Please try again." repeatedly and consistently.

Hosted version, paid account (yes, I do regret it already).

**Comment by kylewm** [comment]
Image upload is working for me on *.withknown.com, is the image you are uploading perhaps very large?

**Comment by benwerd** [comment]
We've had a few reports of this and are trying to track down the cause.
Would you mind sending us the image for testing? ben@withknown.com

On Friday, October 30, 2015, Kyle Mahan <notifications@github.com> wrote:

> Image upload is working for me on *.withknown.com, is the image you are
> uploading perhaps very large?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1092#issuecomment-152652718>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
We've pushed some changes to live. This may also be related to an issue we had earlier today with one of our web servers. We're watching it, but let us know if it reoccurs - and remember that as a withknown.com user you can always use the feedback button on your Known site to send us direct feedback for a faster resolution.

**Comment by nekr0z** [comment]
Works now with the very same picture (which wasn't particularly big, 1701x1080, 122 KiB JPEG).

**Comment by benwerd** [comment]
This turned out to be an issue with the export function (!) which wasn't cleaning up after itself and therefore clogged our servers.
