### ISSUE TITLE
post to FB broken

### ISSUE THREAD

**Issue by jpcaruana** [idno/Known#1093]
Hi,

I tried to post to FB (it used to work very fine so far), but it failed silently (ie no error on my page), but I had the following log: 

````
PHP message: Nothing was posted to Facebook: false" while reading response header from upstream, 
client: a.b.c.d, server: xxxx.xxx, request: "POST /status/edit HTTP/1.1", 
upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxx.xxx", referrer: "https://xxxx.xxx/"
````

Where should I investigate ?

**Comment by kylewm** [comment]
maybe your facebook access token has expired? did you try reauthorizing?

**Comment by jpcaruana** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1093" class="u-in-reply-to"></a>Thanks this worked fine. Too bad there is no way to know it expired.
