### ISSUE TITLE
Post Title to URL conversion create conflicts with bridgy

### ISSUE THREAD

**Issue by rygos** [idno/Known#1094]
Hello,
i posted a picture in my Known installation with the following title:
Tambourcorps Polos =)

The URL Known creates is:
/2015/tambourcorps-polos-

The last - is for the space between s and = i think.
The problem is, bridgy trys to connect to:
/2015/tambourcorps-polos

for this i get the following line in my apache error logs:
2015-11-05 10:00:42	Error	10.251.0.203	410	GET /2015/tambourcorps-polos HTTP/1.0

i think there are 2 possible solutions maybe more =):
Changeable url in Known or Known needs to check the last char in the created url.

Greetings and thx for you great work,

rygos

**Comment by kylewm** [comment]
This seems like a bug with Bridgy more than Known, right?

http://broxxer.de/2015/tambourcorps-polos-

**Comment by physcocode** [comment]
it can be solve either of the way

**Comment by kylewm** [comment]
Or both :) best reason to fix it in Known is trailing hyphen is not very pretty.

Filed a Bridgy issue: https://github.com/snarfed/bridgy/issues/541

**Comment by benwerd** [comment]
We'll fix the trailing hyphen too. Thanks for filing!
