### ISSUE TITLE
No profile pics from bridgy with Zero-byte Files on Server.

### ISSUE THREAD

**Issue by rygos** [idno/Known#1095]
Hello,
i have the following problem with my self hosted known Installation:

i have connected my Useraccount with bridgy and it works like a charm for text messages. but not for profile pictures.

URL to see what i try to tell:
http://broxxer.de/2015/swiftkey-auf-ipad-und-iphone-funktioniert-hervorragend#comments
The last comment is from my KnownAccount.

on my server in the Uploads directory, i have 2 files.
Filename: hash.data
Filedata: {"filename":"cd685210548b2d92d6415a8ff83b83c2","mime_type":"application\/octet-stream"}

Filename: hash.file
Without Filedata. Empty files.

The Only Error in apache-Logs, related to images are the following:
Loading Images-Error: getimagesize(): Read error! in /var/www/vhosts/broxxer.de/httpdocs/Idno/Entities/File.php

in the knownchat log files on github i found another guy with the same issue. i have ask him how to solve this problem but he doesnt know that. He changes his hosting provider.
But i'm my own hosting provider... =P

First i have installed 0.8.5 and i get this problem. after this, i updated to the newest git (head)

if you need more infomrmations feel free toll tell what. =)

Greetings and thx for this software,

rygos

**Comment by paulcmal** [comment]
Hey,

I'm guessing your problem could have to do with #753. Facebook could be returning a redirection with an empty body, leaving you with empty profile pics. I submitted a patch last night, could you try to update to the latest git version?

If your problem is unrelated to #753 and avatars are still not saved after the update, could you please provide your PHP version, and login on [Bridgy](https://brid.gy/) to provide one example log for a webmention?

**Comment by rygos** [comment]
i check this today. is it possible to force a reload for missing profile pictures?

**Comment by paulcmal** [comment]
> PHP Notice: Undefined index: location in /var/www/vhosts/broxxer.de/httpdocs/Idno/Core/Webservice.php on line 296

Looks like only Twitter sends "location" without any capital letters (the HTTP standard being "Location"). Can you try with this [Webservice.php](https://github.com/paulcmal/Known/blob/master/Idno/Core/Webservice.php) ([raw](https://raw.githubusercontent.com/paulcmal/Known/master/Idno/Core/Webservice.php))?

I modified the code to expect "Location" or "location" as a response from the server in case of a redirection.

> is it possible to force a reload for missing profile pictures?

The link to the original image does not seem to be kept. But in the *metadata* table in the database, there's an *annotations* entry for each post, containing the link to the original webmention (in the *known_from* part of *permalink*) and the link to the saved image (in *owner_image*).

So the answer is yes, but we'll need to write a piece of script for this.

**Comment by kylewm** [comment]
I think this was fixed when #753 was fixed.
