### ISSUE TITLE
Webmention avatars are (re-)stored every time

### ISSUE THREAD

**Issue by paulcmal** [idno/Known#1097]
When receiving a webmention, its author's avatar is stored as a new file every time.

For example, @snarfed's avatar on @benwerd's Known is at least stored two times:
- as [56267121bed7de853d47a858](http://werd.io/file/56267121bed7de853d47a858) in reply to http://werd.io/2015/untestable-unsafe-and-on-the-freeway-why-cars-need-to
- as [5628edd5bed7de3b07d8827a](http://werd.io/file/5628edd5bed7de3b07d8827a) in reply to http://werd.io/2015/help-me-debug-a-personal-project

This could turn very problematic on the long run for a Known instance receiving a lot of interactions, especially since each file I believe has its own entry in the database.

If there is a specific method for importing images from the web, it should keep track of previously downloaded images, and when triggered, check if the remote image has been modified. If so, we may in most cases want to save the new version as a new file. But dealing with avatars, we could just replace the old avatar with the new one, so that one person's avatar on the whole instance is the same.

If no such method exists, I think we should write one, as it could be useful for plugins.

What do you think?
##

**Comment by benwerd** [comment]
+1 to this. I think attaching profile images to profile URLs would be a smart way to go.

**Comment by snarfed** [comment]
actually you might want to consider hashing instead. bridgy uses "evergreen" URLs for some silos, eg facebook and twitter, so the images returned by the same URL can change over time. you probably don't want them getting stuck at the profile picture they happened to have when you first got a backfed response from them.

**Comment by paulcmal** [comment]
> I think attaching profile images to profile URLs would be a smart way to go.

Yes, but we need to be careful with Bridgy's webmentions:
- p-name does not necessarily correspond to a website run by the user (e.g. if a Twitter user has "google.com" as a URL in their profile) and different people might have the same URL in their profile
- p-name does not necessarily have a h-card, making it harder to coherently link different accounts together
- there may be conflicts between p-name's h-card and Bridgy's h-card made up with the silo data, and we don't want to change the profile picture every time the person posts from a different platform

So we'd need proper remote user/identity management to link different identities and accounts altogether.

In the meantime, Bridgy provides second u-url (without p-name class) with the URL to the silo's profile. So as a quickfix, we should take webmention's p-name as a reference when the interaction comes from the website directly, or the second u-url when it comes from Bridgy.

I've opened [a ticket](https://github.com/snarfed/bridgy/issues/543) on Bridgy's bugtracker, asking for the silo profile URL to be specifically tagged to make our job easier here. We would then just have to look at the *silo-url* of the webmention when it does exist, and otherwise fall back to p-name as a reference URL.

Also, we should keep in mind to strip the scheme from the URL, so that the corresponding avatar is the same file for both HTTP and HTTPS.

> actually you might want to consider hashing instead.

Yes.

To make my proposition more clear, when we receive a webmention:
- we take a reference URL (without the scheme) for our "remote profile", either silo-url when provided, or p-name otherwise
- if we don't have a corresponding profile picture, we download it and keep a hash of it
- if we do, we download the picture and compare hashes

This solution is far from perfect, as it uses a lot of bandwidth (downloading an image every time we receive a webmention is crazy). But as this is already Known's behaviour at the moment, I would call it a fair improvement.

What do you think?

**Comment by kylewm** [comment]
> we take a reference URL (without the scheme) for our "remote profile", either silo-url when provided, or p-name otherwise

Any reason not to use the URL of the image instead of the URL of the associated profile?

> as it uses a lot of bandwidth (downloading an image every time we receive a webmention is crazy)

If you store `Last-Modified` and `Etag` with the hash, it'll be easy to optimize this later (hopefully silos support one of these, I haven't checked!)

**Comment by benwerd** [comment]
I think it's worth investigating the image URL, and then falling back to @paulcmal's plan.

This is a fantastic conversation, by the way.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1097" class="u-in-reply-to"></a>Chiming in ('cos I wrote this bit)...

The hashes are a direct hash of the image URL, which is written to a file in the simplest way possible ;) If you're getting a new image each time it's because the actual url of the image in the webmention has changed (which I think @snarfed pointed out).

I did think about storing last modified/etags but wanted to get things running quickly and wanted to avoid storing accounting information on files where possible...

**Comment by paulcmal** [comment]
> Any reason not to use the URL of the image instead of the URL of the associated profile?

It depends on what we want to achieve. Using the image URLs as a reference would be perfect to just store the comments as we currently do, but it would be hard to build proper identity management on top of this.

We'd need unique identifiers that we can link together so that in the end a person posting from different platforms could have the same profile on our Known, with the same profile picture on every comment.

> If you're getting a new image each time it's because the actual url of the image in the webmention has changed

I don't believe so. Just take two of your own interactions on your blog ([1](https://mapkyca.com/2015/great-scott), [2](https://mapkyca.com/2015/fucking-us-letter-seriously)). Your Facebook picture appears to be the same yet two files are stored on your Known ([1](https://mapkyca.com/file/5624a7a3150ba0d75b699746), [2](https://mapkyca.com/file/5628188e150ba0813d68d5c9)).

I don't know if the URL has changed in this case, but here's another example from my own Known: two reshares

**Comment by paulcmal** [comment]
> Any reason not to use the URL of the image instead of the URL of the associated profile?

It depends on what we want to achieve. Using the image URLs as a reference would be perfect to just store the comments as we currently do, but it would be hard to build proper identity management on top of this.

We'd need unique identifiers that we can link together so that in the end a person posting from different platforms could have the same profile on our Known, with the same profile picture on every comment.

> If the URL changes when the profile image changes, then you're good. If it doesn't (evergreen urls @snarfed mentioned) then you fall back on hashing.

But how do you distinguish between the two cases when you just receive a webmention? I think we'd have to hash anyway.

> If you're getting a new image each time it's because the actual url of the image in the webmention has changed

I don't believe so. Just take two of your own interactions on your blog ([1](https://mapkyca.com/2015/great-scott), [2](https://mapkyca.com/2015/fucking-us-letter-seriously)). Your Facebook picture appears to be the same yet two files are stored on your Known ([1](https://mapkyca.com/file/5624a7a3150ba0d75b699746), [2](https://mapkyca.com/file/5628188e150ba0813d68d5c9)).

I don't know if the URL has changed in this case, but here's another example from my own Known: two reshares  from the same Twitter account ([1](https://cmal.info/2015/lobbyists-use-gop-debate-ads-to-smear-agency-investigating-their#comments), [2](https://cmal.info/2015/allemagne-block-npd-2015-#comments)) result in the same profile picture being saved twice ([1](https://cmal.info/file/4ca63359ce84027dc51a417bbbff4edb), [2](https://cmal.info/file/f9377e3902345c95e6cfb5dbbd6d07da)). Here are the two corresponding Bridgy webmentions ([1](https://brid-gy.appspot.com/repost/twitter/cmal_PP/664534493915664386/664534545337745408), [2](https://brid-gy.appspot.com/repost/twitter/cmal_PP/664501951992868864/664502026349342720)) where the profile picture has the same URL (there is a redirection but the end URL is the same as well).

> If you store Last-Modified and Etag with the hash, it'll be easy to optimize this later

Yes!!

**Comment by kylewm** [comment]
@mapkyca thanks for weighing in! It looks to me like the filename is initially a hash of the [user's profile URL](https://github.com/idno/Known/blob/master/Idno/Core/Webmention.php#L200), *but* all roads lead eventually to `$fs->storeFile` which generates [a new random ID](https://github.com/idno/Known/blob/717ca24531eab09775df94eb6cdef5db5a743b6d/Idno/Files/LocalFileSystem.php#L69) each time it's called. So saving the avatar twice with the same temporary filename would still result in two files on disk (right?)

For reference, here are the Bridgy sources for those webmentions
```
https://brid-gy.appspot.com/comment/facebook/100001501388539/965285526864818/965285526864818_965642580162446
https://brid-gy.appspot.com/comment/facebook/100001501388539/966600206733350/966600206733350_966717226721648
```
which have identical h-cards

```
  <span class="p-author h-card">
    <a class="p-name u-url" href="https://www.facebook.com/100001501388539">Marcus Povey</a>
    <img class="u-photo" src="https://graph.facebook.com/v2.2/100001501388539/picture?type=large" alt="" />
  </span>
```

**Comment by paulcmal** [comment]
Often only a thumbnail of the image is kept.

Is this the behaviour that we want? If so, we could store with the image we keep (whether it's a thumbnail or not) the hash of the **original** image, so that we can later check if the remote file has been modified.

**Comment by benwerd** [comment]
The bigger issue here is really that we can't search for files by filename. The result is that the obvious thing to do - just go find that hash and see if it exists - is almost impossible. I'm thinking that this is probably the thing to start with.

**Comment by paulcmal** [comment]
> The bigger issue here is really that we can't search for files by filename.

Isn't that what [File::getByUUID()](https://github.com/idno/Known/blob/master/Idno/Entities/File.php#L240)/[FileSystem::findOne()](https://github.com/idno/Known/blob/master/Idno/Files/LocalFileSystem.php#L19) is for? The problem is the filename given by storeFile in the end is [a random md5 hash](https://github.com/idno/Known/blob/master/Idno/Files/LocalFileSystem.php#L69).

But if we can have it store the file as the hash of the original URL when we're just downloading a file from the web, I don't think we have a problem anymore.

There's different ways to achieve this, depending on if we want to achieve backwards-compatibility (by just adding a "keep_name" parameter to createThumbnailFromFile, createFromFile and storeFile) or if we want to start afresh (always consider the "filename" passed to create(Thumbnail)FromFile as the name storeFile should use).

The second option would allow for more modularity: each plugin could have its own structure for filenames, and the name of the file could actually mean different things according to the context. And we wouldn't have [so many files](https://framabin.org/?021554e6390ea1c5#yDZ/vdZO8zLz2o69AJ/BrvFXNTh4lWSSl3ID5T/m6SQ=) to modify.

But the first option is way easier to implement as we'd just have to add a parameter to getIconFromWebsiteContent's calls to create(Thumbnail)FromFile() and then the file would keep [the name](https://github.com/idno/Known/blob/master/Idno/Core/Webmention.php#L200) @mapkyca was refering to.

So other parts of the code (like file uploads) would still have their random md5 names, but here the filename would be a hash of the URL we're downloading.

What do you think?
