### ISSUE TITLE
"Like" is not available as an option from `/status/edit` but it is from `/share`

### ISSUE THREAD

**Issue by funwhilelost** [idno/Known#1098]
I'm curious why you can't access the "Like" type from the main "Status Update" UI.  Maybe I'm misunderstanding how this works in Known.  Is a bookmark equivalent to a like?

`/share` shows you a status update UI with the option to choose like
`/status/edit` shows you a status update UI without like
`/like/edit` shows the UI for "New Bookmark"...

**Comment by kylewm** [comment]
ref: http://indiewebcamp.com/irc/2015-11-10/line/1447207358534

>18:02 benwerd kevinmarks: sorry, only just saw your comment. I did. We've found that "like" confuses people who aren't aware of the indieweb, so figuring out where to put that and how to make it clear is important.

**Comment by erinjo** [comment]
Hi @funwhilelost. Things have evolved over time, but in Known right now there are stars that can be favorited by other users, if you have a multi-user Known site. If you use your Known site with something like Bridgy, likes and hearts from Facebook and Twitter might also translate to your post as stars.

/share is the template for the browser bookmarklet. You should have options for Share - a status update with the current page's URL, Reply - add a comment if you're on a supported site, and Bookmark - save a link to the page you're on to your site. There also appears to be Like, which is actually a duplicate of the bookmark option and an error. That should be removed.

/status/edit is the template for editing the Status Update content type within your site. 

/like/edit is the template for editing the Bookmark content type within your site.

The post annotations, like comments and stars, appear in a separate template and aren't tied to any one content type.

As such, there isn't a specific "Like" type. Confusingly, if you're looking at the file directories, the bookmark plugin is in a folder called "like." That plugin is really for bookmarking a link though.

**Comment by funwhilelost** [comment]
@benwerd In regards to understanding the indieweb stuff: "In reply to", "Like", "RSVP", and "Bookmark" URLs should all be above the content.  This way you can communicate the intent of the share in one, consolidated location.

If it's at the top then you can progressively reveal or hide fields below it without unnecessarily interrupting the user (e.g. hide the body for a "like").  You can also make one, easy URL entry field.  Once entered, reveal a control to choose like/reply-to/rsvp/etc. (or even infer the action from the URL's microformats).

**Comment by funwhilelost** [comment]
@erinjo thanks for the thorough explanation.  I've been using Known solo so some of the semantics were a little beyond me.  I see the use cases you're describing now (and the misnomer with "like" in various places).

What I'm hoping for is just a simple way to take actions like `u-like-of`, `u-repost-of`, `u-in-reply-to` and also some basic webmentions for Brid.gy publish - `<a href="https://brid.gy/publish/facebook"></a>` - without having to write the HTML into the editor.

**Comment by funwhilelost** [comment]
I'll keep an eye out for the next release.  Also curious to see the new reader side of the app.

**Comment by danito** [comment]
BTW when you "favorite" a site with https://quill.p3k.io/favorite and post it on your known site you get a bookmark with the u-like-of and a fa fa-star-o in front of its title. It breaks a bit the layout (even it would be nice to have more of those icons in front of every title)
