### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by Phyks** [idno/Known#1099]
Hi,

I am having some issues with Known recently, getting errors like:
```
Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /home/www/known/Idno/Core/Webservice.php:245 - "Allowed memory size of 134217728 bytes exhausted (tried to allocate 72124767 bytes)", on page known.phyks.me/2015/velib-dataset
```

While trying to edit very basic articles such as http://known.phyks.me/2015/velib-dataset.

I did find a workaround by setting `memory_limit = 512M` in my `php.ini` (`128M` is the default), but this seems to be a really huge value.

Thanks

**Comment by benwerd** [comment]
It looks like the web services component isn't cleaning up after itself well. This is likely to be an issue with outgoing webmentions. Thanks for reporting; we'll take a look.

**Comment by mapkyca** [comment]
Going to close this as I've not been able to replicate the issue and others seem to be doing ok, so I'm guessing it's been fixed at some point. 

Let me know if it's still an issue for you and we can reopen the ticket.
