### ISSUE TITLE
Enhancement share/bookmark bookmarklet (feature request)

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1101]
I use the "Share" bookmarklet often to share webpages on my own Known site. I also use Pinboard.in for storing bookmarks, both for "Read later" purposes as general archiving. It would be useful to have a few more parameters on the share.php url, like:
- ACL; so I can bookmark private by default
- Confirm ; so I can hit the bookmarklet and the url is stored without clicking anything else
##

**Comment by funwhilelost** [comment]
:+1:

**Comment by benwerd** [comment]
I'm not sure I understand the second point? I agree that the first is important though.

**Comment by tinokremer** [comment]
When you bookmark a site using the bookmarklet you have to click the "Save" button. My pinboard bookmarklet has a "jump=close" parameter which causes it to automatically save the bookmark and close the dialog. That basically, even though it's a bookmarklet and another side is loaded in a temporary window, creates a *one click bookmark button*

**Comment by mapkyca** [comment]
Closing; first point about acls has been addressed. Not sure we can do anything about the second point, as I understand it, since it's third party...
