### ISSUE TITLE
On initial setup, the error message about AllowOverride could use a note about the change to make.

### ISSUE THREAD

**Issue by obra** [idno/Known#1105]
On initial setup, the error message about AllowOverride could use a note about the change to make.
Technical settings
Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to default.js, but got this response instead:

HTTP/1.1 404 Not Found
Date: Thu, 03 Dec 2015 19:30:35 GMT
Server: Apache/2.4.16 (Unix) PHP/5.5.27
Content-Length: 210
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /js/canary.js was not found on this server.</p>
</body></html>Technical settings
Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to default.js, but got this response instead:

HTTP/1.1 404 Not Found
Date: Thu, 03 Dec 2015 19:30:35 GMT
Server: Apache/2.4.16 (Unix) PHP/5.5.27
Content-Length: 210
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /js/canary.js was not found on this server.</p>
</body></html>

**Comment by kylewm** [comment]
@wholewheattoast and I ran into this too! I was going to come file an issue and then see it's already been fixed, so awesome :+1:

**Comment by tincho** [comment]
Hi there! Trying to deploy using Nginx, and inside a subdir... any workaround? Thanks!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/1105" class="u-in-reply-to"></a>I do wonder whether subdirs may be the cause of some other installs, i.e. #2238
