### ISSUE TITLE
RSS export not uploading to Wordpress

### ISSUE THREAD

**Issue by davidmead** [idno/Known#1109]
When I upload the exported RSS feed from my [self-hosted Known blog](http://blog.davidjohnmead.com), to Wordpress, it only accepts the first 10 posts, then stops with this error...

<img width="273" alt="rss-import-error" src="https://cloud.githubusercontent.com/assets/1266930/11675285/669d70e2-9df6-11e5-89f6-06272cfa3990.png">

If I then remove the first 10 `<item>`'s in the file it returns the same error, but stops further down in the feed.

<img width="280" alt="import_ _david_john_mead_ _wordpress" src="https://cloud.githubusercontent.com/assets/1266930/11675354/282524a8-9df7-11e5-97df-1b9441c25e71.png">

I'm using the [standard RSS Importer plugin](https://wordpress.org/plugins/rss-importer/) (version 0.2) by Wordpress. I have updated to WP4.4, but this problem was happening on the version before.

Any ideas?

**Comment by benwerd** [comment]
That's super-odd. If you eyeball the eleventh post in the feed, does it
look out of the ordinary? I do know that WordPress's RSS import is a bit
shaky - we had to jump through some hoops to make it acceptably import at
all.

On Tuesday, December 8, 2015, David Mead <notifications@github.com> wrote:

> When I upload the exported RSS feed from my self-hosted Known blog
> <http://blog.davidjohnmead.com>, to Wordpress, it only accepts the first
> 10 posts, then stops with this error...
>
> [image: rss-import-error]
> <https://cloud.githubusercontent.com/assets/1266930/11675285/669d70e2-9df6-11e5-89f6-06272cfa3990.png>
>
> If I then remove the first 10 <item>'s in the file it returns the same
> error, but stops further down in the feed.
>
> [image: import_ _david_john_mead_ _wordpress]
> <https://cloud.githubusercontent.com/assets/1266930/11675354/282524a8-9df7-11e5-97df-1b9441c25e71.png>
>
> I'm using the standard RSS Importer plugin
> <https://wordpress.org/plugins/rss-importer/> (version 0.2) by Wordpress.
> I have updated to WP4.4, but this problem was happening on the version
> before.
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1109>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
Closing since it looks like you were able to import the rest of your posts to http://davidjohnmead.com/blog ... Feel free to re-open if there is still an issue!
