### ISSUE TITLE
Add a URL preview engine

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1110]
Using Slack's unfurl rules:

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.c4k6p4inw

This could then be used by any plugin.
##

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1110" class="u-in-reply-to"></a>There's a very basic version of this in my open graph plugin for bookmarks, but I keep meaning to upgrade it.

**Comment by mapkyca** [comment]
Swinging back around to this... seems like the sort of thing that someone has written a nice javascript library to do. Anyone recommend something? Or are we left to writing from scratch...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1110" class="u-in-reply-to"></a>For my records, this might be useful: https://github.com/Ekito/bootstrap-linkpreview
