### ISSUE TITLE
Support facebook's emoji (or whatever they are)

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1115]
Minor thing, and not sure if it's a Known or a bridgy thing, but check the first comment from Chickensoup (https://mapkyca.com/2015/that-thing-when-you-get-home-so-tired-that-you#comments) which on FB contains a christmas tree icon, but is just a blank square on Known.

**Comment by kylewm** [comment]
It looks like a tree on Firefox on Android and Linux, maybe missing from your particular font?

An emoji -> image converter like Github/Twitter/Slack use would be a nice extension. "None around the forehead? 🎄"

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1115#issuecomment-166977384" class="u-in-reply-to"></a>Interesting... I only see a unicode placeholder (Ubuntu: firefox & chromium). I wonder what could be missing...

**Comment by mapkyca** [comment]
https://github.com/mapkyca/KnownEmoji :)
