### ISSUE TITLE
MongoDB authentication not working for Mongo 3+

### ISSUE THREAD

**Issue by FroznMine** [idno/Known#1116]
I try to use Known with MongoDB 3. For that I try to connect to the database with my credentials. The config.ini looks like that:
```
database = "MongoDB"
dbstring = "mongodb://Known:somePassword@127.0.0.1:27017/?authSource=Known"
dbname = "Known"
```
Now I try to connect and what I get is
```
Failed to connect to: 127.0.0.1:27017: Authentication failed on database 'Known' with username 'Known': auth failed
```
It looks like the password is wrong, but if I look into mongod's log I find:
```
2015-12-23T23:42:54.914+0100 I ACCESS   [conn25]  authenticate db: Known { authenticate: 1, user: "Known", nonce: "xxx", key: "xxx" }
2015-12-23T23:42:54.915+0100 I ACCESS   [conn25] Failed to authenticate Known@Known with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
```
It seems like the password isn't submitted. Trying with different users and databases didn't change the behaviour. It looks like MongoClient does not work correctly. Some research has shown that MongoClient is deprecated, MongoDB\Driver\Manager should be used instead.. Also MONGODB-CR isn't the standard in MongoDB 3 anymore.

Are there any solutions available for this? Am I doing something wrong? Is it planned to change to MongoDB\Driver\Manager in the future? 

Thanks for the help, I'm looking forward to be able to use Known!

**Comment by kylewm** [comment]
Some discussion on IRC a while back: https://github.com/mapkyca/KnownchatLogs/blob/a381b264e1b625f25e99d8707a27c2f82bdb4214/2015-12-23.md

Summary (to the best of my understanding): FroznMine "downgraded" his Mongo schema to work with the older authentication method (MONGODB-CR) Known uses

**Comment by kylewm** [comment]
May just be a doc change to require Mongo < 3

**Comment by kylewm** [comment]
I'd be curious to know if the changes in 2fd0bd963f500c1fec2f962c73f9db24abc84e05 fixed this for Mongo 3. Instead of passing paramters on the connection string, you can use dbuser, dbname, and dbauthsrc config params now. @FroznMine any chance you are still set up for testing?

**Comment by kylewm** [comment]
Tested this with Mongo 3.0.3 and it seems to work now, yay!
