### ISSUE TITLE
mention not printing?

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#1124]
I'm using latest version of the code.

Here is the use case:
 - I go to https://blog.indie.host/2015/the-new-blog
 - I use the firefox plugin to "share" from my own blog: https://microblog.pierre-o.fr/2015/the-new-blog-2015the-new-blog

1 thing strange happened:
 - I received an email saying that I received a mention
 - the mention is not showing here https://blog.indie.host/2015/the-new-blog

I guess it is not normal behavior, but maybe I'm missing something?
let me know if it is a bug or a normal behavior?

Thanks!

**Comment by pierreozoux** [comment]
I just realized the same behaviour from tumblr:
http://belp.audio/post/136334236777/new-indie-web-blog

I receive an email, but nothing is printed on my blog.

**Comment by benwerd** [comment]
What happens if you do a hard refresh? Some servers over-cache.

On Thu, Dec 31, 2015 at 10:28 AM, Pierre Ozoux <notifications@github.com>
wrote:

> I just realized the same behaviour from tumblr:
> http://belp.audio/post/136334236777/new-indie-web-blog
>
> I receive an email, but nothing is printed on my blog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1124#issuecomment-168232682>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by pierreozoux** [comment]
I restart my web/app server, and I hit ctrl-shift-R.
Where could the cache be besides that?

**Comment by kylewm** [comment]
I believe it's true that Known receives and stores simple mentions (i.e. replies that are not in-reply-to, like-of, or repost-of) but does not render them in [any of the default templates](https://github.com/idno/Known/blob/master/templates/default/content/feed/end.tpl.php#L76).

**Comment by kylewm** [comment]
btw, I'm seeing 503 Service Unavailable for https://microblog.pierre-o.fr/2015/the-new-blog-2015the-new-blog

**Comment by pierreozoux** [comment]
@kylewm yes you might be right :)
Thanks for alerting for the blog :)

(I wasn't sure if it was actually a bug or an expected behaviour)

But I just tried to repost this:
http://werd.io/2015/san-francisco-enough-is-enough-its-time-to-look-further

from here:
https://microblog.pierre-o.fr/2016/san-francisco-enough-is-enough-its-time-to-look-further

And no re-post mention.

I'm just wondering why printing twitter retweet, and no indie web repost? (Is twitter more important than indieweb ;) )

@benwerd can you confirm and close the issue please? (it still looks like a bug for me :) )

**Comment by kylewm** [comment]
[Your post](https://microblog.pierre-o.fr/2016/san-francisco-enough-is-enough-its-time-to-look-further) still just looks like a plain old mention to mf2 consumers. If you want it to be recognized as a repost, it needs `class="u-repost-of"` on the link to Ben's post. You can always use http://pin13.net/mf2/?url=https%3A%2F%2Fmicroblog.pierre-o.fr%2F2016%2Fsan-francisco-enough-is-enough-its-time-to-look-further to see what the parsed microformat results look like.

**Comment by kylewm** [comment]
Closing this one as expected behavor (simple mentions aren't displayed). Feel free to open if you disagree!
