### ISSUE TITLE
font-awesome generic share icon on u-syndication with Convoy

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1128]
I have been tinkering and may have broken something, but it looks to me like when syndicating a post via Convoy, the syndication link gets the default fa-share icon instead of the more specific fa-twitter icon (or fa-facebook, etc.)

![missing-font-awesome](https://cloud.githubusercontent.com/assets/950127/12133035/5a6d5bb6-b3d6-11e5-9aa5-57296c8008b2.png)

**Comment by mapkyca** [comment]
Still an issue?

**Comment by mapkyca** [comment]
Closing, since Convoy has been removed from the OS core
