### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by pierreozoux** [idno/known#1130]
I was bored this morning, so I optimized my blog :)

Don't take it wrong, but https://blog.indie.host/2016/i-beat-you-benwerd-speedpagespeedinsightsurlhttp3a2f2fwerdio2ftabdesktopspeedpagespeedinsightsurlhttp3a2f2fblogindiehost2fwe-just-need-to-fix-this :)

Could be ice if we could fix:

```
Eliminate render-blocking JavaScript and CSS in above-the-fold content
```

(I think it is more on the theme than known)

PS: I put it here not as a high priority but just as a nice to have optimization :)

**Comment by mapkyca** [comment]
Might be worth looking at #914 as part of this

**Comment by pierreozoux** [comment]
As a side note to the discussion here is the "optimized" nginx conf used:
https://github.com/indiehosters/known/blob/master/nginx.conf

**Comment by mapkyca** [comment]
Gonna close, a lot had been done by combining js and css
