### ISSUE TITLE
Image rotation broken?

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1137]
Tried to post a photo direct from my phone, and it failed to rotate. [See here](https://vaviblog.com/2016/morning-coffee-in-the-park-almost-springlike)

I have Photos 0.1 plugin enabled. The image has EXIF in it, and is from an iPhone.

Anything I can do to fix this?

**Comment by kylewm** [comment]
hmm, I double checked that exif-rotated images do still work for me for a random vertical iphone picture. Could you share the original of your image somewhere? It should work just to zip it (to prevent Github from resizing/embedding it like an image) and stick it in this issue.

**Comment by jeremycherfas** [comment]
Sorry, I was out of town. Here's that image, zipped.
[2016-01-12 09.43.25.jpg.zip](https://github.com/idno/Known/files/94032/2016-01-12.09.43.25.jpg.zip)

**Comment by kylewm** [comment]
Well I'm stumped. Uploading to my instance of Known seems to work correctly.

The thing is, the original *is not rotated*. The EXIF Orientation value is 1, so Known should not be rotating it at all.

```bash
kmahan@lemur:~/Downloads$ exiftool -Orientation -n 2016-01-12\ 09.43.25.jpg 
Orientation                     : 1
```

If Known did nothing and just stripped the EXIF, the image would look fine :( Is it possible some other app on your phone is rotating it before uploading?

**Comment by jeremycherfas** [comment]
I don't see how another app could be interfering; I just select it from Safari.

Unfortunately, I don't have control over which version of Known and plugins I am using, because I am hosted by IndieHost without access to update and so on. I'll see if I can check on that.

**Comment by benwerd** [comment]
I'll do some further checking in Safari for iOS. I think it may be trying
to do something clever with image rotation - which would be baffling and
annoying ...

On Monday, January 18, 2016, jeremycherfas <notifications@github.com> wrote:

> I don't see how another app could be interfering; I just select it from
> Safari.
>
> Unfortunately, I don't have control over which version of Known and
> plugins I am using, because I am hosted by IndieHost without access to
> update and so on. I'll see if I can check on that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1137#issuecomment-172632268>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by jeremycherfas** [comment]
OK, thanks. It is indeed annoying.


On Mon, 18 Jan 2016, at 08:45 PM, Ben Werdmuller wrote:
> I'll do some further checking in Safari for iOS. I think it may
> be trying
>
to do something clever with image rotation - which would be baffling and
>
annoying ...
>
>
On Monday, January 18, 2016, jeremycherfas <notifications@github.com> wrote:
>
>
> I don't see how another app could be interfering; I just select it
> from
>
> Safari.
>
>
>
> Unfortunately, I don't have control over which version of Known and
>
> plugins I am using, because I am hosted by IndieHost without access to
>
> update and so on. I'll see if I can check on that.
>
>
>
> —
>
> Reply to this email directly or view it on GitHub
>
> <https://github.com/idno/Known/issues/1137#issuecomment-172632268>.
>
>
>
>
>
-- 
> 
Ben Werdmuller
> 
<http://goog_1933028737>
> 
benwerd.com | werd.io
>  
> 
+1 (312) 488-9373
> —
> Reply to this email directly or view it on GitHub[1]. 


>  


Links:

  1. https://github.com/idno/Known/issues/1137#issuecomment-172632708

**Comment by benwerd** [comment]
Safari isn't the issue, but I just realized: could it be that you don't have PHP's EXIF support enabled on your server? This would cause the lack of rotation.

**Comment by jeremycherfas** [comment]
I'll try to find out. I don't manage the server myself.

Jeremy


On Fri, 29 Jan 2016, at 06:53 AM, Ben Werdmuller wrote:
> Safari isn't the issue, but I just realized: could it be that you
> don't have PHP's EXIF support enabled on your server? This would cause
> the lack of rotation.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/idno/Known/issues/1137#issuecomment-176585162

**Comment by mapkyca** [comment]
Have you checked the latest code, which contains an admin notification? 

Commit: acf6115b70fa0980643e624151e9bd39f177b75c

**Comment by pierreozoux** [comment]
There was indeed no [exif](https://github.com/indiehosters/known/commit/68cdb2f12c9c2e2031e92d335ac986cd7038b938), I think it is now fixed, I just updated your known to the latest code, please let me know @jeremycherfas if we need to further investigate?

@benwerd how can I PR http://docs.withknown.com/en/latest/install/requirements/ to add exif to the list?

**Comment by kylewm** [comment]
@pierreozoux It's here: https://github.com/idno/Known/blob/master/docs/install/requirements.md 

Thanks!

**Comment by physcocode** [comment]
oops i already opened a pull request on this !

**Comment by kylewm** [comment]
Sounds like this was fixed, we can reopen if Jeremy is still having a problem. Thanks all!

**Comment by edrex** [comment]
Image orientation still seems broken when I post photos to my Known 0.9.9 instance from my Galaxy S7. This build includes d990d8a AFAICT. I will update my site to the latest master and confirm if it is still an issue there.

Examples:

https://edrex.pdxhub.org/2018/tabor-at-night
(upside down)
https://edrex.pdxhub.org/2018/more-broken-image-previews-in-known

**Comment by edrex** [comment]
This is still an issue with the latest master. This is really a big deal, as I am using known as an instagram replacement and it is really embarrasing when pictures aren't rotated the right way in a post going out to twitter/facebook.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1137" class="u-in-reply-to"></a>Works for me on iphone. 

Could you place the original unmodified image somewhere we can access? This needs to be the unmodified original you uploaded that hasn't gone through any manipulation - so uploading to this ticket probably won't do the job.
