### ISSUE TITLE
support custom permalinks

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1139]
For a couple reasons, it would be nice to identify, uniquify, and look up posts by their full path e.g. "2015/jan-13-homebrew-website-club" rather than "jan-13-homebrew-website-club".

Primarily I'd like this so that I could then customize the path for imported posts. Posts on my site are YYYY/MM/slug, and I'd like to keep that. Rather than, or maybe in addition to, storing the slug, I would generate and store a full "path".

**Comment by kylewm** [comment]
Not that Wordpress is necessarily the platonic ideal... but I tried to look into how they do this a little. It appears that it more or less requires unique slugs across all posts, regardless of what the permalink format is. It makes some sense that it's safest to always have globally unique slugs since the rest of the structure might be changed later.

**Comment by kylewm** [comment]
Ghost also looks up posts by their globally unique slug and treats the optional YYYY/MM/DD fields as just decoration. OK I'm convinced that's the way to go, which is good because it's what Known already does!

So now I'd just like to make the permalink regex and the permalink generated by `Entity::getURL()` lightly customizable. First cut, this can be a toggle between

* YYYY/slug (default)
* YYYY/MM/slug
* YYYY/MM/DD/slug

with an eye to maybe some day let people define their own permalink path with like `/:type/:year/:slug`. Of course one complication will be avoiding ambiguous routes...

**Comment by benwerd** [comment]
This is a much-requested feature by people coming in from WordPress. It
might even be interesting to automatically maintain the slugs on WordPress
imports. In any event, I think this was an important thing to bring up.

On Saturday, January 16, 2016, Kyle Mahan <notifications@github.com> wrote:

> Ghost also looks up posts by their globally unique slug and treats the
> optional YYYY/MM/DD fields as just decoration. OK I'm convinced that's the
> way to go, which is good because it's what Known already does!
>
> So now I'd just like to make the permalink regex and the permalink
> generated by Entity::getURL() lightly customizable. First cut, this can
> be a toggle between
>
>    - YYYY/slug (default)
>    - YYYY/MM/slug
>    - YYYY/MM/DD/slug
>
> with an eye to maybe some day let people define their own permalink path
> with like /:type/:year/:slug. Of course one complication will be avoiding
> ambiguous routes...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1139#issuecomment-172226920>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
