### ISSUE TITLE
Onboarding: Site title seemingly ignored

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1147]
In /warmup/settings, I am prompted for a site title, but this never seems to make it through to the actual site when setup is finished. The site is always called "kylewm's Known" regardless of what name I gave it during setup.

The title should be saved in `$_SESSION['set_name']`, but I have a feeling it's being lost somewhere along the way.

I'm using Known from git with MySQL on nginx.

**Comment by physcocode** [comment]
+1 me to faced this issue
