### ISSUE TITLE
Remove inline Javascript

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1149]
We need to stop putting javascript in the template as it makes it harder to maintain, interferes with CSP and if it's dynamically produced is all to easy to end up with DOM based XSS attacks.

Move all this gumph into its own files.

**Comment by benwerd** [comment]
+1,000.

**Comment by kylewm** [comment]
Semi-related to #914 (Consider using require.js)

**Comment by physcocode** [comment]
Aint this covered under #1152 ?
