### ISSUE TITLE
Regression: Permalink regex may be too strict on number of digits

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1153]
Previously Known's permalink regex was (basically) `/\d+/\w+`, any number of digits allowed for the year. In my permalink structure changes, I made it `/\d{4}/\w+` (exactly four digits).

Unfortunately we were sort of relying on supporting very long numbers because [Facebook interprets years](https://github.com/idno/Facebook/issues/31) as user IDs and rewrites them to app-scoped user IDs. Some Harvard alum with the user ID 2016 gets rewritten to 10102571892817971 for Bridgy, so we see the URL

* https://tinokremer.nl/2016/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-hetlc

as

*  https://tinokremer.nl/10102571892817971/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-hetlc

Which used to work with the more relaxed regex.

We have some options:
* Bridgy (or Known) could hardcode a list of app-scoped IDs for Facebook users 2010-2020 or something, and fix permalinks on its end. On my old site I just added nginx rules to redirect 2014 and 2015.
* Known could go back to supporting years of any length in its permalinks
* Get rid of See Original links, which would fix the problem going forward but not for older posts.

cc: @tinokremer

**Comment by benwerd** [comment]
I've heard people who've set up their own Facebook app in recent times mention that it was rejected because they were using "see original" links. So they may not be long for this world anyway.

**Comment by kylewm** [comment]
OK I'll track this one in https://github.com/idno/Facebook/issues/31
