### ISSUE TITLE
Know Version .9 : still warning newer version .8.5 available

### ISSUE THREAD

**Issue by danito** [idno/Known#1165]
Hi,
when opening the site configuration, I get the alert that a newer version 0.8.5 is available, but I pulled the latest git updates and in about I have version 0.9.
Probably I have somewhere in my db a hardcoded version from when I installed it first.

**Comment by kylewm** [comment]
0.9 hasn't been released quite yet. I'm sure this message will go away when it is.

**Comment by benwerd** [comment]
This is correct. It does a very naive comparison -good reminder to redo it.

On Friday, January 29, 2016, Kyle Mahan <notifications@github.com> wrote:

> 0.9 hasn't been released quite yet. I'm sure this message will go away
> when it is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1165#issuecomment-176874247>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by physcocode** [comment]
0.9 has been released shouldn't we considered it fixed?

**Comment by danito** [comment]
Now I have the message about 0.9.1... 
![version](https://cloud.githubusercontent.com/assets/54977/12758581/3ea406ce-c9dd-11e5-9f68-e442435f8ea3.png)
In about I have still Version 0.9

**Comment by danito** [comment]
ok, after git merge everything is on 0.9.0.2

**Comment by benwerd** [comment]
Yes. Thank you for reporting this: I bungled the release. All should be well now.
