### ISSUE TITLE
Nested Facebook replies

### ISSUE THREAD

**Issue by trilliums** [idno/known#1172]
Not sure if this is a brid.gy issue (I did find [#502](https://github.com/snarfed/bridgy/issues/502) related to this, but it seems it was fixed and closed on brid.gy's end) or not or if it's even possible on Known currently, but Facebook's nested replies aren't showing up as such on this post: https://sensible.mn/2016/when-will-minnesotas-patients-see-prices-drop

Thanks!

**Comment by kylewm** [comment]
(That Bridgy issue was specifically about finding nested comments *at all*, which does seem to be working as they appear on your site)

I'm relatively sure Known doesn't do threaded comments at all. But if support for them was added, then there should be enough information in the backfed comment from Bridgy to arrange them into a thread: Comment1 is in reply to the original post, Comment2 is in reply to the original post *and* to Comment1.

**Comment by trilliums** [comment]
And this is why I shouldn't submit issues before I've fully woken up :-)

Thanks for the quick reply!

I'd really love to see Known implement threaded comments. Especially for posts like this, having comments nested would make a lot more sense for context.

**Comment by kylewm** [comment]
> And this is why I shouldn't submit issues before I've fully woken up :-)

All good! Your question/suggestion made perfect sense.

**Comment by benwerd** [comment]
Nested comments are a really interesting idea. We've had some feedback that they're more useful for people. (And certainly, better representing the FB comment structure would be good.) Making them mobile-friendly is a challenge, but hey, if Facebook can do it ...

**Comment by mapkyca** [comment]
+1 on this, as I'm getting a lot of backfeed nested comments from FB. Bridgy does pass the in-reply-to context as both the post and the comment id, so I think all we need is to scrape the comment ID and store that along side the comment.

That, and implement threaded comment support (#1482)

**Comment by mapkyca** [comment]
Closing, after facebook's api change
