### ISSUE TITLE
\Idno\Core\Logging should follow PSR-3 standards

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1177]
with reference to #1133 would be great for supporting multiple logging engine

**Comment by physcocode** [comment]
I was working on a PR for this just wanted to make sure are you interested in it @benwerd ?

any suggestions @mapkyca @kylewm ?

**Comment by kylewm** [comment]
@physcocode nice! I'd started working on this here https://github.com/kylewm/Known/commit/b103d49dc1d1ff38811079ba66a7b4facca99917 ... that was dependent on the Composer stuff and at the time I was thinking we'd include Monolog in core. But maybe that can save you the trouble of changing all the log() calls yourself.

One bit that I think is particularly useful: https://github.com/kylewm/Known/commit/b103d49dc1d1ff38811079ba66a7b4facca99917#diff-e3f0ea8006f55c95d9bf4d5e689e74caR176 maintains backward compatibility with the existing `log($message, $level);` method by detecting this case and reversing the parameters. In a future version, I think we should add a warning that this order is deprecated, and in an even later version remove it.

**Comment by physcocode** [comment]
@kylewm you made my day :) thats gonna save a lot of labour :+1:

**Comment by physcocode** [comment]
well this boosted my approach ill send a pull request in few hours :)
