### ISSUE TITLE
webmention to known fails after syndication from known

### ISSUE THREAD

**Issue by matzoman** [idno/Known#1181]
Expected:
I syndicated a post and a status I've written to twitter and to facebook. Then someone liked my tweet or made a comment on my facebook posting and I use brid.gy to collect this reactions to my blog.
Actual:
An error happens in brid.gy because brid.gy is trying to send the webmention to the wrong known-URL it seems.

Where does the wrong URL is coming from?

The slug is '2016' but the webmention is sent to a URL with a different slug. Some long number.

[error_log_bridgy_facebook.txt](https://github.com/idno/Known/files/114304/error_log_bridgy_facebook.txt)
Link to note on my blog: http://known.matthias.welling.io/2016/bus-knallvoll-klappsitz-besetzt-von-junger-person-egotrip-knnte-kotzen
Link to Post on facebook: https://www.facebook.com/10153875301995645/posts/10153888328305645?_rdr=p

---

[error_log_bridgy_twitter.txt](https://github.com/idno/Known/files/114305/error_log_bridgy_twitter.txt)
Link to Post on my blog: https://t.co/hbyk8413Bf
Link to the Tweet: https://twitter.com/mwelling_io/status/692672265117421568

---

(I'm using the latest code from master.)

ps.: right NOW is my host down... :/

**Comment by physcocode** [comment]
Did the new URL structure of known broke something on Bridgy? Maybe Bridgy plugin needs to be updates about new url (just a guess)

**Comment by kylewm** [comment]
Hi @matzoman, unfortunately this is an issue with the (invisible) backlink from Facebook to your site. Facebook sees "2016" and thinks it's a user ID, so it tries to protect that user by rewriting it to Bridgy's app-scoped user ID. [More details here](https://github.com/idno/Known/issues/1153)

There are a couple possible (bad) solutions, but realistically we're going probably going to have to get rid of "See Original" links sooner rather than later. Which will make this moot.

Let's discuss/track this issue over here: https://github.com/idno/Facebook/issues/31

**Comment by kylewm** [comment]
> Did the new URL structure of known broke something on Bridgy?

Yes, sort of. Known used to be totally agnostic to the number in the permalink, so `example.com/1234567890/slug` served the same content as `example.com/2016/slug`. Now the permalink regex is slightly less agnostic, looking for something that is 4 digits.

**Comment by kylewm** [comment]
BTW: As a workaround, you can configure your server to rewrite URLs. I don't know how to do it in Apache, but in my nginx config, I have:

```
    location /10101859667637941/ {
      rewrite ^/10101859667637941/(.*)$ /2014/$1 redirect;
    }

    location /10101859667632951/ {
      rewrite ^/10101859667632951/(.*)$ /2015/$1 redirect;
    }

    location /10102571892817971/ {
      rewrite ^/10102571892817971/(.*)$ /2016/$1 redirect;
    }
```

**Comment by matzoman** [comment]
thanks for the helpful answers!
