### ISSUE TITLE
Star in front of Liked/Favourited items

### ISSUE THREAD

**Issue by danito** [idno/Known#1184]
I favorited an url with [Quill](https://quill.p3k.io/) and it appears on my Known as new bookmark with a big star (fa fa-star-o) in front of the title.
It gets the "like of" from [default/entity/Like.tpl.php#L6](https://github.com/idno/Known/blob/master/IdnoPlugins/Like/templates/default/entity/Like.tpl.php#L6)
Is this not obsolete as this is the only way to get this star ? It doesn't fit with the rest of the layout.

**Comment by kylewm** [comment]
> Is this not obsolete as this is the only way to get this star 

FWIW, this plugin adds likes and reposts as first class content types:

https://github.com/kylewm/KnownReactions

But it conflicts with the bookmarks plugin right now, so in practice you can only have one or the other.

**Comment by kylewm** [comment]
So to answer your question the Bookmark plugin handles likes and reposts when they come from micropub and uses the star or retweet icon to differentiate them from regular bookmarks. It's not the most elegant thing in the world but I don't think it's obsolete yet. (It might be nice down the road to tease these apart so they are three different post types).

And honestly I think the star looks OK with the rest of the layout. For others' reference:

![star-like](https://cloud.githubusercontent.com/assets/950127/12908837/700a7730-ceaf-11e5-9f24-b89afa875127.png)
