### ISSUE TITLE
plugin spec should include source url and maybe more

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1187]
Eventually, it would be great if the Known plugins page listed the version of each plugin and whether there is a newer one available. This is obviously more of a long term thing, but it might be good to set a precedent now for the information in plugin.ini files that will make version tracking possible in the future

I'd suggest:

* plugin.ini should list a source url where the plugin can be downloaded (maybe for now, explicitly require a git repo)
* plugin.ini should include minimum (and maximum?) version of Known core with which it is compatible

It should be relatively easy to figure out what the latest version of a plugin is (modulo slightly different repository structures like @mapkyca's that have the plugin itself in subfolder).

Working out compatibility between various different versions (e.g. finding the newest version of a plugin that is still compatible with the current version of Known) is of course a can of worms, and that should be kicked as far down the road as possible (:heart: mixed metaphors)

**Comment by benwerd** [comment]
I feel like @mapkyca suggested something similar a long time ago, and now I can't find it. But yes! I'd say the time has come for that. And that, in turn, would lay the groundwork for a plugin directory, which is insanely overdue and badly needed.

**Comment by kylewm** [comment]
Oh awesome! Was it this? https://github.com/idno/Known/pull/221 ... That looks great, way more thorough than I had proposed :) I'll take on adding a paragraph or two about it in http://docs.withknown.com/en/latest/developers/plugins/

**Comment by kylewm** [comment]
> which is insanely overdue and badly needed.

I'd be interested to talk to you about this some time! I'm not convinced it's badly needed, but it *would* be pretty cool. A central register would certainly make checking whether plugins are up to date a hell of a lot simpler/faster.

**Comment by physcocode** [comment]
I was just wondering does known plugins have priorities ?  setting priorities sometimes solve some conflicts between plugin.

**Comment by kylewm** [comment]
> I was just wondering does known plugins have priorities ? setting priorities sometimes solve some conflicts between plugin.

Interesting idea. I can think of a few kinds of conflicts:

1. two plugins claim the same template path. Ben fixed this by allowing plugins to put their templates in `templates/default/[Namespace]/[ClassName]/...` which does create quite a deep hierarchy but it eliminates the possibility of conflict
2. two plugins can claim the same URL route. I don't think prioritization would help this case.
3. two plugins could subscribe to the same event hook. This is where I can see priority being useful -- if you have a plugin that subscribes at a high priority it could intercept messages before they get to the lower priority plugins. 
  * However, this should probably be done per-subscription in the addEventHook call, rather than in the definition of the plugin.

**Comment by physcocode** [comment]
@kylewm 
I have following cases:
1) Plugins overriding or extending same view
2) Themes.

well priority in plugin are actually very useful in elgg, right @mapkyca ?

**Comment by kylewm** [comment]
> 1) Plugins overriding or extending same view
> 2) Themes.

True!
