### ISSUE TITLE
Unit tests without Apache

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1209]
I love that there are unit tests now and want to write more. Coming from another framework, it bugs me a little bit that the unit tests send out requests to another process (Apache/php-fpm/whatever) running Known on localhost. There are more things to set up, more things to go wrong, and it's harder to see where things went wrong when they fail. (on the plus side, it DOES test that Known+Apache work together)

I would prefer to create a little test client that would basically implement the same interface as \Idno\Core\Webservice but would make fake requests to the Known running in the same process as the unit test.

Does this sound like the right way to go? Is there anything fundamentally wrong with this approach? I'm not exactly sure how it would work yet, but I think I'd set `$_SERVER` variables and then invoke `\Idno\Core\PageHandler::serve()` directly.

**Comment by kylewm** [comment]
Turns out the `header()` function makes this a huge pain. You can capture output with `ob_start`, but you can't capture headers, and it throws a fit when you try to modify the headers after any output is written.

**Comment by mapkyca** [comment]
My only comment on this would be that testing against apache constitutes a "real" test against a more realistic environment, so if we wanted a lighter tester as you suggested, I'd be keen to preserve the apache approach as well.

Also note, you can change the test away from localhost by setting an environment variable, and the travis scripts also capture error.log on the event of a failure, in order to capture debug.

You may also find it helpful that the scripts set a unit test define which allows you to switch off headers for unit tests (not ideal, but the simplest workaround I found to get it working with the travis scripts!)

**Comment by kylewm** [comment]
Totally agree it would be good to still have a full integration test with Apache. I probably wouldn't want to run it for every commit and pull request, maybe just before a release.

-- 

The other big problem is whenever anyone calls `exit;` that kills the unit tests.

I think in my ideal world, `\Idno\Common\Page` would be more functional... it'd take a Request object and return a Response object with the response code, headers, and body.

I haven't worked out yet how to work that into bonita and toro which call `header()` directly

**Comment by benwerd** [comment]
Tempting to have wrapper functions for both things?

**Comment by kylewm** [comment]
> I think in my ideal world, \Idno\Common\Page would be more functional... it'd take a Request object and return a Response object with the response code, headers, and body.

Ah crap, this would break the clever "finish writing the response to the browser but keep processing in the background" stuff

**Comment by benwerd** [comment]
Hmm. Is it too late to rewrite the whole thing in Go?

**Comment by kylewm** [comment]
Ben!

Wrapping `header()` and `exit` with functions that can be mocked is definitely tempting. A lot of people seem to have trouble with `time()` as well. It'd be nice if there was a namespace that everyone agreed on for this (like, Testable)

If we really wanted to go the functional route, I could imagine returning a "postprocessor" callable, and the server would invoke the postprocessor after sending the response. Meh. I'm going to stop thinking about this now.

**Comment by mapkyca** [comment]
Trouble with time()?

**Comment by kylewm** [comment]
>  and the travis scripts also capture error.log on the event of a failure, in order to capture debug.

@mapkyca can you tell whether that capturing is working here: https://travis-ci.org/idno/Known/jobs/110035308

I see lots of "Known (localhost) DEBUG" messages, but not the stacktrace I would expect to see for the error

**Comment by mapkyca** [comment]
Expand the sudo cat... Right at the end..?

**Comment by kylewm** [comment]
Oops, thank you. I blame posting before coffee.


On Thu, Feb 18, 2016, at 03:16 PM, Marcus Povey wrote:
> Expand the sudo cat... Right at the end..?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/idno/Known/issues/1209#issuecomment-185976000

**Comment by mapkyca** [comment]
No worries, we've all been there ;)
