### ISSUE TITLE
in v0.9.4 css is broken somehow

### ISSUE THREAD

**Issue by matzoman** [idno/Known#1210]
Here some screenshots.

Broken (v0.9.0.4):
![known_0904_broken_css](https://cloud.githubusercontent.com/assets/7069789/12881264/bec31196-ce48-11e5-8f48-6fa7bfe7a0a4.png)

Before (v0.9.0.2):
![known_0902_nice_css](https://cloud.githubusercontent.com/assets/7069789/12881268/c4f0c1bc-ce48-11e5-8cbc-9d7b24de934d.png)

**Comment by mapkyca** [comment]
There are some new rules in the .htaccess, be sure you've updated that as well.

**Comment by matzoman** [comment]
Yes, thats solves the problem! big thanks!
