### ISSUE TITLE
Checkin Object doesn't get hashtags

### ISSUE THREAD

**Issue by danito** [idno/Known#1212]
when adding a #hashtag to a checking, it doesn't got into the object.
print_r of $vars['object'] :
```
IdnoPlugins\Checkin\Checkin Object
(
    [collection] => entities
    [attributes] => Array
        (
            [access] => PUBLIC
            [owner] => https://nxd4n.nixekinder.be/profile/nxd4n
            [lat] => 50.8078392
            [long] => 4.3137889
            [placename] => Home Town
            [title] => Checked into Home Town
            [body] => 

#myhashtag

            [address] => ...
            [tags] => 
            [slug] => checked-into-home-town
            [created] => 1455053501
            [updated] => 1455053501
            [_id] => 3741542cfc2d203ada167ff833a4141f
            [uuid] => https://nxd4n.nixekinder.be/2016/checked-into-home-town
            [entity_subtype] => IdnoPlugins\Checkin\Checkin
            [inreplyto] => 
        )

)
````
Strange as [IdnoPlugins/Checkin/templates/default/entity/Checkin.tpl.php#L40](https://github.com/idno/Known/blob/7da22e2548d8df7fe1229ab30ca6c33f1dcda551/IdnoPlugins/Checkin/templates/default/entity/Checkin.tpl.php#L40) does the parseHashtags of the body

**Comment by kylewm** [comment]
You're looking for the `object['hashtags']` field right? I think this is because they are parsed from Entity->getDescription, which is messed up for Checkins https://github.com/idno/Known/blob/7da22e2548d8df7fe1229ab30ca6c33f1dcda551/IdnoPlugins/Checkin/Checkin.php#L13
