### ISSUE TITLE
Previous post remnants

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1213]
Sometimes when I start a new Post the Title and Contents are pre-filled with the previous Post I was writing last.

Odd , anyone else seeing this ?

I am using Iceweasel 38.6.0 under Debian.

**Comment by benwerd** [comment]
This is by design - in the latest Known you should be able to resume
writing. However, if it persists after the post has been published, we have
a bug.

On Wednesday, February 10, 2016, Mark Waters <notifications@github.com>
wrote:

> Sometimes when I start a new Post the Title and Contents are pre-filled
> with the previous Post I was writing last.
>
> Odd , anyone else seeing this ?
>
> I am using Iceweasel 38.6.0 under Debian.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1213>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by markwaters** [comment]
I am using the latest git version but this has been happening for a few months.

**Comment by danito** [comment]
Hi,

I just noted the same (firefox on Osx)

Using the latest from github.

Daniel

**Comment by kylewm** [comment]
> I am using the latest git version but this has been happening for a few months.

Autosave has been implemented in Known for a long time -- it remembers what you were writing so if your browser crashes or you leave the page, you don't lose everything. (it's sort of a hedge until we have real Drafts). The 0.9 release fixed an issue where the contents of the rich text editor were not necessarily saved, but yes this functionality has been in there much longer.

Once you've published the post, the autosave buffer is cleared, so you should not see that content anymore.

If this is doing something unexpected or undesirable do please let us know.
