### ISSUE TITLE
Status Updates / Replies on Homepage

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1216]
I have seen this behavior for a long while, but it never bothered me. Lately I'm posting more and more to my site only (and not POSSE out to Silo's) and now it becomes an annoyance.

In the Admin --> Homepage settings there are toggles to enable or disable post types:
![image](https://cloud.githubusercontent.com/assets/546983/12977765/0416ad58-d0cd-11e5-8020-e8ab35caf284.png)

Now let's take a look at my homepage in an incognito window:
![image](https://cloud.githubusercontent.com/assets/546983/12977844/92bba36a-d0cd-11e5-840a-c17fa90738ff.png)

It contains both Status updates and Replies. I believe this is a bug.

**Comment by mapkyca** [comment]
Do you have a URL I can look at?

**Comment by tinokremer** [comment]
Certainly: https://tinokremer.nl/

**Comment by mapkyca** [comment]
Yep, it's a bug introduced by 7e8e546bc004002b2f869101291c796e2a1c6832. Closing this issue in favour of #1056.

@benwerd I really think we should revert this commit.
