### ISSUE TITLE
share bookmarklet and indieweb 

### ISSUE THREAD

**Issue by danito** [idno/Known#1226]
Hi,
if I understood it right, the share bookmarklet doesn't have full indieweb features like "u-like-of" or reposts "u-repost-of" as most users aren't familiar with those and would be confused. Some plugins have been added to add those possibilities, but why not add a feature in the config.ini that would enable advanced indieweb features so that the FirefoxTool/Bookmarklet works for everything?

**Comment by kylewm** [comment]
For what it's worth, I would gladly merge a PR on https://github.com/kylewm/KnownReactions that added Likes and Reposts to the share bookmarklet page.(I may add that eventually myself, but it'll be a while)

**Comment by mapkyca** [comment]
From chatter, I imagine this has been handled by a plugin...
