### ISSUE TITLE
Sunset PHP 5.4 & 5.5 support

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1238]
PHP 5.4 is EoL (https://secure.php.net/supported-versions.php)
PHP 5.5 is security update only, and EoL mid 2016.

I'm aware that most shared hosts suck, but I'm filing this as a statement of intent, with hopes that they'll pull their respective fingers out.

**Comment by benwerd** [comment]
I'm inclined to find a way to survey hosts running Known and see what their
version numbers actually are. I agree that it'd be nice to just support 5.5.

On Mon, Feb 15, 2016 at 7:52 AM, Marcus Povey <notifications@github.com>
wrote:

> PHP 5.4 is EoL (https://secure.php.net/supported-versions.php)
> PHP 5.5 is security update only, and EoL mid 2016.
>
> I'm aware that most shared hosts suck, but I'm filing this as a statement
> of intent, with hopes that they'll pull their respective fingers out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1238>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Perhaps something on the admin/convoy ping?

**Comment by mapkyca** [comment]
Also, I wonder if we should start using the nagging approach we adopted for TLS - start warning on install and diagnostics about older versions of PHP. My thinking is the vast majority of folk don't even think about PHP versions, and hosting companies don't tend to proactively upgrade people - it's the squeaky wheel that gets the grease. 

Shared hosts tend to be a bad mix of ignorance and indolence.

**Comment by mapkyca** [comment]
Another point of note - PHP 5.4 only supports the legacy mongo extension, 5.5 & 6 support both mongo and mongodb, php7 only supports mongodb.

So, we're going to need to drop 5.4 support if we want to support php 7 + if we want to preserve mongodb support. If we don't, we're going to need to do a migration job for the poor lost souls/early adopters (like myself) who are running on mongo.

**Comment by mapkyca** [comment]
Another gotcha: File upload interface in curl from 5.5 onwards (see errors on #1266). This is a breaking change.

**Comment by physcocode** [comment]
Just to add more support to @mapkyca  the PHP 5.5 will be dead in 24 days

**Comment by mapkyca** [comment]
So what's the report ping say about version numbers @benwerd?

I'm going to suggest we bump the nag up to include 5.5...
