### ISSUE TITLE
MicroPub checkin -> add photo

### ISSUE THREAD

**Issue by danito** [idno/Known#1251]
in https://github.com/idno/Known/blob/master/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php when the GET has a photo = url how can we add this photo to the content? With $_FILE it would become a photo entry. Maybe 
`$content['html'] =. "<p><img src='$url' ...></p>? `
Does this work?

Any ideas?

**Comment by kylewm** [comment]
fixed?

**Comment by danito** [comment]
Added by #1285
