### ISSUE TITLE
\Idno\Pages\Admin\Export\Download not found

### ISSUE THREAD

**Issue by danito** [idno/Known#1255]
since a couple of hours, will say a couple of updates, I have this error in the logs : 
` ERROR - Could not add /admin/export/download/?. \\Idno\\Page
s\\Admin\\Export\\Download not found`
Any idea where this comes from? What file did I forgot to copy (or to delete...)?
Thx

**Comment by kylewm** [comment]
It's a pre-existing error; there was just a log message added for it recently.

**Comment by benwerd** [comment]
... And as a result it's fixed in the latest code!


On Wednesday, February 17, 2016, Kyle Mahan <notifications@github.com>
wrote:

> It's a pre-existing error; there was just a log message added for it
> recently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1255#issuecomment-185321155>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
Confirmed! Thanks Ben
