### ISSUE TITLE
MicroPub Enpoint hashtags : how to handle multiple words categories?

### ISSUE THREAD

**Issue by danito** [idno/Known#1272]
Categories are prefixed with a '#' to handle them as hashtags but if importing a checkin from 4square, categories can have more than one word, e.g. Capitol Building.
How should we handle this? 
- Hash all of the words: #capitol #building ?
- Just the first one: #capitol building ?
- Replace spaces by _: #capitol_building ?

**Comment by paulcmal** [comment]
How about replacing spaces with non-breaking spaces (&nbsp;) for display considerations and hash just the first word?

**Comment by kylewm** [comment]
my instinct is to strip spaces, so it'd be `#CapitolBuilding` ... since hashtags come from Twitter, and I don't think I've ever seen a Twitter hashtag with an _ in it, even though they seem to be supported.

**Comment by benwerd** [comment]
I'm with @kylewm on this - removing spaces makes sense to me.

**Comment by danito** [comment]
fixed partly by #1285 by deleting spaces.
still open as this doesn't yet handles single quotes in categories

**Comment by danito** [comment]
addressed in #1291
