### ISSUE TITLE
Syndication toggles are fixed-width

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1275]
Something broke and syndication toggles no longer adapt to the text inside them.

I need to fix this before release. Will take a look later today.

**Comment by kylewm** [comment]
Cannot reproduce. Maybe theme-specific?

**Comment by mapkyca** [comment]
Ditto, works for me...

**Comment by benwerd** [comment]
Seems to be an issue specific to werd.io - I created a new site (testing /
debugging a new plugin over at jnu.benwerd.com), tested Convoy and all is
hunky dory.

It sometimes happens if assets load in the wrong order, so I'm wondering if
my plugin list is messed up (or something). I'll try refreshing.


On Sat, Feb 20, 2016 at 1:55 AM, Marcus Povey <notifications@github.com>
wrote:

> Ditto, works for me...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1275#issuecomment-186561335>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
