### ISSUE TITLE
Drop Mongo support

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1277]
Kill it. Kill it with fire.

Refs #1271
Closes #1241 
Closes #1018 

Depends on #480

**Comment by physcocode** [comment]
why are we still supporting it ? any special reason ?

**Comment by mapkyca** [comment]
We need to support it until import/export is bullet proof, as we need to provide a way to migrate from mongo to mysql.

**Comment by physcocode** [comment]
+1 sounds cool

**Comment by mapkyca** [comment]
Wondering whether this is still necessary, given that #1241 removes the PHP7 blocker, and that indexes remove the pagination errors.

Still deprecated, but...

**Comment by mapkyca** [comment]
Going to close this. The recent Mongo code migration has resolved many of the outstanding mongo issues and all the PHP7 blockers, however mongo is still deprecated, so use mysql.
