### ISSUE TITLE
Wrong unicode decoded in Webmention

### ISSUE THREAD

**Issue by danito** [idno/Known#1278]
See the mention from @rmendes http://www.rmendes.net/2016/known-091-has-left-the-building-and-its-a-gorgeous
His mention in
http://stream.withknown.com/2016/known-091-has-left-the-building get's the 'prêt à porter' in the title wrong

**Comment by mapkyca** [comment]
I'm not able to replicate. I suspect it's something at @benwerd's end...

**Comment by mapkyca** [comment]
Closing
