### ISSUE TITLE
Homepage doubling

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1286]
I keep up-to-date with the git version , running on Debian Jessie , currently PHP 5.6.17 , MySQL database.

When I click on the Status or Photo buttons to create a new entry , the usual editor section does not appear , instead the page redraws and I now have the original latest five posts followed by the known logo and then the same latest five posts.

I am using Iceweasel 38.6.1 on my desktop and 44.0.2 on my tablet and phone with the same effect.

**Comment by markwaters** [comment]
Switching from Tabula Rasa to Solo theme has fixed it ?!

**Comment by tinokremer** [comment]
Confirmed. I use Cherwell which works fine. I switched to Tabula Rasa for testing and I have the same behavior. It seems to be the theme that is causing the problem.

**Comment by markwaters** [comment]
Thanks @tinokremer

**Comment by benwerd** [comment]
Weird! Checking it out.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1286" class="u-in-reply-to"></a>htaccess changed a little while ago, check that your JS is being fetched. 

Also, try clicking on the link with the dev console on and see if there are any errors...

**Comment by kylewm** [comment]
This is my oversight from https://github.com/idno/Known/commit/45f59779b9493098f2ab0a01b6ebee76c1919f48

I will fix it!

**Comment by markwaters** [comment]
Thanks @kylewm , working perfectly again now.
