### ISSUE TITLE
using issue and pull request templates

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1288]
randomly tailored pull request and issues make it hard for developers I would strongly recommend to use the new issue and pull request template rolled out by github (https://github.com/blog/2111-issue-and-pull-request-templates). This would make PR's and issue cleaner and understandable

**Comment by benwerd** [comment]
I like it!

**Comment by benwerd** [comment]
Added!

**Comment by physcocode** [comment]
that was quick :)
