### ISSUE TITLE
Location & syndication to FourSquare : provide suggestions for place_name

### ISSUE THREAD

**Issue by danito** [idno/Known#1290]
## While trying to do this:

Creating a location and syndicate it to Foursquare 
## I encountered this error:

The provided placename is a street number of the found address or a location name. If this name doesn't correspond to the exact same 4sq name, your checkin is completely wrong.
## Some other notes:

I would provide a list of places to suggest where to checkin if the syndicate to 4sq is toggled on, based on the the LatLong values and not the location name to be sure to get only 4sq places.
Maybe change the placename field to a dropdown with the returned search results with a warning "please chose one of the suggested 4sq places or disable 4sq ".

**Comment by danito** [comment]
I started to address this in a new [branch](https://github.com/danito/Foursquare/tree/4sqVenues).
Any comments are welcome.

**Comment by benwerd** [comment]
Super super super cool!

On Wed, Feb 24, 2016 at 6:13 AM, Daniel nix <notifications@github.com>
wrote:

> I started to address this in a new branch
> <https://github.com/danito/Foursquare/tree/4sqVenues>.
> Any comments are welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1290#issuecomment-188271899>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Closing, is handled by a (yet unmerged) PR on the Foursquare plugin.
