### ISSUE TITLE
Facebook posting looks broken.

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#1297]
Posting to Facebook with integrated cross-posting feature seems to produce broken links to original post that have some weird number (Facebook user ID, presumably) where a year should be.

See https://www.brid.gy/facebook/10152710552987085 for an example.

**Comment by kylewm** [comment]
This has been fixed recently in the Facebook plugin by removing the See Original link. Check that your plugin is up to date

**Comment by nekr0z** [comment]
I wish I could! Here's one more reason to second my old feature request: give the hosted version users some debugging information.

**Comment by kylewm** [comment]
The good news is Bridgy has removed support for See Original links on their side, so these bad links will be ignored now and shouldn't cause any more problems with backfeed (ref https://github.com/snarfed/bridgy/issues/650). Please feel free to reopen if you still see problems!
