### ISSUE TITLE
Using files sessions results in massive numbers of files

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1298]
## While trying to do this:

Using session files
## I encountered this error:

Directory quickly becomes full of hundreds of thousands of files
## Some other notes:

Looks like we probably need to do _some_ garbage collecting

**Comment by kylewm** [comment]
What OS are you on? Is this the Ubuntu thing where it disables garbage collection?

**Comment by mapkyca** [comment]
Debian, so it might be this.... I know they turned off gc to handle it themselves, let me check...

**Comment by mapkyca** [comment]
Of course, unless the session dir is the same as the session path specified in php.ini, garbage collection won't happen automatically in any case and you need to clean it up yourself.

**Comment by mapkyca** [comment]
Think this is a PHP config thing not a Known thing, closing for now.
