### ISSUE TITLE
Checkin leaflet map : global variable map/marker

### ISSUE THREAD

**Issue by danito** [idno/Known#1299]
## While trying to do this:
editing the Foursquare plugin to address #1290 
## I encountered this error:
the leaflet map is not accessible for plugins to modify as the map is defined in a private function
## Some other notes:
If nothing speaks against it, make the map and the marker variable global in [IdnoPlugins/Checkin/checkin.js](https://github.com/idno/Known/blob/master/IdnoPlugins/Checkin/checkin.js)

**Comment by physcocode** [comment]
this is fixed in #1300 right?

**Comment by danito** [comment]
Yes
