### ISSUE TITLE
Render syndication links on feed pages, or support ETags/If-Modified-Since

### ISSUE THREAD

**Issue by snarfed** [idno/Known#1309]
we've been working on optimizing bridgy to cut costs recently (snarfed/bridgy#578 , snarfed/bridgy#624), and one of its big sources of load currently is refetching home pages and permalinks to check for new/updated syndication links.

Known and WordPress are the two biggest CMSes bridgy sees by far. if you all were able to render synd links inside entries in feeds, that would let us skip fetching the permalinks, which would be a huge help.

alternatively, if you supported ETags/If-Modified-Since, we could use them to make them permalink fetches and processing much lighter. a bit more work for us, and not quite as big a win, but still something.

cc @kylewm. thanks in advance! hope you all are good. oh, and feel free to split this into two issues if you want, obviously.

**Comment by benwerd** [comment]
Seems totally reasonable. Are you scanning the mf2 or the RSS feeds?

On Friday, February 26, 2016, Ryan Barrett <notifications@github.com> wrote:

> we've been working on optimizing bridgy to cut costs recently (
> snarfed/bridgy#578 <https://github.com/snarfed/bridgy/issues/578> ,
> snarfed/bridgy#624 <https://github.com/snarfed/bridgy/issues/624>), and
> one of its big sources of load currently is refetching home pages and
> permalinks to check for new/updated syndication links.
>
> Known and WordPress are the two biggest CMSes bridgy sees by far. if you
> all were able to render synd links inside entries in feeds, that would let
> us skip fetching the permalinks, which would be a huge help.
>
> alternatively, if you supported ETags/If-Modified-Since, we could use them
> to make them permalink fetches and processing much lighter. a bit more work
> for us, and not quite as big a win, but still something.
>
> cc @kylewm <https://github.com/kylewm>. thanks in advance! hope you all
> are good. oh, and feel free to split this into two issues if you want,
> obviously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1309>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by snarfed** [comment]
thanks! mf2, from the rendered pages, usually starting from the home page.

**Comment by benwerd** [comment]
OK. So would mf2 syndication links in a sub div for each entry hidden with
display:none be acceptable?

On Friday, February 26, 2016, Ryan Barrett <notifications@github.com> wrote:

> thanks! mf2, from the rendered pages, usually starting from the home page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1309#issuecomment-189378721>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by snarfed** [comment]
that'd be perfect!

**Comment by benwerd** [comment]
Actually disregard last - it's probably outside the div you need it to be inside.

**Comment by benwerd** [comment]
... Or on reflection, is it? Let me know.

**Comment by snarfed** [comment]
looks like it works perfectly: http://mf2.kylewm.com/?url=http://werd.io/

thanks again!

**Comment by benwerd** [comment]
Hooray! Okay, closing this out. We need to update the hosted service soon, so this will make its way to most Known sites before too long. There will also be a release at the beginning of March.

**Comment by kylewm** [comment]
This is a win for woodwind too fwiw :)

**Comment by kylewm** [comment]
Hey that was almost a palindrome

**Comment by kylewm** [comment]
or maybe not quite a win... since `rel=syndication` is page-scoped, it's bad to have it in the feed.

![screenshot from 2016-02-26 11-52-18](https://cloud.githubusercontent.com/assets/950127/13363690/96ba0b38-dc7f-11e5-824e-e4e98f466ffa.png)

**Comment by benwerd** [comment]
Eek. What do you think the better markup would be?

On Friday, February 26, 2016, Kyle Mahan <notifications@github.com> wrote:

> or maybe not quite a win... since rel=syndication is page-scoped, it's
> bad to have it in the feed.
>
> [image: screenshot from 2016-02-26 11-52-18]
> <https://cloud.githubusercontent.com/assets/950127/13363690/96ba0b38-dc7f-11e5-824e-e4e98f466ffa.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1309#issuecomment-189455301>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
Just like it is now but without `rel="syndication"`... (btw, this is always a hassle, I had it with Red Wind, and with adactio.com. Maybe a reason to change the spec)
```html
<a href="https://twitter.com/benwerd/status/703279057329238016" class="u-syndication twitter"><i class="fa fa-twitter"></i>
 @benwerd</a>
```
