### ISSUE TITLE
Overzealous translation of @-values to CURLFiles

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1310]
## While trying to do this:

Call Webservice::post with a parameter `content="@benwerd blah blah blah"`

## I encountered this error:

> Error contacting micropub endpoint (0): couldn't open file "benwerd this is the best evidence I have so far that you *are* @PHP_CEO" 

![screenshot from 2016-02-26 12-07-44](https://cloud.githubusercontent.com/assets/950127/13364086/c2843e12-dc81-11e5-9b78-ee41874d49e0.png)

## Some other notes:
In a day of amusing errors, this is the most amusing so far.

**Comment by kylewm** [comment]
suspect this was introduced in ef20dca3c18c3f81f7db8eb6bb38b460525a264b

**Comment by mapkyca** [comment]
This is a problem with maintaining php 5.4 support.

**Comment by kylewm** [comment]
Proposal: introduce a new class, maybe like `\Idno\Core\WebserviceFile`, that becomes the only sanctioned way to pass file handles to Webservice.

Then Webservice can convert that to @-syntax or CurlFile depending on the PHP version

**Comment by mapkyca** [comment]
That would work, aye, and is probably the best solution in this instance, although I'm cautious of adding too many platform specific shims for obsolete platforms.

**Comment by kylewm** [comment]
Oh dang, I blamed @mapkyca's CurlFile change, but this was *my* fault! db4b169009714bcb750160395a33aecd4764a658 removed the code that manually called http_build_query, which I now understand existed to work around the @-name issue.

I'm going to try setting `CURLOPT_SAFE_UPLOAD` (PHP 5.5+), which is supposed to prevent it from interpreting @'s.

**Comment by kylewm** [comment]
I tested with #1315 and #1326 and confirmed that images and @-replies publish correctly now.
