### ISSUE TITLE
Connection with Bridgy don't work after update to 0.9.1 and moving to https

### ISSUE THREAD

**Issue by georgkaser** [idno/Known#1327]
## While trying to do this:

I updated to the latest version (0.9.1), moved my Known installation to another server (another IP) and changed to https:// instead of http://
## I encountered this error:

After that I tried to reconnect to brid.gy. It authenticated (2 times) and then I got redirected to my Known Backend where the button was gray and "Bridgy connected". From there it switched immediatly back to the blue status "Activate Twitter + Bridgy" and the connection was lost.
## Some other notes:

I tried several times. Here the server logs:

`[Mon Feb 29 13:53:59 2016] [warn] [client 92.217.69.217] mod_fcgid: stderr: Known (geor.gs): debug - Had slug: georg, referer: https://api.twitter.com/oauth/authorize
[Mon Feb 29 13:53:59 2016] [warn] [client 92.217.69.217] mod_fcgid: stderr: Known (geor.gs): debug - saveRecord(): insert or update took 0.0086450576782227s, referer: https://api.twitter.com/oauth/authorize
[Mon Feb 29 13:54:00 2016] [warn] [client 92.217.69.217] mod_fcgid: stderr: Known (geor.gs): debug - Had slug: georg, referer: https://geor.gs/account/bridgy/
[Mon Feb 29 13:54:00 2016] [warn] [client 92.217.69.217] mod_fcgid: stderr: Known (geor.gs): debug - saveRecord(): insert or update took 0.0038118362426758s, referer: https://geor.gs/account/bridgy/
`

**PS: Thank you for that great software :)**

**Comment by mapkyca** [comment]
Check that your twitter application is also changed to HTTPS...

**Comment by georgkaser** [comment]
Sorry, but I don't understand. There is no twitter application for brid.gy - only for the twitter plugin (I've also disabled for testing).

I tried now with a brandnew installation, downloaded from https://withknown.com/opensource/  - same problem here.

**Comment by physcocode** [comment]
@georgkaser you would have enter the URL of your website on your "twitter profile" at www.twitter.com
change that URL from http://yoursite.com to https://yoursite.com

**Comment by physcocode** [comment]
@georgkaser maybe @mapkyca is talking about your twitter app use to syndicate with known available at dev.twitter.com

**Comment by georgkaser** [comment]
Yes, I know - but there is no twitter app for the bridgy plugin, only for the twitter plugin. These are two separate plugin (the twitter plugin is not delivered with Known https://github.com/idno/Known/tree/master/IdnoPlugins). I think the twitter authentication works over brid.gy.

**Comment by kylewm** [comment]
Hmm, well your Bridgy seems to be connected and set up correctly https://brid.gy/twitter/georgkaser

The blue/gray button on your Known site at `/account/bridgy` is just informative... if  https://brid.gy/twitter/georgkaser says you are connected, you are.

If the button on /account/bridgy keeps turning blue, then there's probably some bug in `IdnoPlugins\Bridgy\Pages\Check`...

**Comment by kylewm** [comment]
> It authenticated (2 times)

BTW, this is awkward, but normal for Bridgy. After it authenticates the first time, it sees that you have "publish" enabled, and authorizes again with read/write permission.

**Comment by georgkaser** [comment]
Hey, thanks for your help! You're right, I tested now again. I liked a post of me I made before, it worked. It seems that's really only the status of the button. What do you think, do we need another bug report for this issue?

**Comment by rikmendes** [comment]
my experience doing this move was : 

after correcting all apps to HTTPS and bio descriptions I login to my site and the brid.gy button was gray so I disconnect it, connect it back with the new HTTPS settings and it worked just fine. 

did the same to twitter just to be sure and i'm all set..

**Comment by kylewm** [comment]
> do we need another bug report for this issue?

I think it's fine to keep tracking the issue here. I haven't been able to reproduce though :/

The check in IdnoPlugins\Bridgy\Pages\Check is supposed to work by: fetching your bridgy user page, parsing it for microformats, and looking for the properties `bridgy-account-status` and `bridgy-listen-status`

Looking at the parsed version of your user page http://mf2.kylewm.com/?url=https%3A%2F%2Fbrid.gy%2Ftwitter%2Fgeorgkaser the properties do seem to be there and enabled. Maybe your server cannot connect to brid.gy for some reason? Can you try running `curl -I https://brid.gy/` on the command line?

**Comment by georgkaser** [comment]
Hi @rikmendes  - I did the same - without your luck :) Except my bridgy button was'nt gray after moving to another server.

@kylewm I have no shell access on my server, but with a php-workaround i got this ouptut:
```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Content-Length: 0
Date: Tue, 01 Mar 2016 09:34:28 GMT
Server: Google Frontend
Alt-Svc: quic=":443"; ma=2592000; v="30,29,28,27,26,25"
```
seems to work...
