### ISSUE TITLE
Slugs allow percentages (and therefore break)

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1331]
## While trying to do this:

Saving a post that had a % in the title

## I encountered this error:

The % made it to the slug, which of course triggers the browser to think of it as an encoded value, causing the post to be lost and breaking everything.

## Some other notes:

This was reported by a Known Pro user and duplicated by me.

**Comment by kylewm** [comment]
Argh sorry you guys I hadn't paid attention to this change, and I guess I reverted the fix for this trying to fix the issue with umlauts.

#1347 put the % back that #1334 removed

Ideally I guess we should strip %'s before calling rawurlencode, *or* encode them too.
