### ISSUE TITLE
"Avatar as icon" not working anymore

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1332]
## While trying to do this:
Visit my site running on the latest code, freshly installed this morning)
## I encountered this error:
The site's icon now has the Known logo, while "Avatar as icon" is enabled in Site settings
## Some other notes:
I reverted back to 0.9.1:
![known 0 9 1 release](https://cloud.githubusercontent.com/assets/546983/13422425/08505500-df95-11e5-8368-c4283b7b1377.png)

All fine, back to the latest code:
![known march 2016](https://cloud.githubusercontent.com/assets/546983/13422429/1080e7bc-df95-11e5-89fc-05bf280eebda.png)

**Comment by danito** [comment]
If I open your site I can see your logo. Did you switch back to 0.9.1? 
But I can confirm that I've the K on my homepage, but if I open an entry it switches to my face(palm).
Is it possible that for some themes this line return false ?
https://github.com/idno/Known/blob/master/Idno/Common/Page.php#L953
````php
                        if ($user instanceof \Idno\Entities\User) {
                            $icon = $user->getIcon();
                        }
````

**Comment by tinokremer** [comment]
Yes, I switched back to an earlier commit, because of https://github.com/idno/Known/issues/1336

**Comment by danito** [comment]
After debugging a bit, it seems that the homepage doesn't have a getOwner()
