### ISSUE TITLE
Different CSS for admin than rest of the site

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1333]
## While trying to do this:
Develop a new theme for known
## I encountered this error:
Is there any way that Admin follow a different CSS file from rest of style
## Some other notes:
It would be nice if Admin has a different shell from rest of site as we can give it a more "Admin feel" and rest of the site more "User feel".

Bonus : Developing Material Theme and Nature Theme for known was a butter process when i just looked around solo theme :) . Building theme for known is not a tough process !

**Comment by mapkyca** [comment]
Each page has a unique class on <body>, so you could skin on that...

**Comment by physcocode** [comment]
@mapkyca alas! I got it ! great idea

**Comment by mapkyca** [comment]
Closing for now.
