### ISSUE TITLE
RSVP to facebook events

### ISSUE THREAD

**Issue by danito** [idno/Known#1339]
## While trying to do this:
RSVP to a fb event
## I encountered this error:
The rsvp was syndicated to FB but as a normal status. Does the FB api allow to RSVP?

**Comment by kylewm** [comment]
Yes the API does allow you to post an RSVP, Bridgy Publish supports it. We could look there for inspiration.

**Comment by kylewm** [comment]
working on this, FYI, it will require a new permission `rsvp_event`.
