### ISSUE TITLE
Known instances seem to require TWO webmentions to accept comments, likes

### ISSUE THREAD

**Issue by tantek** [idno/Known#1340]
## While trying to do this:

I posted a reply yesterday:
*  http://tantek.com/2016/060/t9/falcon-webmention-posse-video
and automatically sent a webmention to the in-reply-to URL (a Known post)
* http://www.rmendes.net/2016/so-you-are-actually-posseing-video-right-to-twitter-by 

## I encountered this error:

And nothing showed up.

## Some other notes:

Today I manually curled that same webmention, and my comment on his post showed up immediately.

I've seen this problem before too, when liking or commenting on werd.io posts. Figured it was some ephemeral bug or network glitch, but it is now consistent enough to be annoying and likely an actual bug in Known's Webmention receiving implementation.

**Comment by benwerd** [comment]
This is actually likely a cache issue. I think it's aggressively caching the page too heavily.

**Comment by tinokremer** [comment]
@benwerd your site does not show my likes either:
https://tinokremer.nl/2016/liked-ben-werdm%C3%BCllers-post-on-werdio-a18f1dcacd
https://tinokremer.nl/2016/liked-ben-werdm%c3%bcllers-post-on-werdio-57adfc923f

It could be the same issue. I have not retried the webmentions, but when I like something on @kylewm 's website all is fine. Same goes for others. I thought it was an issue with your site, but it looks a bit like what @tantek describes.

**Comment by georgkaser** [comment]
My likes also not:
https://geor.gs/2016/liked-ben-werdm%C3%BCllers-post-on-werdio-a18f1dcacd

**Comment by tinokremer** [comment]
It could be this https://github.com/idno/Known/pull/1334 fixes it. Let me know when you have installed it on your machine @benwerd and I'll give it a test.

**Comment by kylewm** [comment]
So do we think this is NOTABUG? I have never seen the "two webmentions to accept a comment" behavior, and it sounds like Ben thinks it's down to aggressive caching on @rikmendes's site?

The umlaut URLs are definitely a separate issue that have been fixed in master.

**Comment by kylewm** [comment]
I've been keeping an eye on this and haven't noticed it being an issue on my site sending or receiving. 

Hmm, I cannot webmention @rikmendes at all, e.g. https://kylewm.com/2016/03/test-reply-trying-to-reproduce-idnoknownissues1340 , I get:

```
{"error":"source_not_supported","error_text":"Could not interpret source as a comment."}
```

**Comment by rikmendes** [comment]
that's strange...and also...rmendes.net is on dreamhost shared hosting, there isn't ANY caching going there, in fact I should take care of this google speed spider don't like it like it is now. 

rmendes.net is a default simple Known site without any special caching (neither through htaccess/apache or nginx or php (acpu/memcache etc..) anything I can do to help debug this on my end ?

**Comment by kylewm** [comment]
Closing for now, please let us know if this issue (comments only accepted on the second webmention) comes up again!
