### ISSUE TITLE
Text Toolbar missing in inital load of Post and Page

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1341]
## While trying to do this:
Create a new Post or Page with the Rich Text Editor
## I encountered this error:
The new Post / Page opens but the text toolbar is missing.
## Some other notes:
I click 'Switch to plain text editor' nothing changes on the screen , so I click 'Switch to Rich Text Editor' and the text toolbar appears

I am using the latest git version , this issue appeared in the last couple of days - 2016-02-28 ish.

**Comment by tinokremer** [comment]
Stating a few of the obvious troubleshooting actions:

- Do you have some kind of AdBlocker running that may be blocking parts of the page?
- Did you update the .htaccess file?
- Does it happen with other browsers?
- Does anything show up in the console log (F12 on most browsers)?
- Does anything show up in the server error logs?

**Comment by markwaters** [comment]
I do have an adblocker , but it is disabled on my own site.
The .htaccess file is the original git version , I have not updated it in any way.
I am seeing the same issue on my phone as my desktop , both Firefox.
I have done a hard refresh (control-shift-F5) in the desktop browser and the text toolbar is back but in the console I am still seeing this -
<code>downloadable font: OS/2: bad linegap: -32 (font-family: "tinymce" style:normal weight:normal stretch:normal src index:1) source: https://DOMAIN.TLD/external/tinymce/js/tinymce/skins/light/fonts/tinymce.woff</code>
Hope that helps.

**Comment by tinokremer** [comment]
Fixed it? :)

**Comment by markwaters** [comment]
Well the text toolbar has returned after the browser hard refresh so I guess it is a browser problem if its only happening for me.
I will reopen this issue if it returns / continues.
