### ISSUE TITLE
nginx.conf rewrite rules should only be run for /css and /js

### ISSUE THREAD

**Issue by paulcmal** [idno/Known#1342]
## While trying to do this:

Adding rewrite rules to nginx for CSS/JS for the latest version of Known.

## I encountered this error:

With the default nginx config provided with Known, the regex for the rewrite rules are run on every request!

## Some other notes:

#1194 has changed the structure of URLs to access CSS/JS files.

The nginx.conf packed with Known provides rewrite rules equivalent to those for Apache. But the rewrite rules are placed outside of a location block, and are therefore run on every request.

It would be super neat to have a URL structure that allows redirecting without running a regex, using return. Known is currently the only web service that I run that requires rewrite rules.

If that is really not going to be possible for a reason that I don't get (so far), we should at least isolate the rewrite rules to the concerned URLs, like this:

```
        location /css/ {
                rewrite ^/css/[0-9]+/(.*) /css/$1 last;
        }

        location /js/ {
                rewrite ^/js/[0-9]+/(.*) /js/$1 last;
        }
```

I'm now running this config in production in my nginx config and everything seems to be working fine.

**Comment by kylewm** [comment]
> It would be super neat to have a URL structure that allows redirecting without running a regex, using return. Known is currently the only web service that I run that requires rewrite rules.

Is there a performance advantage to using alias instead of rewrite? e.g., would this work?

```
location ~ ^/css/[0-9]+/(.*) {
  alias css/$1;
}
```

**Comment by paulcmal** [comment]
> Is there a performance advantage to using alias instead of rewrite? e.g., would this work?

alias is filesystem-level and not HTTP so it would be better (saves a roundtrip). But although [the docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#alias) are unspecific, they seem to indicate that alias requires absolute paths.

>  The path value can contain variables, except $document_root and $realpath_root. 

I'd rather be able to change the path to our Known instance by editing just one line in the nginx config so I don't really like this solution.

> ```
> location ~ ^/css/[0-9]+/(.*) {
>  alias css/$1;
>}
> ```

On every request, nginx matches every location block against the requested URI (as explained [in the docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#location)), so better match only the first part of the URI and then run the rewrite, like I was proposing earlier:
```
        location /css/ {
                rewrite ^/css/[0-9]+/(.*) /css/$1 last;
        }
```

Does that make sense to you?

**Comment by kylewm** [comment]
Yes, rewrite in a location block makes sense to me. I thought you were asking for an alternative that doesn't use rewrite.

I'm not sure what you mean about a round-trip. https://kylewm.com/css/2016020602/default.css just points directly to the css file; it's not like it requires extra HTTP requests.

**Comment by paulcmal** [comment]
> points directly to the css file

Indeed. I thought "redirect" was the default behaviour of rewrite, but it seems that's only the case when you provide a full URL.

So no I don't see any advantage using alias.
