### ISSUE TITLE
Non-Ascii character in title force "untitled" in permalink

### ISSUE THREAD

**Issue by oricgn** [idno/Known#1343]
If I use a non-ascii character like for example german umlauts (äöü) in a title the permalink is build with "untitled".

I propose to replace non-ascii characters by a hyphen.

**Comment by kylewm** [comment]
Unicode characters in the post slug are usually percent encoded. `/umlaut-test-%C3%A4%C3%B6%C3%BC`

It sounds like you've run into a more specific bug, can you share the whole body of the post you were trying to make? And also what version of PHP, and what backing datastore?

**Comment by oricgn** [comment]
For example: http://oliver.riesen.org/2016/03/untitled-1

PHP 5.4.45-0+deb7u2
MySQL 5.5.47-0+deb7u1

**Comment by kylewm** [comment]
Confirmed here https://travis-ci.org/kylewm/Known/builds/114283754 that this is specific to php 5.4.

**Comment by kylewm** [comment]
Nope, looks like it affects 5.5 too.

**Comment by benwerd** [comment]
Total bummer. I thought this was fixed and non-ASCII characters were behaving well at this point. @oricgn, I'm sorry you ran into this issue.
