### ISSUE TITLE
How to differentiate facebook and flickr buttons?

### ISSUE THREAD

**Issue by oricgn** [idno/Known#1349]
When I want to upload a new photo I can see on "New photo" form two buttons:

![facebook-and-flickr-buttons](https://cloud.githubusercontent.com/assets/4638641/13597490/442005f6-e519-11e5-82ab-553857832695.jpg)

How can I differentiate facebook and flickr button?

I propose to add "Facebook" and "Flickr" in front of the account name.

**Comment by tinokremer** [comment]
I guess it depends a bit on your theme. Which theme are you using?

It looks like this on Cherwell:
![2016-03-08_133247](https://cloud.githubusercontent.com/assets/546983/13601709/4359db24-e532-11e5-9f2a-d29ebceeb734.png)

**Comment by oricgn** [comment]
I'm using "Default theme 0.1".

**Comment by tinokremer** [comment]
Are you on the latest version of Known? I just checked the Default 0.1 theme and it has exactly the same look as I posted above, **with** icons. Also make sure you are not using an addblocker on your own site, that could also be blocking it.

**Comment by oricgn** [comment]
Thanks Tino, Adblock Plus were blocking the images.
