### ISSUE TITLE
IndieAuth broken because of missing rel="me" on homepage

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1351]
## While trying to do this:
Authenticate myself through my website using IndieAuth
## I encountered this error:
No supported rel="me" links were found on your site! 
## Some other notes:
I'm using the latest code from Github: https://github.com/idno/Known/commit/62e9e853c418b55b6cfc400e3527010e9325d87e

The IndieAuth page looks like this after clicking "Rescan":
![2016-03-08_140102](https://cloud.githubusercontent.com/assets/546983/13602317/4dddc660-e536-11e5-80e7-63d36476de29.png)

I also tested with https://tinokremer.nl/profile/tinokremer which works fine as the links are mentioned there.

I believe that block should be visible on the home page as well so people can login using their naked domain instead of the _ugly_ full profile link.

**Comment by physcocode** [comment]
Rel="me" works on solo theme for me , I think so it is not present in themes supporting multi user site . please try solo the and let me know :)

**Comment by danito** [comment]
I've switched back to a solo theme, and the rel=me links are only visible in the profile page and not on the home page anymore. see also conversation in the [known-dev](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/known-dev/65Gl1aAI5-c/z6EgU1wmIQAJ) group.

**Comment by kylewm** [comment]
Heh, it looks like I can reproduce this bug if I disable the StaticPages plugin.

StaticPages overrides Homepage and calls

```php
                        $this->setOwner($object->getOwner());
```

which is what seems to be missing from the main Homepage implementation

**Comment by tinokremer** [comment]
That may also be the cause of https://github.com/idno/Known/issues/1332 if I understand it correctly.

**Comment by kylewm** [comment]
I think you're right @tinokremer.

Anybody know what constitutes the "owner" of the site's homepage? I guess it really depends if it's a solo site or a group site, and I don't know of a way to differentiate them yet?

**Comment by tinokremer** [comment]
The Cherwell theme allows you to set the "user" that should be the owner.

Op di 8 mrt. 2016 21:15 schreef Kyle Mahan <notifications@github.com>:

**Comment by benwerd** [comment]
"Solo" themes can give the homepage a page owner. Honestly, it's a really horrible kludge.

What I'd like to do is make this a top-level switch across the board, and remove the idea of solo and group themes.

**Comment by kylewm** [comment]
Cool, that should be straightforward.

1. Add a toggle to the admin page
2. set "solo" = true/false in the Config
3. if solo and no other owner has already been set (e.g. by the Cherwell theme's configuration), then set the owner to the first admin user when rendering the homepage.

If that sounds good, I'm happy to implement.

**Comment by rikmendes** [comment]
Just to confirm this is now fixed 
![screenshot_67](https://cloud.githubusercontent.com/assets/12155003/13723097/48a7b1ac-e85a-11e5-944b-9f1781d56995.png)

But i still found some weird behavior just after the "git pull" I did to test on latest Git version when I used my Known instance to publish a status update about it : https://www.rmendes.net/2016/yes-seems-like-withknown-squashed-a-bug-now-i-can
that did got syndicated to twitter https://twitter.com/RikMende/status/708636558425886720 but the browser page crashed on this error : 

Warning: Illegal offset type in /rmendes.net/Idno/Core/Syndication.php on line 109

Warning: Illegal offset type in /rmendes.net/Idno/Core/Syndication.php on line 109

Warning: Cannot modify header information - headers already sent by (output started at /rmendes.net/Idno/Core/Syndication.php:109) in /rmendes.net/Idno/Common/Page.php on line 364

**Comment by kylewm** [comment]
Try updating your Twitter plugin?
