### ISSUE TITLE
Problems with Umlaut in the URLs

### ISSUE THREAD

**Issue by georgkaser** [idno/Known#1355]
## While trying to do this:

I posted a status update on my Known blog - with an german umlaut in the title. It's very common in german language.

## I encountered this error:
The URL looks like this:
https://geor.gs/2016/uii-an-der-serververf%C3%BCgbarkeit-m%C3%BCssens-aber-noch-ein-bissl-arbeiten
or this:
https://geor.gs/2016/fr%C3%BChst%C3%BCck-mit-dem-papa

In both cases bridgy was not able to bring my likes and my answers from twitter back to my blog.

## Some other notes:
All other posts work as excepted. I think it's because of the umlauts.

**Comment by kylewm** [comment]
should have been fixed in 2846c89370bb1af724b17bdcf333b9b760ff4eaf, have you tested with the latest code?

**Comment by georgkaser** [comment]
No, I haven't tested. Should I replace  Idno/Pages/Webmentions/Endpoint.php (I am on Version: 0.9.1)

**Comment by kylewm** [comment]
Yep! Patching that one file (just those two lines) is probably your best bet until the next version is released.

**Comment by georgkaser** [comment]
Kyle, you are great - it's working again :) thank you very much!
