### ISSUE TITLE
inexistent Reply notifications to my own post ? what's the point??

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1358]
## While trying to do this:
I post something new at my site https://www.rmendes.net/2016/why-do-i-get-reply-notifications-from-withknown-on-pages
## I encountered this error:
then i get several notifications that I replied to my own post, when I didn't & nothing show replies under the aforementioned post in the notification area.
![screenshot_70](https://cloud.githubusercontent.com/assets/12155003/13723578/b89465dc-e869-11e5-833b-b64c1a0f29b1.png)

## Some other notes:
Notice that notifications reply are about a static page on the same site that I would never reply to
I'm not even sure where this is coming from.  European Politics and Belgian Politics are 2 static pages running a rebelmouse aggregation on these 2 topics.

**Comment by kylewm** [comment]
My guess is that someone is sending webmentions on your behalf, and it exposes some flaws in Known's webmention receiver. e.g., it could be

* sending a webmention from the homepage / to pages linked to from the homepage
* sending a webmention from the http version of a URL to the https version of a URL.

Have you perhaps configured Superfeedr+Telegraph integration mentioned in this article https://aaronparecki.com/2016/02/20/5/global-webmentions

**Comment by kylewm** [comment]
managed to reproduce this by sending myself a webmention with `source=https://kylewm.com` and `target=https://kylewm.com/2016/03/i-have-upgraded-my-plugins-readme-with-a-perfect-gif` (a post on the homepage)

![screenshot from 2016-03-13 21-38-26](https://cloud.githubusercontent.com/assets/950127/13735206/f5be844c-e963-11e5-8349-fee66825c8dd.png)

kind of funny...

**Comment by rikmendes** [comment]
> Have you perhaps configured Superfeedr+Telegraph integration mentioned in this article https://aaronparecki.com/2016/02/20/5/global-webmentions

nope, I mean there is a superfeedr setting but I never messed with it. seems to be already configured.
not using telegraph. it seems In my case I just need to post a new item to my blog to generate notifications to previous posts/page & it all seems completely beyond my control..
