### ISSUE TITLE
Unknown SSL protocol error using "Like" and "Repost" prevents posting

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1360]
Cross posted from: https://github.com/kylewm/KnownReactions/issues/8 of @kylewm which may possibly be the culprit... 
## While trying to do this:
Create a "like" post using https://petermolnar.eu/press-this-indieweb/
(Using self-hosted official 0.9.1 with most recent KnownReactions plugin installed)

## I encountered this error:
![pm screen cap](https://cloud.githubusercontent.com/assets/5882943/13730392/1c793824-e90b-11e5-9f46-8801478e6fad.PNG)

The error prevents one from clicking save and making the post.  The issue was also replicated when attempting to “repost” (using KnownReactions) but not for “Share” or “Bookmarking” which are in core.

## Some other notes:
@petermolnar, Thanks for the mention of http://stream.boffosocko.com/2016/sharing-from-the-indieweb-on-mobile-android-with-apps-and on https://petermolnar.eu/press-this-indieweb/, glad you found it to be of use/interest.

I use both Known and WordPress for getting to know more about and actually using the indieweb, so I thought I’d mention that interestingly, I didn’t see a ping on the mention of my post (something which WordPress would have done automatically using a pingback) on Known. I’m hoping that perhaps as the indieweb grows, this type of cross-communication works itself out better, or that all URLs on all platforms default to using webmention.

Possibly more importantly, as you mention in the post that you monkeyed with some of your security settings, I wanted to let you know that I tried using Known (with KnownReactions installed) to “like” your post, but Known kicked back a security error that apparently wouldn’t allow it, indicating “Unknown SSL protocol error in connection to petermolnar.eu:443”.  [See also attached photo.] Typically Known would be querying your post to scrape the title from the post’s HTML to include as a description of what it is that I’m liking, so that I can then make the post to Known, which also thereby webmentions your post as well.

On the Known side, I’m not sure how often these errors pop up, but there should potentially be a way to manually fill in the description so that I can still make the post (clicking on the save button wouldn’t allow me to make the post).  I’m self-hosting the official version 0.9.1 which should have all of the updated plugins as of the last week (including [KnownReactions plugin](https://github.com/kylewm/KnownReactions) which may possibly be the piece preventing me from making the post, since it was a “like” after all). 

I’m cross-post this to the KnownReactions and IDNO github repositories for potential follow up there as well.

**Comment by benwerd** [comment]
This looks a lot like this server-side curl error, which is out of Known's scope: https://sourceforge.net/p/curl/bugs/1319/

**Comment by petermolnar** [comment]
I think I know what's causing this: SSLv3 is disabled on my webserver. It only accepts TLSv1, 1.1 and 1.2.

**Comment by kylewm** [comment]
Closing this one as it appears to be a system/library issue, outside of Known's purview. Chris do let us know if upgrading libcurl fixes it!
