### ISSUE TITLE
Extraneous text + URL returned when attempting to post via mobile

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1361]
### While trying to do this:
Trying to use the mobile protocol detailed [here](http://stream.boffosocko.com/2016/sharing-from-the-indieweb-on-mobile-android-with-apps-and) to bookmark, rsvp, reply, share (though it doesn't seem to be as obvious in this case), and similarly with like or repost (using @kylewm plugin [KnownReactions](https://github.com/kylewm/KnownReactions)).)

### I encountered this error:
all of the URL fields include some additional extraneous text from the page title which must be removed before being able to post to Known properly.

![known screenshot](https://cloud.githubusercontent.com/assets/5882943/13730909/4a08e834-e91a-11e5-807c-8f084bdb164c.png)

### Some other notes:
A possible fix is suggested in @kylewm [twitter post](https://twitter.com/kylewmahan/status/524947467087802368) by @snarfed using [this code](https://github.com/pfefferle/wordpress-indieweb-press-this/commit/2f1a3f0ead0b0df9303a066303b429036cf7b128) which I found via [Easy IndieWeb Interactions on Android](https://snarfed.org/easy-indieweb-interactions-on-android) that prompted me to begin noodling with mobile solutions. (Be sure to check out the comments on this last post for additional thoughts for fixing this issue.)

As an anecdotal, but hopefully useful UI-related aside, now that I can share, reply, bookmark, link, and repost to content on mobile in a dead easy way (via the ubiquitous Android share functionality for which I'm using [URL Forwarder](http://stream.boffosocko.com/2016/sharing-from-the-indieweb-on-mobile-android-with-apps-and)), my usage and posting to Known has magnified SIGNIFICANTLY!  I might suggest this as the killer feature that allows Known to _drastically_ expand usage. (I'll also say that this has been in combination with [KnownReactions](https://github.com/kylewm/KnownReactions) which I upvote 2x for inclusion into core functionality, if it's an option.)

I'm happy to hear about alternate potential mobile options if someone has a better path/UI set up which is built out already in addition to those mentioned above.

**Comment by kylewm** [comment]
> A possible fix is suggested in @kylewm twitter post by @snarfed using this code which I found via Easy IndieWeb Interactions on Android that prompted me to begin noodling with mobile solutions.

lol, great archaeology finding that conversation! And thank you for the nice words about my plugin :)

I totally agree we should strip off extra text. I'm tempted to do it on the server side (in PHP) rather than in JS like the press-this plugin.

I don't see any problem with just brazenly skipping any text that doesn't look like a URL in front of text that does look like a URL, i.e. `$url = preg_replace("/(.*?)\s(https:\/\/.+)/", '$1', $url)` which is a bit simpler.

**Comment by chrisaldrich** [comment]
@kylewm RE: Archaeology - This was actually the _easy_ part and is one of the greatest values of webmentions in general: once I'd found/seen the original post, having access to all the comments & mentions of that post in social media and other locations actually made it a no-brainer to find the conversation with the solution! (Though I do notice that there's a display issue on that original post with how my more recent webmentions from Known are showing up -- but that's another problem altogether.)

**Comment by kylewm** [comment]
@chrisaldrich you mentioned in your post that there were some other apps, in addition to Twitter's, that add text in front of the URL. Do you have some examples? (I'm thinking about whether to just strip all leading text, or whether to carefully excise "Check out @-so-and-so's Tweet: ")

**Comment by tinokremer** [comment]
Lot of apps that have a 'share' capability (either to Twitter or something else) add text in there. This is an example of a newspaper app (Volkskrant):

> Bestuurder Haaksbergen: 'Ik heb 1000 procent zeker geremd' http://www.volkskrant.nl/binnenland/bestuurder-haaksbergen-ik-heb-1000-procent-zeker-geremd~a4262829/?hash=d42680f2843f949a582bfc7e9ab2cb26ee6857e9 via @volkskrant

I would probably find the first "http" and then search until there is a space and use that as link (then you have https: or http2 as well :)
