### ISSUE TITLE
API: Cannot modify header information warning from Session::logUserOff

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1365]
logUserOff is called at the end of request, which tries to update headers (in setcookie)
after body has already been written, resulting in "Warning: Cannot modify header information - headers already sent..."

## While trying to do this:

(from Woodwind) fetch @sensiblemn's `/micropub/endpoint?q=syndicate-to` to get micropub syndication targets

```
curl -i -H "Authorization: Bearer ..." -H "Accept: application/json" https://sensible.mn/micropub/endpoint?q=syndicate-to
```

## I encountered this error:

I got the response:

```
{
    "syndicate-to": [
        "facebook::604496009638056",
        "twitter::sensiblemn"
    ],
    "syndicate-to-expanded": [
        {
            "id": "facebook::604496009638056",
            "name": "Sensible Minnesota",
            "service": "facebook"
        },
        {
            "id": "twitter::sensiblemn",
            "name": "sensiblemn",
            "service": "twitter"
        }
    ]
}<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/sensible.mn/public_html/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php:55) in <b>/var/www/sensible.mn/public_html/Idno/Core/Session.php</b> on line <b>334</b><br />
```

which has the proper JSON object followed by a warning message that doesn't parse.

## Some other notes:

This may be IndiePub specific, but I'd think the way logUserOff is called in a shutdown function, it would affect every API call.

**Comment by mapkyca** [comment]
Hmm... it looks like it's a problem introduced when we started destroying the cookie in log off (which is worth doing, but not in this instance). We need to destroy the session as the last thing the API does, but the cookie reset is optional. Perhaps the simplest thing to do would be to *not* send the cookie header if logout is called in an api request.

**Comment by kylewm** [comment]
Is it possible/desirable to avoid setting cookies altogether for API requests?

**Comment by mapkyca** [comment]
Setting on initial request is harmless,but no longer necessary since each request is signed. We *can* remove it! but it doesn't do any harm. The patch removes the unset for api.

**Comment by kylewm** [comment]
On IRC @skddc and @aaronpk mentioned it as weird, but I didn't know if it was actually a problem

```
# 09:37 raucao lol, it's setting a cookie in responses to micropub requests :)
# 09:38 aaronpk lol um, that probably shouldn't happen
```

http://indiewebcamp.com/irc/2016-02-22/line/1456162677231

**Comment by mapkyca** [comment]
It can be considered legacy at this point, but it won't cause any harm. 

It used to be necessary due to the way known used to short circuit logins and created a session, but this was a security risk as well as a ballache to code for so I fixed it a while ago.
