### ISSUE TITLE
known-0.9.1.tgz download has top-level . folder

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1368]
## While trying to do this:

Extract the `known-0.9.1.tgz` file I downloaded from https://withknown.com/opensource/
## I encountered this error:

The tgz file contains a top-level folder named `.`
## Some other notes:

The top-level folder should be called `known` or better `known-0.9.1`.

**Comment by benwerd** [comment]
I think this is a good idea for all packages at this point - but it does represent a structure change.

cc @timmmmyboy @pierreozoux

**Comment by timmmmyboy** [comment]
I'm not able to recreate this. When I download the .tgz I get a folder called known-0.9.1 upon extracting. I just checked and our installer uses the zip release but behavior is the same, we extract and then selectively move folders/files out of the known-0.9.1 folder it creates.

**Comment by cweiske** [comment]
```
$ tar --list -zvf known-0.9.1.tgz |head 
-rwxr-xr-x ben/staff       177 2016-02-20 19:17 ./._.
drwxr-xr-x ben/staff         0 2016-02-20 19:17 ./
-rwxr-xr-x ben/staff       177 2016-02-20 19:17 ./._.gitignore
-rwxr-xr-x ben/staff       796 2016-02-20 19:17 ./.gitignore
-rwxr-xr-x ben/staff       177 2016-02-20 19:17 ./._.htaccess
-rwxr-xr-x ben/staff      1638 2016-02-20 19:17 ./.htaccess
-rwxr-xr-x ben/staff       177 2016-02-20 19:17 ./._.travis.yml
-rwxr-xr-x ben/staff      3306 2016-02-20 19:17 ./.travis.yml
-rwxr-xr-x ben/staff       177 2016-02-20 19:17 ./._ansible.sample
drwxr-xr-x ben/staff         0 2016-02-20 19:17 ./ansible.sample/
```

**Comment by pierreozoux** [comment]
@benwerd for me, whatever suits you the best.
But it is better to have some consistencies between all the projects (known and plugins).

If not, this would become a nightmare :)
https://github.com/idno/Known-Docker/blob/b8d38c7524e51cdf23f839a5b2471b1151101748/Dockerfile#L43-L64

**Comment by cweiske** [comment]
This just bit me again. Now my dev folder is full of `._warmup`, `._templates` and other directories - all among my normal projects :/

**Comment by mapkyca** [comment]
the "." root directory is still present in 0.9.2's archive.

Definite bug in the archive creation script @benwerd

**Comment by mapkyca** [comment]
Perhaps we should just serve a tagged build from github, and let them do the archiving..?

This would also address #1073

**Comment by mapkyca** [comment]
Closing, this'll be fixed on the next release
