### ISSUE TITLE
sqlite setup: Undefined index: description in shell/simple.tpl.php

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1369]
## While trying to do this:
Setup a fresh known installation with sqlite

## I encountered this error:
`Notice: Undefined index: description in /path/to/known/templates/default/shell/simple.tpl.php on line 19 
`
## Some other notes:
Happens when loading the known URL in the browser after creating the `config.ini` with the sqlite settings:
```
database = "Sqlite3"
dbname = "/path/to/known/data/sqlite.db"
```

The URL in the browser is `.../begin/`

**Comment by kylewm** [comment]
this was fixed a while back (the day *after* the most recent release unfortunately) 4639d61dad97602d43d9caa5958b44ec3c8b0018
