### ISSUE TITLE
Feature Request: Add support for video uploads

### ISSUE THREAD

**Issue by neilr8133** [idno/Known#1374]
Feature request: Known already supports audio uploads, would love it if it could properly implement video uploads as well (cross-ref: #1373: video uploading works in some situations but seems to not be intended/reliable behavior).

I looked at the community plugin "Video" by Tyler Gillies but it is a stub and has no video-related functionality I could detect.

Thanks!  :-)

**Comment by benwerd** [comment]
Video uploads would be awesome.

There's a difficult user education problem here. Videos uploaded directly
from a phone are unsuitable for upload: the bitrate, and therefore the file
size, is way too high.

Typically services transcode these files to a lower bitrate, and optimize
the file for progressive downloading. (Not every video, including MP4 h.264
files, will stream as you play.)

Self hosters have very little hope of installing or maintaining the
infrastructure required for this themselves. You often need a combination
of ffmpeg, Handbrake, and sometimes ffmbc depending on the incoming file,
and the resulting server load would force shared hosting users to bump out
of their plans.

So: either users do home transcoding themselves, which is typically a very
fiddly process, or they need to depend on third party infrastructure to do
this.

It's possibly something Convoy could do, but because of the server loads
involved, it would likely need to cost more than $5 a month for many users.
Not only that, but YouTube keeps a copy of every original file as it stood
before transcoding for legal compliance reasons; Convoy would probably need
to do that too.

So, in other words, it's hard, and is the kind of thing that centralized
services can do far more easily. I don't write this expecting to
necessarily figure out a solution - but I figured it would be helpful to go
into the reasons why it's not there.

On Sunday, March 20, 2016, neilr8133 <notifications@github.com> wrote:

> Feature request: Known already supports audio uploads, would love it if it
> could properly implement video uploads as well (cross-ref: #1373
> <https://github.com/idno/Known/issues/1373>: video uploading works in
> some situations but seems to not be intended/reliable behavior).
>
> I looked at the community plugin "Video" by Tyler Gillies but it is a stub
> and has no video-related functionality I could detect.
>
> Thanks! :-)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1374>
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by neilr8133** [comment]
Thank you for the excellent summary.

That's what I was afraid you were going to say; on the other hand, I know
that iPhone users can send videos to other iPhone users, and I thought one
of my old Android phones could MMS videos that weren't originally shot in
'MMS-video friendly resolution' so I was hoping there was some onboard
resampling mechanism that could be tapped. (Progressive/adaptive streaming
would be AWESOME but I agree there would be quite a lot of overhead for
that!)   It sounds like maybe iPhone is doing something unique, and I'd
have to investigate what my old phone was doing.


-Neil

**Comment by mapkyca** [comment]
As a thought; could we use something like a youtube upload/embed instead? Not entirely a self hosted ethos, but....

**Comment by neilr8133** [comment]
'DEAR PEOPLE FROM THE FUTURE: Here's what we've figured out so far ...' [0] ;-)

(As of early April, 2016):

I looked into the YouTube suggestion, and found that you can upload "Private" videos (sharable to others who have a YouTube account) or "Unlisted" videos (shareable to anyone whether they have an account or not, but your account has to be 'in good standing').

I wasn't thrilled with introducing external dependencies, and I had, coincidentally, been doing research on adaptive-streaming technology, so I took a stab at seeing how far I could get with self-hosting options.  I believe I've gotten adaptive-streaming video to work from the webserver (Apache), and even figured out most of what would be necessary to [manually] embed the in a post, but there's one problem remaining which is causing the page to display a "Download File" link instead of displaying the video.  If I can figure that out (or if someone has suggestions on how to fix it), then we may have the basis of a solution.


For the benefit of others, here's the results of my research and experiments so far; it's far from optimal, but the results seem to be working.  (Note: I will use the term "WithKnown" throughout this message to refer to the Known software because in my experience Internet searches for "Known <anything>" don't work very well, whereas "WithKnown <something>" produce somewhat more useful results.)

## Background

Right now it looks like the two biggest technologies in HTTP adaptive-video streaming are MPEG-Dash and HLS.  Dash is created by a consortium and, from what I can tell, is supported by "most" of the browsers either directly or via JavaScript MSE (Media Source Extensions).  HLS is a competing protocol created by Apple, and most browsers only support one or the other.  Safari on iOS does not support MSE, although curiously Safari on the desktop *does*.  But from what I could see, most of the other browsers do not support HLS, so you basically need to support both if you want to cover the largest audience.

The good news is that there are some F/LOSS software tools (FFMpeg, GPAC/MP4Box) that can convert video to both HLS and Dash formats, and a free Dash reference player, so it looks like it's possible to support these formats without having to have someone else transcode/host/stream your videos for you!  Huzzah!  The bad news is that you are probably going to have to compile them from source yourself because some of the libraries are not GNU-compatible so they don't come with support precompiled.

Here's what [seems to be] working for me:

## Compile FFMpeg to support libfdk_aac

(On a virtual machine running Ubuntu 14[.04?] server edition, based off instructions from [4] to build in support for a bunch of different modules; it's probable that we don't need ALL of the extra third-party libraries but I figured it didn't hurt to include them):

    sudo apt-get -y --force-yes install autoconf automake build-essential libass-dev libfreetype6-dev libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev pkg-config texinfo zlib1g-dev yasm libx264-dev cmake mercurial libmp3lame-dev libopus-dev
    mkdir ~/ffmpeg_sources
    cd ffmpeg_sources
    hg clone https://bitbucket.org/multicoreware/x265
    cd x265/build/linux
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED:bool=off ../../source
    make
    make install
    make distclean   # This returned an error but seems to have worked anyway
    wget -O fdk-aac.tar.gz https://github.com/mstorsjo/fdk-aac/tarball/master
    tar xzvf fdk-aac.tar.gz
    cd mstorsjo-fdk-aac*
    autoreconf -fiv
    ./configure --prefix="$HOME/ffmpeg_build" --disable-shared
    make
    make install
    make distclean
    cd ~/ffmpeg_sources
    wget * http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.5.0.tar.bz2
    tar xjvf libvpx-1.5.0.tar.bz2
    cd libvpx-1.5.0
    PATH="$HOME/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests
    PATH="$HOME/bin:$PATH" make
    make install
    make clean
    cd ~/ffmpeg_sources
    wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
    tar xjvf ffmpeg-snapshot.tar.bz2
    cd ffmpeg
    PATH="$HOME/bin:$PATH" * PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
    --prefix="$HOME/ffmpeg_build" \
    --pkg-config-flags="--static" \
    --extra-cflags="-I$HOME/ffmpeg_build/include" \
    --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
    --bindir="$HOME/bin" \
    --enable-gpl \
    --enable-libass \
    --enable-libfdk-aac \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libtheora \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-nonfree
    PATH="$HOME/bin:$PATH" make
    make install
    make distclean

At this point the instructions said to run `hash -r` but I think that was just to generate checksums, and at any rate it didn't work on my system.

## Compile and install GPAC

This tool was available from the apt-get repos, but was very old and had some problems when I tried to use it, so I ended up compiling it from source and also adding in third-party libraries.

Instructions from [5] but specific for my version of Ubuntu

    git clone https://github.com/gpac/gpac.git
    sudo apt-get install subversion make pkg-config g++ zlib1g-dev libfreetype6-dev libjpeg62-dev libpng12-dev libopenjpeg-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev linux-sound-base libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl1.2-dev dvb-apps libavcodec-extra libavdevice-dev libmozjs185-dev
    cd gpac
    ./configure
    make
    sudo make install

## Download the HLS-creation script

I found a script [6] which causes FFmpeg to convert input files to HLS!  By default it worked fine an MP4 input file from my Android phone, but when I tried to convert an MOV from a borrowed iPhone it gave an error about mapping data from one stream onto another, so I ended up removing line 125 ("-map 0") and then everything seemed to work.

## Create the different Dash encodings

With both protocols, you take your source and re-encode it at different bitrates/qualities and the client can pick and switch between the available ones depending on realtime conditions.  For Dash, each audio and video resolution are stored in separate files (older tutorials, such as  [1,2] say that it's possible--although discouraged for compatibility reasons with different commercial players--to have pre-muxed input files, however the Dash reference player emits errors that basically say the filespec has changed and pre-muxed input files are not supported by the reference player).

Both formats also have "manifest files" which tell players about the different source media files that are available and provide information on how to switch between them.  For Dash, it's a single .mpd file; for HLS there's a top-level .m3u8 playlist file, and then each audio+video file there's another .m3u8 playlist.  Fortunately these are generated for us so we don't have to worry too much about them.  :-)

Based on some tutorials and my ad-hoc experiments, I ended up writing a few trivial scripts to do the conversions.  For Dash, they generate a "high quality" video, then two lower quality ones at 1/2 and 1/4 resolution.  I took a guess at what the bitrates would be, based on the assumption (from one of the tutorials) that 1500k was sufficient for the high-quality video, so there's probably a lot of room for optimization there.  It then invokes the Dash manifest-creation tool, and then creates the HLS files.  They are invoked with `rip_all.sh [INPUT_FILE] [DASH_INTERMEDIATE_OUTPUT_FOLDER]`.  Output files end up in `./dashify` and `./hls`.

    #!/bin/bash -xv
    # rip_all.sh
    
    declare -r INPUT_FILE=$1
    declare -r OUTPUT_PREFIX=$2
    
    # Convert to 3 audio and video formats
    ./rip_1.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 1500 1000 810
    ./rip_1.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 800 500 540 2
    ./rip_1.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 400 400 270 4
    ./rip_audio.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 44100
    ./rip_audio.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 22050
    ./rip_audio.sh ${INPUT_FILE} ./dash/${OUTPUT_PREFIX} 16000
    
    # Create the .mpd file
    MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out ./dashify/${OUTPUT_PREFIX}.mpd ./dash/${OUTPUT_PREFIX}_video_1500.mp4 ./dash/${OUTPUT_PREFIX}_video_800.mp4 ./dash/${OUTPUT_PREFIX}_video_400.mp4 ./dash/${OUTPUT_PREFIX}_audio_44100.mp4 ./dash/${OUTPUT_PREFIX}_audio_22050.mp4 ./dash/${OUTPUT_PREFIX}_audio_16000.mp4
    
    # Create the HLS version
    ./HLS-Stream-Creator.sh -i ${INPUT_FILE} -s 5 -o ./hls/${OUTPUT_PREFIX} -f -b 64,128,256,512
    
    echo "Finished at $(date)"

rip_1.sh:

    #!/bin/bash
    # begin rip_1.sh
    
    declare -r INPUT_FILE=$1
    declare -r OUTPUT_PREFIX=$2
    declare SCALE_FLAG
    declare BUFSIZE
    declare MAXRATE
    declare VRES=810
    
    if [[ -z $3 ]] ; then
        MAXRATE=1500
    else
        MAXRATE=$3
    fi
    readonly MAXRATE
    if [[ -z $4 ]] ; then
        BUFSIZE=1000
    else
        BUFSIZE=$4
    fi
    readonly BUFSIZE
    if [[ -z $5 ]] ; then
        VRES=810
    else
        VRES=$5
    fi
    readonly VRES
    if [[ -z "$6" ]] ; then
        SCALE_FLAG=""
    else
        SCALE_FLAG="-vf scale=w=iw/$6:h=ih/$6"
    fi
    
    ffmpeg -report -y -i ${INPUT_FILE} -c:a libfdk_aac -an -c:v libx264 -x264opts 'keyint=24:min-keyint=24:no-scenecut' -b:v ${MAXRATE}k -maxrate ${MAXRATE}k -bufsize ${BUFSIZE}k ${SCALE_FLAG} ${OUTPUT_PREFIX}_video_${MAXRATE}.mp4

rip_audio.sh:

    #!/bin/bash
    # rip_audio.sh
    
    declare -r INPUT_FILE=$1
    declare -r OUTPUT_FILE=$2
    declare SAMPLE_RATE
    
    if [[ -z $3 ]] ; then
        SAMPLE_RATE=44100
    else
        SAMPLE_RATE=$3
    fi
    readonly SAMPLE_RATE
    
    ffmpeg -report -vn -ar ${SAMPLE_RATE} ${OUTPUT_FILE}_audio_${SAMPLE_RATE}.mp4 -i ${INPUT_FILE}



## Set up Apache

In my experiments, I didn't need to make any configuration changes to Apache to get Dash streaming to work, but HLS was a different matter.  From [7], I added MIME registration for the HLS format to my top-level Apache configuration files:

    AddType application/x-mpegurl .m3u8
    AddType video/mp2t .ts
    AddType application/dash+xml .mpd   # Doesn't seem to really be needed but we'll do it anyway

Like the comment above says, I didn't need to register the .mpd extension originally but over the course of debugging it got added and I'm not aware of there being any harm to leaving it.

At this point you should be ready to add the Dash reference player from [6].  They have nice documentation on how to just drop-in a few lines of HTML+JS and use their CDN to get a player going and even have some hosted test videos so even if all you have is the ability to save an arbitrary HTML file you may still be able to embed DASH video.  However I wanted to "pin" to a specific version (and my site uses HTTPS so my browser was not happy with trying to load cross-site scripts via HTTP anyway) so I downloaded their player from [9] and saved it to the webserver (I used a folder outside my WithKnown tree).

To confirm functionality I uploaded all the videos to the webserver and made an HTML page (again, outside the WithKnown tree) that looked like this:

    <!DOCTYPE html>
    <HTML LANG="en">
    <HEAD>
    <script src="/dash.all.min.js"></script>
    <TITLE>HLS Demo</TITLE>
    </head>
    <BODY>
    <P>The video should be below here.</p>
    <video data-dashjs-player controls width="480" height="270">
            
            <source type="application/x-mpegurl" src="path_to_hls.mp4_master.m3u8" />
            
            <source type="application/dash+xml" src="path_to_dash.mpd" />
    </video>
    <P>The video should be above here.</p>
    </body>
    </html>

Once I confirmed that was working I went into the WithKnown admin pages and set the footer to include the SCRIPT tag that imports the dash.all.min.js file (rather wasteful, especially on mobile, because it's a 300K library and not every page will require it, but Good Enough For Now and I'm hoping that the Dash reference implementation will also include a player-only version that's smaller).

Finally, I loaded the WithKnown site, seleted the "New Post" option and toggled into the "Source Code" option ("<>") and copied the body of the test page to use for the post:

    <P>The video should be below here.</p>
    <video data-dashjs-player controls width="480" height="270">
            
            <source type="application/x-mpegurl" src="path_to_hls.mp4_master.m3u8" />
            
            <source type="application/dash+xml" src="path_to_dash.mpd" />
    </video>

Like I said, it almost works: it presents a box of the appropriate size but overlays it with a text link to download the video (which is downloadable, so access permissions should be correct).

I believe this is an accurate summary of my work so far, I tried to take careful notes but if I've found I left anything out I'll edit this post to try and present an accurate recipie for anyone trying to duplicate my work (unless we're able to fully bake a solution into WithKnown itself, obviously  :-)


## References
[0] http://xkcd.com/979/
[1] https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
[2] https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players-22/
[3] https://github.com/Dash-Industry-Forum/dash.js/issues/127
[4] https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
[5] https://gpac.wp.mines-telecom.fr/2011/04/20/compiling-gpac-on-ubuntu/
[6] https://github.com/bentasker/HLS-Stream-Creator
[7] https://bitbucket.org/walterebert/ffmpeg-hls/src
[8] https://github.com/Dash-Industry-Forum/dash.js
[9] http://cdn.dashjs.org/latest/dash.all.min.js

And possibly others.

**Comment by cweiske** [comment]
https://github.com/cweiske/withknownVideo brings tyler's video plugin into a usable state. It does no conversion at all, which is fine if you already have browser-ready mp4 video files.

**Comment by mapkyca** [comment]
Going to close, as this is a big project that I certainly don't have time for ;) PRs/Plugins welcome.

Also recently fixed a ranged request bug recently, which at least means the media plugin can theoretically handle video (although this functionality has been submerged as it's not widely supported sans transcoding)
