### ISSUE TITLE
Location check-in lookup stalls on 'Hang tight ... searching for your location

### ISSUE THREAD

**Issue by neilr8133** [idno/Known#1375]
## While trying to do this:
Check-in to a location.

## I encountered this error:
UI mostly populates but says "Hang tight ... searching for your location" and displays the 'throbber' but never acquires location or displays map (even after waiting >5 minutes).

## Some other notes:
* Bug manifests on Android using Firefox and Chrome.  (I think it manifests on laptop too but I'm not sure what behavior to expect on a device with no GPS.)
* I believe behavior has existed since at least Jan 27, 2016.
* Possibly this should be two bugs:
   1. Doesn't find the location and populate UI; and 
   2. Location search doesn't seem to ever 'time out' and display any error message
* #1336 ("Callbacks from Plugins not working on mobile Chrome on Android") sounded like a similar problem but fixed itself and no cause was ever identified.  (I tried following the link to 'android-remote-debugging' but got a 404 page so I don't know what they tried to do.)

**Comment by tinokremer** [comment]
For me it works fine. I use it in my own Journals plugin as well, the exact same code. Make sure you allow location access in your browser though. I did see issues with it before, but I was not able to reproduce it that evening when I got home from work. I still think the issue was in my phone, not knowing the location for some reason.

Opening Google Maps and let it get a fix from GPS might do the trick.

Does the check-in on your site work with a desktop browser? If not, could you post the console output (F12 in most browsers)

Lastly, you do not have a rooted phone and/or some kind of ad blocking features enabled?

**Comment by neilr8133** [comment]
I think I see the problem, although I'm not sure how to fix it:

Testing with a desktop browser (Firefox 44.0.2) I got the following:

        Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:4:25244
        POST 
        XHR 
        https://www.______.com/checkin/callback [HTTP/1.1 404 Not Found 18ms]

However my site is in a subfolder, at `www.________.com/foo/bar/` so I think it's not recognizing that it needs to load `/foo/bar/checkin/callback`.

Looking back at my notes, I have re-created the following sequence of events:

- A while ago, installed Known, used it for a period of time
- Known gained the ability to run from a subdirectory
- Exported Known data 
- Moved or installed Known code in subfolder
- Ad-hock folder migration (because people have mentioned migrating Known sites but I couldn't find any instructions, and even now the "Site Administration | Import" page only lists Wordpress and Blogger)
    - Dump the SQL database to file
    - Update the database SQL
      - `vi [database dump]`
      - `%s!www.________.com!www.________.com/foo/bar/g`
      - `%s!1.2.3.4!1.2.3.4/foo/bar!g`
    - `mysql -p [site db] < [modified db dump]

So this is at least 50% PEBKAC (depending on whether the plugin is supposed to auto-detect the folder it's running from), and possibly 100%.

So right now the question I have is: "Where does the Check-In plugin figure out the path to load?  Is it in a config file, or a setting that I haven't been able to find (despite searching)?  Or is it a bug that it doesn't recognize subfolders?"

Thank you,
-Neil

**Comment by kylewm** [comment]
@neilr8133 can you check to see if Ben's commit from yesterday resolves this issue for you? (It's a little annoying that GH doesn't send notifications for commits that reference an issue)

**Comment by rikmendes** [comment]
Works fine for me on Google Chrome on android Lolipop 

- it won't work if localisation is disabled on "Google settings" - > Position

**Comment by kylewm** [comment]
I think it's safe to assume this is fixed. Can reopen if it comes up with the updated code.

**Comment by neilr8133** [comment]
Sorry, took me until today to test and I literally just saw that this was
closed as I went to reply...

Updated from commit b01413f7f to commit 4fe57a743 but got this error in the
debugging console in Chrome:

https://www.________.com/foo/bar//checkin/callback Failed to load resource:
the server responded with a status of 500 (Internal Server Error)



-Neil

**Comment by neilr8133** [comment]
Confirmed fixed on the problem installation, thank you much!  :-)
