### ISSUE TITLE
Email notifications: cut to the chase

### ISSUE THREAD

**Issue by kylewm** [idno/known#1377]
I'd like to remove the "Hi! We wanted to let you know that" prefix from email notifications. When they pop up in a notification or on my phone, this would let me see more of the relevant information in the notification.

It might be cool to show this expository text (or maybe even a little bit more) for the first few email notifications, and then cut it out after a while?

**Comment by benwerd** [comment]
cc @erinjo

On Monday, March 21, 2016, Kyle Mahan <notifications@github.com> wrote:

> I'd like to remove the "Hi! We wanted to let you know that" prefix from
> email notifications. When they pop up in a notification or on my phone,
> this would let me see more of the relevant information in the notification.
>
> It might be cool to show this expository text (or maybe even a little bit
> more) for the first few email notifications, and then cut it out after a
> while?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1377>
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
As a reminder, these are templates which we could override - I for example strip HTML so the notification can be encrypted

**Comment by kylewm** [comment]
Good point @mapkyca; if other folks like the friendly greeting, I'm totally content to just do that.

**Comment by physcocode** [comment]
Well I support @kylewm at this point !

**Comment by benwerd** [comment]
I'm also in favor of this, fwiw. I think getting the email text to a point where it shows up in my notifications would be A+ good.

I'm not sure it has to be incompatible with a friendly body message - an email preheader should suffice. Does anyone have advice about how to optimize these?

**Comment by tinokremer** [comment]
Here is a webpage that shows how to do a preheader which seems to work fine with Gmail. I haven't tested myself: https://www.campaignmonitor.com/blog/email-marketing/2011/12/a-practical-guide-to-email-preheaders/

**Comment by mapkyca** [comment]
Bumping, since @erinjo has been doing some email template work recently...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1377" class="u-in-reply-to"></a>Did some experiments with this, and it's not just a simple matter of putting the span in the mention template...

Seems the preheader needs to be the first thing after the body tag, which doesn't fit too well with how we currently do templates, so we'd need to modify the core to give the option of passing a preheader with the notification...
