### ISSUE TITLE
Dreamhost still appears in /admin/about/

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1390]
Quick note in relation to https://github.com/idno/Known/pull/1359 
Dreamhost was taken out of the readme file recently, but I suspect it still appears prominently within the /admin/about/ page. Are there other occurrences built in?

**Comment by kylewm** [comment]
Hi Chris, I actually deleted that PR unmerged because it's none of my business to be changing that kind of thing :) Dreamhost was removed from /admin/about in https://github.com/idno/Known/commit/62e9e853c418b55b6cfc400e3527010e9325d87e but just hasn't been in an official release yet

**Comment by chrisaldrich** [comment]
It was way beyond my pay grade too :)
