### ISSUE TITLE
Percent character in status post leads to Bad Request

### ISSUE THREAD

**Issue by skddc** [idno/Known#1392]
## While trying to do this:

Open https://updates.kip.pe/2016/when-you-talk-or-write-about-the-1%-you-should

## I encountered this error:

HTTP status 400 - Bad Request

(Using Apache.)

**Comment by kylewm** [comment]
Duplicate of https://github.com/idno/Known/issues/1331 ?

**Comment by skddc** [comment]
Oops, sorry.

**Comment by kylewm** [comment]
No worries! It's been a while since the last release *nudge nudge* @benwerd ;)
