### ISSUE TITLE
just fyi : syndicate a status with a link to a wikipedia page to Facebook fails sometimes

### ISSUE THREAD

**Issue by danito** [idno/Known#1393]
## While trying to do this:

I created a status : https://nxd4n.nixekinder.be/2016/nix---wikipedia-la-enciclopedia-libre-9i with syndication to FB and twitter
## I encountered this error:

My FB account got logged out and I had to prove my identity and change password. The syndication to FB failed
## Some other notes:

The status links to https://es.wikipedia.org/wiki/Nix which shows a reproduction of a painting with a nude breast.

**Comment by benwerd** [comment]
Facebook invisibly censors links in its API, even when those links aren't illegal or abusive, which is not what one would normally hope for from a universal sharing platform.

**Comment by kylewm** [comment]
The docs could use a troubleshooting/FAQ section; this would be a good thing to include.

**Comment by mapkyca** [comment]
As an American platform they also, specifically, have a problem with boobs.

**Comment by benwerd** [comment]
It's not that they're American (Twitter doesn't impose the same
restrictions, for example). But they do censor some pages for their own
reasons.

I'm with Kyle: troubleshooting (and proactive notifications) would be good
here.

On Wednesday, April 27, 2016, Marcus Povey <notifications@github.com> wrote:

> As an American platform they also, specifically, have a problem with boobs.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1393#issuecomment-215127437>
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Facebook weirdness, going to close as I doubt it's something we can do anything about...

**Comment by danito** [comment]
Agree, but let's check if the FB plugin can catch and log this
