### ISSUE TITLE
Call to a member function getEntityClass() on boolean

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1394]
## While trying to do this:
Editing an existing page for a typo/modification
## I encountered this error: (when saving the page)
Fatal error: Call to a member function getEntityClass() on boolean in /rmendes.net/Idno/Core/PubSubHubbub.php on line 253
Oh no! Known experienced a problem!

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /rmendes.net/Idno/Core/PubSubHubbub.php:253 - "Call to a member function getEntityClass() on boolean", on page www.rmendes.net/pages/my-cv
## Some other notes:
I can confirm this happens when saving the page. 
the page get saved even though the crash bug happens without returning 
to the site when saving finished. 
![screenshot_116](https://cloud.githubusercontent.com/assets/12155003/14351591/765955bc-fcd0-11e5-846e-761be294558b.png)

**Comment by kylewm** [comment]
true, thanks for reporting!
