### ISSUE TITLE
Permalink generation for Unicode posts is broken

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#1404]
Here are two of my recent posts in the timeline:
http://www.evgenykuznetsov.org/content/all?q=%D0%B2%D0%BE%D0%BB%D1%88%D0%B5%D0%B1%D0%BD%D1%8B%D0%B9

The only difference is the upper one starts with a hashtag in Latin letters, the other one does not. Try clicking the direct link to the second one - it's broken.

Oh, and by the way: even the working link is generated in such manner that Facebook gets a Error 400 out of it — see https://www.facebook.com/evgkuz/posts/10153365275287085

**Comment by kylewm** [comment]
I am pretty sure this has been fixed in master (see #1354, #1331, #1392). We're overdue for a proper release (which includes upgrading the hosted site)... I know Ben has an awful lot on his plate right now, but I will try to prod him to do this soon :)

P.S. sorry this is frustrating, but thank you for the good Unicode test cases!

**Comment by nekr0z** [comment]
I actually did more testing, and here is what I've got reliably reproducing on current hosting version:

If a post (and a permalink, for that matter) begins with a non-ASCII characters, it is broken. If the first character in a permalink is ASCII, the permalink is valid.

For now my workaround is creating a post starting with a random alphanumeric character, saving it so a permalink is created, then editing that first character out. Works reliably, but is annoying as hell.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1404" class="u-in-reply-to"></a>I've not been able to replicate this on my local build (vanilla Known, latest checkout from repo).

Method: pasted paragraph from example page into status, stub and post created and displayed sucessfully.

**Comment by nekr0z** [comment]
@mapkyca Thanks for update. I've just tried on hosted, works as expected. Looks like this oe is finally fixed (at least for now).
