### ISSUE TITLE
Special characters in auto-created slug break webmention support

### ISSUE THREAD

**Issue by egoexpress** [idno/Known#1405]
## While trying to do this:

I wrote a status update on my self-hosted Known site. Known auto-created the slug for this. As the updated contained a german umlaut, this shows up in the slug as well like this as 'n**ü**rnberg':

https://known.stierand.org/2016/04/indiewebcamp-nürnberg-2016-is-live-eventscfi2461bb39rd4ajmr85huj2dp0-indieweb-indiewebcamp-iwc16

## I encountered this error:

As this status update got posted to Twitter as well and got some likes there, brid.gy tried to collect those and send them back to my site. If failed here because the URL somewhere got encoded wrong (now showing 'n**\xc3\xbc**rnberg' instead of 'n**ü**rnberg'). No handler for the status update can't be found as the original URL and the one requested don't match.

[Sat Apr 16 22:40:51.257955 2016] [:error] [pid 222] [client 172.17.0.11:43582] Known (known.stierand.org): error - Could not find handler for https://known.stierand.org/2016/04/indiewebcamp-n\xc3\xbcrnberg-2016-is-live-eventscfi2461bb39rd4ajmr85huj2dp0-indieweb-indiewebcamp-iwc16

## Some other notes:

Some other tools generating slugs (like Wordpress) strip special characters out of the slug in the first place preventing such issues. Maybe this is an option here as well.

**Comment by kylewm** [comment]
I think this is the same as #1404?

**Comment by egoexpress** [comment]
Could be related to #1404 and the other issues posted therein.
However, my slug is at least working and doesn't throw a HTTP 400. So its somewhat different, at least in the resulting effect.

**Comment by kylewm** [comment]
Ah sorry for jumping to that conclusion, you're right. Are you running code from github, or the release from withknown.com?

**Comment by kylewm** [comment]
OK found it, this was #1301 and will have been fixed in https://github.com/idno/Known/commit/2846c89370bb1af724b17bdcf333b9b760ff4eaf#diff-d521d33f35592f0fa363e4ac902f80ce

**Comment by egoexpress** [comment]
I'm currently running the 0.9.1 release code. Thanks for the pointer to the other issue, this looks like the error case I'm having. As I already planned to setup a dev site I'll switch to the github code for that one and I hope that the next release will come soon.

**Comment by kylewm** [comment]
@egoexpress since it's such a tiny change, you could just manually remove `urldecode()` from those two lines in Idno/Pages/Webmentions/Endpoint.php on your production site.

**Comment by egoexpress** [comment]
Oh, right, just checked out the diff. Thanks!

**Comment by egoexpress** [comment]
Applied the change from 2846c89370bb1af724b17bdcf333b9b760ff4eaf on my site running 0.9.1. Resent webmentions using brid.gy - success!
