### ISSUE TITLE
Syndication of photo to twitter : add link to post if title is too

### ISSUE THREAD

**Issue by danito** [idno/Known#1408]
## While trying to do this:
Syndicate a photo with its title as status text. 
## I encountered this error:
If the title exeeds 140 signs, the text is truncated in the twitter status and if permalinks are switched off, no link to the rest of the text will show up in twitter

**Comment by kylewm** [comment]
Good timing, I was literally just working on this in the library that we're using to truncate text.

**Comment by kylewm** [comment]
@danito actually is your Twitter plugin up-to-date? I thought I fixed this issue a few months ago: https://github.com/idno/Twitter/commit/3363d947e0fff7b6249cfca52452fd40809eb006

**Comment by danito** [comment]
I thought I had every utd, but apparently not... you're right, it's fixed
