### ISSUE TITLE
Warning errors with .../MentionClient.php Known 0.9.2 / 3?

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1411]
## While trying to do this:

I saw the alert on my dashboard to upgrade to Known 0.9.3
so I "git pull" like I always do before checking if everything is fine and I usually do a test-post
to see if anything got wrong. my test post crashed with the errors below but still got saved : https://www.rmendes.net/2016/i-think-i-just-upgraded-withknown-but-the-about-page#comments

## I encountered this error:

Warning: array_key_exists() expects parameter 2 to be array, null given in rmendes.net/external/mention-client-php/src/IndieWeb/MentionClient.php on line 162

Warning: Illegal string offset 'body' in /rmendes.net/external/mention-client-php/src/IndieWeb/MentionClient.php on line 178

Warning: Illegal string offset 'body' in /rmendes.net/external/mention-client-php/src/IndieWeb/MentionClient.php on line 179

Warning: array_key_exists() expects parameter 2 to be array, null given in /rmendes.net/external/mention-client-php/src/IndieWeb/MentionClient.php on line 43

Warning: Cannot modify header information - headers already sent by (output started at /rmendes.net/external/mention-client-php/src/IndieWeb/MentionClient.php:162) in /rmendes.net/Idno/Common/Page.php on line 367

![screenshot_172](https://cloud.githubusercontent.com/assets/12155003/14783669/77635a00-0af1-11e6-83bb-9949a30de400.png)

## Some other notes:
by going back (after the warning crash) I could re-send the edit post and it crashed a second time but produced a duplicate post. when I tried to delete the duplicate I had just created I got the same warnings over. when going back to the root of the domain to see if the duplicate was still there, i had the Known info alert telling me the post got deleted correctly.

**Comment by rikmendes** [comment]
confirmed each new post produce a lot of warnings even though the post still get saved & published. 
![screenshot_173](https://cloud.githubusercontent.com/assets/12155003/14785201/efa81d0e-0af9-11e6-82db-8f88423cae31.png)

**Comment by kylewm** [comment]
Thanks for playing canary in the coal mine, @rikmendes! I really don't know how this happened, it looks like I lost my changes to `Idno\Core\MentionClient` somehow ... fixing asap

**Comment by rikmendes** [comment]
It's the least I can do :)
