### ISSUE TITLE
Export RSS encoding issues in the body

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1412]
## While trying to do this:

Exporting my site using "Export to WordPress"
## I encountered this error:

Body text of many posts contains strange characters
## Some other notes:

Correct representation (title):
`Liked Tantek &#xC7;elik's post on tantek.com`
Incorrect representation in the body:
`Liked Tantek &#xC3;&#x87;elik's post on tantek.com`

This is just one of the examples, I notice it with various different characters like é and such. I think something gets wrongly encoded.

This is the file, I renamed it to .txt to allow GitHub to store it: [test export 1 item.txt](https://github.com/idno/Known/files/234678/test.export.1.item.txt)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1412" class="u-in-reply-to"></a>I'm wondering if the export needs to be outputted as CDATA....

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1412" class="u-in-reply-to"></a>You may wish to try this against the latest version in github, as I just pushed some encoding changes to RSS

**Comment by mapkyca** [comment]
*think* this has been addressed, so closing. Reopen if still not fixed...
