### ISSUE TITLE
Posts from Known being buried by Facebook algorithm

### ISSUE THREAD

**Issue by fraserYT** [idno/Known#1415]
## Some other notes:
When I post anything through Known and push to Facebook, I'm suspecting that none of my friends are actually seeing any of my posts, since I get zero interaction. When I check Facebook, the posts are there, but they seem to be getting buried. I'm not exactly Mr Popular, but normally, if I post anything on Facebook directly, I could expect a few likes or a comment or two, but I have now posted 5 or 6 things via Known and haven't received a single interaction on any of them. 

Is this a known issue, or a possible problem with how I have configured it?

**Comment by danito** [comment]
Hi,
did you make your FB app public? I had the same and my app was still in dev mode and even I could see my posts from my Known site, noone else could.

**Comment by fraserYT** [comment]
it was still in dev mode so that seems likely. I've changed it now and will try it out, so i'll close this. Thanks
