### ISSUE TITLE
Fatal Error: /var/www/html/Idno/Data/Mongo.php:59 - "Class 'MongoClient' not found"

### ISSUE THREAD

**Issue by kescobo** [idno/Known#1417]
Trying to install Known on AWS EC2 instance with MySQL on their RDS. I pulled in the tarball from `http://assets.withknown.com/releases/known-0.9.2.tgz` yesterday. I ran the automatic installer, and after entering in my database info, I got the following error:

```
Oh no! Known experienced a problem!
Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /var/www/html/Idno/Data/Mongo.php:59 - "Class 'MongoClient' not found"
```

Not sure why it matters since I'm not useing MongoDB... any help would be appreciated.

**Comment by kescobo** [comment]
So I tried moving `Mongo.php` to a different folder and now I get the error 

```
Fatal Error: /var/www/html/Idno/Core/Idno.php:58 - "Class 'Idno\Data\Mongo' not found"
```

Looking in `idno.php`, it looks like the issue is here: 

```php
switch (trim(strtolower($this->config->database))) {
                    case 'mongodb':
                        $this->db = new \Idno\Data\Mongo();
                        break;
                    case 'mysql':
                        $this->db = new \Idno\Data\MySQL();
                        break;
```

Apparently `case` is set to mongodb? But I have no idea why that would be.

**Comment by physcocode** [comment]
is mongoDB extension for php properly installed ? is you instance properly running mongoDB? Likely the problem is due to unavailability of mongo extension for PHP

**Comment by physcocode** [comment]
changing database from mongodb to mysql manually in the config.ini file in your root folder

**Comment by kylewm** [comment]
> Apparently case is set to mongodb? But I have no idea why that would be.

Mongo is also the default if you don't have another database set. There should've been a step during /warmup/settings.php that either wrote config.ini itself, or had you copy/paste text into the config.ini in your Known directory.

**Comment by kescobo** [comment]
@kylewm That's probably it - I'll dig in and find it, or I might start from scratch and reinstall. I was poking around a lot and might have tweaked something by mistake. Thanks!
