### ISSUE TITLE
IndiePub sets API request to true, breaking OAuth callbacks

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1419]
## While trying to do this:

Implement an OAuth2 callback

## I encountered this error:

API Mode is set to true, breaking forward() and headers

## Some other notes:

This is down to the fact that OAuth2 always passes an access_token, we should only set API to true if this token is confirmed to be a Micropub token

**Comment by kylewm** [comment]
Hmm yeah I sort of remember this being an issue, there are some weird interactions if you have both enabled. Suggested fix makes sense to me!
