### ISSUE TITLE
Syndication format on micropub is obsolete, confuses woodwind and quill

### ISSUE THREAD

**Issue by kevinmarks** [idno/Known#1423]
## While trying to do this:
log into quill via known.kevinmarks.com
## I encountered this error:
https://github.com/aaronpk/Quill/issues/47
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 2
Message: array_key_exists() expects parameter 2 to be array, string given
File: /web/sites/quill.p3k.io/lib/helpers.php
Line: 208
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'array_key_exist...', '/web/sites/quil...', 208, Array)
#1 /web/sites/quill.p3k.io/lib/helpers.php(208): array_key_exists('service', 'twitter::kevinm...')
#2 /web/sites/quill.p3k.io/controllers/auth.php(217): get_syndication_targets(Object(ORM))
#3 [internal function]: {closure}()
#4 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#5 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#6 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#7 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#10 /web/sites/quill.p3k.io/public/index.php(23): Slim\Slim->run()
#11 {main}

which implies the syndication format is not working
## Some other notes:
woodwind has issues with it too, as it doesn't know what to display on the buttons

**Comment by kylewm** [comment]
I have a good idea how to fix this short term without changes to Convoy
