### ISSUE TITLE
Call to a member function deniedContent

### ISSUE THREAD

**Issue by dosch** [idno/Known#1435]
## While trying to do this:
Load the site
## I encountered this error:

Fatal error: Call to a member function deniedContent() on a non-object in **/domains/website.com/DEFAULT/Idno/Core/Session.php** on line **447**
## Oh no! Known experienced a problem!

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

`Fatal Error: /domains/website.com/DEFAULT/Idno/Core/Session.php:447 - "Call to a member function deniedContent() on a non-object", on page website.com/`

If you continue to have problems, [open source users have a number of resources available](https://withknown.com/opensource)
.

## Some other notes:
I use Known .0.9.2 (derbyshire) and tried to re-upload the files (omitting .htaccess and uploads), but to no avail...

**Comment by mapkyca** [comment]
Thanks for the report! This issue has been addressed by #1422; you can either wait for the next version or update to the latest from git.
