### ISSUE TITLE
Images missing for logged-out users

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1453]
This morning I updated to 0b6a121633ce80357aa684768dc6eb87fcd5f8f9
Images are now missing for logged-out users , server showing a HTTP 500 error.
When I rolled back to 74e5e9e2a5a7ba958b94a32e35c0f6f99eeff8dc the images are showing.
HTH

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>I'm not able to replicate on my localhost.

Could you take a look at the logs and post any errors you can see?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>... the only recent thing that touches file support recently was the partial content code, but I'll need actual error messages to confirm.

(and I'm not sure why this would only affect logged out users)

**Comment by markwaters** [comment]
I have moved forward through the commits and it breaks at 86e32d16766c9d885ffa40b1c768a5f6085eb8c2

I am testing by using a Firefox Private Window for viewing without affecting my usual logged-in session , my father also contacted me with the same issue when viewing my site using his tablet and not logged-in.

Do you want the Apache2 logs or is there a separate Known log file ?
If so where is it stored ?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>Apache logs, which should show the PHP errors. If you're uncomfortable putting them on github, feel free to email them to me.

**Comment by markwaters** [comment]
Error Logs sent via mail

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>Thanks, taking a look now....

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>Ok, try applying c81f18f and let me know how you get on...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453" class="u-in-reply-to"></a>Ok, I merged this change in, so you should be able to update without importing from my branch.

**Comment by markwaters** [comment]
Thanks for fixing the issue @mapkyca , and so quickly.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1453#issuecomment-220612356" class="u-in-reply-to"></a>Happy to help!
