### ISSUE TITLE
Chrome browser can't find my location

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1456]
## While trying to do this:

Create a new "location" post in Chrome (desktop or on Android mobile)
## I encountered this error:

I get a continually recurring "Hang tight ... searching for your location."
## Some other notes:

Alternate browsers on both mobile and desktop both seem to work without any problem. On both mobile and desktop version of Chrome, I've tried toggling every location related switch, clear caches, memory, etc. that I can think of. Nothing seems to work and I don't even get the popup asking me if I'll allow the browser access to my location.

It's been going on for a while, and potentially since I upgraded to 0.9.2, though I'm not sure that this may have been the cause. Has anyone else had this problem with the Chrome browser on desktop/mobile/both? Thoughts?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1456" class="u-in-reply-to"></a>Looks like you're getting an error back, but that's not being reported...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1456" class="u-in-reply-to"></a>Looking at this further, it looks like google's location api is now returning 404... so I'm going to go out on a limb and say this is actually a google chrome bug!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1456" class="u-in-reply-to"></a>Scratch that, that's just what google returns when it can't find you.

I managed to replicate when I connect via desktop routing through tor (so it can't locate via geoip) and no wifi (so it can't use skyhook).

Looks like the location JS needs a bit more debug, and a fallback to manual entry. Will put a PR through...

**Comment by chrisaldrich** [comment]
<a href="https://github.com/idno/Known/issues/1456#issuecomment-220827711" class="u-in-reply-to"></a>Thanks @mapkyca. I'm also more prone to think it's a chrome bug (or less possibly a quirk with how idno interacts with chrome). The one thing I haven't tried is blowing out the entire phone and reinstalling everything from factory, which I may sadly and coincidentally be forced to do later this afternoon for completely different reasons. I wish I had noted the date this started happening in relation to upgrading to 0.9.2 vis-a-vis upgrades/changes to my version of mobile chrome.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/idno/Known/issues/1456#issuecomment-220827711" class="u-in-reply-to"></a>After playing around with some settings and doing some uninstall/reinstall work, I have an even stronger suspicion that this is a chrome mobile specific issue.  

Uninstalling updates and reverting back to the factory installed version allows Known to ask for permission to use location and then finds the location properly.  Updating thereafter to the most recent version of chrome mobile then prevents Known from finding my location (and it doesn't ask for permission to use location either.)

Two other mobile browsers don't seem to have any issues.

**Comment by WilliamVercken** [comment]
Same issue for me on Chrome Desktop and Mobile. This is a fresh install.

In my JS Console, I just have two warnings (not errors).

jquery.min.js:4 :
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

VM5074:61 :
`getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

You should also consider a textual alternative instead of a geolocation.
