### ISSUE TITLE
Convoy infinity loop loading

### ISSUE THREAD

**Issue by hugoroy** [idno/Known#1457]
## While trying to do this:
1. In Admin > Connect services
2. Subscribe to Convoy
## I encountered this error:

I got redirected to my domain admin panel on "Connect Services" --- then it only loads infinitely something from domains.withknown.com

Tried the link by email http://MyDomain/convoy/token/?convoy_token=XXXXX (same result)
## Some other notes:

Glad to test Known again :-)

**Comment by kylewm** [comment]
At one point did this redirect loop thing happen -- Were you able to successfully sign up for Convoy (like give your credit card number and everything) but then when it redirected to your site, it wouldn't load the iframe correctly? Or did the loop happen before it got that far?

**Comment by hugoroy** [comment]
I got redirected back to the site after giving the payment info and on the admin panel, on my domain, I get infinite loading

**Comment by kylewm** [comment]
Dang, well, the 302 redirect from "connect" seems strange. That doesn't happen in mine:

![screenshot from 2016-05-21 13-47-10](https://cloud.githubusercontent.com/assets/950127/15450783/aec5be48-1f5a-11e6-9c0f-018b4b58caed.png)

This looks like a job for @benwerd!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1457" class="u-in-reply-to"></a>Anything in the error log?

Looking at the code there's only a couple of places that'd bounce to referrer, and that's if there's no hub defined or it couldn't connect to the remote hub.

The former is worth checking that you've not somehow overridden the hub in config, and that it's reachable.

Anything more than that is up to @benwerd, but it might be worth improving the debug in the client side convoy plugin..

**Comment by hugoroy** [comment]
From my side, I couldn't see anything in the console.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1457" class="u-in-reply-to"></a>Do you have a hub defined?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1457" class="u-in-reply-to"></a>... Not pubsub, but known hub.... which you should have defined, unless there's a bug in config.

What does it say in diagnostics?

**Comment by hugoroy** [comment]
I know about the PubSubHubbub hub which is https://withknown.superfeedr.com/ (the default). What other hub are you talking about?

This is a fresh install from the zip available on the website.

**Comment by kylewm** [comment]
It's attempting to connect to `domains.withknown.com/connect` which is the default `known_hub`, so I think that means it's set correctly. (Hub here is \Idno\Core\Hub -- "Hubs are central, or semi-central servers, that provide functionality for groups of Known users. Functionality may include managed cron jobs, feed parsing, social syndication, discovery, and more.")

> (I was able to connect to the Convoy services by going directly to the iframe by the way)

That's interesting. It looks like you have NoScript running, it'd be helpful to know if the same bug happens with it disabled? What about with all plugins disabled?

**Comment by hugoroy** [comment]
↪ mai 22, 2016 6:12 — Kyle Mahan:
> That's interesting. It looks like you have NoScript running, it'd be helpful to know if the same bug happens with it disabled? What about with all plugins disabled?

Yes. I deactivated noscript and get the same issue.

However, it's true that I don't get this in Chromium.

**Comment by kylewm** [comment]
what version of Firefox are you running? (grasping at straws :stuck_out_tongue:)

**Comment by benwerd** [comment]
This is weird. Perhaps try clearing your cookies for both your domain and *.withknown.com?

**Comment by hugoroy** [comment]
↪ mai 22, 2016 6:30 — Ben Werdmuller:
> This is weird. Perhaps try clearing your cookies for both your domain and *.withknown.com?

Same issue.

(firefox 46.0.1)

**Comment by mapkyca** [comment]
Is this still an issue?

**Comment by mapkyca** [comment]
Closing as Convoy is no longer part of OS core
