### ISSUE TITLE
URLs with percentage sign

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1461]
## While trying to do this:

Using the yourls URL shortener to shorten a link with a Known URL containing a percentage sign , for example
http://erinjo.xyz/content/all?q=%23Eurovision
The URL shortener returns 
http://erinjo.xyz/content/all?q=#Eurovision
Which doesn't work as expected in Known , it shows the regular full page instead of the page of the tag.

## Some other notes:

Raised the issue at the yourls issue tracker.
https://github.com/YOURLS/YOURLS/issues/1303#issuecomment-220946585

**Comment by kylewm** [comment]
I don't think there's anything Known can do about this -- `http://erinjo.xyz/content/all?q=#Eurovision` is a valid URL with a fragment identifier `#Eurovision` (which the browser doesn't even send to the server)

What happens with a URL that percent encodes other characters, like this?

http://www.evgenykuznetsov.org/2016/33-%D0%B5%D1%89%D1%91-%D0%B8%D0%B7-%D0%B2%D0%B5%D1%88%D0%BD%D1%8F%D0%BA%D0%BE%D0%B2

**Comment by kylewm** [comment]
Closing since it sounds like a bug in the URL shortener.
