### ISSUE TITLE
Cherwell template class img u-photo 

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1470]
## While trying to do this:

When changing the size of the browser window I noticed the u-photo class image (of the user) disappear. not the main user photo related to the post, this manifest on chrome on the comment area.
## I encountered this error:

full size
![screenshot_207](https://cloud.githubusercontent.com/assets/12155003/15652838/55c210b8-2689-11e6-9170-5d5cc6f9d232.png)

resized : 
![screenshot_208](https://cloud.githubusercontent.com/assets/12155003/15652850/6450870e-2689-11e6-8b81-54b28d9b9f0a.png)

![screenshot_209](https://cloud.githubusercontent.com/assets/12155003/15652858/6d346584-2689-11e6-8c25-7bbf7af57bd2.png)
## Some other notes:

While searching for the css code I noticed some strange "storify" mentions in the code, so I disabled the storify extention and now the behavior is back to normal. at least avatar icons are aligned with the comments. my user avatar still disappear when resizing manually but at least comments and avatars display fine when published.

**Comment by kylewm** [comment]
I don't really understand what's causing this, but it only happens for me on pages without comments, e.g.: https://known.kylewm.com/2016/05/oh-bridgy-youre-so-pretty-cant-you-understandits-guys-like

If I edit the HTML to put `<div class="annotations"></div>` in between the `clearall` and `annotation-add`, things line up properly again.

**Comment by rikmendes** [comment]
Glad you found it too, I was not sure the issue i posted was clear enough. 

I have come to the same conclusion, when there is comments or likes/reshare etc..it all line up nicely like here https://www.rmendes.net/2016/check-out-the-euref-data-hub-twitter-blurrt#comments

here a post without comments : https://www.rmendes.net/2016/le-gar-de-bfmtv-genre-%C3%A9tonn%C3%A9-que-le-gr%C3%A8ve-se#comments

**Comment by mapkyca** [comment]
Is this still an issue?
