### ISSUE TITLE
DOMDocument::createElement(): unterminated entity reference in RSS template

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1471]
## While trying to do this:

Checking logs to debug something else, spotted a PHP warning...

## I encountered this error:

```PHP Warning:  DOMDocument::createElement(): unterminated entity reference  required spying). Used the net without an adblock? Forget it. in /var/xxx/html/templates/rss/shell.tpl.php on line 30
PHP Warning:  DOMDocument::createElement(): unterminated entity reference  required spying). Used the net without an adblock? Forget it. in /var/xxx/html/templates/rss/shell.tpl.php on line 83```

## Some other notes:

Odd error.

**Comment by kylewm** [comment]
Something to do with this post having an `&` rather than `&amp;`? https://www.mapkyca.com/2014/shanehudson-benwerd-pretty-sick-of-everything-being-about-serving-you

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1471" class="u-in-reply-to"></a>Nice spot, I tried looking for the error but didn't think to actually look back in my own posts *doh*.

Probably means we need to htmlentities the text before parsing it to the domdocument then...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1471" class="u-in-reply-to"></a>I wonder if this is related to #1412...

**Comment by benwerd** [comment]
Needs to be in a CDATA block probably.

**Comment by pierreozoux** [comment]
Just hit it also.

I `s/&/&amp;/` and it fixed it. I use markdown editor, but not sure it applies for `status`?

Here is the post: https://blog.indie.host/2016/got-unlisted-from-11-blacklist-o-just-used-support1and1com-and
