### ISSUE TITLE
Bridgy interactions not working when Known is in a subdirectory

### ISSUE THREAD

**Issue by herbsmn** [idno/Known#1473]
## While trying to do this:

Get comments after I connected to Bridgy.

## I encountered this error:

target_not_found

https://brid.gy/log?start_time=1465382239&key=aglzfmJyaWQtZ3lyTQsSCFJlc3BvbnNlIj90YWc6ZmFjZWJvb2suY29tLDIwMTM6MTA0NDU3MzUyMjI5Njk2N19saWtlZF9ieV84MTgyNzE0NjgyNTU4ODIM

you can view other message errors at https://brid.gy/twitter/sensiblemn and https://brid.gy/facebook/sensiblemn

I think this error comes from the source code here:
https://github.com/idno/Known/blob/6f253664b4999a944a59d1bab7c4498efced3b0c/Idno/Pages/Webmentions/Endpoint.php#L91

This suggests that bridgy "could not find handler".

The code related to getting a handler seems to be at these two links: 

https://github.com/idno/Known/blob/6f253664b4999a944a59d1bab7c4498efced3b0c/Idno/Pages/Webmentions/Endpoint.php#L48

https://github.com/idno/Known/blob/6f253664b4999a944a59d1bab7c4498efced3b0c/Idno/Core/Idno.php#L525

## Some other notes:

I'm using Known in a subdirectory and use nginx.

I use the recommended nginx configs: https://github.com/idno/Known/blob/6f253664b4999a944a59d1bab7c4498efced3b0c/nginx.conf

**Comment by kylewm** [comment]
I don't think we've quite worked out all the kinks in nginx + subdirectory. Apache and nginx seem to want to do things very differently here, and it's been hard to come up with one solution that satisfies both.

Could you share your nginx configuration? When I had it mostly working I had a line like

```
    location /blog/ {
       try_files $uri $uri/index.html /blog/index.php?$query_string;
    }
```

**Comment by kylewm** [comment]
Diagnosed the issue... In `Idno\Core\Idno::getPageHandler()`, it strips off the prefix so `http://known.dev/blog/2016/testing` becomes `/2016/testing`.

However, `Idno\Core\Idno::addPageHandler()` adds all the page handlers *with* the subdirectory, so it's trying to match against `/blog/2016/testing`

```
PHP message: cleaned up target is '/2016/testing'
PHP message: checking begin/connect/? -> \IdnoPlugins\Convoy\Pages\Connect
PHP message: checking /blog/session/login -> \Idno\Pages\Session\Login
PHP message: checking /blog/session/logout -> \Idno\Pages\Session\Logout
PHP message: checking /blog/currentUser/? -> \Idno\Pages\Session\CurrentUser
...
```

**Comment by kylewm** [comment]
@herbsmn, I'm curious if the URL http://sensible.mn/blog/share?share_url=https%3A%2F%2Fkylewm.com%2Fn%2F4he5&share_type=reply

works for you? It uses the same route as webmentions, so I suspect it will be blank

**Comment by herbsmn** [comment]
Yeah, it was blank.
