### ISSUE TITLE
Files are not deleted (ever)

### ISSUE THREAD

**Issue by tinokremer** [idno/Known#1475]
## While trying to do this:
1. Add a post
2. Add a picture to that post by uploading one
3. Delete the post

## I encountered this error:
The uploaded file remains in the Uploads\* folder. I checked it several times, the Uploads folder is growing while my test installation has **no posts** anymore (I deleted them all).

## Some other notes:
For current users a lot of space can be recovered if the admin interface would have a "Cleanup" button somewhere in the Site Settings that deletes all files that are not referenced in any entity

**Comment by physcocode** [comment]
@tinokremer i noticed this and i have opened a pull request

**Comment by tinokremer** [comment]
Great! You are fast!!

Now I need to find a way to delete all orphan files that make up ~ 2 GB in total :)

**Comment by rikmendes** [comment]
Would be great to check if files are associated with a post and if not allow us to delete them...
that means all the stuff I have been deleting are still there... :/

**Comment by rikmendes** [comment]
Curious to know if the "Audio" post type is also concerned by this issue...because that means I have an explanation why my user disk-space is increasing that much..

**Comment by physcocode** [comment]
@rikmendes yes audio and any other attached files are also deleted :) I have tested

**Comment by physcocode** [comment]
@rikmendes it deletes any file attached to the post on deletion of post

**Comment by kylewm** [comment]
To be clear, this pull request will not change the behavior of the Media
plugin, only of Photos .
 
 
On Wed, Jun 15, 2016, at 09:54 AM, Pranjal Pandey wrote:
> @rikmendes[1] it deletes any file attached to the post on
> deletion of post
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
>

Links:

  1. https://github.com/rikmendes
  2. https://github.com/idno/Known/issues/1475#issuecomment-226249773
  3. https://github.com/notifications/unsubscribe/AA5_b-G6FY84w3N8zodQt9I1chI3-Yt9ks5qMC5HgaJpZM4I1VQp

**Comment by physcocode** [comment]
@kylewm nope you are wrong . If you look at the 3rd commit i have made changes to Idno/Common/Entity::delete() to delete all attachment after deleting post from database . It affect behaviour of all plugins

**Comment by physcocode** [comment]
@kylewm i was planning to do it plugin wise but i thought why not delete attachments of all types ? super optimisation!

**Comment by kylewm** [comment]
I apologize, was only looking at the commit linked above not the full PR! I retract my complaint :)
