### ISSUE TITLE
Giving "#" as Category name crash Known. 

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1479]
## While trying to do this:

I was teaching how to use Pages to my coworker
and she proposed to name the category of the page "#" so we did it.

and then : 
## I encountered this error:

Fatal Error: /www/IdnoPlugins/StaticPages/templates/default/staticpages/toolbar.tpl.php:34 - "Call to a member function isHomepage() on null", on page celinebouton.eu/

![selection_010](https://cloud.githubusercontent.com/assets/12155003/16412243/86348e34-3d2b-11e6-9878-1c1c4299e3a5.png)
## Some other notes:

I tried to do something about the error, first i disabled the StaticPage plugin from the config.ini file then I went into the database and removed the entry with 
DELETE \* FROM `metadata` WHERE `value` LIKE '#'
and successfully removed the row. 

but the problem persist the moment i reactivate the StaticPage plugin. 

Any idea How I can fix this ? I suspect I have another row to delete to completely return back to empty categories/pages on the database.

right now I have to disable the plugin to be able to use the website.

**Comment by kylewm** [comment]
> DELETE * FROM metadata WHERE value LIKE '#'

Whoa I'm not sure I'd have done that 😛 . You will still have the Entity in your `entities` table, could try `
```
SELECT * from entities where entity_subtype LIKE '%StaticPage';
```
and potentially delete the one that you don't like.

I definitely see the bug in the template. You can patch it like this https://github.com/idno/Known/compare/master...kylewm:fix-static-pages-crash ... but that's not the right solution -- I think there is a bit of a hack to treat categories that start with # as searches instead of actual collections of pages, and that needs a little more thought than I can give it right now.

**Comment by rikmendes** [comment]
I searched well before executing this : DELETE * FROM metadata WHERE value LIKE '#'
it was the only value I had since the site is completely new..I assumed this would be the entry of my category name. I hope I'm not wrecking my Known with this :/

I tried this SQL query : SELECT * from entities where entity_subtype LIKE '%StaticPage';
but does not return any results...

**Comment by rikmendes** [comment]
So if in the meantime I apply the patch, does it mean I will be able to activate the plugin StaticPages without crashing the site and move from there on?

**Comment by rikmendes** [comment]
Confirmed: by applying your patch I can activate the plugin (without crashing the site), go to the PAGE section, remove the category I still had (seems what I removed wasn't the actual category item) with the name # and move along :) thanks for your fix !

**Comment by kylewm** [comment]
Yay! Thanks for checking it out :)
