### ISSUE TITLE
Feature idea: Use TNTSearch in place of native SQL full-text search

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1481]
use https://github.com/teamtnt/tntsearch for full text search will solve major problems with search

**Comment by physcocode** [comment]
@chrisaldrich Elastic Search is a big no no for share hosting we have discussed in separate issue

**Comment by mapkyca** [comment]
I can see this being a plugin, but unlikely to be a core thing.. at least not right now.

**Comment by physcocode** [comment]
@mapkyca currently search is not pluggable! Needs some recent mainly because known is using objects mapping over relational database

**Comment by mapkyca** [comment]
Search might not be, but database handlers are. 

Someone could, for example, subclass the mysql handler and replace the object search with an elastic search overlay, or similar....

**Comment by mapkyca** [comment]
Closing, should be a plugin.
