### ISSUE TITLE
Using << >> in status text post hide the content between the characters 

### ISSUE THREAD

**Issue by rikmendes** [idno/Known#1485]
## While trying to do this:

Create a new Status text post with : **<< Your Text >>**
## I encountered this error:

No error but all the text between << and >> isn't displayed at all. 
## Some other notes:

If I edit the post and remove << >> the content is displayed fine. 

looks like Known is "interpreting" something where he should just show << the content text even if between >>

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1485" class="u-in-reply-to"></a>Probably means that those characters aren't turned to entities prior to being passed through HTML sanitisation....

**Comment by kylewm** [comment]
Huh, I would've expected you to use the unicode marks « … » instead of <<…>>. Is the latter common?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1485" class="u-in-reply-to"></a>Easier to type, certainly... I wonder if there's a case for quietly converting by way of a workaround....

**Comment by rikmendes** [comment]
@kylewm not common, but I never bother to find how to type this on my belgian keyboard
@mapkyca would be great to be able convert <<...>> to quote ?
ps: I used the status text post kind, not sure post/article type does this

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1485#issuecomment-236256736" class="u-in-reply-to"></a>I wouldn't be surprised if the editor converted them on the fly...

**Comment by mapkyca** [comment]
Is fixed in latest build

**Comment by rikmendes** [comment]
Cool ;)
