### ISSUE TITLE
AMP Validation Errors

### ISSUE THREAD

**Issue by lindner** [idno/Known#1498]
## While trying to do this:

Publish a site using Known at http://1500wordMTU.com
## I encountered this error:

Google Webmaster Console reports AMP validation errors.  One can find many from the [AMP Validation tool](https://validator.ampproject.org).
- The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 
- The tag 'head > style[amp-boilerplate] - old variant' is deprecated - use 'head > style[amp-boilerplate]' instead.
- The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate] - old variant' is missing or incorrect.
- The implied layout 'CONTAINER' is not supported by tag 'amp-img'

See more details on the [Validation Report](https://validator.ampproject.org/#url=http%3A%2F%2Fwww.1500wordmtu.com%2F2016%2Fwelcome-to-1500-word-mtu%3F_t%3Damp)
## Some other notes:

This is with the hosted version of Known on withknown.com, so unsure of which version it is currently using.

**Comment by mapkyca** [comment]
Possibly related to #1280

**Comment by mapkyca** [comment]
I don't really know enough about amp to really get into this, pull requests welcome of course. 

Looks like, among other things, that linking to stylesheets isn't permitted... which seems daft. The workaround seems to be to include the file directly inline, which will be possible for known core styles, and anything inserted by assets, but if you're not using either then urrrp... no go.
