### ISSUE TITLE
Can we get font awesome upgrade to the 4.6

### ISSUE THREAD

**Issue by srcr** [idno/Known#1500]
Simple feature request, can we get font awesome upgrade to the 4.6.
I'm running into the 'problem' that snapchat icons are not available.

**Comment by paulcmal** [comment]
For the time it takes to merge the update, you can update the files manually. They are located in external/font-awesome.

If you have a terminal on the server:
```
cd external/
rm -R font-awesome
git clone https://github.com/FortAwesome/Font-Awesome font-awesome
```

Alternatively, if you only have FTP/SFTP access to your website, you may download the [latest](https://github.com/FortAwesome/Font-Awesome/archive/v4.6.3.zip) font-awesome and replace the files manually with your (S)FTP client.

**Comment by srcr** [comment]
Hi @paulcmal thanks, I already have done that ;)
still I think updating it wouldn't be a bad idea.

**Comment by mapkyca** [comment]
Pull requests welcome :)
