### ISSUE TITLE
known-0.9.2.tar.gz full of 222 byte dotfiles

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1503]
## While trying to do this:
Extracting `known-0.9.2.tar.gz`

## I encountered this error:
There are many many files that have the same name as "normal" files, but are prefixed with `._` and are 222 bytes large

## Some other notes:
```
$ find . -name '._*'|wc -l
5504

$ ls -la
insgesamt 296
drwxr-xr-x 19 cweiske users 4096 Apr 24 02:51 .
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._.
drwxr-xr-x 94 cweiske users 4096 Sep  7 22:21 ..
drwxr-xr-x  3 cweiske users 4096 Sep  7 22:22 ansible.sample
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._ansible.sample
drwxr-xr-x  2 cweiske users 4096 Sep  7 22:22 chrome
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._chrome
drwxr-xr-x  2 cweiske users 4096 Sep  7 22:22 ConsolePlugins
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._ConsolePlugins
-rwxr-xr-x  1 cweiske users  696 Apr 24 02:51 CONTRIBUTORS.md
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._CONTRIBUTORS.md
drwxr-xr-x  2 cweiske users 4096 Sep  7 22:22 css
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._css
drwxr-xr-x  6 cweiske users 4096 Sep  7 22:22 docs
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._docs
-rwxr-xr-x  1 cweiske users  987 Apr 24 02:51 docs-mkdocs.yml
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._docs-mkdocs.yml
drwxr-xr-x 28 cweiske users 4096 Sep  7 22:22 external
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._external
...

$ ls -la js/
insgesamt 36
drwxr-xr-x  3 cweiske users 4096 Sep  7 22:22 .
drwxr-xr-x 19 cweiske users 4096 Apr 24 02:51 ..
-rwxr-xr-x  1 cweiske users 5538 Apr 24 02:51 default.js
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._default.js
-rwxr-xr-x  1 cweiske users 1248 Apr 24 02:51 embeds.js
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._embeds.js
drwxr-xr-x  3 cweiske users 4096 Apr 24 02:51 templates
-rwxr-xr-x  1 cweiske users  222 Apr 24 02:51 ._templates
```

**Comment by mapkyca** [comment]
Isn't this #1368...? 

I've not been able to replicate this. 

Those look like something is generating lock files and not tidying them up for whatever reason. 

My guess would be that they're temporary files generated either by your unzip program, or if you're ftping them to your server, by your file transfer program.

Definitely doesn't appear to be anything in the .zip...

**Comment by cweiske** [comment]
They are in the tgz:

```
$ wget http://assets.withknown.com/releases/known-0.9.2.tgz
$ tar xlvf known-0.9.2.tgz |head
./._.
./
./._.gitignore
./.gitignore
./._.htaccess
./.htaccess
./._.travis.yml
./.travis.yml
./._ansible.sample
./ansible.sample/
```

**Comment by mapkyca** [comment]
Soz, I meant gz.

Interestingly, this appears to be a bug/feature of either the (presumably) mac tools used to compress, or the tools used to extract.

If you use gnu tar/gunzip you get the weird dot files, but if you use the Ubuntu GUI to extract, you don't.

I'm going to give this one the Gaelic shrug, and suggest that whatever it is that is used to package up known releases (which is @benwerd's domain) be replaced prior to the next release build.

**Comment by cweiske** [comment]
I think it would be good to have a script (or ant or phing) to create a release.

**Comment by mapkyca** [comment]
My €0.02 is that we distribute from tagged branches in github, but that's not really my call
