### ISSUE TITLE
Micropub authorization does not work on fastcgi servers

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1509]
## While trying to do this:

Post a note via micropub on a apache web server that uses fastcgi to speak with PHP
## I encountered this error:

`403 Access denied`
## Some other notes:

Micropub bearer tokens are transmitted via the `Authorization` HTTP header.
### Authorization header

On fastcgi, the HTTP `Authorization` header is not available in `$_SERVER` (ant neither in `getallheaders()`). There is no trace of it visible.

To make pass the header to PHP, `.htacess` must be modified:

```
RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

or

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

Both variants make the header available at `REDIRECT_HTTP_AUTHORIZATION`.
There is no way to get rid of the `REDIRECT_`.
### known

Known's `Idno/Common/Page::getallheaders()` uses PHP's in-built `getallheaders()` function, which does not contain the rewritten `REDIRECT_HTTP_AUTHORIZATION` header.

To fix the issue, the call to `getallheaders` must be removed and only the fallback variant be used.

The nginx fallback variant must be extendet:

```
foreach ($_SERVER as $name => $value) {
    if (substr($name, 0, 14) == 'REDIRECT_HTTP_') {
        $name = substr($name, 9);
    }
    if (substr($name, 0, 5) == 'HTTP_') {
```

With those changes (.htaccess and Page.php) micropub works.

**Comment by mapkyca** [comment]
Can close?

Your patch seems to have been merged...
