### ISSUE TITLE
Time zone module #enhancement

### ISSUE THREAD

**Issue by erinjo** [idno/Known#151]
This is mostly for me, as a reminder. 

I would like a module for users' profiles that displays their current local time. This might be as simple as a current time display based on a setting they've selected in their settings.

In the future I'll be using this for a private community install, where members are potentially in different locations, and you might want a quick refresher on who's working in which time zones. 
##

**Comment by benwerd** [comment]
Bumping this - a pretty neat idea, particularly for (eg) students participating in a remote course from lots of different places.

**Comment by mapkyca** [comment]
This would be cool. 

Also could be used for meeting resolution - e.g. send an event, invite folk, and the software does a handshake as to what time that event is for all the folk invited.
