### ISSUE TITLE
Micropub: action=delete not implemented

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1514]
## While trying to do this:
Delete an existing post via [micropub's `action=delete`](http://micropub.net/draft/#delete).

## I encountered this error:
```
HTTP/1.1 500 Internal Server Error
...
Couldn't create note
```

## Some other notes:
When this gets implemented, maybe undeleting can also be added.

**Comment by kylewm** [comment]
Appreciate you filing these issues @cweiske.

Full compatibility with the CRUD/JSON spec is not an itch for me personally; I cannot speak for anyone else, but my guess is that these issues won't be fixed soon 😕 Pull requests are of course welcome!

**Comment by cweiske** [comment]
Undelete is not possible since the posts are really deleted in the database.
