### ISSUE TITLE
Non semantic markup

### ISSUE THREAD

**Issue by smth** [idno/Known#1530]
I'm looking at Known for the first time. Really like POSSE concept. One of my first impressions though is "this is going to be a pain to theme". If the HTML was purely semantic, then a lot could be done by adding a stylesheet, but with all the Bootstrap stuff in there, all the templates would really need to be replaced to make any significant changes (which looks like a daunting prospect at the moment).

**Comment by cweiske** [comment]
Known has full support for [microformats](http://microformats.org/), which can be used to extract information from the page.

**Comment by physcocode** [comment]
Building theme is really easy you dont actually need to "replace" stuff in bootstrap . I have made two themes for known and you can always refer the docs . 
Just dropping CSS in known will do the stuff as known support microformats for extracting in formation . This all boil downs to Semantic after everything is extracting it is just HTML all over the page !
You can see www.github.com/physcocode/material how easy it is !

**Comment by smth** [comment]
Thanks for the replies. I have read the Theming docs, but didn't see anything about changing the structure of a page. I think I'm probably missing something. If someone wanted to create a homepage for example, without all the `row` and `col-md-` (this is the non semantic stuff I'm referring too), how should they go about it?

Are you saying @cweiske that the content should be pulled into an entirely separate page, outside of the Known installation?

**Comment by cweiske** [comment]
No. I misunderstood what you said about "semantic markup". Ignore my comment.

**Comment by physcocode** [comment]
@smth you could actually override complete homepage of known (of course not recommended) the docs are relatively new I would strongly suggest you to look at code of solo theme ! I too had these doubts during making of theme . And many of known theme uses CSS and elements not present in bootstrap!
