### ISSUE TITLE
feature request: plugin to upload presentation slides

### ISSUE THREAD

**Issue by schiessle** [idno/Known#1542]
Everytime I share some of my presentations on slideshare.net or a similar platform I wonder why there is no way to do this in a self-hosted way. I think it would be a great addition to known if I could share my slides in a way that people can easily click through it, download it and comment on it.

What do you think?

**Comment by cweiske** [comment]
This is not trivial, and should most definitely not be part of the core - rather a plugin.

**Comment by danito** [comment]
If you want to host your own slides, it's not so easy, as one needs to create a presentation viewer for Known.
If you're fin with just embed Slideshare presentation in one of your posts, then it can be easily done by taking the embeding code and paste it into a new Post's source code. You get this code when you click on the share-button of the slide.

You can see how it looks like here https://nxd4n.nixekinder.be/2016/slideshare-test

**Comment by mapkyca** [comment]
Would be cool, but yes... plugin not core. Closing for now.
