### ISSUE TITLE
Fetching feeds from Social Network - Feature Request

### ISSUE THREAD

**Issue by harshjoshi55** [idno/Known#1545]
I got a feature request that if we can fetch user timeline from particular social networks it would be awesome please look in to the request and revert

**Comment by mapkyca** [comment]
This is not an official comment, but I can pretty much say that this is not going to be something that's possible. 

Pulling content out of the main social networks is something that, if it's even possible via their api, is something that would definitely be against their terms of service.

A one time import via something like the facebook export archive might be something that's possible, or if an RSS feed is something that is available, which is not something that facebook does certainly.

**Comment by harshjoshi55** [comment]
We can fetch from the social networks there is an iOS app for it named Social Stream 
I tried for Facebook for an app and I am receiving data in JSON format but not able to convert in an view

**Comment by harshjoshi55** [comment]
Facebook doesn't allows directly from the api but we can use follow method for it for fetching only important feeds from Facebook and Twitter , LinkedIN and Instagram is open and we can get the data via API I guess

**Comment by kylewm** [comment]
I don't totally understand what you want Known to do with feeds from social networks, but have a look at https://granary-demo.appspot.com/

**Comment by harshjoshi55** [comment]
it could be like one stop place for a user he can manage blog , social sites and stay updated thanks a lot for that link I will try to integrate that with known

**Comment by physcocode** [comment]
Agreed with @mapkyca it's against the privacy terms mlto use someone else data RSS import is an option but that does not import anything posted by other users in support of @kylewm I do agree it's not something worth part of known @harshjoshi55 if you are able to import json from face book (as you mentioned ) you can actually make a entity plugin that would parse json and convert it to known entity then you can use the standard entity view (like status) to display it on the user stream 
CC @benwerd

**Comment by harshjoshi55** [comment]
thanks @physcocode

**Comment by physcocode** [comment]
@harshjoshi55 http://docs.withknown.com/en/latest/developers/plugins/ here is the doc see how your plugin can make a new entity just use the json data to fill the data of entity and boom you are ready !

**Comment by physcocode** [comment]
@harshjoshi55 on a side node you can use https://granary-demo.appspot.com to import data in microformats whichbis out of the box supported by known !

**Comment by physcocode** [comment]
I think we can close this @harshjoshi55 @kylewm ?
