### ISSUE TITLE
Update Symphony components

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1554]
## While trying to do this:

Use MongoDB sessions after #1551 
## I encountered this error:

Symphony Mongo DB session handler only supports old style Mongo clients. The latest code supports the supported Mongo client classes.

**Comment by physcocode** [comment]
I suggest hand I'n hand we move to composer yo and publish known in same !

**Comment by mapkyca** [comment]
I'd prefer not to use composer, as I've mentioned before elsewhere. Git submodules works fine for me, although I know folk have problems at times, but bundling in the main archive is the least worst option so far...

**Comment by mapkyca** [comment]
This seems to be no small undertaking, so downgrading for now.

**Comment by mapkyca** [comment]
Closing, I don't need this headache right now.
