### ISSUE TITLE
New release and development activities 

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1561]
There have been many merges and changes since last release features like actual deleting of media , various webmention fixes and much more .. there should be a new relese 

PS : there have been a decline in development activities in known. . I suggest @benwerd should release some roadmaps so enthusiastic known developers like me can work on new features and boost activities of known .

CC @mapkyca @kylewm your thoughts please . 

Regards,
      A Known developer

**Comment by kylewm** [comment]
@physcocode are you on the mailing list? there's been some discussion of this lately, e.g. https://groups.google.com/forum/#!topic/known-dev/cRzukB6DBVs

**Comment by physcocode** [comment]
@kylewm thanks for pointing me that out as I was too lazy to check Google groups . @benwerd mentioned there are many people working on known and not all contributions have been pushed to open source , so can we assume work is done for known pro ?

**Comment by erinjo** [comment]
@physcocode There is a lot of work being done for our enterprise clients.

**Comment by physcocode** [comment]
@erinjo just a question .. is there a slab for corporate sponsors 
PS: I knie it's not the right place . Where should I contact for same ?

**Comment by mapkyca** [comment]
Speaking for myself, my time is limited, so new features are largely driven by necessity (paid projects / itch scratching). I suspect it's the same for others.

As noted above, community driven road maps has been/is being discussed in the mailing list. Nothing official for how community desires could feed into roadmaps, but I suggest we look at how other projects do it. Largely this seems to be done as a matter of "the squeeky wheel gets the grease" :)

For a direction for community developers, I would suggest that obvious bugs are pretty safe to work on. New features, well, pull requests are always welcome, but in no way guaranteed to be merged... so it might be worth mentioning it in the group before embarking on any massive flights of fancy. Your own forks and your own plugins are of course your own business :)

Closing this ticket, further discussion should go to the group...

**Comment by physcocode** [comment]
@mapkyca totally convinced
