### ISSUE TITLE
Decouple session interface

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1565]
## While trying to do this:

Use something else other than file or the specific DB to store sessions

## I encountered this error:

Can't

## Some other notes:

Session handling should be decoupled from datastore, so you can e.g. use a mysql db and a memcache session

**Comment by physcocode** [comment]
I was just going to file this after an failed attempt to use redis with symfony . But I really have no idea where things are going wrong 
1) I made changes in core replaced database adapter with stash 
2) Boom I could not login
