### ISSUE TITLE
get page title for Bookmarks

### ISSUE THREAD

**Issue by danito** [idno/Known#1573]
## While trying to do this:

Bookmarking a page
## I encountered this error:

html entities are decoded as is, so & quote; will be decoded to & amp;quote; (without the spaces)
## Some other notes:

is there any reason to not use html_entity_decode in place of htmlspecialchars_decode in
 https://github.com/idno/Known/blob/master/IdnoPlugins/Like/Like.php#L63 ?

**Comment by physcocode** [comment]
Well it's just a safer play towards xss injection . I actually agree on using htmlspecialchar_decode though

**Comment by danito** [comment]
Is there any way to sanitize the title and get rip of &_amp; at the end?
A page returning
````html
<title>YODABLOG &raquo; Episode 497 : Sith Down</title>
````
will be htlmspecialschars_decode as
````
YODABLOG &amp;raquo; Episode 497 : Sith Down
````

**Comment by mapkyca** [comment]
Still a thing?

**Comment by danito** [comment]
No, I don't get why but know the title with & raquo; are not double decoded anymore : 
https://nxd4n.nixekinder.be/2017/yodablog-episode-497-sith-down
