### ISSUE TITLE
Make profile feeds configurable

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1587]
## While trying to do this:

Display the profile feed

## I encountered this error:

Profiles only display status and blog posts in feeds, it should probably be configurable on content type, like the main feed is.

**Comment by benwerd** [comment]
TBH I think the fewer configuration panels the better. A plugin could always override this.

**Comment by mapkyca** [comment]
Fair enough, although would it make sense to simply reuse the same setting as the main feed? i.e. we show on the users profile what the default setting for the main feed is?
