### ISSUE TITLE
API photo/edit body seems not to get decoded

### ISSUE THREAD

**Issue by danito** [idno/Known#1594]
## While trying to do this:
posting a photo to my known site with API
## I encountered this error:
While the _body_  that I sent had been urlencoded(), it seems that it is not decoded (while the title was decoded). 
## Some other notes:
This is what I get:
this+is+a+%23test+description

**Comment by mapkyca** [comment]
Got an example of code/script you're using?

**Comment by danito** [comment]
I did a test with https://github.com/mapkyca/BashKnown/blob/master/photo.sh
I added a line to urlencode the body message (which is done in status.sh)

````bash
read post

syndication="${@:6}"
syn=""

for word in $syndication;
	do 
	enc=$(echo -n $word | php -r  "echo urlencode(file_get_contents('php://stdin'));");
	syn="${syn}syndication%5B%5D=$enc&";
done

#added by me:
mdata=$(echo -n  $post | php -r "echo urlencode(file_get_contents('php://stdin'));")

ACTION='photo/edit'
HMAC=$(echo -n "/$ACTION" | openssl dgst -binary -sha256 -hmac $3 |  base64 -w0)

NEWDATA="${syn}title=${4}&body=${data}"

# Temp cookie file
COOKIE="/tmp/$(basename $0).$$.tmp"

curl -sS -c $COOKIE -L \
	-H "Accept: application/json" \
        -H "X-KNOWN-USERNAME: $2" \
        -H "X-KNOWN-SIGNATURE: $HMAC" \
	-H "Content-Type: multipart/form-data"  \
        -F "photo=@${5};filename=alert.jpg;type=image/jpeg" \
        -F "title=${4}" \
	-F "body=${post}" \
	$1/photo/edit | python -m json.tool

rm $COOKIE

````
I didn't check with the title field yet

**Comment by danito** [comment]
I added a command to urlencoding the title, same happens: https://nxd4n.nixekinder.be/2016/tite%2523test

**Comment by mapkyca** [comment]
Have you tried not url encoding the parameters? 

IIRC *pretty* sure you don't need to do that for multipart/form-data, but I'm not at my computer atm so can't check.

**Comment by danito** [comment]
You're right :
http://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data/4073451#4073451
