### ISSUE TITLE
Dementia

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1595]
## While trying to do this:
Find older posts / bookmarked pages / tracks

## I encountered this error:
Missing items.

## Some other notes:
I recently switched hosting providers leaving the old installation at commit be70233 and keeping the new installation at the latest commit. Imported the database. Everything went perfectly.

Last night I posted a Track using the Track plugin , no problems , changed the Filter to show me just tracks and now I can only see a single track. Oh no. Checked the Bookmarked Pages filter - Nothing even though I have posted a few items previously. Aarrgghh.

Searching for tags I know I used on previous posts - nothing shows up.

Changed my local DNS hostname to use the previous server still on the old be70233 commit version and everything is still there and working as expected.

Tried a 'git checkout be70233' on the new installation but Known then fails with a white page / database error message.

Has something happened in the last two weeks commits that could hide certain posts like this ?

**Comment by mapkyca** [comment]
In a word, yes.

Check that the publish_status patches have applied to your database.

**Comment by markwaters** [comment]
Sorry , I am not a programmer , would this be a correct way of achieving this ?

mysql -u root -p $DATABASENAME < /var/www/known.multisite/schemas/mysql/2016102601.sql

Thanks @mapkyca

**Comment by markwaters** [comment]
I have applied the last two schema files ( 2016102601.sql and 2016110301.sql ) , the output showed that it had already been applied however , it has made no difference to the missing posts.

**Comment by mapkyca** [comment]
This is the only recent change I can think that's applicable.

Try commenting out Idno/Pages/Homepage.php:81 and see if that brings them back, if so, then I'd suggest that the schema change hasn't been successfully applied.

**Comment by markwaters** [comment]
Oh praise the maker! It works again , thank you so much , I was going out of my mind thinking I had lost 90% of my posts.

I have applied the last two schema files again manually , here is the output -

MariaDB [markwaters]> ALTER TABLE `config` ADD COLUMN `publish_status` varchar(255) NOT NULL DEFAULT 'published';
ERROR 1060 (42S21): Duplicate column name 'publish_status'
MariaDB [markwaters]> ALTER TABLE `entities` ADD COLUMN `publish_status` varchar(255) NOT NULL DEFAULT 'published';
ERROR 1060 (42S21): Duplicate column name 'publish_status'
MariaDB [markwaters]> ALTER TABLE `reader` ADD COLUMN `publish_status` varchar(255) NOT NULL DEFAULT 'published';
ERROR 1060 (42S21): Duplicate column name 'publish_status'
MariaDB [markwaters]> ALTER TABLE `config` ADD KEY `publish_status` (`publish_status`);
ERROR 1061 (42000): Duplicate key name 'publish_status'
MariaDB [markwaters]> ALTER TABLE `entities` ADD KEY `publish_status` (`publish_status`);
ERROR 1061 (42000): Duplicate key name 'publish_status'
MariaDB [markwaters]> ALTER TABLE `reader` ADD KEY `publish_status` (`publish_status`);
ERROR 1061 (42000): Duplicate key name 'publish_status'
MariaDB [markwaters]> UPDATE `versions` SET `value` = '2016102601' WHERE `label` = 'schema';
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0
MariaDB [markwaters]> CREATE TABLE IF NOT EXISTS `versions` (`label` varchar(32) NOT NULL,`value` varchar(10) NOT NULL,PRIMARY KEY (`label`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected, 1 warning (0.01 sec)
MariaDB [markwaters]> REPLACE INTO `versions` VALUES('schema', '2016110301');
Query OK, 2 rows affected (0.02 sec)

Does that help ?
Any other suggestions would be appreciated.

**Comment by mapkyca** [comment]
Try executing the following query against your database and see what the result is:

```select count(*) from entities where publish_status != 'published';```

If the count is not 0, then it rather implies that something isn't setting 'published' on posts, and we can do some further investigation.

**Comment by markwaters** [comment]
The count = 0

**Comment by mapkyca** [comment]
Hmmm.... that's odd, very odd.

**Comment by mcg** [comment]
Did a fresh, `git pull` and **all** my posts disappeared. I can confirm that `select count(*) from entities where publish_status != 'published';` returns `count=0` for me as well.  Commenting `Idno/Pages/Homepage.php:81` brought the posts back.

**Comment by mapkyca** [comment]
And no errors in the log for either?

**Comment by markwaters** [comment]
Please tell me how to enable logging , I cannot find anything about it in http://docs.withknown.com/en/latest/

**Comment by mapkyca** [comment]
It's different for every server; usually it'll be somewhere in /var/log/apache

**Comment by markwaters** [comment]
Sorry , I thought there was a Known logging system that I hadn't enabled in the config.ini file after finding 'Idno/Core/Logging.php'.

The apache2 access log looks normal , shows no errors , all 200's.
The error log is empty apart from expected abuse blocking.

**Comment by mapkyca** [comment]
Ahh, you do generally have to enable logging (although iirc errors are always shown).

Start by setting loglevel = 4; in your config.ini, which will log debug info.

**Comment by markwaters** [comment]
I have added 'loglevel = 4;' to the config.ini and my sites .ini file.
Not seeing anything extra in the Apache2 access or error logs.
Is there a Known log file for each site where this logging is enabled like sitename.log ?

**Comment by mapkyca** [comment]
Possibly, if your server is configured that way. This is an apache thing rather than a Known thing though...

**Comment by neilr8133** [comment]
FWIW, I'm experiencing the same thing:


* Updated WithKnown from commit 6f253664b499 to 4b1b1e649, all posts
disappear; roll back, posts re-appear!

* Tried SQL query:

mysql> select count(*) from entities where publish_status != 'published';
+----------+
| count(*) |
+----------+
|        0 |
+----------+

* Per Marcus's comment on the 8th, commented-out Idno/Pages/Homepage.php:81
and the posts re-appeared.


I will attempt to follow the rest of the debugging steps in this thread and
report back any useful information I can find.


-Neil R.

**Comment by mapkyca** [comment]
Do you folk apply any filters to the homepage? I.e. hiding certain content types...?

**Comment by mapkyca** [comment]
I've added some debug to the search, please post the results...

**Comment by markwaters** [comment]
This morning I pulled the latest commits , uncommented Homepage:81 and now see this in the Apache error logs for the site -

```
[Wed Nov 30 07:29:53.505676 2016] [:error] [pid 5348] [client 81.56.228.17:3931] Known (markwaters.eu): debug - Searching for  using search Array\n(\n    [uuid] => http://markwaters.eu/profile/mark\n)\n [/var/www/known.multisite/Idno/Common/Entity.php:203], referer: https://markwaters.eu/content/all/
[Wed Nov 30 07:29:53.559336 2016] [:error] [pid 5348] [client 81.56.228.17:3931] Known (markwaters.eu): debug - Searching for Array\n(\n    [0] => IdnoPlugins\\Status\\Status\n    [1] => IdnoPlugins\\Text\\Entry\n    [2] => IdnoPlugins\\Photo\\Photo\n    [3] => IdnoPlugins\\Like\\Like\n    [4] => IdnoPlugins\\Checkin\\Checkin\n    [5] => IdnoPlugins\\Media\\Media\n    [6] => IdnoPlugins\\Tracks\\Tracks\n)\n using search Array\n(\n)\n [/var/www/known.multisite/Idno/Pages/Homepage.php:84], referer: https://markwaters.eu/content/all/
[Wed Nov 30 07:33:50.140145 2016] [:error] [pid 5452] [client 81.56.228.17:52458] Known (markwaters.eu): debug - Searching for  using search Array\n(\n    [uuid] => http://markwaters.eu/profile/mark\n)\n [/var/www/known.multisite/Idno/Common/Entity.php:203], referer: https://markwaters.eu/
[Wed Nov 30 07:33:50.184561 2016] [:error] [pid 5452] [client 81.56.228.17:52458] Known (markwaters.eu): debug - Searching for Array\n(\n    [0] => IdnoPlugins\\Status\\Status\n    [1] => IdnoPlugins\\Text\\Entry\n    [2] => IdnoPlugins\\Photo\\Photo\n    [3] => IdnoPlugins\\Like\\Like\n    [4] => IdnoPlugins\\Checkin\\Checkin\n    [5] => IdnoPlugins\\Media\\Media\n    [6] => IdnoPlugins\\Tracks\\Tracks\n)\n using search Array\n(\n    [publish_status] => published\n)\n [/var/www/known.multisite/Idno/Pages/Homepage.php:84], referer: https://markwaters.eu/
[Wed Nov 30 07:33:59.895960 2016] [:error] [pid 5451] [client 81.56.228.17:52465] Known (markwaters.eu): debug - Searching for  using search Array\n(\n    [uuid] => http://markwaters.eu/profile/mark\n)\n [/var/www/known.multisite/Idno/Common/Entity.php:203]
[Wed Nov 30 07:33:59.899735 2016] [:error] [pid 5451] [client 81.56.228.17:52465] Known (markwaters.eu): debug - Searching for Array\n(\n    [0] => IdnoPlugins\\Status\\Status\n    [1] => IdnoPlugins\\Text\\Entry\n    [2] => IdnoPlugins\\Photo\\Photo\n    [3] => IdnoPlugins\\Like\\Like\n    [4] => IdnoPlugins\\Checkin\\Checkin\n    [5] => IdnoPlugins\\Media\\Media\n    [6] => IdnoPlugins\\Tracks\\Tracks\n)\n using search Array\n(\n    [publish_status] => published\n)\n [/var/www/known.multisite/Idno/Pages/Homepage.php:84]
```
My site is public but also uses 'per-post-privacy'.

**Comment by benwerd** [comment]
I think I know what's happening here. It's to do with how metadata on the entities is saved and search results are requested. Working on a fix.

**Comment by benwerd** [comment]
Try pulling again - I'm hoping that fixed it!

**Comment by markwaters** [comment]
Woohoo! , the site is now working as expected again , all posts showing.
Thanks @benwerd and @mapkyca

**Comment by benwerd** [comment]
I'm glad that worked!

**Comment by neilr8133** [comment]
Confirmed: Updated from commit 4b1b1e6 to 4702ea73 and all posts are
showing again.  Thank you very much, really appreciate the help (and the
quick fix!)


-Neil R.

**Comment by herbsmn** [comment]
>Sorry , I am not a programmer , would this be a correct way of achieving this ?
>mysql -u root -p $DATABASENAME < /var/www/known.multisite/schemas/mysql/2016102601.sql

I'm not sure how to apply the publish_status patches to my database. Was this the correct answer? Must this be done with all four of them in chronological order?

**Comment by markwaters** [comment]
Hi @herbsmn , I applied these database updates manually but they had all already been applied.
The fix came from @benwerd , see above , my site is now working as expected.

**Comment by herbsmn** [comment]
Thanks for the reply. I had read everything above, but I didn't fully
understand it all.

So if I update to the newest version it should work? I don't have to
apply any database schema things anymore? That's what I was told to do
yesterday in the Known IRC.

**Comment by markwaters** [comment]
yep , just grab the latest version from the git repo.

**Comment by herbsmn** [comment]
I did 'git clone https://github.com/idno/Known.git Known2' just now.

Then I copied my old /Uploads, /IdnoPlugins, and config.ini into the new folder, Known2.

Then I did the mv command to make Known into Known-LastStable and Known2 into Known.

I unfortunately got the same error as I did the last time.

![da](https://cloud.githubusercontent.com/assets/8562898/21757326/bb1c1364-d624-11e6-8c95-85dd49534a75.png)

Are you sure I don't need to apply a new schema via the stuff here? /var/www/known.multisite/schemas/mysql/

**Comment by herbsmn** [comment]
The nice thing was that I was able to just switch the names back with the mv command and everything came right back.

**Comment by markwaters** [comment]
Of course you need to keep your database structure up-to-date by applying the latest schemas , this was always done automatically for me.
I don't think you can break the database by doing the update more than once anyway.

**Comment by herbsmn** [comment]
markwaters: either i need to apply the latest schemas or they are done automatically. if i need to manually apply the latest schemas, i don't know how. 

i'm willing to add this information in the docs via a pull request if someone helps me understand what to do here.

my best guess is 'mysql -u root -p $DATABASENAME < /var/www/known.multisite/schemas/mysql/2016102601.sql' which is what you wrote above. 

Some questions:

do i only do that with the most recent schema in the folder? 

do it do it to all of them chronologically? 

do I need to figure out what my current schema is in order to make sure i don't accidentally apply an older schema during this process?

is this risky enough that it is wise to back up my Known database before applying it? 

if so, how do I do that?

I really appreciate any help on this I can get. I should say again though that my current install is working great and that this isn't time sensitive on my end. I just want to be able to be rocking the latest version and document how other people can do so as well. I've been using Known for a few years now and don't remember ever having applied database schemas as I progressed.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1595#issuecomment-271237740" class="u-in-reply-to"></a>If its a new install, apply mysql.sql. If it's an old install you're updating install the sql patches in chronological order where those dates are greater than that in your versions table.

Most people should be update automatically, but it seems that a couple of folk this update failed... not sure why, but I suspect it was because the code was passing multiple line queries to the PDO driver (which is bad).

Some patches are safe to double up on, others may not be, but I can't think of any since 99/100 reapplying something like an alter table will simply puke. 

Applying them in order is important though, since e.g. insert column queries rely on the table being an expected format.

Because this is messing with the database, you should of course take a backup of your database first :)
