### ISSUE TITLE
ACL: Allow objects to have more than one access group

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1597]
## While trying to do this:

Alice create a Post, shares it with all the people in her Friends group, but then also wants to share it with her Family group

## I encountered this error:

At the moment this is not possible without creating a new group as an amalgamation of the two, adding complexity, especially since groups are not static.

**Comment by benwerd** [comment]
I think, for now, this is too much complexity. I'd advocate for marking this #wontfix.

**Comment by mapkyca** [comment]
Yeah, maybe not a now thing, but I'll put money down that we'll have to build it out at some point relatively soon...

**Comment by mapkyca** [comment]
Closing, will build if there's a specific usecase which can't be handled another way.
