### ISSUE TITLE
Can't post status update

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1598]
## While trying to do this:
Post a status update to Known (on URL http://stream.boffosocko.com/status/edit) I get no response--that is, I don't get the fields to fill out to create/send an update. When using a bookmarklet to create a status update, I get a page with the appropriate fields and data filled out, but get a "403 Forbidden" response with "nginx" when I attempt to post.

## Some other notes:
All of the other post types seem to work and post properly, I'm just having issues with status updates.

I haven't monkeyed with internal settings, plugins, or anything in months and this seemed to suddenly pop up today. I've tried blowing out my install and reinstalling everything, but that doesn't seem to be the issue.

Has anyone else run across this? Anyone have ideas about what I can do to fix/trouble shoot it? I'm sure I'm missing something silly.

(Self-hosting v0.9.2 with mySQL)

**Comment by mapkyca** [comment]
Anything in your logs?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/idno/Known/issues/1598#issuecomment-260613213" class="u-in-reply-to"></a>The logs were non-illustrative. The handful of fixes I tried didn't seem to work, but early yesterday the bug seemed to have resolved itself and hasn't recurred. I've also been having some php related issues with a site running on the same server which seem to have resolved themselves simultaneously, so I can only presume it was a glitch there somehow, but I'm now unable to replicate it.
