### ISSUE TITLE
update to 0.9.2 broken past (Media) entries

### ISSUE THREAD

**Issue by grantpotter** [idno/Known#1599]
I updated to 0.9.2 yesterday from 0.8.3 - known.networkeffects.ca

All appears well, except all my previous Media entries no longer playback.  Posted a new Media entry today and it plays back fine - see http://known.networkeffects.ca/content/audio/

**Comment by mapkyca** [comment]
Anything in your logs?

**Comment by benwerd** [comment]
Hi @grantpotter - can you confirm that your uploads directory was not overwritten in the upgrade? (Although, if your user icons remained intact, it _shouldn't_ be this.)

**Comment by grantpotter** [comment]
@benwerd no, not overwritten and user icons all good.  All my uploads post upgrade work fine ... just the audio pieces before upgrade broken.  Only 6-7 pieces broken, so happy to go back and fix those posts, but not sure where to start with that.

**Comment by mapkyca** [comment]
What's you database backend?

**Comment by grantpotter** [comment]
@mapkyca mysql 5.5.52 ... also, I was wrong a bout icons ... all icons before update appear broken - see http://known.networkeffects.ca/2016/scope-and-volume-of-incidentally-gathered-information-has-been-tremendously

**Comment by grantpotter** [comment]
@mapkyca now that I'm looking closer, it appears I made a real mess with my update .. my photos are hooped as well ... ex: no photo - http://known.networkeffects.ca/2016/thank-you-bryanmmathers-for-my-great-doodle-please-consider-supporting ... updated a few weeks ago, have about 150 entries since the update ... wondering what best option is for correcting this

**Comment by mapkyca** [comment]
Check you've not overwritten your upload directory, and if it's still there check ownership and permissions of the directory and the files inside.

**Comment by grantpotter** [comment]
@mapkyca permissions 755 and last modified Nov 17 - so may overwritten ... nothing currently in the 'Uploads' directory although I have been adding lots of media since Nov 17.

**Comment by grantpotter** [comment]
@mapkyca have pre-update backup - so could roll back, but wondering how to best preserve content post Nov 17-present and import it ...

**Comment by grantpotter** [comment]
Sorted things out - thanks for the guidance.

**Comment by mapkyca** [comment]
Updates shouldn't clobber the upload directory, unless the archive utility you're using to unpack the archive is stupid... 

This has happened a couple of times for folk, for information... how are you patching? FTP, Cpanel, or scp/gunzip/cp?

**Comment by mapkyca** [comment]
I'm wondering whether it'd be better to not have the upload directory in the archive, but have the engine create it on install... thoughts @benwerd?
