### ISSUE TITLE
incoming webmentions: use u-url property instead of source URL

### ISSUE THREAD

**Issue by snarfed** [idno/Known#160]
low priority:

right now, it looks like idno's webmention handler uses the source query parameter as the source's canonical URL. no surprise there: most current webmention implementations do this, since they're almost always the same. http://brid.gy/ is one case where they're different, though, and in that case the u-url property should take precedence (i hope).

e.g. bridgy generated the likes and retweets on http://werd.io/2014/why-i-love-silicon-valley-despite-hating-silicon-valley#comments, and the permalinks all point to brid.gy, but they should ideally point to the twitter.com links in the u-urls instead.

**Comment by ruihildt** [comment]
@benwerd , does this mean this bug is gonna stay closed forever ?

**Comment by benwerd** [comment]
This bug is closed because it was fixed with a commit. There is another bug, #603, that needs to be addressed.
