### ISSUE TITLE
update to current master => older posts are not shown

### ISSUE THREAD

**Issue by jdinse** [idno/Known#1600]
I updated our Known-Installation (about half a year old) to the current master. After doing this, all post we wrote are not shown anymore. If I write a new post it will be shown, but not the older ones. Rewind the update of our Known-Installation back to version 0.9.2, all older post are visible again including the new post I wrote.

**Comment by mapkyca** [comment]
Dupe #1595 

What database engine are you using, have the patches from #1572 applied?
