### ISSUE TITLE
Full Size Images

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1609]
## While trying to do this:

View the full size image.

## I encountered this error:

Only shown post with regular size image

## Some other notes:

I am sure in the past when I clicked on an image from the homepage I was taken to the post and when I clicked on this post image I was taken to the direct image URL with the full size image.

Now I just get repeatedly get taken to the post with no chance to see the full size image.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1609" class="u-in-reply-to"></a>The template's anchor tag has been changed to the object url, rather than the image. You could modify this in your template, or you might find my lightbox plugin useful: https://github.com/mapkyca/KnownLightbox
