### ISSUE TITLE
Each IDNO powered site should have their own login with button like FB #idea #inhancement

### ISSUE THREAD

**Issue by ghost** [idno/Known#161]
Each IDNO powered site should have a public oAuth API were other sites can get Login with button what I exactly Mean is everyone should have there own login with button like FB , Twitter , G+ :)

**Comment by benwerd** [comment]
I think there's something here - and it may be worth bringing oauth2 support into core to support it. It would also allow other functionality, like one-click migration.

**Comment by mapkyca** [comment]
Happy to put together a PR containing my OAuth2 server if that's the way folks want to go!

**Comment by mapkyca** [comment]
Of course, it might be easier to include the third party project. I'll leave it up to you :)

**Comment by benwerd** [comment]
It might well be easier to include that in the package. Let's take this to the mailing list.

**Comment by physcocode** [comment]
maybe known is now enough APIfied to close this issue. Or you may wait till Oauth is on the cards !
