### ISSUE TITLE
Feature Request: Save Bookmarks to the Wayback Machine

### ISSUE THREAD

**Issue by rosetree** [idno/Known#1610]
Please forgive me, if this topic has already been discussed.

I think it would be great, if Known saved bookmarks to the [Wayback Machine](https://archive.org/web/). That would allow users to revisit their saved pages, even if they disappeared from the web. (Aside: The Wayback Machine could also be a helpful syndication option for own posts.)

The implementation shouldn’t be to hard. It’s probably only a request to a save URL, as explained in a [Wikipedia help page](https://en.wikipedia.org/wiki/Help:Using_the_Wayback_Machine#URL_formats).

    $ curl -I 'https://web.archive.org/save/https://withknown.com/'

The `Content-Location` Header could be used to store the archived url. Please note, that the returned HTTP Status Code is not always “200 OK”, but could also be “301 Moved Permanently”. Maybe that happens, if an URL is saved twice in a second.

I’m not sure how this archiving feature should behave with private bookmarks or on private sites.

What do you think?

**Comment by mapkyca** [comment]
Dont we already do this...?

**Comment by rosetree** [comment]
I don’t think so. I found three occurrences of a variable `$wayback_machine` but without usage as far as I could tell. Also I just checked a few bookmarks I saved in my Known (v0.9.2) and couldn’t find them in the archive.

**Comment by chrisaldrich** [comment]
I just started tinkering with something similar on the WordPress side after @Adactio mentioned it at IndieWebCamp LA.

If it helps, here are two fairly simple WP plugins (with .php code) that archive each post published on a site to the archive (rather than bookmarks):
- https://wordpress.org/plugins/post-archival/  (the simpler of the two)
- https://wordpress.org/plugins/archiver/ with code at https://github.com/MickeyKay/archiver

See also: http://indieweb.org/Internet_Archive

**Comment by tantek** [comment]
Going to + 1 this, given the current climate (so to speak) of Tweets by government organizations being deleted it's even more urgent to have stuff you link to get auto-archived.

Also:
1. A bunch of us are already doing it: http://indieweb.org/Internet_Archive#IndieWeb_Examples
2. There's a WordPress Plugin: http://indieweb.org/Internet_Archive#WordPress

Please implement this and turn it on by default for *.withknown.com blogs!

**Comment by mapkyca** [comment]
Going with an external plugin to do this: mapkyca/KnownWaybackMachine might be a good start...
