### ISSUE TITLE
SVG author icons broken

### ISSUE THREAD

**Issue by cweiske** [idno/Known#1612]
## While trying to do this:
Comment on a known post from my blog. 

## I encountered this error:
The comment under the post did not show my SVG author icon correctly

## Some other notes:
See the "Have a look at" comment on http://www.raretrack.uk/2016/wish-i-remembered-to-use-withknown-to-posse-my-tweets which I authored on https://commentpara.de/comment/76.htm and uses a svg author icon.

**Comment by mapkyca** [comment]
It'll be down to the remote image being retrieved and thumbnailed, unfortunately PHP's GD library doesn't support SVG.

**Comment by cweiske** [comment]
What about  not thumbnailing .svg images? That would solve the problem.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1612" class="u-in-reply-to"></a>Thumbnailing was done in part for security, and in part to avoid mixed mode errors between HTTP and HTTPS.

I've been thinking about image proxying as an alternative to this approach.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1612" class="u-in-reply-to"></a>You could try the latest master, as this has an image proxy for remote images, which is slightly less hacky than the approach previously taken.
