### ISSUE TITLE
Images broken

### ISSUE THREAD

**Issue by klickreflex** [idno/Known#1615]
## While trying to do this:
Viewing uploaded images, either profile or post content

## I encountered this error:
Images are broken
![screen shot 2016-12-16 at 11 04 29](https://cloud.githubusercontent.com/assets/435825/21258917/801530c8-c37f-11e6-8fdf-ece99b638e82.png)

## Some other notes:
When I check my uploads folder I can see that images are being uploaded and thumbnail generation is working, too. They just don't show up as they should.

The image links look like this: `src="https://wentsch.dev/file/5e778cff23334ca3a99098cfe56e800e/thumb.jpg"`

Also there is no http error thrown, just a somewhat broken non-image image is being displayed:
![screen shot 2016-12-16 at 11 07 35](https://cloud.githubusercontent.com/assets/435825/21259054/f8f68bf4-c37f-11e6-84fc-094cd3cc05a3.png)

- Running MAMP Pro 4.0.6 on macOS 10.12.2 
- Tried both PHP 7.0.12 and 5.6.27
- Apache is running under my user's privileges, Uploads dir is writable and owned by the same user
- No apache errors

After I set my config.ini to logging=4 I get the following PHP Notice that sounds like it could be related:

    [16-Dec-2016 10:02:31 UTC] PHP Notice:  ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in /Users/daniel/sites/wentschme/known/Idno/Files/LocalFile.php on line 30

Regards,
Daniel

**Comment by mapkyca** [comment]
Check ownership and access on your uploads directory

**Comment by klickreflex** [comment]
Checked and writable. If permissions weren't okay I suppose files wouldn't be written, would they?

**Comment by mapkyca** [comment]
Should, but not always.

Also check you've got the GD libraries loaded / enabled. Might help to look at the diagnostics page on admin menu.

**Comment by klickreflex** [comment]
GD is working, too. Thumbnails are being generated - they just can't be displayed. Diagnostic page shows no errors.

**Comment by danito** [comment]
Hi,
Did you by any chance first set up your site in http before switching to https? I had the case and had to replace all http references in the database to https.

**Comment by klickreflex** [comment]
As a matter of fact I did setup with http and, after having said problems, switched over to https. So the issue has been there before. And after switching back to http now didn't change anything neither. Besides: does known really save absolute URLs in the database and requires me to search and replace the DB before deploying from a testing domain to live? This would be a dealbreaker anyway.

**Comment by rikmendes** [comment]
Hmm I don't think so...all the previous report of this bug has been about incorrect write/ownership permission.

**Comment by klickreflex** [comment]
FWIW the issue can be closed, as I moved away from Known.

**Comment by physcocode** [comment]
@klickreflex we are sorry to hear you move away from Known , I could not particularly reproduce your issue you can always drop me a mail at pranjaltech10@gmail.com I could personally help you ! We want to make known better again
