### ISSUE TITLE
List of works 

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1619]
so finally I got one week holiday from college and I would like to dedicate it to Known if some one can drop me a list for some works to do I would start it ASAP . 
Contributing giluidlines and tips are welcomed 
PS: I have been a bit behind in the google group discussion so any feature that need to be implemented can be added in the list I will try my 100% to make working feature

**Comment by erinjo** [comment]
Hi @physcocode.

I would suggest taking a look through the open issues here on Github to see if there is anything that interests you and that you might like to work on.

You could also look at the plugins that other members of the community have created here: http://docs.withknown.com/en/latest/plugins/community/ 

If you think that there's a plugin missing that would be valuable to you, you could start on that as well.

**Comment by mapkyca** [comment]
It'd be useful to have some issues confirmed (e.g. micropub issues). Code is always a moving target, and i've not had a chance to confirm that many issues can be replicated or are still relevant.

**Comment by physcocode** [comment]
Yes sir , I'll have a look on issues tommrow morning and give my comments/advice/pull requests on the same !
