### ISSUE TITLE
Importing Exported Data

### ISSUE THREAD

**Issue by drjnet** [idno/Known#1620]
Hi,

I am attempting to move my posts from an existing self-hosted known installation to a new fresh  installation on a new domain, i have successfully used the EXPORT function in site configuration on the old site but I cannot find a way to import it on the new site. The only choices i see when viewing the IMPORT section on the new site is to import wordpress or blogger zips, the folder structure in the export zip doesnt look like anything in the filesystem so I've been unable to simply drop those files anywhere.

Am i missing something obvious? Thanks in advance.

**Comment by rikmendes** [comment]
There is no way to import Known to Known with the currently exported data. 
What others and I have done is to use the SQL dump file from the export data to repopulate your new Known database and then move your /IdnoPlugins and /Uploads back to your new Known install. this is how most people have been moving from Known Pro to Known Self-Hosted.

**Comment by drjnet** [comment]
Hey, thanks for the response. The export page is confusing in that case:

_Known gives you an archive containing all of your site's data........**. You can then import these into other Known sites** or process them using other software._

May be worth tweaking that.

I can reimport the db on the new host no problem (i tried it already) but all my posts are broken i believe its because I am moving from stream.domain.com to domain.com.

Would a find/replace in the entities table and rename of Uploads/olddomain to Uploads/newdomain be enough or would i need to do anything else?

**Comment by drjnet** [comment]
Ive resolved the issue now, thanks for your help.

**Comment by drjnet** [comment]
Just for anyone else who wants to do this these are the things i did

- Unzipped a fresh known installer (latest) to my new domain's web root.
- Dumped entire mysql db from old host
- Imported mysql dump into new db on new host
- Renamed the folder in Uploads/ from my old domain to my new domain
- Logged into new known, reuploaded profile pic/avatar (for some reason this didnt copy over properly, reuploading sorted it.
- I didnt have any plugins but read above comment on what to do there if you do..

Hope that helps.
