### ISSUE TITLE
Not respecting q values in Accept header

### ISSUE THREAD

**Issue by rhiaro** [idno/Known#1622]
It looks like Known returns JSON if `application/json` is anywhere in the `Accept` header, regardless of the order or `q` values. If `Accept` is not present or contains only `text/html`, then HTML is returned.

ie. even  `curl -v -H "Accept: text/html;q=1,application/json;q=0" http://stromgeber.lischka.cc/ ` returns JSON.

I picked on @klischka 's site (Known version 0.9.2) because this was flagged in https://github.com/snarfed/bridgy/issues/713

**Comment by mapkyca** [comment]
Correct, it simply searches for the string in the accept header.

The culpret is Idno/Core/Template.php:665-77 which is a simple if statement.

**Comment by mapkyca** [comment]
Or maybe isAcceptedContentType() on Page
