### ISSUE TITLE
accept webmentions against front page

### ISSUE THREAD

**Issue by snarfed** [idno/Known#164]
it looks like idno doesn't accept webmentions against the front page, e.g. http://werd.io/ . here's an example failure. low priority, obviously!

https://www.brid.gy/log?start_time=1389283282&key=aglzfmJyaWQtZ3lyaQsSCFJlc3BvbnNlIlt0YWc6cGx1cy5nb29nbGUuY29tLDIwMTM6ejEyM2c1ajVlb3VtaGh1Z20wNGNqZjR3MHh5NWh4ajRwaXNfbGlrZWRfYnlfMTA5MTgyNTEzNTM2NzM5Nzg2MjA2DA

Error sending to endpoint: {'code': 'RECEIVER_ERROR', 'request': u'POST http://werd.io/webmention/ (with source=https://brid-gy.appspot.com/like/googleplus/106119964731604142156/z123g5j5eoumhhugm04cjf4w0xy5hxj4pis/103585125347392273655, target=http://werd.io)', u'error_text': u'The target page does not exist.', 'http_status': 400, u'error': u'target_not_found'}

**Comment by benwerd** [comment]
Re-bumping. We're slower than we'd hoped but this is still something we're interested in.

**Comment by mapkyca** [comment]
Cross referencing with #7
