### ISSUE TITLE
Not closing a script tag in custom JS breaks the site

### ISSUE THREAD

**Issue by kevinmarks** [idno/Known#1641]
## While trying to do this:
include an external js script
## I encountered this error:
I didn't close the script tag, and made known.kevinmarks.com blank.
## Some other notes:
The admin pages should probably not inject the user scripts and styles, so I could undo this.
Appending ?_t=amp means I can see the pages, and even the admin ones, but can't use them because of the buttons not being real buttons.
More info at http://www.kevinmarks.com/day4-broke-known.html

**Comment by mapkyca** [comment]
Closing in favour of #1846
