### ISSUE TITLE
Quill still not able to find syndication targets

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1646]
## While trying to do this:

Use Quill to publish to Known and syndicate -- https://quill.p3k.io/new

## I encountered this error:

> No syndication targets were found on your site. You can provide a list of supported syndication targets that will appear as checkboxes here.

## Some other notes:

I know this has been discussed as an issue in the past, and closed, but I am encountering the issue today and it would be very good if it could be resolved.

**Comment by jeremycherfas** [comment]
As suggested in IRC, I tested 601 Syndication Endpoint Query at micro pub.rocks and Known appears to have failed that test.

**Comment by aaronpk** [comment]
This appears to be fixed in the latest Known, just not released as a specific version yet.

**Comment by jeremycherfas** [comment]
Not fixed yet, as far as I can tell.

````
HTTP/1.1 403 Forbidden
Date: Tue, 21 Feb 2017 18:28:39 GMT
Server: Apache
P3P: CP="CAO PSA OUR"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Link: <https://stream.jeremycherfas.net/indieauth/auth>; rel="authorization_endpoint", <https://stream.jeremycherfas.net/indieauth/token>; rel="token_endpoint", <https://stream.jeremycherfas.net/micropub/endpoint>; rel="micropub"
X-Powered-By: https://withknown.com
X-Clacks-Overhead: GNU Terry Pratchett
Access-Control-Allow-Origin: *
Set-Cookie: known=4VxAkB0dXvulaoP4vKfhv3; expires=Tue, 28-Feb-2017 18:28:40 GMT; Max-Age=604800; path=/; secure; HttpOnly
Content-Length: 58
Content-Type: application/json

{
    "error": "forbidden",
    "error_description": "",
    "messages": []
}
````

**Comment by mapkyca** [comment]
Tried on my site, seems to work. Closing.
