### ISSUE TITLE
Quill editor breaks editing posts with lists

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1647]
## While trying to do this:
Edit unordered and numbered lists in a previously created post.

## I encountered this error:
The entire text of the lists is missing , headers and paragraph text still exists.

**Comment by kylewm** [comment]
Is this quill.p3k.io or QuillJS the new text editor? Sigh.

**Comment by markwaters** [comment]
Sorry , this is the new text editor.

**Comment by mapkyca** [comment]
Not been able to replicate this on my build, anyone else?

**Comment by erinjo** [comment]
@markwaters We've replicated this. Thanks for reporting.

@mapkyca I've left you a Trello card with examples on staging.

**Comment by markwaters** [comment]
Not really worth another issue , but I am also missing -
* Source Mode - the ability to post in HTML text and have it appear as just plain text.
* code and pre HTML tags.
* The ability to use the TAB key to switch from post text area to Cancel and Publish buttons.

The new editor seems to have fixed the image import though , I discovered that wasn't working for me a couple of days ago but hadn't tested it on other browsers.
