### ISSUE TITLE
Feature Request: Change post-type

### ISSUE THREAD

**Issue by dg01d** [idno/Known#1650]
## While trying to do this:
Change a post from e.g. a status to a bookmark

## I encountered this error:
No facility to accomplish this.

Related to importing a post from a WP export - the WP export has some errors in post-kinds, these errors are, of necessity, imported into the known instance. Unlike in WP, however, there is no way to edit a post-kind/type in known to rectify possible data loss on importation.

**Comment by mapkyca** [comment]
You might be able to do it using the tweak tool here https://github.com/mapkyca/KnownConsoleTools

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1650" class="u-in-reply-to"></a>Going to close this, I don't think this is something we're going to build into core, but a plugin to do this sort of thing could be cool if you want to build one!
