### ISSUE TITLE
Edit screen does not present some content

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1653]
## While trying to do this:

Edit a post produced by `https://quill.p3k.io/` that contained HTML formatting -- a block quote.

## I encountered this error:

The content of the block quote is not shown in the editor. See [screen grabs in this post](https://stream.jeremycherfas.net/2017/completely-mystified-by-editing-a-bookmark-in-withknown).

## Some other notes:

This occurs with any post from Quill that contains HTML formatting. It may also relate to the issue that the Content of a bookmark generated by Quill does not seem to be picked up by Known.

Could it be something to do with the use of PHP_strip_tags?

**Comment by erinjo** [comment]
Hi @jeremycherfas, is this an issue with using https://quill.p3k.io or with using [Quill](http://quilljs.com/) - the text editor? They are two different things. It looks like you're using Quill as your text editor in the screenshots, and that might be the source of the issues you're experiencing.

First, on not being able to edit the blockquote. It sounds like you're saving the bookmark with your text, then editing the post and the blockquote portion of your text is missing from the editor. This is an issue related to Quill the text editor. It sounds similar to an issue we just resolved where ordered and unordered lists weren't being displayed in the text editor during an edit state. This is an issue that I can recreate, and we will try to resolve.

From your other posts, it also sounds like the background color on the text is a problem you were trying to resolve. Please correct me if I'm wrong. 

From the screenshots, it looks like you copied and pasted text from the URL you bookmarked - http://boroughmarket.org.uk/articles/a-matter-of-opinion-demonising-food-groups - and placed that quote in a blockquote. The yellow-cream background color is coming from the page you copied and pasted from. If you view source on your post, you'll see color: rgb(51, 49, 46); background-color: rgb(249, 241, 227). This was likely picked up during the copy/paste and then persisted when you added your own comments.

This is a common problem with rich text editors. Often they bring over inline styling from the word processor or page where the content was copied from. We added a number of hacks to TinyMCE to correct for many of these, but we were never able to catch all of them.

As we're testing Quill as a possible text editor replacement, none of the modifications we put in place for TinyMCE exist yet. The problem of bringing over inline styling from an original source into the Quill text editor is an issue that we're aware of. We're currently building up a list of various areas of inline styling that regularly get pasted in from various editors.

If we choose to move forward with Quill, we may either try to put our own modification in place to strip these out, or we may add the "clear formatting" option to the Quill toolbar. 

I hope that helps clarify a few things.

**Comment by jeremycherfas** [comment]
Thanks @erinjo for the detailed explanation. It certainly is confusing having both the with known internal editor and an external micro.pub site share the name Quill. 

I look forward to your resolving the issue with the block quote. 

In the meantime, are there any plans to enable toggling from the rich text editor -- whatever it is -- to being able to edit the HTML directly?

I know a lot of other CMSs offer this ability, and it would make a lot of sense. That way, I could simply edit out the inline styling if I want to.

**Comment by erinjo** [comment]
@jeremycherfas I agree, it's confusing. Unfortunately, we didn't name either.

If we move forward with Quill as our rich text editor, there will not be functionality for directly editing HTML. TinyMCE has a source code editing option; Quill does not.

People using a straight install of Known can enable the markdown plugin to replace the rich text editor with a markdown editor as one alternative.

**Comment by mapkyca** [comment]
Quill.js has been put on ice for now, so closing this issue.
