### ISSUE TITLE
More Quill Editor issues

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1656]
1. When editing a new line , after tapping the first character the cursor jumps forward , resulting in Took becoming ookT and #checkin becoming checkin#
2. Source Mode - Unable to paste HTML text from elsewhere and have it displayed as plaintext , all the links come across.
3. Unable to resize editing window.
4. I have had the URL link editing box appear over the post privacy selector resulting in mangled HTML in the URL.
5. code and pre HTML tags now gone.
6. The ability to use the TAB key to switch from post title to text area then to Cancel and Publish buttons.

**Comment by mapkyca** [comment]
Quill.js has been put on ice for now, so closing this issue.
