### ISSUE TITLE
Micropub: audio upload not supported

### ISSUE THREAD

**Issue by martymcguire** [idno/Known#1664]
## While trying to do this:

Making an audio post via micropub with [Screech](https://screech.schmarty.net/).

## I encountered this error:

The audio does not appear in the contents of the post. It looks like the uploaded file is dropped altogether.

## Some other notes:

It looks like the `master` version of the IndiePub plugin now supports photo and video uploads, but audio is ignored:

https://github.com/idno/Known/blob/v0.9.2/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php#L89

**Comment by mapkyca** [comment]
Closed by #1665
