### ISSUE TITLE
Feature request: Add a flatfile storage option instead of MySQL

### ISSUE THREAD

**Issue by tantek** [idno/Known#1668]
## While trying to do this:
Setup Known without a database

## I encountered this error:
No nodb/nosql/flatfile option

## Some other notes:

It would be great if you could run Known purely locally on a laptop (or server) and have it store its data in a directory as flat files that you could inspect, backup, restore etc. without having to worry about setting up a database (installing db software like MySQL), manage db passwords etc.

**Comment by benwerd** [comment]
One could imagine doing this with another database backend, using the data concierge to abstract calls. It might not always be super-fast - but with a moderate personal site, it might be.

**Comment by mapkyca** [comment]
Have you tried the SQLlite back end? Not quite flat file, but it is at least a file that can be copied about without drama...

**Comment by tantek** [comment]
Have not - mostly filed this for @benwerd's benefit, since the dependency on a database makes it harder to setup a local dev env on your laptop to update/stage your install before updating your server, and then you might end up just updating your server, and breaking something db(server) related. Purely hypothetically of course.

**Comment by mapkyca** [comment]
Going to close, since I don't think anybody currently has time to look at this. Would welcome a PR to support it though, or a plugin implementing flat files...
