### ISSUE TITLE
MongoDB broken in latest code

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1669]
## While trying to do this:

Upgrade my site

## I encountered this error:

My site is broken because the MongoDB client can't find the right class path.

## Some other notes:

Error:

```
Fatal Error: /home/ben/werdio_html/external/mongo-php-library/src/Client.php:58 - "Class 'MongoDB\Driver\Manager' not found", on page werd.io/
```

**Comment by benwerd** [comment]
cc @mapkyca - I know you rewrote this. Is Known missing a path / some code in the client?

**Comment by mapkyca** [comment]
No, its that you're running the old PHP mongo driver, when you need to install mongodb from pecl/apt.

Looks like the wrapper class doesn't give you very helpful errors... I'll see what I can do about that...

**Comment by mapkyca** [comment]
Note: warmup, unit tests and diagnostics all check for this, so it's just an issue for the handful of folk upgrading from mongo

**Comment by benwerd** [comment]
Aha. Thanks!
