### ISSUE TITLE
Document how to add JS to an idno plugin

### ISSUE THREAD

**Issue by ghost** [idno/Known#167]
I like the Idea of using fitvids js in core to Handel video . Here I have a suggestion for handling images  http://imsky.github.io/holder/ . Holder js render image holder in client side reducing load on server.

**Comment by benwerd** [comment]
Confirming that we'll be adding much improved documentation shortly, on a new documentation site.

**Comment by physcocode** [comment]
Bump ! this has now been sorted time to close it !
