### ISSUE TITLE
MongoDB dotted field error on upgrade

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1672]
## While trying to do this:

I upgraded my site and installed the latest MongoDB PECL driver on my server.

## I encountered this error:

```
Fatal Error: /home/ben/werdio_html/external/mongo-php-library/src/Operation/FindAndModify.php:137 - "Uncaught exception 'MongoDB\Driver\Exception\RuntimeException' with message 'exception: The dotted field 'http://werd.io/2016/choose-life-choose-a-job-choose-a-career-choose-a/annotations/6334cd6a6b5bc1811ce65a0e844eb97c' in 'owner.attributes.annotations.like.http://werd.io/2016/choose-life-choose-a-job-choose-a-career-choose-a/annotations/6334cd6a6b5bc1811ce65a0e844eb97c' is not valid for storage.' in /home/ben/werdio_html/external/mongo-php-library/src/Operation/FindAndModify.php:137
```

## Some other notes:

😭 

I remember a configuration option around supporting this for legacy users, but I can't seem to find it in the code.

**Comment by mapkyca** [comment]
Bleeeerrrrrgh....

Never saw this in test, sorry. 

I vaguely remember seeing something about that as a horrible hack on the regex, I think I may have wrongly assumed that a brand new and officially supported library/subsystem would have fixed this shit.

#include previous gripes about mongo Only Having One Job

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1672" class="u-in-reply-to"></a>Hmm... I'm not sure how to replicate... I've been running mongo for ages and have received many webmentions and likes...

**Comment by mapkyca** [comment]
Hmm... still not able to replicate...

This issue looks like it's related to setting dotted fields as variable names, however using my mongo I was able to do this happily, so I'm wondering whether this is an old mongo server version problem - what version of MongoDB are you running? Have you tried rolling up to the latest?

For the record, my tests were performed against 2.4.10

**Comment by mapkyca** [comment]
... although, assuming you're on the server I think you are, it looks like you're running 2.6.12

... maybe this was a bug introduced later...? hmm!

**Comment by benwerd** [comment]
Just tried to upgrade and have the same problem. I'll try and figure something out - it'd be nice to get my site back online! ;)

**Comment by mapkyca** [comment]
Did you try my PR patch I posted last night?
