### ISSUE TITLE
Possible regression - comments are not ordering by dt-published timestamp from incoming webmentions

### ISSUE THREAD

**Issue by jaduncan** [idno/Known#1674]
I'm currently getting incorrectly ordered comments on FB and Twitter comments sent from bridgy. I'm running 0.9.2 as provided by Reclaim Hosting (stock, I would think) and the order is broken in that, while comments from different bridgy pushes are ordered correctly, if bridgy is picking up multiple comments in one check (let's say that 10 have been added since bridgy last scanned FB) then the order within those 10 comments is random.

I note that #1104 was previously closed - this might be a regression, because on checking with @snarfed at https://github.com/snarfed/bridgy/issues/737 he has confirmed that the dt-published mf2 property is still being passed.

**Comment by jaduncan** [comment]
Oh, and like #1104 it does appear that it's being ordered based on Webmention receipt time.

**Comment by mapkyca** [comment]
Can you confirm against latest master?

**Comment by benwerd** [comment]
Pinging here - I'm not reproducing in the latest version, but let us know / reopen the issue if it's still a problem for you.
