### ISSUE TITLE
Server hangs when creating a post with a similar slug

### ISSUE THREAD

**Issue by aaronpk** [idno/Known#1676]
## While trying to do this:

Creating a post with the same first 20 "pieces" as an existing post 

## I encountered this error:

The server hangs. I tracked it town to getting stuck in the "while" loop trying to generate a new unique slug. 

## Some other notes:

The `setSlugResilient` method appends a number to the slug when trying to generate a new slug. However, if the post has the same first 20 "pieces" as an existing slug, the number is truncated when using the name to generate a slug.

**Comment by mapkyca** [comment]
Hmm... can't seem to replicate.... 

Database? Also, is this the old package or latest from git?

**Comment by aaronpk** [comment]
This is the latest from git. I'm using MySQL, although I don't think that has anything to do with the problem.

Try using this text: "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty"

The first post is created fine, with the slug `one-two-three-four-five-six-seven-eight-nine-ten`

The second post is created fine, with the slug `one-two-three-four-five-six-seven-eight-nine-ten-eleven-twelve-thirteen-fourteen-fifteen-sixteen-seventeen-eighteen-nineteen-twenty`

It is then impossible to create another post with that text, since the numeric incrementer is appended after the word `twenty` so is cut off when generating the slug.

**Comment by mapkyca** [comment]
Hmmm... that seems to be working for me (latest git/mongo, but will try mysql tomorrow).

I get a slug with "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty", "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty-1" and "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty-2"

Hmmm.....

**Comment by aaronpk** [comment]
ah, try with `twentyone` at the end. In my test I also had a category in the post, which is appended to the content.

**Comment by mapkyca** [comment]
... hmm... that was it... interesting...

**Comment by mapkyca** [comment]
What I find odd is if you post longer identical posts it seems to be fine....

**Comment by aaronpk** [comment]
Yeah, it's pretty bad. I realize this is sort of an edge case, but it's a fundamental flaw with the way unique slugs are generated. If it's going to truncate the post content to generate a slug, then it needs to add the incrementer after having truncated the content rather than before.

**Comment by mapkyca** [comment]
I'll try and take a look at it... seems like it should be straightforward to fix...

**Comment by mapkyca** [comment]
Looks like a number of weird things falling into alignment.. basically, there's a problem in setSlug() where a comparison between getUUID of the entity and $this, which has not been saved and is returning the editURL

```
if ($entity = \Idno\Common\Entity::getBySlug($slug)) {
                    if ($entity->getUUID() != $this->getUUID()) {
                        return false;
                    }
}
```

I'm not entirely sure the purpose of this short circuit (comments!!!!), but I'm assuming its to prevent duplicate slugs being saved.

What looks like is happening is getUUID() isn't returning the correct value because the object hasn't been saved.

/cc @benwerd

**Comment by mapkyca** [comment]
ahh no, sorry you were right, the problem is with prepareSlug
