### ISSUE TITLE
mp4 video file "broken", partial HTTP responses missing last byte

### ISSUE THREAD

**Issue by martymcguire** [idno/Known#1682]
## While trying to do this:

I uploaded [this mp4 video file](https://aaronparecki.com/2017/03/29/3/video.mp4) to Known running on `master` via the "Audio" interface.

A new post is created and the `<video>` widget is displayed correctly. The `src` attribute of that URL points to the `.mp4` file on disk.

The test case can be found here:

https://known.schmarty.net/2017/test-video-upload-w-native-known-interface

## I encountered this error:

In Firefox or Chrome, clicking play on the `<video>` spins for a moment but then stops.

Attempting to load the `.mp4` URL directly in Chrome or Firefox results in an HTTP 200 response from the server showing the correct Content-Length. However, the browsers then make one or more extra requests for specific byte ranges, getting back HTTP 206 Partial Content responses that seem to be missing the last byte. For example, in a byte range request from FireFox, the server response contained this header:

`Content-Range: bytes 5308416-5380899/5380900`

Perhaps the file serving handler is off-by-one for these responses?

## Some other notes:

Safari displays the video by playing the smaller chunks that it has. It fails on the last chunk, like the rest, but is a bit more forgiving of the missing byte until it needs it.

Curl is able to fetch the entire .mp4 file.

This was first encountered by @aaronpk when adding JSON support to the Known micropub handler. Original discussion can be found at #1665.

**Comment by mapkyca** [comment]
Partial content ranges would be handled by Pages/File/View.php, so if there's a by-one error here it'd be good to get it sorted as it'll affect many things.

I'll see if I can replicate and do some debugging....

**Comment by mapkyca** [comment]
Although, I will add that video is actually a really complicated thing to do - there's all kinds of resampling that needs to take place to get a file to play reliably across multiple devices. This was part of the reason why video isn't officially supported and the media plugin was switched to audio only some time ago...

**Comment by mapkyca** [comment]
See PR: There was definitely an issue on mongo since gridfs isn't a physical file and so fread was chunking at 8192 bytes. 

Videos work for me on firefox, chromium still has issues, but nothing to do with the data returned...
