### ISSUE TITLE
Feature request: POSSE to Mastodon servers

### ISSUE THREAD

**Issue by skddc** [idno/Known#1686]
There's a nice new gnusocial/ostatus implementation, which is becoming popular really fast at the moment:

https://github.com/tootsuite/mastodon

It comes with OAuth and a REST api, so would probably be fairly easy to implement with the Twitter plugin as a template. The main difference being that one would have to be able to add a custom URL for the server when setting it up.

**Comment by danito** [comment]
just started to look into it : https://github.com/danito/KnownMastodon

**Comment by mapkyca** [comment]
Definitely a plugin rather than a core thing...

**Comment by danito** [comment]
You can start to test it. WIP, but you can now syndicate your statuses with Mastodon.

**Comment by mapkyca** [comment]
Closing as there's a community plugin for this
