### ISSUE TITLE
Aleph bot initial post helper does nothing.

### ISSUE THREAD

**Issue by tdb-alcorn** [idno/Known#1689]
Version info: Known version 0.9.2 running from the latest Docker container pulled from https://hub.docker.com/_/known/.

I'm running my own instance of Known on AWS using an adapted version of the docker compose deploy setup from https://github.com/indiehosters/known. I successfully deployed Known and it was mostly painless, thanks for making such great software! The only problems I encountered were related to DNS within AWS+Docker. If others are interested in how to deploy known to AWS, with a persistent RDS database instead of using a MySQL container, I'd be happy to write it up. 

Anyway, I'm now at the point of configuring and using my new site. Aleph bots instructions to get started by "adding your first status update". However this seems to be a link to $MY_DOMAIN.com/#, which brings me back to the same page.

**Comment by mapkyca** [comment]
Can you confirm against 0.9.5? Pretty sure I remember this being fixed....

**Comment by physcocode** [comment]
I guess it's already fixed in 0.9.5

**Comment by mapkyca** [comment]
Btw, a writeup of what you did would be a useful thing to have in the docs
