### ISSUE TITLE
error in Idno/Core/Config.php:178

### ISSUE THREAD

**Issue by danito** [idno/Known#1698]
## While trying to do this:
 print_r(error_get_last(), true) 
## I encountered this error:
parse_ini_file(/var/.../nxd4n.nixekinder.be.ini): failed to open stream: No such file or directory
https://github.com/idno/Known/blob/master/Idno/Core/Config.php#L178

**Comment by mapkyca** [comment]
It's a suppressed error caused by using the @ directive, safe to ignore...
