### ISSUE TITLE
Add in-Known notification pane

### ISSUE THREAD

**Issue by erinjo** [idno/Known#170]
For a multi-user install like an intranet where everyone is on the same domain, what's the plan for handling mentions/responses between users?  Is there something in the works like an @-mention notification section or a recent comments section so that employees could easily see when another coworker posted a comment or left a mention on a status update?

**Comment by benwerd** [comment]
I know this is on your tasklist, but bumping to indicate that it's still something we're interested in :)

**Comment by benwerd** [comment]
Bumping this. Having internal notifications for, eg, new webmentions, new joined users, etc, would be really useful.

**Comment by mapkyca** [comment]
Should this ticket be merged with #7 ?

**Comment by benwerd** [comment]
Let's keep them linked, as technically one is notifications themselves, while the other is a native notification pane. Subtle difference, but still ;)

**Comment by mapkyca** [comment]
Closing this, as I think this was addressed by @kylewm's work
