### ISSUE TITLE
Support for Read posts? (Core or Plugin?)

### ISSUE THREAD

**Issue by chrisaldrich** [idno/known#1703]
From what I can tell the current master version now supports bookmarks, likes, replies, and reposts from within the core "Like" plugin while earlier versions (0.9.2 and prior) would require the KnownReactions plugin to support all of these.

I was considering making a "Read" plugin to better differentiate (from bookmarks) as posts which I've actually read the content of. To most users bookmark implies one will come back to and read something at a later date.

In an educational setting, I can see it would be useful to be able to indicate implicitly that one has actually read a particular article/assignment/other along with a field of notes one may have taken on the assignment--very similar to a current bookmark post, but with a slightly different connotation and slightly different mf2 markup (u-read-of perhaps?)

I'm happy to take a shot at a PR the the core "Like" plugin since it appears that it'd only need a handful of lines of code (and would be a bit more DRY than yet another full blown plugin especially for the portion of the tabbed UI which allows one to easily switch between the multiple types after starting a post), but thought I'd see what the thoughts were with regard to core since the company version has an academic focus which this would certainly dovetail with well. 

In a similar vein, I could also imagine Watch and Listen post types as well. I'll note that there's already a more entertainment focused version of a plugin called `[Known-Watching](https://github.com/cleverdevil/Known-Watching)`.

Cross-posting this to the Google Group as well.

**Comment by egoexpress** [comment]
Are bookmarks really used primarily for read-later purposes as you describe? I currently use the Known Bookmark post type exactly like you describe your proposed "Read" type - I post a bookmark for things I read and want to comment on and syndicate those to a social bookmarking service. All the stuff I didn't read yet but want to read later on I put in a read-later service.

**Comment by egoexpress** [comment]
However, if you would implement this I wouldn't add even more functions to the core "Like" plugin. The way Kyle took with the Reactions plugin (that integrated itself in the tabbed UI nicely) is imho the way to go. Mashing up bookmarks and interactions (like, repost etc.) in one plugin as it is right now is confusing enough (at least for me) :)

**Comment by rikmendes** [comment]
I agree, I think unread articles should be either a tag or a state of the post, something you could append to a bookmark. I use the bookmark system with both read/unread type and right now use a tag for things I want to read later than I fetch this particular RSS feed-tag into my feedreader so I can avoid using a third party read-later service, it works for me :)

**Comment by jgmac1106** [comment]
https://github.com/jgmac1106/Known-Read
