### ISSUE TITLE
Fixing output of title in RSS feed

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1704]
## While trying to do this:

View the RSS feed of an item that contained an `&` in the title

## I encountered this error:

The feed was truncated immediately before the `&`

## Some other notes:

So I looked at the file `/templates/rss/shell.tpl.php`and saw that line 84 contains `strip_tags($title)` to generate `<title>` in the field.

I changed this to `htmlspecialchars($title)` and it now works as I expect, but I wonder whether this is the correct way to handle the error. I'm not sure what else `strip_tags` might be doing in that context.

*Give us some context, it'd also be really handy if you could tell us the contents of your ```0.9.2``` file*

**Comment by mapkyca** [comment]
This was done as part of 1071afa 

We used to use htmlentities but this caused issues with rss parsing and export. Theoretically the dom document *should* be handling encoding...
