### ISSUE TITLE
Email settings don't work

### ISSUE THREAD

**Issue by TheOtterslider** [idno/Known#1744]
## While trying to do this:
have the site send an email (admin -> Site -> email)

## I encountered this error:
There was a problem sending a test message to <EMAIL ADDRESS>

## Some other notes:
I tried it both with/without entering email server settings; however, both conditions (with and without settings) threw the error shown.  But, I can't see anything in my apache logs

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*
0.9.2

**Comment by mapkyca** [comment]
Most likely this is something to do with your server setup. You could try with the latest git, which allows you to test settings and see a little more debug in your logs...

**Comment by TheOtterslider** [comment]
Probably as you posted this I saw I was out of date.  I'm now running the latest git.  Same error.  

Was able to get some more logs this time:

[11-May-2017 16:36:14 UTC] Known (maxsons.org): error - Error sending mail {"error":"Connection could not be established with host localhost [Connection timed out #110]"}
[11-May-2017 16:38:04 UTC] Known (maxsons.org): error - Error sending mail {"error":"Connection could not be established with host smtp.1and1.com [Connection timed out #110]"}

The first error was with no fields filled in...the second was with them filled out.  Any idea how I can test the connection?  I do have ssh access to the server....

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1744" class="u-in-reply-to"></a>So, the error implies that for whatever reason you can't connect to the mail server using the settings you gave. 

Assuming you're connecting to the right port, timeouts usually imply a firewall somewhere along the line quietly dropping packets. 

You could try sshing in and telneting port 25 of the server and see if you get a connection, that'd rule out the client side at least.

**Comment by pepe84** [comment]
@TheOtterslider I had the same issue and I discover that 1and1 hosting doesn't allow SMTP transport right now (they say that maybe in the future...). So you have to use PHP mail. 

Although is not a "pretty" solution, you can change send method at Idno/Core/Email.php:

```
} else {
    //$transport = \Swift_SmtpTransport::newInstance();
    $transport = \Swift_MailTransport::newInstance(); // 1and1 issue
}
```

**Comment by chrisaldrich** [comment]
<a href="https://github.com/idno/Known/issues/1744#issuecomment-301447928" class="u-in-reply-to"></a>@pepe84 @TheOtterslider I'm using 1and1 on one of my subsidiary sites as well and had issues ages ago. I did eventually change the settings to those below and found that they finally worked: 
SMTP host: smtp.1and1.com
SMTP username: email@domainname.com
SMTP port: 25
Secure connection: no
Not as ideal from a security perspective, but at least they did go through.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1744#issuecomment-301447928" class="u-in-reply-to"></a>Wondering if this might be a case for #779 afterall...

**Comment by TheOtterslider** [comment]
Thanks for the idea guys.  In other packages, I've used email on the local server and it worked great.  I bet they used PHP email (as @pepe84 commented here https://github.com/idno/Known/issues/1744#issuecomment-301447928)  

From an admin perspective, it would be nice to know what the options were doing.  The radio buttons didn't make it clear in the UI what was going on.

Thanks for the suggestions/input.
