### ISSUE TITLE
doc: clarify which mongodb user privileges are required

### ISSUE THREAD

**Issue by indieboxproject** [idno/Known#175]
For security reasons, it may be preferable to only allow the idno user to perform certain mongodb database operations and not others. Document which ones.

**Comment by benwerd** [comment]
A new, much more extensive documentation site is coming.

**Comment by mapkyca** [comment]
Can this be closed, since MySQL is now "blessed"?

**Comment by benwerd** [comment]
Not yet. I think going deeper on mongodb would be good.
