### ISSUE TITLE
Newest Known; Updated Mongo DB driver.. Still doesn't work

### ISSUE THREAD

**Issue by finalcut** [idno/Known#1754]
## While trying to do this:
I tried to upgrade my known self-hosted install

## I encountered this error:
Oh no! We couldn't connect to the database.

## Some other notes:
I followed the upgrade instructions for Mongodb.  I'm not sure what version you are saying we should be using but I appear to be using MongoDB 1.6.6  My PHP MongoDB Extension Version is 1.2.9  - the documentation is pretty sparse on this so I'm just not sure if I'm at the right place with mongo and, if I am, then what should be happening.

For no apparant reason that I can tell the apache log is showing some mysql errors in it as of today 
`SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost'`

I don't mind switching from MongoDB to a different backend since MongoDB is now deprecated.  But I don't want to lose the content I have in MongoDB currently and I don't know how to go about migrating Known to use a different backend.

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*

Using Version: 0.99

**Comment by mapkyca** [comment]
The default engine was changed, specify database='mongo' in your config.ini

**Comment by finalcut** [comment]
thanks.  that did it.  I appreciate the help.
