### ISSUE TITLE
Link to notifications interface missing in v0.9.9

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1757]
## While trying to do this:
View the notifications interface in v0.9.9

## I encountered this error:
I noticed it's no longer available from the menu drop down along with Profile, Account Settings, Site Configuration, Feedback, or Sign Out like it had been before.

## Some other notes:
The notification interface is still available by going to the URL http://example.com/account/notifications, so the interface still exists, but just doesn't seem to be accessible within the UI/menu system anymore (unless I'm just missing it somewhere or it's being hidden by the Cherwell theme I'm currently using).

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*
version = "0.9.9"
build = 2017051501

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1757" class="u-in-reply-to"></a>This functionality was temporarily disabled in a3ad6f9003da66645dad116b86653f3ce38e00f8 as notifications need a little bit more work.

You can uncomment the relevant section to re-enable.
