### ISSUE TITLE
"Image wasn't attached" message and hard-to-parse error message

### ISSUE THREAD

**Issue by benjaminwil** [idno/Known#1758]
## While trying to do this:

Post an image.

## I encountered this error:

"Image wasn't attached."

## Some other notes:

I'm using nginx, and I do get one error in my error.log, but I'm having trouble figuring out exactly what it means:

```
FastCGI sent in stderr: "PHP message: Known (sub.domain.name): info - Pinging
https://withknown.superfeedr.com/ with data hub.mode=publish&hub.url
=https%3A%2F%2Fsub.domain.name%2Fcontent%2Fposts
%2F,https%3A%2F%2Fsub.domain.name%2Fcontent%2Fposts%2F%3F_t%3Drss,
https%3A%2F%2Fsub.domain.name%2Fcontent%2Fall%2F,https%3A%2F%2Fsub.domain.name
%2Fcontent%2Fall%2F%3F_t%3Drss" while reading response header from upstream, client:
11.11.111.11, server: sub.domain.name, request: "POST /entry/edit/ HTTP/1.1", upstream:
"fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "sub.domain.name", referrer:
"https://sub.domain.name/"
```

(I replaced my actual domain name with `sub.domain.name` here, and an IP address with `11.11.111.11`.)

And here's the contents of my version.known file for you:

```
version = "0.9.9"
build = 2017051901
```

**Comment by benjaminwil** [comment]
Turns out I made a mistake in my `config.ini` which was causing the files to not upload.

I'm still getting the `FastCGI send in stderr`, but it's not blocking me. If I figure out what's going on I'll open another (sweeter) issue about it.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1758" class="u-in-reply-to"></a>Glad it's working! 

For the record, that's an info level warning. You might try dialling down your logging level in your config.ini
