### ISSUE TITLE
Failure to find syndication endpoints

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1768]
## While trying to do this:

Use [Quill](http://quill.p3k.io) to publish via micropub.

## I encountered this error:

Quill cannot find my syndication endpoint.

## Some other notes:

With help from the IndieWeb community, I tried `curl -H 'Authorization: Bearer TOKEN' http://stream.jeremycherfas.net/micropub/endpoint?q=syndicate-to` and ` ... q=config` with my token and received the error `{"error":"forbidden","error_description":"","messages":[]}` both times.

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*

**Comment by jeremycherfas** [comment]
Not sure whether [this](https://github.com/idno/Known/issues/519) is relevant or whether that is a separate issue. All I know is that Quill cannot see my syndication targets.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1768" class="u-in-reply-to"></a>Are you able to file a PR with a failing test for this?

**Comment by jeremycherfas** [comment]
No. I don't know what you mean by a failing test. I copied the error I received. I do not know enough to use, e.g. Micropub.rocks to test the micropub endpoint. If you are willing to guide me through that on IRC (or suggest somewhere else I could look) I would be happy to try.

**Comment by mapkyca** [comment]
I was able to post happily with quill on two separate sites running indiepub, and various builds of 0.9.9. Tempted to say it's a quill/local config issue. I do notice that =config isn't implemented, but I don't know enough about micropub to say whether that's significant.

**Comment by jeremycherfas** [comment]
It is not a question of posting; I can post from Quill. It is that Known does not return the syndication targets.

**Comment by mapkyca** [comment]
Hmm, well I'm also seeing syndication targets available...

**Comment by jeremycherfas** [comment]
Please, what is the command you are using to see that?

And shall we take this to IRC?

**Comment by Zegnat** [comment]
During [yesterday’s Homebrew Website Club](https://indieweb.org/events/2017-05-31-homebrew-website-club), I was able to set-up Known and the Twitter plugin from their respective repositories and had Quill recognise Twitter as a syndication target instantly. This suggests an error on @jeremycherfas’ side and not with the code.

**Comment by jeremycherfas** [comment]
Fair point. I will investigate further with a clean install from the repositories.

**Comment by chrisaldrich** [comment]
Jeremy, I finally got around to testing this earlier this evening as well. Quill seems to work fine for me with 0.9.9 as well.

**Comment by cweiske** [comment]
It was a quill issue. @jeremycherfas got it working after logging out and in again, then by clicking "(refresh list)" in the "Syndicate" section, the syndication targets got loaded correctly with known 0.9.9.
