### ISSUE TITLE
config.ini: why is dbname needed?

### ISSUE THREAD

**Issue by indieboxproject** [idno/Known#177]
It appears mongo lets you specify the database name in the connection string: http://docs.mongodb.org/manual/reference/connection-string/
So entry dbstring in config.ini should be sufficient. Why is dbname needed?

(This may be just a documentation issue.)

**Comment by benwerd** [comment]
I'll be honest: I'm having trouble discerning how to detect if we're connected to a specific database in the PHP MongoDB extension. It's probably something I'm missing, but that's the blocker here.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/177" class="u-in-reply-to"></a>Guessing this can be closed, since mongo is now deprecated...
