### ISSUE TITLE
(Optional) list of hashtags on front page

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#1780]
A feature request rather than a bug, obviously, but anyway:

Woldn't an option to have a list of all hashtags used on a particular site on the front page be welcome? Or even something like a hashtag cloud?

Known already has a way to display all entries containing a particular hashtag. Having a list of hashtags seems to be an obvious next step.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1780" class="u-in-reply-to"></a>Going to say this is probably better done in a plugin...

At the moment tags aren't actually stored as an explicit list (they're a bit of magic between some regex to turn a hashtag into a link, and the search function built in to Known).

A plugin to do this would, I imagine, listen to the save event to catch an object, parse the body text for hashtags, and then update some list of tags - possibly incrementing a counter based on how many times it's seen etc.

This data could then be used to construct the view you describe.
