### ISSUE TITLE
Feature Request: Add support for JF2 Feed

### ISSUE THREAD

**Issue by dissolve** [idno/Known#1805]
This is a request to add support for JF2 Feed from the W3C Social Web WG.  Info and validator is all linked from jf2.rocks.  Its quite similar to JSON Feed but is based on microformats vocabulary, has a mime type, and is more extensible.

CC: @cleverdevil

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1805" class="u-in-reply-to"></a>New one to me :)

Doubt I'll have time to read about this, but pull requests / plugins welcome :)

**Comment by cleverdevil** [comment]
Thanks, @dissolve. I'll plan on working on this over my upcoming holiday. Should be a fun little project.

I'll implement it as a separate feed from JSON Feed and the Known-native JSON feed format, so as to avoid conflicts or issues.

**Comment by mapkyca** [comment]
Closing as it have almost been a year. PRs or plugins welcome though!
