### ISSUE TITLE
Headers on feeds: Last-Modified, Etag

### ISSUE THREAD

**Issue by gRegorLove** [idno/Known#1815]
While [discussing](https://chat.indieweb.org/2017-07-07#t1499451632792000) why superfeedr might be re-sending notifications for older posts for @chrisaldrich (and other Known users), I checked a per-post RSS feed (http://stream.boffosocko.com/2017/i-was-just-enjoying-the-new-twitter-icons-when-i?_t=rss) and noticed the `Last-Modified` header appears to always be the current timestamp, not a static timestamp.

My hypothesis is Superfeedr is finding the XML feeds after the initial WebSub notification and then polling them periodically. https://blog.superfeedr.com/publishers.html explains that `Etag` will be respected, so it might be a good idea to add that along with support for `If-Modified-Since` request headers, and correcting the `Last-Modified`.

Edit: clarified `If-Modified-Since`, thanks @cweiske!

**Comment by cweiske** [comment]
`If-Modified-Since` is a request header, not something the server sends.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/idno/Known/issues/1815" class="u-in-reply-to"></a>Here's another example of this superfeedr quirk in action:
https://indiechat.search.cweiske.de/?q=%22Why+we+built+Known%22

**Comment by mapkyca** [comment]
Hmm... definitely *used* to set last modified correctly.... I'll have a look when I get a moment...
