### ISSUE TITLE
Can't Filter Content to show Replies

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#1816]
## While trying to do this:
Filter my site to just see "Replies" using the "Filter content" dropdown menu in the header

## I encountered this error:
There somehow isn't a dropdown option to choose looking only at replies even though the URL for it exists at the path /content/replies/. I can potentially see how/why it may have been made as a conscious UI/UX choice to not include it, but since all of the other options exist as a default, I'm guessing it may have been an oversight?

## Some other notes:
This is separate from anything to do with the "Site Configuration" settings at /admin/homepage/ which allow one to remove "Replies" from showing on the homepage.

Using stock v0.9.9.

**Comment by mapkyca** [comment]
IIRC this was removed from the dropdown as it was felt that it was confusing for people...

/cc @benwerd

**Comment by mapkyca** [comment]
Closing, confirmed this was a concious UX decision a while back...
