### ISSUE TITLE
Error: source not supported

### ISSUE THREAD

**Issue by jeremycherfas** [idno/known#1830]
## While trying to do this:

Send a webmention from Grav, locally, to Known, locally, using curl:

````
Curl -i -d source=http://localhost:8888/grav-admin/blog/testing-send-of-web-mention -d target=http://localhost:8888/Known/2017/this-a-reply-from-the-local-withknown-install-to-the http://localhost:8888/Known/webmention/
````

## I encountered this error:
`{"error":"source_not_supported","error_text":"Could not interpret source as a comment."}`

Full return [here](https://gist.github.com/jeremycherfas/ff4d841d60b656e84092704373a64bb2).

## Some other notes:

The [source HTML](https://gist.github.com/jeremycherfas/cf65220b33bfbce520ab169a4117526b) seems fine.

Not sure whether this relates to [this issue ](https://github.com/idno/Known/issues/1340#issuecomment-200120885).

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version = "0.9.9"
build = 2017051501``` file*

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1830" class="u-in-reply-to"></a>Not sure if this is still an issue - but if it is you could try against the latest master

**Comment by mapkyca** [comment]
Closing as no reply - but this error can be generated when you're trying to web mention a page that doesn't implement fully webmentionContent(), which typically occurs if a plugin implements their own view handler, rather than using the framework one.
