### ISSUE TITLE
Post permissions not set when posting

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1839]
## While trying to do this:
Post a photo post with 'Members Only' permission.

## I encountered this error:
Photo post is Public

## Some other notes:
When I change the permission from Public to Members Only the page resets and takes me back to the top as usual but when posting completes I can see the post is Public.

When edit the post afterwards and change the post to Members Only it is set correctly.

Using latest git commit 659d89369daeb655f4db894d68da62c6179e6810
version.known = version = "0.9.9" build = 2017072401

**Comment by markwaters** [comment]
I pulled to commit 47ca2ec566281dae0de2961f40e7982381587dc9 but the 'Members Only' posts are still being set to 'Public'.

**Comment by mapkyca** [comment]
Make sure you do a ctrl-f5 refresh to get the latest build of the javascript libraries

**Comment by markwaters** [comment]
Thanks @mapkyca , that fixed it in Firefox on my desktop.
