### ISSUE TITLE
Admin (and maybe settings) should probably have it's own page shell

### ISSUE THREAD

**Issue by mapkyca** [idno/known#1846]
## While trying to do this:

Use admin settings

## I encountered this error:

I had broken something on the theme which meant all the forms were broken. Currently it's all too easy for a theme or plugin to break something and leave you with an inoperable admin section. 

Discuss

## Some other notes:

Ref #1641

**Comment by mapkyca** [comment]
Based on discussion, I'm bumping this and adding it to the Known 1.0 todo list.

This will likely be a breaking change for a number of plugins, so should probably be done now rather than later, and I think it is important to follow the wordpress model and keep settings and admin settings separate from any code added by the theme (which can break the site)

**Comment by physcocode** [comment]
Is it about themes should not override admin view ? Like WordPress?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/1846#issuecomment-444234782" class="u-in-reply-to"></a>Basically. I'd like to see admin and user settings in its own isolated theme. We've had issues where people have for example embedded javascript into their theme (or fudged their PHP) and it renders the whole site unusable and making it difficult to disable the theme and work backwards.
