### ISSUE TITLE
Is POSSE to elgg powered site possible?

### ISSUE THREAD

**Issue by ghost** [idno/Known#185]
I wonder whether  poose with elgg power site possible by cross API's

**Comment by benwerd** [comment]
We're not going to implement this, but it would be fun to see a third-party plugin!

**Comment by physcocode** [comment]
Job undertaken ! I am little off from the latest development of egg since i caught up with known but i would possibly love working on this

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/185#issuecomment-176841597" class="u-in-reply-to"></a>IIRC newer versions of elgg have native OAuth2 server support, but I may have imagined that. Certainly there's a plugin that provides such support, which you could require.

Assuming that's in place xpost should be fairly straightforward: I've written a Wordpress <-> Elgg integration in the past, and I don't remember that being all that painful.
