### ISSUE TITLE
Only at root of virtual host?

### ISSUE THREAD

**Issue by indieboxproject** [idno/Known#188]
Is it correct that Idno currently only wants to run at the root of a virtual host? If so, could this be documented somewhere. And, it would be nice if could also run at paths below, so I could, for example, run Idno at http://example.com/idno/, and a wiki at http://example.com/wiki/

**Comment by benwerd** [comment]
Bumping this. We will categorically fix Known to work in any directory.

**Comment by benwerd** [comment]
This has now been fixed in the latest version.
