### ISSUE TITLE
Can administrator account creation be scripted?

### ISSUE THREAD

**Issue by indieboxproject** [idno/Known#189]
Right now, the first account that is being created is the admin account, right? Could this somehow be scripted? (Might just be a few inserts into the db)
This would avoid a race between the installation and the first guy who hits the website and creates themselves an admin account.
##

**Comment by benwerd** [comment]
Also see #524 and #488.

I've recently become aware of Drupal's solution for this, which is actually pretty good. We may emulate.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/189" class="u-in-reply-to"></a>Bumping with a note about CLI existing

**Comment by mapkyca** [comment]
Superceded by #524
