### ISSUE TITLE
Option to control import of summary from bookmarked site

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1908]
## While trying to do this:

Bookmark a page at https://danwarne.wordpress.com/2014/03/05/fix-stuck-mac-os-clipboard-copypaste

## I encountered this error:

Known seems to be trying to pull in something -- maybe the summary? --  of the page I want to bookmark.

## Some other notes:

It looks really weird, and there doesn't seem to be any way in Known to control this behaviour. I can't see anything about it in the source, and I can't see or edit the source for the title, which I guess is where the micro format is.

Here's the post in Known https://stream.jeremycherfas.net/2017/how-to-fix-stuck-mac-os-x-clipboard-wont-copypaste

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version = "0.9.9"
build = 2017091201``` file*

**Comment by mapkyca** [comment]
That's link unfurling, it's pulled from the site's open graph tags etc. Same way facebook and twitter do.

It is possible to theme this though, so you could modify the object/UnfurledUrl template to render it in a different way/not at all

**Comment by jeremycherfas** [comment]
Fair enough. I'll have a play eventually, although a straight optional would be easier, at least for me.
