### ISSUE TITLE
## While trying to do this:

Delete a comment

## I encountered this error:

Page not found

## Some other notes:

The delete links generated beside comments seem to be

### ISSUE THREAD

**Issue by mruncieman** [idno/Known#1909]
<a href="https://github.com/idno/Known/issues" class="u-in-reply-to"></a>## While trying to do this:

Delete a comment

## I encountered this error:

Page not found

## Some other notes:

The delete links generated beside comments seem to be missing information. All of them are generated as
http://www.domain.com/2017/0
http://www.domain.com/2017/1
http://www.domain.com/2017/2

cat known.version
version = "0.9.9"
build = 2017091501

**Comment by markwaters** [comment]
I am also seeing the same thing.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1909" class="u-in-reply-to"></a>Odd... looks like comments (well, webmentions at least) are being generated with a weird permalink, not sure why.

**Comment by markwaters** [comment]
Thanks @mapkyca , works perfectly for me.

**Comment by mruncieman** [comment]
<a href="https://github.com/idno/Known/issues/1909" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1909" class="u-in-reply-to"></a><a href="https://michael.runcieman.com/2017/-while-trying-to-do-thisdelete-a-comment-i-encountered" class="u-in-reply-to"></a>This is still happening for likes.
