### ISSUE TITLE
Known Community website and central plugin management

### ISSUE THREAD

**Issue by physcocode** [idno/Known#1926]
Known needs a community website or a known instance where community can communicate and a central plugin system 

If composer is merged with core which was rejected we can use composer as plugin management, symphony and others have already started using composer as a installation for there extended services.

To be fair I have been promoting known to many people but its lack of central plugin and theming system its not being adopted and people switch to wordpress

**Comment by jeremycherfas** [comment]
There is the IRC channel -- freenode#knownchat -- which is bridged to the indieweb Slack channel but I agree it needs some activity to indicate that the single-user, self-hosted version has not been abandoned. The instructions for hosting at Dreamhost and the one-click install at Reclaim hosting should be more widely promoted too.

**Comment by mapkyca** [comment]
In terms of rumour control, the self hosted version is not going to go anywhere any time soon - it's still being actively developed, and used by paying clients.

In terms of plugin repo, I don't think anyone has time to get to that at the moment, ditto a community site.  PRs entirely welcome to keep the plugin list in docs more up to date though...
