### ISSUE TITLE
broken twitter images

### ISSUE THREAD

**Issue by drikkes** [idno/Known#1969]
### When syndicating likes from Twitter, profile pics gets broken. 

![bildschirmfoto 2017-12-05 um 14 42 18](https://user-images.githubusercontent.com/6489982/33610118-c522982e-d9ca-11e7-850d-e312faa21ff0.png)

### This seems to happen more often, when Facebook likes/comments already exist for the known post.

![bildschirmfoto 2017-12-05 um 14 45 19](https://user-images.githubusercontent.com/6489982/33610213-186a1340-d9cb-11e7-9c28-03aab1f3b288.png)

### I can't code, I have absolutely no idea, why this happens. Not installed the latest Known version. (Or could this be a Bridgy issue?)

**Comment by mapkyca** [comment]
I cant check, but this is likely a bridgy issue... known gets the image url from bridgy, so if that's broken there's not much we can do. Worth opening the network console and seeing what error it is (404/500 etc) and what the url is that we're getting.

**Comment by mapkyca** [comment]
Ok, back at my desk. Could you send me some examples? Want to try and isolate whether this is an imageproxy problem, a bridgy problem or a source url problem

**Comment by drikkes** [comment]
Yes, sure.
Here, Facebook worked, Twitter not. http://drikk.es/2017/erster
One Twitter profile broken, the other is fine. http://drikk.es/2017/alexa-kaufe-alles-von-seitenbacher
And I found one with a broken FB pic as well. http://drikk.es/2017/die-tvdirekt-hat-schnell-einen-clp-kommentar-geschaltet-zum-fall-thomas
Thanks for investigating!

**Comment by snarfed** [comment]
just fyi, cross posting this here from https://github.com/snarfed/bridgy/issues/782#issuecomment-350426167 :

> i checked a few of these, and they seem to be ok on bridgy's end. both broken twitter profile pictures on the http://drikk.es/2017/erster responses are ok:
> 
>     https://brid-gy.appspot.com/like/twitter/drikkes/933729772471050240/248732513
>     https://brid-gy.appspot.com/like/twitter/drikkes/933729772471050240/18722530
> 
> and the facebook response on http://drikk.es/2017/die-tvdirekt-hat-schnell-einen-clp-kommentar-geschaltet-zum-fall-thomas is ok too:
> 
>     https://brid-gy.appspot.com/like/facebook/10206219375153745/10214333171593585/1717151104977519
> 
> the image URLs point to twitter and facebook themselves, not bridgy, and some of them (e.g. twitter's) do change when people change their profile pictures...but it looks like known fetches and stores them locally, so that's not the problem here.

**Comment by mapkyca** [comment]
Ok, well it looks like this is a fairly old build of Known as it's not using the imageproxy. The old way that known used to handle profile images was to fetch them and store them as a local file (to handle a security issue with webmentions), however the way it did this was a one shot deal, with no failure recovery. So, if it failed to get the file, you might get some html instead, or a zero byte file - this appears to be happening.

You could try using the latest master, since this includes the image proxy code which allows for much better recovery, and a manual retry if all else fails.
