### ISSUE TITLE
POSSE to email/email list #plugin #idea

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#197]
Be able to select "email" from the posse list and be able to enter one or more email addresses, select from previous addresses or pre-prepared mailing lists.

Example use case: my dad, who's just about on email, but hasn't got the whole "social network" thing yet - it'd be nice to easily keep him up to date with an email from the platform.
##

**Comment by herbsmn** [comment]
Hey @dshanske what do you use on https://david.shanske.com/ to be able to POSSE to email and pull the responses back? I remember @rhiaro commented on this post via email. https://david.shanske.com/2015/03/19/at-indiewebcamp/

Maybe it'd help Known on this issue if they could look at the code you used.

**Comment by benwerd** [comment]
We have an understanding of how to build this, but it's not at the top of the list of priorities right now. We'd love to work with any group that wants us to build this with them - or wants to submit this as a community contribution.

**Comment by herbsmn** [comment]
To facilitate community contributions on this, the Google+ plugin, and other plugins do you have a space on github or elsewhere where general outlines of what needs to be done and what code needs to be written is posted? I'm guessing http://indiewebcamp.com/Google_Plus & http://indiewebcamp.com/email has the majority of info on this right now, no?

**Comment by dshanske** [comment]
I use Postmatic. It is a third party service. It fits very well into my needs, so as of now, I haven't given rolling my own solution serious consideration.

**Comment by physcocode** [comment]
can be closed , third party plugin,not related to core !
