### ISSUE TITLE
[MicroPub] Token Endpoint should return content as application/json not application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by EdwardHinkle** [idno/Known#1986]
## While trying to do this:
Authenticate using IndieAuth in a Micropub Application

## I encountered this error:
The content returned from the token verification endpoint was in application/x-www-form-urlencoded, however the current standard for IndieAuth is to line up with OAuth 2.0's standard which is that the returned content from a token verification endpoint is returned as application/json.

## Some other notes:
You can see the current IndieAuth standard at: https://www.w3.org/TR/indieauth/#access-token-response

**Comment by swentel** [comment]
Shouldn't this be added to Pages/IndieAuth/Token.php too ?
I'm encoutering this in with the Android client now as well, cf https://github.com/swentel/indigenous-android/issues/25

**Comment by aaronpk** [comment]
Yeah that needs to be changed in the token endpoint. Looks like 5bd7a9fab6d2f3043d507a8425da8898b471da34 only changed the response from the Micropub endpoint

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1986" class="u-in-reply-to"></a>Does the auth token need this too?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1986" class="u-in-reply-to"></a>s/token/endpoint

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1986" class="u-in-reply-to"></a>... although url encoded strings should be supported, right? That seems to be what the referenced ticket implies...
