### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by jernst** [idno/Known#1987]
Lots of messages in the log when running with PHP 7.2, such as:

```
warning - PHP [2] Illegal string offset 'Host' in ...Idno/Common/Page.php:942
```

Just FYI.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1987" class="u-in-reply-to"></a>Not seeing this in the travis builds (and I don't currently have a PHP 7.2 build handy). Have you tried with the latest master?

**Comment by jernst** [comment]
I'm pulling the release tars for @uboslinux, and noticed that during testing for the next release. Trying to avoid master because that's much harder to support. Is there an easy script that assembles the tar from git? If so, I'd happy to try that.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1987#issuecomment-364542471" class="u-in-reply-to"></a>You could take a look at https://github.com/mapkyca/known-package, although if you want the signed stuff you'll need to use your own gnupg id

**Comment by jernst** [comment]
It appears git HEAD does not have this problem. Good! Are there plans for a new versioned release some time soon? :-)
