### ISSUE TITLE
Support multiple photo posts

### ISSUE THREAD

**Issue by cleverdevil** [idno/Known#1991]
Micro.blog's iOS and macOS clients support a nice feature where you can attach multiple photos to a post, and then create an entry with some prose and the images as well. According to @manton, he uses Micropub, with `h=entry`, and multiple `photo[]=` params passed, after using the Media Endpoint to first upload each photo.

Currently, Known rejects these posts, and I'm not entirely sure why. There are several ways I can think of to handle this:

1. Create a new `Entity` called `Gallery` or `Photos`, which is specifically targeted to handling this use case, and then do a bunch of work to support it in the Micropub Endpoint and the frontend. This seems to fit the pattern of other problems solved in Known, but I don't particularly like this way.

2. Work on the `Text` Entity's support for multiple attachments, and smartly render them, along with any provided content, then enhance the Micropub Endpoint to create these in the case that multiple photos are passed in.

I would love to hear @mapkyca and @benwerd chime in when they have a chance :)

**Comment by EdwardHinkle** [comment]
Also just to support the importance of this, Indigenous, an iOS Micropub Client also uploads photos individually using a media endpoint and then gathers the urls into multiple photo[]= params.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1991" class="u-in-reply-to"></a>Sure I had a "support galleries" ticket around here somewhere...

Yes, it would be nice to support multiple photos. I think the biggest block on it thus far has been getting the UX right.

From an object level, having an upload of multiple files be intercepted and created as a Gallery object would probably be smart, they could then be rendered out in a nice way (maybe something along the lines of Facebook's collage).

**Comment by cleverdevil** [comment]
While I think a Gallery object would be nice, eventually, I am not convinced that its necessarily the best way to go here. Its my understanding that pretty much all Entities support attachments, so doing it in the near-term in a more cross-cutting way would enable any type of post created via Micropub that contains multiple attachments to elegantly display the images.

(Originally published at: https://cleverdevil.io/2018/while-i-think-a-gallery-object-would)

**Comment by mapkyca** [comment]
Related #1508

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1991#issuecomment-364557504" class="u-in-reply-to"></a>@cleverdevel Yes, I agree, that would probably be the simplest mechanism. Known can indeed make use of multiple attachments.

Downside the title and description would not be per - photo, so in this context photo does become a gallery. 

I think we'd also need to mod the template to render this in a nice way.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1991#issuecomment-364557504" class="u-in-reply-to"></a>So, we'd need to modify the save to handle arrays, if given. Add an "add another" to the edit template, and modify the display template to render these images in nice thumbnails in the list, with a nice clickthrough to a full version where appropriate.

Bonus would be to set the appropriate meta to allow my lightbox plugin to hook in and render it as a gallery

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1991" class="u-in-reply-to"></a>Also, it should be noted, that the $_FILES array is *horrible*. As part of this I'd love to see a normalisation method added to Input...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1991" class="u-in-reply-to"></a>Another issue to consider is we need a way to  edit the post, and specifically change the picture, without clobbering other pictures.

Currently deleteAttachments() doesn't allow granular removal/replacement.

Uploading of replacement pictures is functionality that needs to be preserved.
