### ISSUE TITLE
Editing Post cache issue

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1993]
## While trying to do this:
Edit a post
## I encountered this error:
Shows previous version.

Steps to reproduce.
1. Create a post.
2. Publish Post.
3. Edit same post.
4. Edit page shows older version.
5. Hard reload browser with Control+Shift+R
6. Post reloads with latest correct contents.

I have cleared the Firefox cache , I have also tried disabling the PHP op-cache.
Seeing same issue in Chromium browser and Firefox on Android and Windows.

version = "0.9.9"
build = 2018020401

**Comment by markwaters** [comment]
I have rolled back to dbdec001ce94c279db94165055c82857d1be4d9b
with
git reset --hard dbdec001ce94c279db94165055c82857d1be4d9b
and I am no longer seeing this issue.

**Comment by markwaters** [comment]
Rolling forward this morning.
Not seeing this issue at commit 6e351614bea32fdb99a4e1d8046f9951a4468a32
But I am seeing it at 39d87d8637056d73b1de9a1ddb7d753b56817fb3

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1993" class="u-in-reply-to"></a>My bet is that this was introduced by the fixing of the cache header with ce203f7d5d87b303f81819a802e6bc86d11b0979
