### ISSUE TITLE
[MicroPub] Bookmark API does not accept description

### ISSUE THREAD

**Issue by jeremycherfas** [idno/known#1994]
## While trying to do this:
Use Micropub to post a Bookmark with a Description 

## I encountered this error:
Known refuses to accept the content of the Description. This is despite the fact that if I create a bookmark from the Known posting interface, I can include a Description. 

## Some other notes:
The reason seems to be that Known forces the POST to be type Bookmark, and the Plugin then has no Description element. When creating a Bookmark via the posting interface, there is no field for that.

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1994" class="u-in-reply-to"></a>Could you attach some json you're sending?

Not that familiar with MicroPub, but it looks like we're accepting a 'content' field... which I imagine is analogous to 'description'...?

**Comment by jeremycherfas** [comment]
Sure.

I try this, for example:
````
curl -X POST -H 'User-Agent: shpub' -H 'Content-Type: application/json' -H 'Authorization: Bearer xxxx' --data '{"type":["h-entry"],"properties":{"bookmark-of":["https:\/\/indieweb.org\/bookmark"],"tags":["#testtag"],"title":["Description edited curl"],"https:\/\/indieweb.org\/bookmark":[null]}}' 'https://stream.jeremycherfas.net/micropub/endpoint'
````

And I get the result you see here https://stream.jeremycherfas.net/2018/bookmark---indieweb-1 Note that the field that Known calls Description when I create a post by hand is empty.

Creating the bookmark by hand results in this https://stream.jeremycherfas.net/2018/bookmark---indieweb-3 which **does** include the content of the Description field.

The reason seems to be that although Known accepts 

````
$body = \Idno\Core\Idno::site()->currentPage()->getInput('body');
                $description = \Idno\Core\Idno::site()->currentPage()-` 
````

If the `type` is `bookmark` then the Description gets stripped out.

**Comment by jeremycherfas** [comment]
Added more detail [here](https://www.jeremycherfas.net/blog/why-i-cannot-post-bookmarks-to-known-automatically).

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1994#issuecomment-364044730" class="u-in-reply-to"></a>Correct me if I'm wrong, but regardless of whether it's being stripped out, it doesn't look like that json contains a description field...?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1994#issuecomment-364044730" class="u-in-reply-to"></a>the bookmark plugin looks for description in the 'description' attr, but if it's being supplied then maybe we're looking in the wrong place...

**Comment by jeremycherfas** [comment]
I've tried so many permutations of the curl POST I may have selected the wrong one. Regardless, it strips out the tags too.

Take a look at the blobs I linked in my longer post, especialy this:

````
                        if (!empty($bookmarkof)) {
                            $this->body = $bookmarkof;
                            $this->bookmarkof = $bookmarkof;
                        }
````

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1994#issuecomment-364044730" class="u-in-reply-to"></a>Yes, but we're talking about description, right? For Like, ```body``` is the link, not the description. 

When you send a description of the link, what does the JSON look like?

**Comment by jeremycherfas** [comment]
Oh cool. Thanks. Now to update and test.
