### ISSUE TITLE
[MicroPub] syndication targets should return both UID and name from the q=config micropub endpoint

### ISSUE THREAD

**Issue by EdwardHinkle** [idno/known#2001]
When logging in to a Micropub Client, it queries the micropub endpoint for information (/endpoint/?q=config), the syndication targets returned from that endpoint are an array of UIDs. However, when you ping /endpoint/?q=syndicate-to you get an array of UID and Name.

The responses from both q=config and q=syndicate-to should match. The login in q=syndicate-to that contains both the UID and name should be used in the q=config query as well.

**Comment by mapkyca** [comment]
Is this fixed by #2277 ..?

**Comment by EdwardHinkle** [comment]
Yep, that’s the fix! 👍

**Comment by mapkyca** [comment]
Awesome!
