### ISSUE TITLE
Redirect to ./warmup

### ISSUE THREAD

**Issue by jernst** [idno/Known#2007]
Fresh install from git into Linux container `test`. Very first HTTP request via curl:
```
curl -v test1
* Rebuilt URL to: test1/
*   Trying 10.0.0.6...
* TCP_NODELAY set
* Connected to test1 (10.0.0.6) port 80 (#0)
> GET / HTTP/1.1
> Host: test1
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Sat, 10 Feb 2018 23:19:45 GMT
< Server: Apache
< X-Powered-By: PHP/7.2.2
< Location: ./warmup/
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
```

The `Location` header is `./warmup/`. I don't think it this is a valid value.

**Comment by physcocode** [comment]
i guess the fresh installation of known starts with warmup so whats wrong here ?

**Comment by mapkyca** [comment]
Yep, that sounds like the correct behaviour.

Warmup will trigger if there's no config.ini or database

**Comment by jernst** [comment]
I was referring to the `./warmup/` relative URL, but you guys are right, apparently since rfc7231 this is a valid content for `Location:`. I must have missed that update.

As a side note, there are two references to it in the code, and they are inconsistent:
```
Idno/Core/Idno.php:                    header('Location: ./warmup/');
index.php:        header('Location: warmup/'); exit;
```
(Yes, I agree now that both are valid)
