### ISSUE TITLE
Syndicating pic to Twitter

### ISSUE THREAD

**Issue by erinjo** [idno/Known#201]
Either Idno doesn't post to Twitter when you're trying to reply to someone who has a protected account (even if you follow that person),

or

Idno doesn't like posting pictures to Twitter that @mention someone who has a protected account.

Either way, the Twitter syndication got stripped off a picture I tried to @mention to my mom.  :-(

I will need to replicate to narrow it down.

**Comment by beck24** [comment]
I just came to report that pics weren't posting to Twitter correctly, the one I did today had a mention, the previous one did not.

**Comment by davidmead** [comment]
I noticed the same thing over the weekend @erinjo. When posting photos from The IA Summit, only the ones *without* a twitter username would post to Twitter. It didn't seem to matter if the user was protected or not.

![screen shot 2015-04-29 at 2 55 17 pm](https://cloud.githubusercontent.com/assets/1266930/7398918/197ebdc8-ee80-11e4-964c-b432e7736f1f.png)

I had to post the top photo using Twitter, whereas the bottom photo syndicated just fine. Only difference is one contains an '@'.

![screen shot 2015-04-29 at 2 59 34 pm](https://cloud.githubusercontent.com/assets/1266930/7398956/65a09d3e-ee80-11e4-9b86-3bbf27584807.png)

**Comment by benwerd** [comment]
Duplicated. Looking into it.

On Wed, Apr 29, 2015 at 12:02 PM, David Mead <notifications@github.com>
wrote:

> I noticed the same thing over the weekend @erinjo
> <https://github.com/erinjo>. When posting photos from The IA Summit, only
> the ones *without* a twitter username would post to Twitter. It didn't
> seem to matter if the user was protected or not.
>
> [image: screen shot 2015-04-29 at 2 55 17 pm]
> <https://cloud.githubusercontent.com/assets/1266930/7398918/197ebdc8-ee80-11e4-964c-b432e7736f1f.png>
>
> I had to post the top photo using Twitter, whereas the bottom photo
> syndicated just fine. Only difference is one contains an '@'.
>
> [image: screen shot 2015-04-29 at 2 59 34 pm]
> <https://cloud.githubusercontent.com/assets/1266930/7398956/65a09d3e-ee80-11e4-9b86-3bbf27584807.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/201#issuecomment-97542985>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
This no longer seems to be happening.
