### ISSUE TITLE
Can no longer log into my site after removal of `referrerGatekeeper`

### ISSUE THREAD

**Issue by cleverdevil** [idno/Known#2019]
## While trying to do this:

Log in to my site running the latest from master.

## I encountered this error:

An error about a missing method `referrerGatekeeper`.

## Some other notes:

If I roll back to just before this commit:

https://github.com/idno/Known/commit/ee1e4a0b5d8657ff1199fd20652b9c8518921902

Everything works again.

**Comment by mapkyca** [comment]
Looks like I didn't remove references for the alternate spelling! Sorry about that.

**Comment by markwaters** [comment]
I am seeing this when trying to leave a comment as a non-logged-in user of a site.
Not sure if it is related.

Fatal Error: /var/www/known.multisite/IdnoPlugins/Comments/Pages/Post.php:26 - "Call to undefined method IdnoPlugins\Comments\Pages\Post::referrerGatekeeper()", on page weloveit.info/comments/post
