### ISSUE TITLE
Fatal Error: /IdnoPlugins/Comments/Pages/Post.php:26

### ISSUE THREAD

**Issue by lgbti** [idno/Known#2029]
## While trying to do this:
Add comment

## I encountered this error:
Oh no! Known experienced a problem!
Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /home/xxx/public_html/IdnoPlugins/Comments/Pages/Post.php:26 - "Call to undefined method IdnoPlugins\Comments\Pages\Post::referrerGatekeeper()", on page xxx.com/comments/post

## Some other notes:
Version: 0.9.9

**Comment by mapkyca** [comment]
Already addressed by #2028
