### ISSUE TITLE
Translation mechanism requires translators to be programmers

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2033]
Caveat: I created the original Language object, and I can't remember what my intentions were.

Right now, any translator of Known has to actually write a plugin to make a language available. It's possible that translators are also programmers, but it's not necessarily true.

Known needs a standard way to extract all GetText strings, make them available as a corpus for translation using standard tools, and have pure language files be automatically available.

Without these things, it's almost impossible to translate Known in an efficient way using tools familiar to most open source translators.

**Comment by mapkyca** [comment]
That already exists, and is one of the reasons why I added gettext support in extension to the MAoS support (which absolutely definitely does require translators to be programmers, and was one of its biggest problems).

So, at the moment, the priority is add the translation hooks around strings. The next step is that we generate this corpus, using a script I've already written (see /languages), which generates a .POT file. 

This file needs to only be generated when strings are added or changed, but largely this will be static, and only *really* needs to be done by us. We distribute this with Known, and can be loaded into any number of existing tools, including web based ones.

**Comment by mapkyca** [comment]
I'm in favour of keeping the MAoS support as it currently stands, as it allows one-man-band plugin authors (who are programmers) a quick way of being compliant, without needing to read up on gettext - which might be a little onerous, especially if you've only a couple of strings.

However, as I've written it, it can largely be used interchangeably, and conversion to a gettext corpus can be done largely automatically.

**Comment by mapkyca** [comment]
Here's a bit of a summary: https://www.marcus-povey.co.uk/2018/02/22/gettext-support-in-known/ also on docs.withknown.com

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2033" class="u-in-reply-to"></a>Latest build demonstrates how to apply per-plugin translations. 

If you look at the Status plugin now, you'll see that (for all the hooks I've added so far) all the actual programming has been done, and it can now be translated.
