### ISSUE TITLE
In the profile page of a site-member status updates get shown (listed) but photos or other stuffs such as comics are not shown. 

### ISSUE THREAD

**Issue by rhisss** [idno/Known#2036]
I am trying a self-hosted Known installation where others/members can register and upload own photos or status or other stuffs. In the profile page of a site-member status updates get shown (listed) but photos or other stuffs such as comics are not shown. How as an admin I can set this so that when clicked on an user's name, contents by him can be seen.

**Comment by mapkyca** [comment]
This is not something that's currently possible. It was mooted a while ago, but so far nobody has had time to work on it, and it hasn't been sufficiently big enough of an itch for anyone to submit a PR (although personally I'd like to see it).

See #1587

**Comment by rhisss** [comment]
Thanks Mapkyca for the fast and helpful response. So may be / do I assume that multi-user set up for Known is sort of useless (when one is not interested in getting fb, twitter, xyz comments or posts in one place) because an user cannot find another user's photos / comics / events etc when there are even as little as some 100 users. So basically Known is for single user so far ?? Thanks again for participating and helping me to understand Known better.

**Comment by rhisss** [comment]
However, if it is rather a site that is multi-user **but** shared between a small group of family members or a few members of a small club, who can agree to use / not use certain reserved hashtags - then user A can upload photos with a hashtag userApics ( similarly userNpics) and then add the weblink of that hashtag in his profile website fields. If the about me field supported hashtag ( or if custom profile fields be vreated by the site superadmin) it would be even better. How difficult is it for the core devs to add hashtag support to the about field ? Another thing will be great, if by default, such hashtag is added by the system (with an unique hidden number attached to it) and if the system adds this to the profile field by default.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2036#issuecomment-368871629" class="u-in-reply-to"></a>Useless is a little bit strong, but multi-user "social network" style builds are a less trodden path.

They do exist, however, but often have customisations which add much of what you're asking in this another tickets - e.g. often, they replace the profile to something more configurable and relevant to their custom domain.  

Enabling hashtag support on the profile would be fairly straightforward (in fact, I'm not entirely sure if that isn't already in place...)
