### ISSUE TITLE
Searching the contents created/posted by an user gives no result

### ISSUE THREAD

**Issue by rhisss** [idno/Known#2038]
**While trying to do this:**
Trying to search the contents created/posted by an user, in a multi-user set-up of Known via the search box at top
**I encountered this error:**
Nothing shows.
Creates confusion as how to find contents by an user

**Some other notes**: Is anyone else or any actual site using multi-user Known? How are they tackling this problem or is it just an error on my side ?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2038" class="u-in-reply-to"></a>Are you saying that search produce no results, or that they're not the results you're expecting? What exactly are you searching *for*, i.e. are you trying to use some specific syntax to search for a specific user's contents? (that functionality doesn't currently exist, search is global across all content)

**Comment by rhisss** [comment]
Thanks mapkyca. Search produce no results and this is what I am not expecting. When I enter the name of an user in search box in a multi-user set-up of Known, the search results show nothing. Please forget for a moment, what I am doing, and kindly point me to how does one user find the contents posted by another user by using search ? Many thanks.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2038" class="u-in-reply-to"></a>Out of the box search doesn't search users, or give the option of limiting search to a specific user/set of users. Rather, it searches for user's *content* across all users.

**Comment by rhisss** [comment]
In the context of multi-user installations of Known, then, it should be specifically mentioned under or atop the search box, that user or user-specific content **cannot** be searched to avoid the confusion of end-users or site members. This needs to be mentioned as this is a very specific search behavior that any common php script does not have. Putting an user name in any search box ususally gives some result, as far as I can remember. Many thanks again mapkyca,

**Comment by rhisss** [comment]
Wait. Hold on. I think I am confused about the problem to some extent. How I am searching an user ?
- Am I typing the user name in search box and hitting enter ?
-OR Am I typing the user name and then clicking on "All content" / Status / Photo etc ?
What was the intended behavior of the devs ? Hitting enter after typing a search term / user name and then if needed filter by clicking the drop-down of content options ? Or something else ? Can some one please elaborate ?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2038" class="u-in-reply-to"></a>I'm a little confused what you're asking here, but basically at the moment you can't search for users (if that's what you're trying to do) only content of users.
