### ISSUE TITLE
With PHP 7.2.2 installation of Known fails

### ISSUE THREAD

**Issue by rhisss** [idno/Known#2039]
With PHP 7.2.2 installation of the latest available Known fails from the very beginning and gives this error message:
`Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /home/xxx/public_html/xxx.com/known/external/htmlpurifier-lite/library/HTMLPurifier.autoload.php on line 17`

Is it essential to downgrade php version for Known ?

**Comment by mapkyca** [comment]
Are you using the latest master build? This should have been fixed in the latest builds...

**Comment by rhisss** [comment]
I am using http://assets.withknown.com/releases/known-0.9.9.zip as available at present on https://withknown.com/opensource/

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2039#issuecomment-368938443" class="u-in-reply-to"></a>Yep, use the master build. There's a lot of work that has been done since that build was put together...

**Comment by physcocode** [comment]
@rhisss clone the latest build from git and you are good to go for PHP 7+
