### ISSUE TITLE
Linked release from withknown.com fails registration

### ISSUE THREAD

**Issue by 33mhz** [idno/Known#2041]
## While trying to do this:
Install from https://withknown.com/opensource/ ("Download Known"), or log in afterwards.
## I encountered this error:
nginx returns 502 when trying to register initially, or log in afterwards. I ended up doing this fix myself:  https://github.com/idno/Known/commit/152c801a6252d17777a1e9c25946406a0cd97251#diff-da60d8a7c43bed0e3cfa66c2b5c43e87, and then went looking for a reported issue for it. The instance works now, but the linked release is faulty.
## Some other notes:
This is in my `version.known` file:
```
version = "0.9.9"
build = 2017051501
```

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2041" class="u-in-reply-to"></a>Thanks for the report. 

This is fixed on Master, and will be fixed on site with the next release build.
