### ISSUE TITLE
Posting status of "0" is not allowed

### ISSUE THREAD

**Issue by 33mhz** [idno/Known#2042]
## While trying to do this:
Post a status of `0`.
## I encountered this error:
*You can't save an empty status update.*
## Some other notes:
Checks for `empty()` here: https://github.com/idno/Known/blob/6d6133e4351b2f3b27e15ca684784934997c5e63/IdnoPlugins/Status/Status.php#L102

**Comment by rhisss** [comment]
However, I am able to post actual empty status update, that is at least visibly empty to viewers. Hit spacebar once or twice in the textbox, and then "publish". Empty status gets published both in my site and elsewhere (if "Reply to a site" is used).

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2042" class="u-in-reply-to"></a>LOL :D Amusing edge case, I'll have a think about a better way...

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2042" class="u-in-reply-to"></a>This actually exposed a larger issue with the Input functions, now fixed.
