### ISSUE TITLE
Tag doesn't stick to post if added to the bottom after posting

### ISSUE THREAD

**Issue by voss** [idno/Known#2043]
## While trying to do this:
I wanted to tag a post I had made a while back, so edited the post, and added it to the bottom of the textfield:

https://blog.voss.co/2017/sticky-links-december-30th-edition

## I encountered this error:
Now, when I click on the highlighted tag in the post, I'm taken to this page:

https://blog.voss.co/tag/stickylinks

Which gives me the message: "We couldn't find anything that matches your search."
![screenshot](https://user-images.githubusercontent.com/10601/36970813-b79b1658-2061-11e8-98ee-638ee5d39cad.png)

If I however insert it into the top of the post, the tag works, and https://blog.voss.co/tag/stickylinks takes me to the tag overview page, which includes the post I've tagged.

## Some other notes:
I've left the post now with the tag added at the bottom so that it can be reproduced. If you want me to, I can change it to be on the top, where it works as expected.

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*
Content of version.known:

```
version = "0.9.9"
build = 2017051501
```

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2043" class="u-in-reply-to"></a>I've not been able to replicate this on the latest master. Could you try confirming against the latest build?

**Comment by voss** [comment]
I'll give it a try later this week to check if it's reproducible in latest build.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2043" class="u-in-reply-to"></a>Any luck on the later builds?

**Comment by voss** [comment]
Sorry Marcus, haven't had time to try this. When I do, I'll update this.
