### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by phillycodehound** [idno/Known#2051]
## Some other notes:

*Give us some context, it'd also be really handy if you could tell us the contents of your ```version.known``` file*

**Comment by phillycodehound** [comment]
I'm unable to change any settings. Is it a permissions issue on a file?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2051" class="u-in-reply-to"></a>What version of Known are you running, latest master?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2051" class="u-in-reply-to"></a>Also, do you mean user account settings or system wide admin settings?

**Comment by phillycodehound** [comment]
Running the latest version.  Both user and System-wide

**Comment by phillycodehound** [comment]
Known Diagnostics: Version 0.9.9 (2017051501) 
Date: Mon, 19 Mar 2018 18:31:48 +0000

*** WARNING: This report contains sensitive information. Be careful about how you transmit it, and to whom. ***

Basics:
-------

security : Warning - Your site doesn't seem to be loaded with HTTPS. We strongly recommend using HTTPS to make your site secure and protect your privacy.

php-version : Ok
php-extensions : Ok
upload-path : Ok

Running config:
---------------
Idno\Core\Config::__set_state(array(
   'config' => 
  array (
    'database' => 'MySQL',
    'dbstring' => 'mongodb://localhost:27017',
    'dbname' => 'knowntobeknown',
    'sessionname' => 'known',
    'boolean_search' => true,
    'open_registration' => false,
    'initial_plugins' => 
    array (
      0 => 'Status',
      1 => 'Text',
      2 => 'Photo',
      3 => 'Firefox',
      4 => 'FooterJS',
      5 => 'IndiePub',
      6 => 'Styles',
    ),
    'plugins' => 
    array (
      0 => 'Status',
      1 => 'Text',
      2 => 'Photo',
      3 => 'Firefox',
      4 => 'FooterJS',
      5 => 'IndiePub',
      6 => 'Styles',
      7 => 'Media',
      8 => 'Like',
      9 => 'Comic',
      11 => 'Webhooks',
      12 => 'Bridgy',
      13 => 'Checkin',
      14 => 'Comments',
    ),
    'assets' => 
    array (
      'mediaelementplayer' => true,
      'fitvids' => true,
    ),
    'themes' => 
    array (
    ),
    'antiplugins' => 
    array (
    ),
    'alwaysplugins' => 
    array (
    ),
    'prerequisiteplugins' => 
    array (
    ),
    'directloadplugins' => 
    array (
    ),
    'hiddenthemes' => 
    array (
    ),
    'hiddenplugins' => 
    array (
    ),
    'items_per_page' => 10,
    'experimental' => false,
    'multitenant' => false,
    'default_config' => false,
    'loglevel' => 5,
    'multi_syndication' => true,
    'wayback_machine' => false,
    'static_url' => false,
    'user_avatar_favicons' => true,
    'form_token_expiry' => 21600,
    'show_privacy' => true,
    'bypass_fulltext_search' => false,
    'permalink_structure' => '/:year/:slug',
    'single_user' => true,
    'pedantic_mode' => false,
    'path' => '/home/gmedia/public_html/encryptr.net',
    'url' => 'http://encryptr.net/',
    'title' => 'Encryptr',
    'description' => 'A social website powered by Known',
    'timezone' => 'UTC',
    'host' => 'encryptr.net',
    'feed' => 'http://encryptr.net/content/all/?_t=rss',
    'indieweb_citation' => false,
    'indieweb_reference' => false,
    'known_hub' => false,
    'known_hubs' => 
    array (
    ),
    'hub' => 'https://withknown.superfeedr.com/',
    'session_path' => '/tmp',
    'session_hash_function' => 'sha256',
    'sessions_database' => true,
    'disable_cleartext_warning' => false,
    'cookie_jar' => '/tmp/',
    'dbpass' => '** REDACTED **',
    'dbuser' => 'knowntobeknown',
    'dbhost' => 'localhost',
    'filesystem' => 'local',
    'uploadpath' => '/home/gmedia/public_html/encryptr.net/Uploads/',
    'default_plugins' => 
    array (
      0 => 'Status',
      1 => 'Text',
      2 => 'Photo',
      3 => 'Firefox',
      4 => 'FooterJS',
      5 => 'IndiePub',
      6 => 'Styles',
      7 => 'Status',
      8 => 'Text',
      9 => 'Photo',
      10 => 'Firefox',
      11 => 'FooterJS',
      12 => 'IndiePub',
      13 => 'Styles',
    ),
    'dbport' => NULL,
    'site_secret' => '** REDACTED **',
    '_id' => '8ddda3a13263ad35f6a2497dd6450a7d',
    'uuid' => 'http://encryptr.net/view/8ddda3a13263ad35f6a2497dd6450a7d',
    'owner' => '',
    'update_version' => '2017051501',
    'from_email' => 'smg@encryptr.net',
    'dboptimized' => 1521405060,
    'theme' => 'Black',
    'default_feed_content' => 
    array (
      0 => 'statusupdates',
      1 => 'replies',
      2 => 'posts',
      3 => 'photos',
      4 => 'audio',
      5 => 'bookmarkedpages',
      6 => 'comics',
      7 => 'events',
      8 => 'rsvp',
    ),
    'sessions_storage' => NULL,
  ),
   'ini_config' => 
  array (
    'database' => 'MySQL',
    'dbname' => 'knowntobeknown',
    'dbpass' => '** REDACTED **',
    'dbuser' => 'knowntobeknown',
    'dbhost' => 'localhost',
    'filesystem' => 'local',
    'uploadpath' => '/home/gmedia/public_html/encryptr.net/Uploads/',
  ),
))

$_SESSION:
----------
array (
  'secure' => false,
  'messages' => 
  array (
  ),
  'last_message_flush' => 'Mon, 19 Mar 2018 18:31:47 +0000',
  'user_uuid' => 'http://encryptr.net/view/bb770c4c533c9c65f91dcf0325f7fc20',
)

$_SERVER:
---------
array (
  'PATH' => '/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin',
  'PWD' => '/usr/local/cpanel/cgi-sys',
  'SHLVL' => '0',
  'PHP_FCGI_MAX_REQUESTS' => '5000',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/admin/diagnostics/',
  'QUERY_STRING' => '/admin/diagnostics/',
  'REQUEST_METHOD' => 'GET',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'REDIRECT_QUERY_STRING' => '/admin/diagnostics/',
  'REDIRECT_URL' => '/admin/diagnostics/',
  'REMOTE_PORT' => '50129',
  'SCRIPT_FILENAME' => '/home/gmedia/public_html/encryptr.net/index.php',
  'SERVER_ADMIN' => 'webmaster@encryptr.goldstein.media',
  'CONTEXT_DOCUMENT_ROOT' => '/home/gmedia/public_html/encryptr.net',
  'CONTEXT_PREFIX' => '',
  'REQUEST_SCHEME' => 'http',
  'DOCUMENT_ROOT' => '/home/gmedia/public_html/encryptr.net',
  'REMOTE_ADDR' => '73.30.126.139',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '107.180.99.158',
  'SERVER_NAME' => 'encryptr.net',
  'SERVER_SOFTWARE' => 'Apache',
  'SERVER_SIGNATURE' => '',
  'LD_LIBRARY_PATH' => '/usr/local/apache/lib',
  'HTTP_COOKIE' => 'known=a681f045003451a87f89ff579b504725',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_REFERER' => 'http://encryptr.net/admin/diagnostics/',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36',
  'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest',
  'HTTP_ACCEPT' => 'text/html, */*; q=0.01',
  'HTTP_CONNECTION' => 'close',
  'HTTP_HOST' => 'encryptr.net',
  'BASE' => '/',
  'UNIQUE_ID' => 'WrACFFXkoXdXDSv6c@q6hgAAABY',
  'REDIRECT_STATUS' => '200',
  'REDIRECT_BASE' => '/',
  'REDIRECT_UNIQUE_ID' => 'WrACFFXkoXdXDSv6c@q6hgAAABY',
  'FCGI_ROLE' => 'RESPONDER',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1521484308.6124780178070068359375,
  'REQUEST_TIME' => 1521484308,
)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2051#issuecomment-374318113" class="u-in-reply-to"></a>I can't think off the top of my head a reason why that'd be the case. I've not been able to replicate, so it's not something systemic.

You self hosted or hosted? Any warnings or errors on your diagnostics panel? Are you doing something like editing on HTTP but posting to HTTPS or the other way round? (in which case the POST could be being rejected)

All else fails you could capture your save exchange in your browser's dev tools and email me the exchange (marcus at dushka.co.uk)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2051#issuecomment-374343373" class="u-in-reply-to"></a>I saw a notification with your diagnostics (I presume you deleted it from the ticket!)

The build version is that of the release package, but much has happened since. I suggest you try again from the latest github build.

**Comment by phillycodehound** [comment]
Oh ok

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2051" class="u-in-reply-to"></a>Any luck on the latest build?
