### ISSUE TITLE
Support /:slug as permalink structure?

### ISSUE THREAD

**Issue by skpy** [idno/Known#2066]
I have a bunch of legacy content using `/slug` as the permalink for each item.  Known does not currently support this permalink format, so if I were to import all my content I'd either break all my current public links, or try to set up server-side redirects.

I'd be happy with a plugin that simply enabled `/slug` as a permalink option, if it's not something suitable for the core code.

**Comment by mapkyca** [comment]
I think the issue with having something like this in core is that the routing of /slug/ will likely interfere with a whole bunch of other page routes. So, you'd have to do some very fancy routing, with maybe a two pass / alternative fallback route for things not already claimed, and I'm not sure that's something Toro can do.

So, I'd say for your case that a plugin would be a solution, but be prepared for it to break surprising things :D
