### ISSUE TITLE
Repeated warnings about session.configuration 'session.hash_function'

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#2089]
## While trying to do this:

Find out why a photo from OwnYourGram was not displaying at https://stream.jeremycherfas.net/2018/baked-out-just-fine, I looked in the error log.

## I encountered this error:

There are many, many instances of an error of the form:

````
warning - PHP [2] ini_set(): session.configuration 'session.hash_function' must be existing hash function. sha256 does not exist. in /home/jeremygrav/stream.jeremycherfas.net/Idno/Core/Session.php:37
````

## Some other notes:

This is the only consistent warning I can see, and it comes from other referers too.

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

````
version = "0.9.9-a"
build = 2018052302
````

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

* Any warnings or errors in you admin/diagnostics page?

None.

* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2089" class="u-in-reply-to"></a>Make sure sha256 is installed and enabled on your version of PHP, or specify another algorithm by setting ```session_hash_function``` in your config.ini

**Comment by jeremycherfas** [comment]
That's the point; sorry not to have been explicit. I believe it is installed and enabled:

````

hash support | enabled
-- | --
Hashing Engines | md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b fnv132 fnv1a32 fnv164 fnv1a64 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5

````

This is on PHP Version 7.0.30

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2089#issuecomment-392039100" class="u-in-reply-to"></a>Hard to say without knowing some more specifics. I know that a couple of people in hosted environments have had certain algos turned off by their provider - never got to the bottom of it, their workaround was to specify a different function in their config - which was why I put the option in there in the first place..

**Comment by jeremycherfas** [comment]
I can try that, I suppose. Just `session.hash_function = 'sha256'`? I mean, if it is installed and enabled, maybe being spefici will force it to be used.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2089#issuecomment-392104840" class="u-in-reply-to"></a>I doubt that'll work, but if you set ```session_hash_function = 'md5'``` in ```config.ini```
