### ISSUE TITLE
Add structured data support

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#2090]
https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by benwerd** [comment]
Known has microformats all over the place, of course, and should really have a set of microformats tests (I'll work on that).

I strongly support also adding JSON+LD schema.org data.

**Comment by akuckartz** [comment]
:+1: for JSON-LD

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2090" class="u-in-reply-to"></a>I've actually had a request for this, so I'll look at putting something together when I can.
