### ISSUE TITLE
MIME type not attached to photos from Micropub

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#2097]
## While trying to do this:

Upload images from Quill and OwnYourGram.

## I encountered this error:

The file at the temporary location has the correct `Content-Type: image/jpeg` as revealed by `curl -I link-to-tempfile'

The file after permanent storage has `Content-Type: application/data`.

## Some other notes:

Give us some context: 

```
version = "0.9.9-a"
build = 2018060901
```

* What database are you using? (e.g. mongo, mysql, postgres) mysql
* Any warnings or errors in you admin/diagnostics page? No
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2097" class="u-in-reply-to"></a>Did 89409b855fed4eb8592b984234db3c24d80a83f6 do anything to help this?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2097#issuecomment-397629154" class="u-in-reply-to"></a>Awesome, glad to hear!
