### ISSUE TITLE
Managing js and sass files

### ISSUE THREAD

**Issue by physcocode** [idno/known#2127]
@mapkyca has been working on this lately here is my take on it, I personally prefer https://github.com/JeffreyWay/laravel-mix to manage my vue.js and saas compilation it covers most of the heavy configuration task , we can simply use the npm run  command to build and minify all dependency , thanks to laravel mix made over webpack for easing the nightmare of asset compilation

**Comment by physcocode** [comment]
On a side note I would love to see known themes made on SAAS overriding the desired variables rather than overriding the whole ugly css files @mapkyca @benwerd @erinjo

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2127" class="u-in-reply-to"></a>Certainly going to be using Grunt more and more to manage css, js and other assets - definitely seems like the way to go. Also should make certain things in the future easier - e.g. vue/react fronts, etc.

I would certainly like to move the CSS over to SASS or similar, and yes, it would make sense to have themes take advantage. But that's a little ways off right now!

**Comment by mapkyca** [comment]
Closing for now. Would be interested in web pack etc builds, but got no time right now.

PRs welcome of course.
