### ISSUE TITLE
[Micropub] Photo posts not containing proper photo link anymore, but inlined HTML image instead

### ISSUE THREAD

**Issue by skddc** [idno/known#2138]
## While trying to do this:

Post a photo via Micropub. I post my Instagram photos to https://updates.kip.pe/ from IFTT, with a form payload like this:

```
h=entry&content={{Caption}}&photo={{SourceUrl}}&syndication={{Url}}&access_token=b71dfd944abbc8955fe84fc2e0229889
```

## I encountered this error:

Before recently (I couldn't pinpoint the change that broke it), my posts would be stored as normal photo posts. I could edit them, change the picture, sync them to other sites, etc.. But after some update, they are now inlined as HTML content. And now, editing doesn't work anymore, i.e. I cannot change the photo, even if I remove the inlined one, save, and then try again. Also, my integration to sync it to Mastodon broke, because it can't deal with the inline photo. Here's how it looks in my edit UI now:

![screenshot from 2018-08-24 12-59-50](https://user-images.githubusercontent.com/842/44908495-40bd4400-ad4e-11e8-8a75-220791af1e76.png)

## Some other notes:

```
version = "0.9.9-a"
build = 2018082301
```
* Using MySQL
* Diagnostics page says _"You are running PHP version 5.5.9-1ubuntu4.25, which cannot run Known."_ but everything else has been working fine. However, the editing bug might have to with a missing PHP feature? Not sure what that could be.
* The editing issues could also be related to #2008

**Comment by benwerd** [comment]
I'm trying to take a look also. I think it's a bigger issue than just micropub, at first glance - it looks like images never link to their full source anymore.

**Comment by mapkyca** [comment]
In micropub I noticed there's a fetch by url and a post image $_FILE which are two possible routes. IIRC the former does a fetch and save (iirc), but it might be that we simplified this by using a proxied image... I'll take a look

**Comment by skddc** [comment]
Anyone had a chance to look into this yet?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2138" class="u-in-reply-to"></a>Just had a couple of minutes to look at it, PR waiting.

**Comment by skddc** [comment]
Hooray, it works!
