### ISSUE TITLE
Cookie Expiry

### ISSUE THREAD

**Issue by markwaters** [idno/Known#2139]
Occasionally when I am posting the site cookie expires and I am asked to login again , losing the latest update in the post.

Could the cookie expiry time default to be at 0400 , this way it would always expire overnight and I would login the next morning knowing it wasn't going to expire while I was posting.

Thanks.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2139" class="u-in-reply-to"></a>This isn't so much a Known thing as it is a PHP session cookie thing - you need to tweak your PHP settings. Also, if you're running on a debian based system you need to set an alternative cookie location as they do their own housekeeping

**Comment by markwaters** [comment]
OK , Thanks @mapkyca
