### ISSUE TITLE
Outdated symfony components/ Composer plan of action 

### ISSUE THREAD

**Issue by physcocode** [idno/Known#2145]
## While trying to do this:
Trying to load classes , files and external dependencies via composer 

## I encountered this error:
Known uses 2.x components , while symfony has reached the 4.x milestone, secondly class loader component has been completely deprecated by symfony as of 4.x

## Steps to move to composer:
Here is my plan of action for moving towards composer 
1) load dependencies via packagist
2) load packages which are not available on packagist via github (using composer)
3) depedencies which has been modified and does not lie in above 2 categories , make a fork of it and link it with packagist using composer standards 
4) Upgrade Symfony component and completely remove the depricated class loader component 

## Why 
1) It's easier to update and keep track of version of external depedencies 
2) Composer optimized autoloading files and caches speeds up the class loading process 
3) because it's 2018 !

## Some other note 
Possibly we can manage js/css by npm , although most of our depedencies like bootstrap does support composer 

I really want to see this new eco system before our beloved 1.0 release (WIP on my local machine )

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2145" class="u-in-reply-to"></a>In principle yes, previous reservations not withstanding.

One additional note is that the change from simfony 2 - 4 is a breaking change. I tried an upgrade a little while ago and while I could put in class loader shims etc which got things working on desktop, but I couldn't get it to pass travis tests before I ran out of time.

**Comment by physcocode** [comment]
We don't need class loader , even if we do not use packagist we can still use composer as our class loader at least , it's really much faster and optimized

**Comment by physcocode** [comment]
Interesting, what kind of installer are we talking about here ? @benwerd @timmmmyboy

**Comment by timmmmyboy** [comment]
Composer just handles the initial build of dependencies right? In other words would it be possible for me to locally use composer to build all dependencies and then package that up? If so it would be a bit more reliable, otherwise I have to make sure Composer is installed globally and available to all shell accounts on all servers (I've done similar with Drush but it's a weak point given we inevitably miss servers here and there or it doesn't get added to config for new servers).

@physcocode We have an [Installatron](http://installatron.com/) installer we built for Known that's available on our server environment (I run [Reclaim Hosting](https://reclaimhosting.com)).

**Comment by benwerd** [comment]
@timmmmyboy Thank you so much for clarifying!

While you _can_ use Composer locally, effectively you'd need to download / install it, run it, and then clean it up every time for security's sake, which doesn't sound like a great deal of fun. So I'm inclined to think we can't make it a standard requirement.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2145" class="u-in-reply-to"></a>My preference is for bundled libraries over requiring a package manager. That said composer might be useful for development and periodic library updates.

**Comment by benwerd** [comment]
Yeah. I think bundled libraries are still the way to go here, based on Tim's feedback. I agree with you, too.

Generally I think it's important to go the way of modern development - eg if this was a node project, npm would be a must. But PHP hasn't quite followed the same path. In a lot of ways this is a really antiquated way of doing things, but compatibility is really important.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2145#issuecomment-420721936" class="u-in-reply-to"></a>Aye, it's legacy stuff, but hey, node is new... and npm has its own problems. I've still got a bit of a devops head, so my comment about "apt-get rootkit" with composer and npm still applies (and proven right, as it happens).

Funny you should mention npm though, I've moved lang generation and java minify over to grunt, and just pushed a PR to do the same with core plugins

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2145#issuecomment-420721936" class="u-in-reply-to"></a>... with that in mind, I'm wondering whether we should piggyback on package.json in favour of plugin.ini to avoid duplication of names and version numbers etc...

**Comment by physcocode** [comment]
@timmmmyboy @benwerd @mapkya correct me if I am wrong , but according to my knowledge you CAN build everything once and package it up , just like known currently have "external" directory it would be replaced by "vendor" directory and know's symfony class loader would be replaced by composer. And once the vendor directory is present there is NO NEED of composer at all , so I dont think of any reason we can make a package by running composer once locally and secondly we can actually make Known release with "vendor" directory generated by composer so that it's NOT mandatory for the end user to use composer ever in there life

**Comment by physcocode** [comment]
Closing in favor of "not right now" maybe I can make a fork and demonstrate the new pattern
