### ISSUE TITLE
Add linting to test process

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2147]
Let's add a linter to the build process, such that we can test for formatting issues both on the command line and at the point of submitting a PR. All part of bringing the code to a common standard.

This would check for:

* Actual syntax errors
* Code style adherence

I'll look around, but a combination of PHP's built-in linter and a style checker would be optimal.

It's a very common practice in ES6-land, but here's a good guide to doing this in PHP: https://webdevstudios.com/2017/04/06/lint-code-like-boss/

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2147" class="u-in-reply-to"></a>This might be a good start... https://www.npmjs.com/package/grunt-phplint

**Comment by benwerd** [comment]
Yeah - although the php linter only handles syntax, not style, so this would also help: https://www.npmjs.com/package/grunt-phpcs

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2147" class="u-in-reply-to"></a>Cool, I might have a play when I get the chance, unless you want to take this one.

Not sure how configurable it'd be... I guess it'll handle spacing etc, but not everything in our coding styles.

**Comment by physcocode** [comment]
Are we talking something like phpcs fixer over here ?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2147" class="u-in-reply-to"></a>Hmm... actually, it looks like PHPCS has ability to apply code styling. Not sure how easy it is, but e.g. wordpress has its own style rules.

**Comment by benwerd** [comment]
To clarify, I don't think we should _apply_ code styling - automatic fixing would be really bad - but we should probably configure something to be heavy-handed about checking for it.

**Comment by benwerd** [comment]
Rightrightright. Makes sense.

**Comment by mapkyca** [comment]
And by that I mean rules to linting, not actually any code changes...

**Comment by benwerd** [comment]
Committed #2186 as a first step.

**Comment by mapkyca** [comment]
To keep things clear, I'm closing this issue as we've _implemented_ linting.

Other issues should be specific tickets....
