### ISSUE TITLE
Document PHP testing on command line

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2148]
I'm having some trouble running the current state of the tests on my command line. A guide in the docs to running these tests using common scripts would be a good thing.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2148" class="u-in-reply-to"></a>What issues are you running into? Should just be a matter of running phpunit ... once you've set the appropriate environment variable ... or is that what you mean? ;)

**Comment by benwerd** [comment]
Actually my issue turns out to be an internal npm / brew problem. But it's helpful to understand explicitly how to run the tests, even if theoretically everyone should read the phpunit manfile etc etc.

**Comment by benwerd** [comment]
Although now I've recompiled my entire stack (sadface), it's not immediately clear that you should just run `phpunit Tests` from the installation directory, vs `cd Tests; phpunit`, etc.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2148" class="u-in-reply-to"></a>Aye, run PHPUnit from the root, and set domain if you're running off anything other than localhost.

I'm off training this evening with a cold, so I'll put something together... might as well do something useful!
