### ISSUE TITLE
Photo gallery support

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#215]
Multiple photos in a post, with posse. Bonus points create sets 

Related #214 
##

**Comment by haschek** [comment]
+1

Important to switch easily to Known, eg. from Tumblr.

With multiple photos each photo needs an own caption. Post title and body is now the description of the gallery.

**Comment by mapkyca** [comment]
Closing, reckon this is a separate plugin. Either way, nobody has got to it for 3 years, soooo.....
