### ISSUE TITLE
Make it easier for non-engineers to translate Known

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2153]
To do the actual translation, you shouldn't need to write any PHP code. Ideally, you should be able to install a translation file and avoid writing PHP, too, although I'd say this is lower-priority.

I seem to remember using an Ubuntu-related tool to achieve this with GetText files in Elgg. I can't remember what it was called, but using it brought us to 80+ languages. It would be nice to be in a similar situation with Known.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2153" class="u-in-reply-to"></a>You mean LaunchPad?

Not ever figured out how to use that, but there's an ecosystem around handling .POT files, and editors for every platform. No PHP required.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2153" class="u-in-reply-to"></a>Also, zipped language packs should be fairly simple to distribute regardless, without PHP

**Comment by benwerd** [comment]
Totally. I think it's more about making sure the rails are explicit. I'll try and have a go at revising the translation documentation into a set for developers and a set for translators later. The components are  there, which is awesome. Just a question of lowering the barrier to entry.

**Comment by mapkyca** [comment]
Going to close this, because in general it's there. If there are _specific_ enhancements, open tickets/PRs for those...
