### ISSUE TITLE
Pull & post first image in a link

### ISSUE THREAD

**Issue by batgranny** [idno/Known#2154]
Just installed Known and I'm loving it so far!

This is really a feature request more than an issue but I think it would be cool to add.  When adding a link as a bookmark or status update it would be great if it would also post an image from the page.  Currently All you get is a URL or (in bookmarks) what looks to be a headline with no image.

**Comment by mapkyca** [comment]
What version are you on? Recent versions should do link expansion on posted link...

**Comment by batgranny** [comment]
I'm on the latest version and I'm hosting it myself.  Here's a screenshot from a test status update:
<img width="814" alt="screen shot 2018-09-14 at 23 37 10" src="https://user-images.githubusercontent.com/15010980/45578072-3f743700-b877-11e8-8c26-5666e83c08fd.png">

**Comment by mapkyca** [comment]
This is what I get on localhost for the same link. Can you confirm the contents of your ```version.known``` file?


![untitled](https://user-images.githubusercontent.com/124070/45584798-dcfc5480-b8d1-11e8-93bd-b5c513091849.png)

**Comment by batgranny** [comment]
version = "0.9.9"
build = 2017051501

The server is Ubuntu and the PHP version is PHP7 if that helps

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2154#issuecomment-421551687" class="u-in-reply-to"></a>Hmm, this is a pretty old version which I don't think had the link expansion code. 

I suggest you use the latest from GitHub, or if you want a package, you can grab some _unofficial_ packages here: https://www.marcus-povey.co.uk/known/

**Comment by batgranny** [comment]
That sorted the issue, thanks!  I downloaded Known from the version on the homepage so you might want to update the link.  

Thanks again for your help!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2154" class="u-in-reply-to"></a>That's out of my control, unfortunately, but it's a known issue that will hopefully be resolved soon.

**Comment by benwerd** [comment]
We’ll make a new release by EOM.
