### ISSUE TITLE
Travis is failing tests

### ISSUE THREAD

**Issue by benwerd** [idno/known#2168]
It looks like this is because tests are running on infrastructure that's being made obsolete? But can't say for certain yet. I'd like to work on fixing this, so we can be sure PRs are doing what they ought to.

**Comment by mapkyca** [comment]
It happens from time to time when they tweak things, plus sometimes it fails because the boot times out. 

You need to look at the logs to be sure rather than relying on the check mark

**Comment by mapkyca** [comment]
Will take a look...

**Comment by mapkyca** [comment]
Yeah, on latest builds it looks like it's an individual VM not spooling up properly rather than a build error.

**Comment by benwerd** [comment]
It seems to always be relating to PHP 7.1. Given this, I'm inclined to move those builds into the "allowed failures" section for now.

**Comment by benwerd** [comment]
(On the grounds that it's pretty important to be able to tell if a build is _actually_ failing.)

**Comment by mapkyca** [comment]
I disagree... these seem like build errors I've seen before where a specific branch fails to spool up. This is something that unfortunately happens with travis from time to time - you always need to look at the build log rather than rely on the checkmark

**Comment by mapkyca** [comment]
E.g. current build is passing

**Comment by mapkyca** [comment]
Well, not quite, but the builds are greyed out - which admittedly I've not seen before, but points at a travis issue

**Comment by mapkyca** [comment]
(disagree on the 7.1 thing, not the knowing things are failing)

**Comment by mapkyca** [comment]
As I said previously, I'm pretty sure we can close this - the observed errors are pretty certainly temporary travis platform errors...

**Comment by mapkyca** [comment]
Hmmm, I'll leave this to you, but it's intermittent (so not code), and when I've seen it (recent mongo errors not withstanding) it has been due to a timeout booting the VM. Re-running the test (e.g. by pushing a non-code commit) works

**Comment by benwerd** [comment]
Yeah, It may be enough to just increase the number of retries. That's one approach I'm looking at.

**Comment by mapkyca** [comment]
There's also the other vm architecture they talk about, but when I looked that looked like a lot of work to convert and wouldn't be guaranteed to solve the problem (and would likely introduce a bunch of new ones)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2168" class="u-in-reply-to"></a>Seems to be solved.
