### ISSUE TITLE
Known documentation docs.withknown.com no longer updating

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#2176]
## While trying to do this:

Update the Known docs on readthedocs

## I encountered this error:

Documentation is no longer updating when github repo is updated

**Comment by benwerd** [comment]
Readthedocs is reporting that documentation _is_  updating. Can you confirm that an update you made is not showing up?

**Comment by mapkyca** [comment]
Hmm.... it is now, must have taken a while.

Although, since removing the pages from the .yml, the side navigation is horrible.
