### ISSUE TITLE
Updating bootstrap to version 4

### ISSUE THREAD

**Issue by physcocode** [idno/known#2199]
I was recently playing around building wild know themes and I wondered why we havnt updates to bootstrap 4 yet.

PS : if this is on the cards before 1.0 release I would be glad to make a PR

**Comment by benwerd** [comment]
An upgrade is probably a good idea. Ideally I'd like to remove Bootstrap entirely and use CSS grids, now they're widely supported.

**Comment by physcocode** [comment]
Also on a personal note I would like to replace Bonita with twig or blade , keeping the front end free from PHP codes really makes the code pritty and as @mapkyca said , it will help us in keeping front and and backend really independent and clean

**Comment by physcocode** [comment]
Please spread some light on my proposal so I can start working for a PR ASAP

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2199" class="u-in-reply-to"></a>I'm on the fence wrt changing the templating engine. Bonita does have it's problems, but changing it would involve rewriting the world. So, ideally, if it's possible for them to co-exist and then be deprecated, that would be the way I'd like it done.

Another approach, which may be better, is to actually build the front end almost as a separate project (but often bundled), talking to the API / JSON endpoints.

**Comment by physcocode** [comment]
Should I work on bootstrap 4 update for now ?

**Comment by benwerd** [comment]
Bootstrap 4 makes sense for now. The other stuff (like creating a better interface separation) definitely sounds like something after 1.0.

**Comment by physcocode** [comment]
Can we have a separate branch for bootstrap 4 were I can make pull request ? Would be much nice rather than me giving a huge pull request in main branch

**Comment by benwerd** [comment]
I now see there's a serious known vulnerability with the version of Bootstrap we're on, so moving to 4 before any further release is a hard requirement. @physcocode, are you working on this? If not, I'll take this on as a matter of haste.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2199" class="u-in-reply-to"></a>What's the vuln?

Also worth looking at the admin template while doing this.

**Comment by physcocode** [comment]
@benwerd definitely up for this, whats the vuln?

**Comment by jgmac1106** [comment]
@benwerd @physcocode I am happy to help on the move from Bootstrap to CSS Grid.

**Comment by jgmac1106** [comment]
Taking a look there are plenty of Bootstrap 4->to CSS Grid style sheets these basically define a 12 grid row and use the same classes.

.or we could rethink how we name classes. Fine with either approach but wanted to see what folks think.

**Comment by physcocode** [comment]
I was just thinking about rewriting using the new standards , also I was playing around trying to implement UI kit (just out of curiosity)

**Comment by mapkyca** [comment]
Closing in favour of #2617
