### ISSUE TITLE
Add Known to packagist.org

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2208]
We have a composer.json, which I think is all that is required. 

I could do this, but it should be done via the official Known account.

**Comment by physcocode** [comment]
I don't think this is everything that is required , pakagist install the package as a external component and unlike Elgg , know is still not capable of being a external package and being loaded into the project manually , correct me if I am wrong

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2208#issuecomment-425683421" class="u-in-reply-to"></a>Default "type" is "library", which expects the behaviour as you describe, but my understanding is that isn't the case if you set "type" to "project"...

**Comment by physcocode** [comment]
Oops my bad , also can we install known-plugin as type : composer-plugin so that we can use composer to manage plugins depedencies too ? 🤔

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2208#issuecomment-425708920" class="u-in-reply-to"></a>You mean individual Known plugins? That would be up to the individual plugin author, but I'd probably encourage it.

**Comment by benwerd** [comment]
"The package name idno/Known is invalid, it should not contain uppercase characters. We suggest using idno/known instead."

**Comment by benwerd** [comment]
Commencing breaking everything by switching the name ...

**Comment by benwerd** [comment]
Packagist is crawling Known now. I'll close this issue once we've confirmed it's there and can be pulled.

**Comment by benwerd** [comment]
Scratch that: a release needs to be made with the composer.json in it. So Known can't be added until a new release.

**Comment by benwerd** [comment]
You at least have to tag it, so people can pin to a specific version in their composer files. We'll get to that point pretty quickly. I'd really like to get 1.0 out before Thanksgiving (Nov 22).

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2208#issuecomment-433205430" class="u-in-reply-to"></a>Promises promises ;)

**Comment by physcocode** [comment]
i wanna join the know code-a-thon

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2208" class="u-in-reply-to"></a>I love the sound of deadlines as they fly by ;)

From now on, lets not promise anything in terms of when 1.0 will eventually land, eh?

**Comment by mapkyca** [comment]
Something to consider when doing this - might be worth looking at how the Elgg project manages its code. There, Elgg is itself installed via composer to /vendor. This seems a bit confusing, but I'm pretty sure this was done so that upgrades could be managed cleanly via composer. Also nicely segregates the core away from any custom mods built for a client.

**Comment by mapkyca** [comment]
Just so you know, I've added projects to packagist that don't have releases. They just appear as master or dev-master, which tracks github head.

**Comment by mapkyca** [comment]
Closing, as it is available.

You can fetch ```composer create-project idno/known -s dev``` to get the master
