### ISSUE TITLE
Enable IndiePub plugin by default (IndieAuth + Micropub)

### ISSUE THREAD

**Issue by aaronpk** [idno/known#2209]
## While trying to do this:

Set up a new Known site and use a Micropub app

## I encountered this error:

App did not find a way to authenticate me

## Some other notes:

Enabling the IndiePub plugin then works.

**Comment by jaduncan** [comment]
I would also recommend this.

**Comment by cleverdevil** [comment]
Totally agree, I'd like to see Micropub and IndieAuth be enabled by default, and promoted as the "native" way to publish content and interactions via third-party apps like Quill, Together, Indigenous, and Omnibear.

**Comment by jgmac1106** [comment]
Yes I tried to set my kids up with indigenous so they could post and check out each other' blog.

+1 as well for 1.0

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2209" class="u-in-reply-to"></a>See discussion on #2249. Indiepub plugin is enabled by default, but it's likely an interaction with older versions or saved configs.
