### ISSUE TITLE
Post Stub missing

### ISSUE THREAD

**Issue by markwaters** [idno/Known#2228]
## While trying to do this:
Creating a location checkin.

## I encountered this error:
No error , but the location checkin URLs are now https://domain.tld/2018/-1 and https://domain.tld/2018/-2 instead of the usual longer text-based.
After posting the posts do not have a Title showing.

## Some other notes:
I was using the latest git code at the time ( 20181003 ) , I've since rolled back.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2228" class="u-in-reply-to"></a>This is a known problem, fixed by #2224
