### ISSUE TITLE
Warmup goes to endless loop when hosting on dreamhost 

### ISSUE THREAD

**Issue by voss** [idno/known#2238]
## While trying to do this:

Installing Known.

## I encountered this error:

"Apache mod_rewrite
We couldn't detect if mod_rewrite was installed. Known cannot process page URLs without it. Proceed with caution."

## Some other notes:

Give us some context: 

Basically, when on a clean install on a shared host on Dreamhost, at the requirements screen of the warmup, you are told that Known wasn't able to detect the presence of mod_rewrite, and that things might get funny.

After clicking "Hooray! Let's get you set up.", and configuring the database details and then clicking on "Onwards!", I end up on /warmup/?stage=settings, with yellow highlight on top, saying 

> Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to default.js
> 
> You can usually fix this by setting AllowOverride All in your Apache configuration.

![screenshot 2018-10-20 at 15 47 54](https://user-images.githubusercontent.com/10601/47256987-0899ce00-d480-11e8-998b-cbce7955257e.png)
 
I can put in my details once again, and hit "Onwards!" and I end up on the same page, with the same yellow highlight in the top.

[According to Dreamhost](https://help.dreamhost.com/hc/en-us/articles/217141627-Supported-and-unsupported-technologies), mod_rewrite is enabled on all their hosts, and sure enough, if I build my config file manually, everything works fine, including all the rewrite rules in the .htaccess file.

This is happening on PHP version 7.0.32.

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

`version = 0.9.9-a`
`build = 2018101001`

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

* Any warnings or errors in your admin/diagnostics page?

It says:

"Your site doesn't seem to be loaded over HTTPS. We strongly recommend using HTTPS to make your site secure and protect your privacy."

* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2238" class="u-in-reply-to"></a>Have you tried modifying your AllowOverride settings as suggested?

**Comment by voss** [comment]
@mapkyca I forgot to specify that on the shared hosting environment on Dreamhost, it's not possible to edit your apache2.conf file, so that's not an option. In order for you to do so, you need to get a DreamCompute instance, or pay for a dedicated server.

I don't believe it's possible to change the AllowOverride directive anywhere else but in the apache2.conf file.

**Comment by cdn** [comment]
@voss https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride may help?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2238" class="u-in-reply-to"></a>I wonder whether rewrite is installed, but not necessarily enabled for your host. 

If you're certain it is and you're convinced warmup is giving you an erroneous error you could try forcing the issue using the CLI installer: http://docs.withknown.com/en/latest/install/cliinstaller/

**Comment by voss** [comment]
@cdn Hmm, No matter where I put the

AllowOverride All

directive int he .htaccess file, the site throws a 500 error.

I've tried putting it into the a Directory section, and also just putting it in the open, like I would normally do with

AllowOverride Indexes

for example.

Both result in HTTP 500 errors.

I suspect Dreamhost has done something to stop you from doing that.

Either way, it seems irrelevant since mod_rewrite seems to be working, as the vanilla .htaccess file works, including any new directives I've added to it, for example to always redirect http to https requests.

**Comment by cdn** [comment]
@voss DreamHost probably have that capability [locked down](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverridelist).

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/2238#issuecomment-431603399" class="u-in-reply-to"></a>iirc AllowOverride is verbotten in .htaccess, it has to be set in the central apache conf (for security reasons)

**Comment by benwerd** [comment]
Do you get error logs with your DreamHost account? Are you able to see what shows up there when you get those 500 errors?

**Comment by voss** [comment]
@benwerd when I place it as the first line in the .htaccess file, outside of any directives:

.htaccess: AllowOverride not allowed here

<Directory> type directives are not allowed in .htaccess files, so whenever I put that in there, it simply says:

htaccess: <Directory not allowed here.

So, as @mapkyca says, and as I mentioned earlier, you can not change AllowOverride in .htaccess. You can only set it in the apache2.conf file. On Dreamhost, you can not change your apache2.conf if you are on shared hosting (which I am).

So, to get back to the issue, either Dreamhost has a non-standard setup, where they are able to hide the fact that mod_rewrite is installed and enabled, or the test being done by Known in the warmup section, to test whether mod_rewrite is installed and enabled, is missing something.

I'll happily take a look at the CLI installer, thanks for that @mapkyca,

**Comment by cdn** [comment]
NginX also suffers from the Rewrite test looping warmup due to some recent change(s) in master

**Comment by benwerd** [comment]
OTOH, DreamHost itself has a page about mod_rewrite. So I wonder if it's the detection rather than the implementation? https://help.dreamhost.com/hc/en-us/articles/215747748-How-can-I-redirect-and-rewrite-my-URLs-with-an-htaccess-file-

**Comment by funwhilelost** [comment]
@benwerd you're correct.  Dreamhost defaults to a FastCGI implementation of PHP 7.0 at the moment.  I have mine running fine there.  Unfortunately that means that `apache_get_modules()` will not work correctly - nor is `$_SERVER['HTTP_MOD_REWRITE']` set (which I think is just more of a convention).

I've had no problems running Known on Dreamhost but I just did the config by hand.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2238" class="u-in-reply-to"></a>The installer shouldn't be checking for apache_get_modules on nginx, so I don't think that's the issue.

The error shown above is less likely to be a false alarm, since it is trying to access the canary rewrite. Might be worth seeing if you can access that directly.

**Comment by voss** [comment]
<a href="https://github.com/idno/known/issues/2238" class="u-in-reply-to"></a>@mapkyca if you need access to Dreamhost to test things out, I'll happily set up a user on my account for you, with ssh access. Just let me know.

**Comment by ejheil** [comment]
OK, I had a chance to check out what's happening.  In warmup/WebInstaller.php, on line 41, is:

        if (function_exists('apache_get_version')) {

I believe the function_exists call is returning false, so the rest of that if-clause isn't executed, and the function (with no explicit return) returns null.

Can't double check that is correct right now, I'll need to do so later today, but I think that's what's going on.

**Comment by cdn** [comment]
@ejheil and for Nginx it will never exist :o)

**Comment by mapkyca** [comment]
D'oh. Obviously.

Ok, I'll fix this shortly...

**Comment by voss** [comment]
> That'd be quite helpful, actually. You can email me on [marcus@marcus-povey.co.uk](mailto:marcus@marcus-povey.co.uk), my pgp key should be on the standard key servers or my website.

I've added you on Keybase. Are you ok with using that for exchanging the info?

**Comment by PascalHeynmoeller** [comment]
I've installed latest version of known: version = "0.9.9-a" build = 2019011501 on Debian stable
with the same error discribed above.
CLIinstall worked but the wrong .htaccess was distributed!
Then I've copyed manualy .httaccess-2.4.dist and renamed it. Also changed all left .htaccess files inside into "Require all denied".
The Apache known site-conf has "<Directory /var/www/known/*> AllowOverride All" inside.
It seems like the Apache version info wasn't adequate for the Installer and the CLInstaller.
Now it stucks at https://blog.mydomain.tld/begin/ with "The requested URL /begin/ was not found on this server."
Maybe an bestpractice example apache2.4 site-conf could be provided in the documentation for better understanding of the requierements.
Thank you all

**Comment by nekr0z** [comment]
Still the same issue on DreamHost.

**Comment by mapkyca** [comment]
It was fixed, and then broken, and then fixed. We changed a lot of the JS recently, so try a bleeding edge build

**Comment by TheDavidJohnson** [comment]
Just tried a fresh install on nginx with php7.2-fpm and I'm in the same loop. Same issue with `-s dev`, which if I'm not mistaken uses the 'bleeding edge" code?

**Comment by TheDavidJohnson** [comment]
Update: I was able to install via the CLI and everything is working correctly.
