### ISSUE TITLE
Improve API onboarding

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2240]
## While trying to do this:

Use an API based client

## I encountered this error:

I have to use the api key for the user - fine - however getting this is non-intuitive for regular folk, who will almost certainly expect standard username/password.

We should probably have a mechanism to exchange a username/password for a key... although this is in essence the same thing, so perhaps we should do away with the api key system altogether... see #831 (keys are basically passwords) 

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2240" class="u-in-reply-to"></a>The obvious way would be to somehow get a token from a username/password, which might be to use a form/token post on the login and retrieve a token. This proves difficult, owing to the session id portion in the token generation.

I'm thinking OAuth is probably the way to go

**Comment by physcocode** [comment]
Oauth 2.0 is the answer here , for all user who want to authenticate with username and password can do so using the password grant type . I would definitely suggest using https://github.com/thephpleague/oauth2-server inside known core for getting up and running 2.0 server in no time . 
If someone wants to authenticate with standard token they can always use the implicit grant type 💯

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2240" class="u-in-reply-to"></a>Hmm... OAuth is only part of the story.

The issue is that if a client wants to connect, it needs to know what client app to talk to. Fine for a central service, not so much for self hosted installs. 

The out of the box OAuth2 process needs some tweaks to the workflow to solve this issue...

**Comment by mapkyca** [comment]
So the use case I'm particularly interest in is for signing up a client on to someone's site. The OAuth2 route is fine for clients of a particular hosted service and matched client, where the admin has created an app, and has done the necessary reconfiguration in order to get the 'sign on with....' buttons working.

However, it's very poor UX for people who want to use a third party client with their personal site. 

So, my current thinking is that we have the session/login page itself generate/return the specific user's API access token as json on a successful login. This would mean that a client would log in with a familiar username and password combination, and then after a successful login the client would retrieve this api token and use it going forward.

Can anyone see a problem with this ?
