### ISSUE TITLE
Getting "Oops! We couldn't find it."  Error on Windows

### ISSUE THREAD

**Issue by GaneshKandu** [idno/known#2291]
## While trying to do this:
While Installing on Windows
## I encountered this error:
Getting "Oops! We couldn't find it."
```

Oops! We couldn't find it.

Whatever you were looking for, it's not here. It might have been moved, deleted, or it doesn't exist. Or the robots ate it. That's always a possibility too.

Maybe you'll find something interesting if you head back to the New Known site homepage.
```
## Some other notes:

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = "0.9.9"
build = 2017051501
* What database are you using? (e.g. mongo, mysql, postgres)
mysql

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2291" class="u-in-reply-to"></a>Anything in your php logs? What content are you trying to view?

Also, the version you're using is really old - I recommend rolling up to what's on github, or use one of the unofficial builds (https://www.marcus-povey.co.uk/known) if you're uncomfortable tracking git.

**Comment by mapkyca** [comment]
Closing as I'm unable to replicate.

Re-open with extra detail if still a problem
