### ISSUE TITLE
Linking to a large PDF causes Known to crash

### ISSUE THREAD

**Issue by benwerd** [idno/known#2292]
I linked to a 24MB PDF (the Parliamentary release of Facebook's emails). While [the post](https://werd.io/2018/the-facebook-emails) was published, I received a PHP "out of memory" error. I strongly suspect it's because Known is actively trying to load or webmention the PDF.

Known should not attempt to webmention large web files, and certainly not PDFs.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2292" class="u-in-reply-to"></a>Yeah, it'll either be the webmention ping (which I think pulls the full url), or the link unfurling (which I think may do the same, but I can't remember if I was more clever with it)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2292" class="u-in-reply-to"></a>Simple solution would be to limit the amount of data retrieved to a few tens of k, but I'm not sure that's currently possible at the moment
