### ISSUE TITLE
Reflected XSS when deleting a post

### ISSUE THREAD

**Issue by fozzedout** [idno/known#2296]
## While trying to do this:
create a post and use the following as the title:
`Tester <script>alert(123)</script>`

## I encountered this error:
The original scripting is kept, and allows for Reflected XSS when deleting a post - so when deleting the script is executed - this allows for a security breach

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = "0.9.9-a"
build = 2018120201

* What database are you using? (e.g. mongo, mysql, postgres)
mysql

**Comment by mapkyca** [comment]
Replicated, nice spot
