### ISSUE TITLE
Script tags causing issues

### ISSUE THREAD

**Issue by fozzedout** [idno/known#2297]
## While trying to do this:
adding in script tags in a post or in the title:
`<script>alert(1)</script><script>alert(1)</script>`

## I encountered this error:
when viewing the post causes extra info to be dumped to the page as well as allowing for scripting attacks

## Some other notes:
it appears that the JSON+LD executes the second script tag. I would have expected a more filtered title and description, rather than using the tags directly

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = "0.9.9-a"
build = 2018120201

* What database are you using? (e.g. mongo, mysql, postgres)
mysql
* Any warnings or errors in your admin/diagnostics page?
No

**Comment by mapkyca** [comment]
Nice spot, thanks

**Comment by fozzedout** [comment]
Also found that the Edit Profile does not scrub script tags, so javascript can be run when viewing someones profile. Not sure if that is intended behaviour or not though

**Comment by mapkyca** [comment]
No, that shouldn't happen. Can you give an example?

**Comment by fozzedout** [comment]
I just put a <script>alert(1)</script> at the start of the Edit Profile box. Save and alert box will appear

**Comment by fozzedout** [comment]
I've applied the xss fixes in the pending pull to test them, and one thing I noticed is that using the YouTube embedded code (the iframe) in a post will now no longer work - you can only share YouTube videos via a status update only.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2297" class="u-in-reply-to"></a>I think this might be a separate issue, and doesn't appear to be down to the new output filtering. Will investigate a bit further when I get a chance.

Meanwhile, putting a youtube link in your post should still expand out into a youtube video.
