### ISSUE TITLE
On iOS, profile pic chooser forces camera

### ISSUE THREAD

**Issue by ejheil** [idno/known#2311]
## While trying to do this:

Add a profile photo to a new Known site using Safari in iOS.

## I encountered this error:

I couldn't upload one, only take a new one with the camera.  This is because of the HTML5 media capture api:  https://mobilehtml5.org/ts/?id=23

The text for the button says "select a user picture" so this is counterintuitive -- taking a new picture isn't "selecting" one.

Suggestion: just use a regular upload, or else provide two buttons, one for "take picture" and one for "upload picture."

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = "0.9.9-a"
build = 2018122001

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

* Any warnings or errors in your admin/diagnostics page?

nope

* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2311" class="u-in-reply-to"></a>The capture API seems to have slightly different behaviour on every device, and we ran into this issue last year some time. Something must have changed, because it used to offer a choice between capture and camera roll.

**Comment by fozzedout** [comment]
This also happens on my Android device, so maybe it's a more generic change?
