### ISSUE TITLE
Help needed for upgrading Yunohost Package / Nginx

### ISSUE THREAD

**Issue by raphaeljolivet** [idno/known#2313]
Some months ago, I [packaged Known](https://github.com/raphaeljolivet/known_ynh) for [Yunohost](https://yunohost.org/#/) (a distribution made for easy self hosting, deploying apps in a few clicks).

Today, I just wanted to install the [Twitter plugin](https://github.com/idno/twitter). Unfortunately, it does not work for the official (and quite outdated) 0.9.9 version of Known : I am [advised to go for the tip of the master branch](https://github.com/idno/Twitter/issues/58#issuecomment-450820926). BTW, I find it a pitty that a great software like Known does not have regular stable versions published.

Anyway, I just tried to upgrade my package to the latest version of Known, but I am now stuck with Url rewriting. Installation complains that : 

> Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to default.js
> You can usually fix this by setting AllowOverride All in your Apache configuration.

Yunohost uses Nginx as a HTTP server, not Apache.
I managed to have the previous version (0.9.9) working with [those nginx settings](https://github.com/raphaeljolivet/known_ynh/blob/bb2a2cce0d0147d89626e1de4eba3ab8f0cc7bec/conf/nginx.conf).

Since Known complains about "default.js" not being rewritten, I added one rewrite rule[ in this commit](https://github.com/raphaeljolivet/known_ynh/commit/f4a54b19a36b9a821af5940e0332dc2a07e8b46e), with no luck : 
`rewrite ^js/canary\.js$ /js/default.js last;`

Any help would be appreciated : official support for Nginx configuration would be great : It is used more and more. 
I also think that proper packaging for YunoHost, or Docker, is key for wide spreading web apps.

**Comment by mapkyca** [comment]
Hi sorry it took so long to reply. Assuming this is still an issue, you could try using the latest version from GitHub, as IIRC there was a fairly recent bug fix for this warning pushed.
