### ISSUE TITLE
Add support for Content-Addressable Asset Storage (IPFS, etc.)

### ISSUE THREAD

**Issue by lindner** [idno/known#2322]
The current implementation of Known stores most media assets in a local filesystem and creates UUIDs to reference them.   As an alternate I would like to propose supporting Content-Addressable storage.  That is, storage based on the Hash of the content.  This is used by [IPFS](https://ipfs.io) and other systems.  It can be applied to both user uploaded content and especially for embed content that is fetched and rendered.

With this in place it will be possible to use a public IPFS gateway instead of a CDN (Content Delivery Network)  Read more on how CloudFlare supports this in their [blog post](https://www.cloudflare.com/distributed-web-gateway/).

Ideal scenario is that core has the right hooks and then an IPFS plugin (or DAT, or Swarm, or other future system) can use these for to do their job.

## Proposed Solution

1. Replace or augment the UUID handling for uploaded content/images to use consistent hashing of the content for URLs.
- IPFS uses the hash of the content, or the hash of a container that holds references to other content.
- The same content always has the same hash values, this means that this content is deduplicated between instances and scales with usage.

2. Allow for an alternate URL prefix for content serving.
   - Internal file-based, using the /file/ prefix, but use consistent hashing for paths that 'look like' hashes, due to encoding they will start with `Qm`
   - Internal path-mapped IPFS, use /ipfs/ prefix on same server
   - External IPFS content service like https://cloudflare-ipfs.com/ipfs/

3. On upload allow for hashing the content, storing content in an external system, and storing the resulting consistent hash code

4. Handle Deletes, since there is no deleting content once it's out there.

5. Support Content-Addressable assets in imageproxy.  Instead of storing the encoded URL, store the content hash and pin the content locally.  This allows for the same image to be shared among multiple instances.

6. Bonus points: store generated js/css assets in IPFS as well.  On server startup find the static assets used and add them to the content-addressable backend and use the resulting hash codes to construct the serving URLs.

**Comment by mapkyca** [comment]
Closing this in favour of https://github.com/mapkyca/known-ipfs - bugs / feature requests / etc over there :)
