### ISSUE TITLE
Make separate "IdnoPlugins" folder for user installed plugins

### ISSUE THREAD

**Issue by voss** [idno/known#2327]
It would be nice to have an IdnoPlugins.local folder as a place to store user-installed plugins.

This would make it clear which plugins came with the Known installer, and would also make it easier to migrate/update your Known installation.

Tiny Tiny RSS does this and makes it super easy to migrate/update/troubleshoot

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/known/issues/2327" class="u-in-reply-to"></a>Yep, I like this - also needed for ConsolePlugins. Possibly would make this easier to install things e.g. by composer...
