### ISSUE TITLE
Move get/set Input methods

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#235]
Because you quite often need to call these _before_ there's a current page...

**Comment by benwerd** [comment]
Couldn't this be achieved with an event in getContent / postContent?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/235" class="u-in-reply-to"></a>I don't believe so. There have been times where I've needed access to these in plugin init hooks, and this is before there's a current page defined. I've had to fall back to using the unfiltered variables directly, which is less than idea.

So, current page either needs to be instantiated before plugin hooks are registered, or we need to move input functions somewhere else.

**Comment by benwerd** [comment]
It does make some sense to be able to access input variables in a way that's untethered from the current page.
