### ISSUE TITLE
Can not access account settings after 0.9.9a

### ISSUE THREAD

**Issue by jgmac1106** [idno/known#2357]
When I click on account settings I get "Call to undefined method Idno\Core\Language::_()"

**Comment by mapkyca** [comment]
From the package on withknown.com, right?

That package should not be used. Almost everything needs newer code, which includes language support.

**Comment by jgmac1106** [comment]
no, this is an update from your 0.9.9a

**Comment by jgmac1106** [comment]
Well, I start with 0.9.2 and then update to 0.9.9a.

**Comment by mapkyca** [comment]
Hmm... I'm not seeing that... What page on settings are you looking at?

**Comment by mapkyca** [comment]
Also, do you have the full error from the log (particularly the file/line number dump)

**Comment by jgmac1106** [comment]
...as soon as I go learn how to pull the error logs...Good thing to know
anyways

**Comment by mapkyca** [comment]
Did you not get a line number / error with the "Call to undefined..." ?

**Comment by jgmac1106** [comment]
Console is showing: Failed to load resource: the server responded with a status of 404 () for a favicon

**Comment by mapkyca** [comment]
Hmmm....I'd expect a line number to go along with the output of the fatal error...

**Comment by jgmac1106** [comment]
I can just download uploads and start over correct? We can probably close
this issue since it seems specific to my install and not a bug

**Comment by jgmac1106** [comment]
Actually I think it is related to this: https://github.com/danito/KnownMastodon/issues/20
