### ISSUE TITLE
Consider a move from font-awesome to fork-awesome

### ISSUE THREAD

**Issue by cleverdevil** [idno/known#2358]
**Is your feature request related to a problem? Please describe.**
Known pervasively makes use of font-awesome, which is a great project, but is now no longer a 100% free project. It has a commercial "pro" version.

**Describe the solution you'd like**
A new project called [fork-awesome](http://forkaweso.me/Fork-Awesome/) has been created that is 100% free and licensed appropriately for an open source project like Known. We should consider a switch to fork-awesome.

**Describe alternatives you've considered**
We could stay with font-awesome, we just won't have access to the "pro" level features/icons.

**Additional context**
I'm not certain that a switch is founded or worthwhile, but I thought I'd bring the existence of fork-awesome to the attention of the Known core team so that you could make an effective decision about how to proceed.

**Comment by cleverdevil** [comment]
Additional context: https://github.com/FortAwesome/Font-Awesome/issues/12199#issuecomment-362919956

**Comment by trwnh** [comment]
Fork-Awesome also willingly adds icons that Font-Awesome refuses to add, such as those for libre brands.

http://forkaweso.me/Fork-Awesome/whats-new/ contains notable icons such as:
- activitypub
- archive-org
- diaspora
- f-droid
- friendica
- gnu-social
- hubzilla
- liberapay
- mastodon
- matrix-org
- peertube
- pixelfed
- pleroma
- xmpp

and many others.

**Comment by mapkyca** [comment]
I've no objection so long as it's a drop in replacement / not too much of a change.

**Comment by ketudb** [comment]
I found it to be a pretty drop-in replacement on my install. I had other motivations for doing it - namely to try to solve some issues with some plugins that wanted newer versions of FA etc. But just dropping this in meant I had access to more icons that I needed, while not having to go through and update class names throughout the code - it just magically worked with all the icons that Known expects by default.

**Comment by lindner** [comment]
@ketudb can you review #2426 and compare with your implementation?

**Comment by ketudb** [comment]
@lindner sure! I'll try to do that today.
