### ISSUE TITLE
img URLs in webmentions showing http and not https

### ISSUE THREAD

**Issue by kenwbauer** [idno/known#2388]
## While trying to do this:
Viewing my own page on self hosted Known running with a LetsEncrypt SSL certificate.

## I encountered this error:
"Connection not secure". Some of the img URLs are pointing to http instead of https

## Some other notes:
Shows on various pages with webmentions, specific example on this page: https://known.kenbauer.me/2019/03/22/homebrew-website-club---guadalajara---april-3-2019#comments

The webmentions via Twitter from brlamb, esau_preciado, DavidOjedaL have their images mapped to http image sources from my own site under "service/web/imageproxy" instead of https like others are. No idea why as there are other webmentions from Twitter users that map fine. The site has always been under SSL, not changed at any point.

Like this img src URL on that page: 
http://known.kenbauer.me/service/web/imageproxy/aHR0cHM6Ly9wYnMudHdpbWcuY29tL3Byb2ZpbGVfaW1hZ2VzLzEwNzI2Njk1NzY0MjM1MDU5MjEvNTgxOWJmb00uanBn/300/square

Give us some context: 
* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = "0.9.9-a"
build = 2019031001

* What database are you using? (e.g. mongo, mysql, postgres)
mysql

* Any warnings or errors in your admin/diagnostics page?
None, says: 
Basic checks on installation discovered no problems.

* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!

* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
Shouldn't be happening, as the display url is detected. 

My guess is that there's something different about your setup - maybe you're running behind a reverse proxy or some such? Basically Config::getDisplayUrl() will call Page::isSSL(), and that attempts to establish whether SSL is active through a variety of ways:

1. The $_SERVER['HTTPS'] variable is either "1" or "on"
2. SERVER_PORT is 443
3. X-FORWARDED-PROTO is https

You could take a look at $_SERVER in your diagnostics dump to see what Known is detecting and if anything stands out as fishy.

**Comment by mapkyca** [comment]
That being said, I have spotted a logic fault in isSSL(). Still good to see what your $_SERVER says, so we could confirm whether it's this test that's failing...

**Comment by kenwbauer** [comment]
Thanks mapkyca. I wonder why GitHub is not alerting me to activity. I noticed the commit related to this when I upgraded today. This is running on ReclaimHosting. Checking a phpinfo dump lets me know that:
$_SERVER['HTTPS'] is indeed on
port 443 check

Again, cheers and thanks.
