### ISSUE TITLE
Just git-pulled and broke my Known instance

### ISSUE THREAD

**Issue by rikmendes** [idno/known#2390]
## While trying to do this:
I have always updated my Known install at Dreamhost using the terminal and git pull in the root Known folder and it always went just fine, but not this time. 

## I encountered this error:
Could not find autoload.php, did you run "composer install" ..?
in the doc I can read : If you're using a direct checkout from GitHub (rather than using one of the prepared packages), you need to update any dependencies using "composer update"

## Some other notes:
Sadly I can't invoke composer at Dreamhost, it's just not part of the commands shared hosting are allowed to run. 
Give us some context: 
So what's next ? is there something I can do and still use github to upgrade my Known ? 
OR
should I keep my config.ini, remove all the files and install Known from a zip archive ?

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
I think I was on a pretty recent version, maybe from 2 month ago ?

* What database are you using? (e.g. mongo, mysql, postgres)
MYSQL
* Any warnings or errors in your admin/diagnostics page?
There is no way to even access the admin page, the error I see is outside of Known.

**Comment by mapkyca** [comment]
Two options, you could run composer locally and upload the vendor directory, or you could use one of the unofficial packages which contain the dependencies already
