### ISSUE TITLE
Class 'IndieWeb\MentionClient' not found

### ISSUE THREAD

**Issue by markwaters** [idno/known#2397]
## While trying to do this:
Post a Photo , Selected Photo , Entered Post Text , clicked Publish.

## I encountered this error:
500
Oh no! Known experienced a problem!
Known experienced a problem with this page and couldn't continue.
Class 'IndieWeb\MentionClient' not found
The technical details are as follows:
Fatal Error: /var/www/known.multisite/Idno/Core/MentionClient.php:15 - "Class 'IndieWeb\MentionClient' not found", on page markwaters.eu/photo/edit/
Connect to other open source users for help.

## Some other notes:
I had just checked-out 70a820096de0197f7be47c0015871fb7f7f55a79
Rolled back to b0921dcf69b48313f9d642584d0e11dbf6c1a5ed
Post seems to have been posted successfully despite the error.

Debian Stable 9.8
MariaDB = 10.1.37-0+deb9u1
PHP = 7.0.33-0+deb9u3

**Comment by mapkyca** [comment]
Did you run a composer update?

**Comment by markwaters** [comment]
No I hadn't run `composer update`.
All working perfectly again now.
Thanks.
