### ISSUE TITLE
Version numbers are getting farcical 

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2442]
## While trying to do this:
See the version we're using

## I encountered this error:

We've been at 0.9.9-a for over a year, and at this point it's meaningless.

Since I can count higher than 9, unless there are strong objections I'm going to follow semver from now on - so, minor version goes up all the time. But I'm not going to change major number until the api has settled down.

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by johanbove** [comment]
@mapkyca  Great idea! But what about the "releases" and git tags in this Github project? Could you please set the tags there as well? So it would make it easier for us to follow your progress.
