### ISSUE TITLE
Rich editor broken

### ISSUE THREAD

**Issue by nekr0z** [idno/known#2443]
Trying to do anything that requires Rich Text Editor (making a post, posting a picture, but not a status update for instance) shows blank space instead of the editor.

By going up the commit history I was able to pinpoint this to commit cbe7e70 - up until and including  c159f3f of main tree and up until and including 228c7a4 things work as expected.

**Comment by lindner** [comment]
Can you give some details on the environment where this is happening?

Specific browser / env, plus any messages the show up in the console log
would be very helpful.

Thanks!

**Comment by nekr0z** [comment]
> Can you give some details on the environment where this is happening?

Totally.

Known instance is hosted on Dreamhost (shared hosting) running PHP 7.2.13 and is, as you might have guessed, pulled from github directly. The annoying behaviour is observed on Google Chrome browser ver. 74.0.3729.169 (official 64-bit build) running on Debian Linux 9.9 (current stable, latest updates).

Server error.log remains clear. However, https access log may be offering something useful here:
```
2001:470:1f15:13ee:9910:beaa:734e:c8ea - - [31/May/2019:11:23:33 -0700] "GET /entry/edit HTTP/1.1" 200 9717 "https://evgenykuznetsov.org/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"                                                                                                                                                                                                                                    
2001:470:1f15:13ee:9910:beaa:734e:c8ea - - [31/May/2019:11:23:33 -0700] "GET /vendor/tinymce/tinymce/skins/lightgray/skin.min.css HTTP/1.1" 404 16762 "https://evgenykuznetsov.org/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"                                                                                                                                                                                          
2001:470:1f15:13ee:9910:beaa:734e:c8ea - - [31/May/2019:11:23:33 -0700] "GET /vendor/tinymce/tinymce/skins/lightgray/content.min.css HTTP/1.1" 404 16918 "https://evgenykuznetsov.org/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"                                                                                                                                                                                       
2001:470:1f15:13ee:9910:beaa:734e:c8ea - - [31/May/2019:11:23:44 -0700] "POST /autosave/ HTTP/1.1" 200 886 "https://evgenykuznetsov.org/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"                                                                            
```

**Comment by nekr0z** [comment]
I might add that
```
$ ls vendor/tinymce/tinymce/skins/
content  ui
```
so no `lightgray` there.

`vendor` directory was populated by `composer install` while on `master` git branch, as advised by readme.

**Comment by mapkyca** [comment]
You on mobile (#2430 )?

You could also try a ```composer update``` to make absolutely sure you've got the newest version of things, and also do a ctrl refresh to clear any cached javascript.

**Comment by nekr0z** [comment]
> and also do a ctrl refresh to clear any cached javascript.

Yes, this did the trick. You're awesome. Also, no more 404s in logs, so this should be a question of JS cached through update between your latest 0.9.9-a release and current master. Perhaps, worth documenting somewhere, but I can't really figure out where.

> You could also try a `composer update` to make absolutely sure you've got the newest version of things

No, that was not the issue. I did try, but it returned "nothing to return or update".

> You on mobile (#2430 )?

I had this issue both on mobile and desktop. Now, after clearing cached JS on both, I'm enjoying #2430 on mobile! :-)

**Comment by mapkyca** [comment]
Happy to help!
