### ISSUE TITLE
Uncaught Error: Class 'Idno\Core\Bonita\Main' not found

### ISSUE THREAD

**Issue by jaranta** [idno/known#2464]
## While trying to do this:

Load Known.

## I encountered this error:
```
Fatal Error: /var/www/posts.arjoranta.fi/public_html/Idno/start.php:122 - "Uncaught Error: Class 'Idno\Core\Bonita\Main' not found in /var/www/posts.arjoranta.fi/public_html/Idno/start.php:122
Stack trace:
#0 /var/www/posts.arjoranta.fi/public_html/index.php(30): require_once()
#1 {main}
  thrown", on page posts.arjoranta.fi/
```

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

Running 004083ac5cc0ca4a59783e833d8004bc4f54e02b

* What database are you using? (e.g. mongo, mysql, postgres)

Mysql

**Comment by mapkyca** [comment]
Have you run composer install or update?
