### ISSUE TITLE
Datamodel: Get rid of search field

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2485]
Having a munged search field as a column is a bad way of doing it. 

Not only is it non-relational, it's inefficient,  plus limits you to certain database engines on that table. 

The "correct" way to do this is to use Elastic Search or similar, but since that's not possible for most users, we should split the search fields out into their own tables

**Comment by cdn** [comment]
I think Known with SQLite did that as a matter of course

**Comment by mapkyca** [comment]
If you're talking about the SQLite plugin, it didn't 'cos I wrote it and it used a search field. :D 

There's a lot of datamodel work that needs to be done for the next major versions, so I hope this will be part of it.

**Comment by cdn** [comment]
Well…
> sqlite> .tables
config                    entities_search           reader_search           
config_search             entities_search_content   reader_search_content   
config_search_content     entities_search_docsize   reader_search_docsize   
config_search_docsize     entities_search_segdir    reader_search_segdir    
config_search_segdir      entities_search_segments  reader_search_segments  
config_search_segments    entities_search_stat      reader_search_stat      
config_search_stat        metadata                  session                 
entities                  reader                    versions

**Comment by mapkyca** [comment]
Heh heh! Well that serves me right for being a cocky a-hole, I stand corrected!

Also, yay past me for doing things properly.
