### ISSUE TITLE
Use an alternate template for embeds/furls with small images

### ISSUE THREAD

**Issue by lindner** [idno/known#2492]
The template used for embedded links will often display a very large image which does not look great.  It may also crop it in suboptimal ways.

Instead a template optimized for smaller images could be used.  It would have the smaller image on the left and the title/description to the right.  This is consistent with how other social networks/blogs embed content.

Example post where this occurs

https://1500wordmtu.com/2019/every-developer-should-ask-themselves-what-they

**Comment by johanbove** [comment]
@benwerd Hi Ben, are you working on this? I could have at this too if you want.
