### ISSUE TITLE
WebInstaller fails

### ISSUE THREAD

**Issue by slehoun** [idno/known#2495]
## While trying to do this:
During installation procedure, WebInstaller fails. I went through all the steps in installation guide succesfully up to the WebInstaller point.

## I encountered this error:
Navigating to https://domainname.com/known redirects me to https://domainname.com/known/begin - there is no such path. Manually navigating to webinstaller (https://domainname.com/known/warmup) fails with this message:

```
[Mon Jul 15 19:45:16.269291 2019] [php7:error] [pid 6344] [client xxx.xxx.xxx.xxx:49228] PHP Fatal error:  Uncaught Error: Call to undefined method WebInstaller::template() in /var/www/html/known/begin/WebInstaller.php:18\nStack trace:\n#0 /var/www/html/known/begin/WebInstaller.php(223): WebInstaller->__construct()\n#1 /var/www/html/known/begin/index.php(14):              WebInstaller::installer()\n#2 {main}\n  thrown in /var/www/html/known/begin/WebInstaller.php on line 18
```

## Some other notes:
Just to make sure, I followed installation steps:

- cloned git repo into /var/www/html/known
- installed plugins via composer
- set the permissions to apache
- created MySQL user, MySQL DB, granted permissions
- created .../known/configuration/config.ini file with DB settings
- navigated to https://domainname.com/known

## Give us some context: 
Operating system: CentOS Linux release 7.6.1810 (Core)
Web server: Apache 2.4.34
Database: MariaDB 5.5.60
PHP version: 7.2.10

version.known:
```
version = "0.12.2"
build = 2019061402
revision = "bc6ac0d"
```

**Comment by mapkyca** [comment]
Fixed in latest builds. Run off GitHub, or wait for me to get time to build a package.
