### ISSUE TITLE
Google APIS appear to have stopped working

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2538]
## While trying to do this:

Any call to www.googleapis.com

## I encountered this error:

"not found"

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by johanbove** [comment]
Where are the Google APIS used within the Known code?

**Comment by mapkyca** [comment]
_seems_ to be ok now, but I was getting an error from location resolution (lat/long into place) from checkin. That said, visiting the url still gives "not found" so who knows...

**Comment by johanbove** [comment]
Which URL are you testing this with? Checkin worked for me just now.

**Comment by mapkyca** [comment]
Literally just opened the checkin, but it might have been a one off. Closing for now...
