### ISSUE TITLE
Add .editorconfig for code formatting consistency 

### ISSUE THREAD

**Issue by johanbove** [idno/known#2540]
Happened to notice some code-formatting inconsistencies in regards to spaces and etc in older files. 

To make it easier for developers to stick to the [code formatting guidelines](http://docs.withknown.com/en/latest/developers/standards/#indentation), I would like to propose to introduce an ``.editorconfig`` file which would help set up the developer's IDE to stick to the project expected defaults.

An example `.editorconfig` file:
```
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true
````

See https://editorconfig.org/

cf. http://docs.withknown.com/en/latest/developers/standards/#indentation

**Comment by mapkyca** [comment]
I'm not familiar with this, how widely supported is this file? 

Also note that there is a phpcs file, so I'd be keen to see that kept updated: https://github.com/mapkyca/known-phpcs

**Comment by johanbove** [comment]
[Regarding the editorconfig support:](https://github.com/idno/known/issues/2540)

That's a good question. Looking at the Github project and the number of integrations that are available for all editors, I would say it's fairly widely supported. [https://github.com/editorconfig](https://github.com/editorconfig)

It helps us to have everyone use spaces instead of tabs, even-though colleagues might use a different editor for coding.

(Originally published at: https://social.johanbove.info/2019/10/07/replying-to-add-editorconfig-for-code-formatting-consistency)
