### ISSUE TITLE
Comments disabled

### ISSUE THREAD

**Issue by markwaters** [idno/known#2543]
I've just noticed that comments are disabled on all our Known sites.
Not found any plugins disabled that are related to comments.
Clicking comments opens the Post but the comment form is not shown.
Can't see anything related in the Docs site or in other Issues here.

I am using the latest git version - c948f201e95b690124e6fa4360b90d47fa21b118
Known Version = 2019100601

**Comment by johanbove** [comment]
Which version of the "Comments" plugin is active on your set up?
See https://github.com/idno/comments

**Comment by markwaters** [comment]
Hi @johanbove 
The entire comments plugin folder was missing somehow.
I have cloned the repository and now the commenting functionality has been restored.
Thank you!

**Comment by johanbove** [comment]
[@markwaters](https://github.com/markwaters) You're welcome. 😀

(Originally published at: https://social.johanbove.info/2019/10/19/markwaters-youre-welcome)
