### ISSUE TITLE
tag rss feeds should have the tag as a title rather than site title

### ISSUE THREAD

**Issue by jgmac1106** [idno/known#2544]
## While trying to do this:
adding multiple rss tag feeds to a header

## I encountered this error:
only one feed displays because they all have the same names

**Comment by jgmac1106** [comment]
Thinking maybe:
.if (!empty($vars['tags']))  $vars['title'] = $title .  $tag  }
else....

Or something to that effect, basically trying to grab site title and the tag into the new title

**Comment by johanbove** [comment]
This is already taken care of in my PR #2536 
It works on my site, eg. https://social.johanbove.info/tag/music?_t=rss

**Comment by johanbove** [comment]
Only the jsonfeed output still has the "static" title.

**Comment by jgmac1106** [comment]
Closing due to fix in #2536
