### ISSUE TITLE
LinkedIn plugin won't save settings in version 1.0.0-rc.2+2019100601 

### ISSUE THREAD

**Issue by jevdemon** [idno/known#2546]
## While trying to do this:
Enabled LinkedIn plugin, trying to save the LinkedIn API Key and Secret Key from the LinkedIn app I created on the LinkedIn site.

## I encountered this error:
Something went wrong.
Cannot access private property Idno\Core\Idno::$config

## Some other notes:
Found this entry in the error log:
[19-Oct-2019 00:07:03 UTC] Known (k.evdemon.org): critical - Cannot access private property Idno\Core\Idno::$config [/home/evdemon1/k.evdemon.org/IdnoPlugins/LinkedIn/Pages/Admin.php:27]

Give us some context: 
I compared my config Blob against an older version of Known I have installed (0.92).  The 0.92 version of the config Blob includes a JSON construct containing the LinkedIn API Key and Secret Key from the LinkedIn app I created on the LinkedIn site.  
The config Blob from version 1.0.0-rc.2+2019100601 is missing the additional LinkedIn API Key and Secret Key (obviously because it is unable to write these values into the config Blob).

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = '1.0.0-rc.2'
build = 2019100601
* What database are you using? (e.g. mongo, mysql, postgres)
10.2.27-MariaDB - MariaDB Server 
* Any warnings or errors in your admin/diagnostics page?
You appear to be running directly from a git checkout. While this is fine, you might find a pre-packaged version of Known more stable.
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
According to the error log the exception occurs on line 27 of the LinkedIn Admin.php plugin Page.  The function containing the **line throwing the uncaught exception** appears below:
            function postContent() {
                $this->adminGatekeeper(); // Admins only
                $appId = $this->getInput('appId');
                $secret = $this->getInput('secret');
                ****\Idno\Core\site()->config->config['linkedin'] = [
                    'appId' => $appId,
                    'secret' => $secret
                ];****
                \Idno\Core\site()->config()->save();
                \Idno\Core\site()->session()->addMessage('Your LinkedIn application details were saved.');
                $this->forward(\Idno\Core\site()->config()->getDisplayURL() . 'admin/linkedin/');
            }
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
Thanks for the report.

At this stage the linkedin plugin can largely be considered deprecated and unmaintained. They changed their api recently and it looks like posting to it has been severely restricted
