### ISSUE TITLE
Installer strips minus from database name

### ISSUE THREAD

**Issue by derixithy** [idno/known#2563]
## While trying to do this:
The installer strips - caracter from database name, so it can not install the system

## I encountered this error:
SQLSTATE[HY000] [1044] Access denied for user 'dbuser'@'%' to database 'dbname'

## Some other notes:
My hosting provider sets up my database for me so i can not remove the minus from the database name!

Give us some context: 
version = '1.0.0'
build = 2019102701
revision = "a8a5af7"
Using mysql
database name, hast and user all contain a minus in it

**Comment by mapkyca** [comment]
Yep. 

"-" is a character that is not permitted in most versions of mysql/mariadb so is stripped out.
