### ISSUE TITLE
Error while deleting Photo post

### ISSUE THREAD

**Issue by markwaters** [idno/known#2573]
## While trying to do this:
Deleting a Photo post

## I encountered this error:
Your photo was deleted.
Something went wrong.
Argument 1 passed to Idno\Common\Page::forward() must be of the type string, null given, called in /var/www/known.multisite/IdnoPlugins/Photo/Pages/Delete.php on line 52

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = '1.0.1'
build = 2019102702

* What database are you using? (e.g. mongo, mysql, postgres)
MariaDB

**Comment by mapkyca** [comment]
Hmm... the error appears to be thrown because the HTTP_REFERER isn't being set by your browser or is being stripped somewhere. This shouldn't happen in usual operation, and if it's being stripped out somewhere you're going to see some odd things happening!
