### ISSUE TITLE
Uploading Avatar in New Profile

### ISSUE THREAD

**Issue by erinjo** [idno/Known#258]
For when we redesign the user profiles / onboarding:

a) Clicking the "upload a new photo" link should take the user straight to a photo upload option, not to the edit profile page when the photo link is lower/nonobvious and they have to click it a second time to upload.

b) If the red ? / default profile image on /profile/USERNAME/ is clickable, it should either open a photo upload or take the user to another page, not reload the same page.

Sorry if that sounds cranky.  I'm hot and tired...

**Comment by benwerd** [comment]
I'm closing this, just because we've done a bunch of style work since then and we should revisit from scratch.
