### ISSUE TITLE
Cannot access private property Idno\Core\Idno::$config

### ISSUE THREAD

**Issue by markwaters** [idno/known#2606]
## While trying to do this:
Remove Custom Javascript and Save

## I encountered this error:
Cannot access private property Idno\Core\Idno::$config

## Some other notes:
I have Known up-to-date via Git.
Currently I have the Matomo javascript snippet in the Footer section , I select all text and delete , then click Save.
Same error in Desktop Firefox and Brave browsers.

Give us some context: 
version = '1.0.7'
build = 2019112701
MariaDB 10.1.38
No errors in Diagnostics page.

**Comment by cdn** [comment]
Have you got the latest version of [FooterJS](https://github.com/idno/FooterJS)?

**Comment by markwaters** [comment]
LOL. Deja-vu.
I didn't.
I do now.
Fixed.
Thanks again @cdn
