### ISSUE TITLE
Test language files

### ISSUE THREAD

**Issue by cdn** [idno/known#2630]
What does a developer need to do to trigger localisation via po files in languages/xx_XX/LC_MESSAGES/plugin.po ?

Have tried:
- browser accept language change.
- Known user language
- Known config lang
- server LC_* environment variables

PHP's `var_export` gives

> Idno\Core\Language::__set_state(array(
   'translations' =>
  array (
    0 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'known',
       'canProvide' => true,
       'language' => NULL,
    )),
    1 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'status',
       'canProvide' => true,
       'language' => NULL,
    )),
    2 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'text',
       'canProvide' => true,
       'language' => NULL,
    )),
    3 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'photo',
       'canProvide' => true,
       'language' => NULL,
    )),
    4 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'event',
       'canProvide' => true,
       'language' => NULL,
    )),
    5 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'indiepub',
       'canProvide' => true,
       'language' => NULL,
    )),
    6 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'styles',
       'canProvide' => true,
       'language' => NULL,
    )),
    7 =>
    Idno\Core\GetTextTranslation::__set_state(array(
       'domain' => 'mastodon',
       'canProvide' => true,
       'language' => NULL,
    )),
  ),
   'language' => 'en_US',
))

Where language has been other things, but nothing has changed.

**Comment by mapkyca** [comment]
Should work with any of those, but it does rely on there being a compiled get text dictionary in place

**Comment by cdn** [comment]
A `.mo` created via `msgfmt`?

**Comment by cdn** [comment]
Removing `LANG` and/or `LANGUAGE` environment variables means there’s a chance of getting a cli php script to use the .mo for (e.g.) fr_FR, however an HTTP request to Known tends to be a hyphenated language reference.

Whatever the language reference nothing seems to change.

**Comment by cdn** [comment]
Had to massage [the code](https://github.com/cdn/Known/blob/languages-fix/Idno/Core/Language.php#L42) to get anything to happen 🤷🏻‍♂️

**Comment by cdn** [comment]
This works much better with `detectBrowserLanguage()` [changes](https://github.com/idno/Known/blob/master/Idno/Core/Language.php#L193).
