### ISSUE TITLE
known.po[t] has issues preventing compilation

### ISSUE THREAD

**Issue by cdn** [idno/known#2631]
## While trying to do this:

Create a known.mo from a known.po derived from known.pot

## I encountered this error:

> /known$ msgfmt languages/source/known.pot
languages/source/known.pot:54:31: invalid control sequence
languages/source/known.pot:78:55: invalid control sequence
languages/source/known.pot:406: keyword "http" unknown
languages/source/known.pot:406:115: syntax error
languages/source/known.pot:410: keyword "http" unknown
languages/source/known.pot:410:48: syntax error
languages/source/known.pot:438:12: invalid control sequence
languages/source/known.pot:442:31: invalid control sequence
languages/source/known.pot:518:41: invalid control sequence
languages/source/known.pot:550:24: invalid control sequence
languages/source/known.pot:574:25: invalid control sequence
languages/source/known.pot:578:22: invalid control sequence
languages/source/known.pot:634: keyword "https" unknown
languages/source/known.pot:634:87: syntax error
languages/source/known.pot:850: duplicate message definition...
languages/source/known.pot:375: ...this is the location of the first definition
languages/source/known.pot:982: duplicate message definition...
languages/source/known.pot:351: ...this is the location of the first definition
languages/source/known.pot:1002: duplicate message definition...
languages/source/known.pot:343: ...this is the location of the first definition
languages/source/known.pot:1006: duplicate message definition...
languages/source/known.pot:323: ...this is the location of the first definition
languages/source/known.pot:1010: duplicate message definition...
languages/source/known.pot:319: ...this is the location of the first definition
languages/source/known.pot:1026: duplicate message definition...
languages/source/known.pot:387: ...this is the location of the first definition
languages/source/known.pot:1038: duplicate message definition...
languages/source/known.pot:339: ...this is the location of the first definition
languages/source/known.pot:1111: end-of-line within string
msgfmt: too many errors, aborting

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
Github master HEAD
* What database are you using? (e.g. mongo, mysql, postgres)
n/a
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

The escapes of apostrophes `\'` do not appear to be needed.
The double escaped quotes `\\"` produce the `keyword "http" unknown`
There are a number of duplicated strings between files (templates etc.)

Presumably where these escapes are referenced will need altering.

**Comment by mapkyca** [comment]
I used Poedit, and I'm not seeing any issues apart from the duplication (which I'm aware of but haven't had a chance to look at, and Poedit automatically handles).

The compiler script is over at mapkyca/known-language-tools, so feel free to send PRs in the meantime

**Comment by cdn** [comment]
Some of these issues have been addressed by changes to known-language-tools, and could also be addressed by #2657 ...
