### ISSUE TITLE
Restore (un)ordered list rich editor toolbar icons

### ISSUE THREAD

**Issue by svandragt** [idno/known#2645]
## While trying to do this:
As a content editor I want to use lists to structure my writing in an easy manner.

## I encountered this error:

 I used to be able to add ordered / unordered lists using toolbar icons But these have disappeared for a while. As a result I have to go into html mode and type the elements which I can then add to via the rich text mode. 

## Some other notes:

Used to be there I think a year ago when I first started using known. If I remember typing asterisk markdown style does not create them either which was my fallback. 

Give us some context: 

I’m not at my computer just now but can add to this later. 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by lindner** [comment]
You can customize the toolbar here:

https://github.com/idno/known/blob/23e9bccce4cb9b3aee058ee595e36b7aa70af178/templates/default/forms/input/richtext.tpl.php#L74

Not sure why these settings are not taking..

**Comment by svandragt** [comment]
Looking at composer the project is using tinymce 5.9.2 and looking at that project that project the list options have been moved to a list plugin. https://github.com/tinymce/tinymce/issues/3342#issuecomment-262698302 and https://www.tiny.cloud/docs/advanced/available-toolbar-buttons/#listsplugin.

It doesn't look like known sets up the list plugins: https://github.com/idno/known/blob/dev/templates/default/forms/input/richtext.tpl.php#L75-L89

As a result, the toolbar items are ignored. I'll test this theory.

**Comment by lindner** [comment]
Thanks for delving into this.  I tested and the linked PR fixes!!!
