### ISSUE TITLE
Upgrade broke display of pages

### ISSUE THREAD

**Issue by tsparks** [idno/known#2663]
I upgraded to version 1, 

Page display broke so my profile picture went large and the header of the site now takes up half the page. Site address: http://tom.sparkshouse.com

I have been using Known for about 4 years with few problems. This makes my site unuseable.

Can anyone offer a solution?

Thank you..... Tom in Seattle

* Version 1
* Mysql
* No warnings
* Self Hosted at  Pair.net
* Site address: http://tom.sparkshouse.com

**Comment by tsparks** [comment]
I changed my profile picture to a small 5px file and that put the page header back in a proper display.  The site configuration and  account setting displays weird like it is missing css   The site is useable now but I know something is wrong.

**Comment by jeremycherfas** [comment]
Have you tried changing themes to see whether that makes any difference? I notice also that the icons for your social links are missing too. Perhaps the theme is not finding its assets any more?

**Comment by tsparks** [comment]
I believe something broke during the upgrade, I discovered I can not add a post. If you you understand the file structure of Kirby, which directories would you review first for a problem. I can repost that directory to see it the clears up the issue,

**Comment by cdn** [comment]
For one thing, JavaScript files are being served as text/html (because they’re missing) :

`curl -I https://tom.sparkshouse.com/js/1579555190/known.min.js`
> HTTP/1.1 404 Not Found
Date: Tue, 21 Jan 2020 18:02:32 GMT
Server: Apache
P3P: CP="CAO PSA OUR"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Link: <https://tom.sparkshouse.com/indieauth/auth>; rel="authorization_endpoint", <https://tom.sparkshouse.com/indieauth/token>; rel="token_endpoint", <https://tom.sparkshouse.com/micropub/endpoint>; rel="micropub"
X-Powered-By: https://withknown.com
X-Clacks-Overhead: GNU Terry Pratchett
X-Known-Build-Fingerprint: 084[...]589b2
Access-Control-Allow-Origin: *
Set-Cookie: known=40rqes31s5e9k6sqc1m2q8qv43; expires=Tue, 28-Jan-2020 18:02:32 GMT; Max-Age=604800; path=/; secure; HttpOnly
Content-Length: 13522
Content-Type: text/html;charset=UTF-8

It’s unlikely to be at that path on the server:
> /js/known.min.js

Have you run any `composer` or `grunt` tasks post–upgrade?

**Comment by tsparks** [comment]
> Have you tried changing themes to see whether that makes any difference? I notice also that the icons for your social links are missing too. Perhaps the theme is not finding its assets any more?

Thank you Jeremy for the suggestion, yes I have tested a couple themes, same results.

**Comment by cdn** [comment]
https://tom.sparkshouse.com/js/known.min.js exists, and is served with the correct MIME type suggesting a Rewrite issue with Apache…

**Comment by cdn** [comment]
Ditto https://tom.sparkshouse.com/css/known.min.css

**Comment by tsparks** [comment]
> For one thing, JavaScript files are being served as text/html (because they’re missing) :
> 
> `curl -I https://tom.sparkshouse.com/js/1579555190/known.min.js`
> 
> > HTTP/1.1 404 Not Found
> > Date: Tue, 21 Jan 2020 18:02:32 GMT
> > Server: Apache
> > P3P: CP="CAO PSA OUR"
> > Expires: Thu, 19 Nov 1981 08:52:00 GMT
> > Cache-Control: no-store, no-cache, must-revalidate
> > Pragma: no-cache
> > Link: https://tom.sparkshouse.com/indieauth/auth; rel="authorization_endpoint", https://tom.sparkshouse.com/indieauth/token; rel="token_endpoint", https://tom.sparkshouse.com/micropub/endpoint; rel="micropub"
> > X-Powered-By: https://withknown.com
> > X-Clacks-Overhead: GNU Terry Pratchett
> > X-Known-Build-Fingerprint: 084[...]589b2
> > Access-Control-Allow-Origin: *
> > Set-Cookie: known=40rqes31s5e9k6sqc1m2q8qv43; expires=Tue, 28-Jan-2020 18:02:32 GMT; Max-Age=604800; path=/; secure; HttpOnly
> > Content-Length: 13522
> > Content-Type: text/html;charset=UTF-8
> 
> It’s unlikely to be at that path on the server:
> 
> > /js/known.min.js
> 
> Have you run any `composer` or `grunt` tasks post–upgrade?

No I have not run any `composer` or `grunt` jobs I am not familiar with either. Can i investigate a location for the  JavaScript files? Maybe they were not uploaded during the upgrade installation.

**Comment by tsparks** [comment]
> https://tom.sparkshouse.com/js/known.min.js exists, and is served with the correct MIME type suggesting a Rewrite issue with Apache…

Thanks CDN... Is this an issue with my Internet Provider? Should I check in with **Pair.net**, they have a good support team.

**Comment by cdn** [comment]
It might be a small portion of `.htaccess` not being interpreted appropriately.

The js / css are referenced in `/path/to/webroot/templates/default/shell/`, within the files;
`javascript.tpl.php` and `css.tpl.php`

Both those create URLs with the modified timestamp as a subdirectory.
Removing those sections would restore your aesthetics, although what the developers would say is another matter.

I suspect you need `composer install` or `composer update`.

(Much of this is ottomh (o: )

**Comment by tsparks** [comment]
> It might be a small portion of `.htaccess` not being interpreted appropriately.
> 
> The js / css are referenced in `/path/to/webroot/templates/default/shell/`, within the files;
> `javascript.tpl.php` and `css.tpl.php`
> 
> Both those create URLs with the modified timestamp as a subdirectory.
> Removing those sections would restore your aesthetics, although what the developers would say is another matter.
> 
> I suspect you need `composer install` or `composer update`.
> 
> (Much of this is ottomh (o: )

CDN... Thank you for your time and insight, I am not a developer so my understanding is limited. Your  

suggestion to look to the .htaccess file was the key. I had failed to create the htaccess file. I copied the file from my backup of the older installation and that solved the problem.  Hurray!!
