### ISSUE TITLE
addPageHandler /admin/apitester/

### ISSUE THREAD

**Issue by alisonw** [idno/known#2668]
Running slightly outdated version I noted very frequent entries in the apache error log for the domain of the forrm:

[Sun Jan 26 23:10:25.035170 2020] [php7:notice] [pid 20493] [client XXX.XXX.XXX.XXX:48160] Known (SITE): debug - DEPRECATION WARNING: Use \\Idno\\Core\\Idno::site()->routes()->addRoute() [{"file":"/var/www/SITE/IdnoPlugins/APITester/Main.php","line":10,"function":"addPageHandler","class":"Idno\\\\Core\\\\Idno","type":"->","args":["/admin/apitester/?","\\\\IdnoPlugins\\\\APITester\\\\Pages\\\\Admin"]},{"file":"/var/www/alisonw-uk/Idno/Common/Component.php","line":20,"function":"registerPages","class":"IdnoPlugins\\\\APITester\\\\Main","type":"->","args":[]},{"file":"/var/www/SITE/Idno/Core/Plugins.php","line":55,"function":"__construct","class":"Idno\\\\Common\\\\Component","type":"->","args":[]}]

I updated, therefore, to the latest commit but the issue is still there. As a temporary measure I've just commented out the offending line:
//            \Idno\Core\Idno::site()->addPageHandler('/admin/apitester/?', '\IdnoPlugins\APITester\Pages\Admin');
which has stopped the log entries but, obviously, is not the appropriate answer!

Context:
Ubuntu 19.10 / Apache/2.4.41 (Ubuntu) / PHP 7.3.11 
Known Diagnostics: Version 1.1.1+2020012001 
"API Tester 0.9.10" plugin is *not* enabled.

DB runs on separate machine - 10.3.20-MariaDB-0ubuntu0.19.10.1 Ubuntu 19.10

**Comment by alisonw** [comment]
I'm now having issues trying to repeat this. Closing.

**Comment by mapkyca** [comment]
Yeah, the api tester needs to be updated, but since it's only used by a handful of people (if at all) it hasn't been a priority!
