### ISSUE TITLE
Merge S3 PR into known

### ISSUE THREAD

**Issue by Lewiscowles1986** [idno/known#2688]
This feature is related to using Known on cloud providers with ephemeral file systems

The solution I would like is my 2020 updates to the S3 plugin to become part of Known core distribution, so that S3 support (via local filesystem) is turn-key for cloud users who configure S3.

Alternatives I've tried are to manually cat file changes and commit to git. This is not ideal because some of the files contain secrets in them. It would make it too easy for people to not source manage, or poorly source manage.

Another alternative is any other distributed file-storage. I Picked S3 because most of the maintenance will be undertaken by Amazon. It actually has a number of third-party compatible services if you don't do too many "flowery" things.

This is part of some works I used to stand Known up on Heroku, test uploads, find out what the project is about.

Additionally, this has some benefits for security; including ephemeral source-controlled solutions wiping out a whole class of PHP errors and attacks from ad-hoc edits; Further it allows read-only safe working environments, which I've used to test read-only S3 to stop file uploads for the heroku copy, without shipping gigabytes of files per-release.

**Comment by mapkyca** [comment]
S3 support is not used by the vast majority of users (which explains why it has suffered from extensive bitrot over the years)

The solution would be to convert the S3 plugin to be composer installable, that way it would be easy for those wanting to deploy in a cloud environment to roll their own custom builds.

The primary purpose of moving plugin support to composer is to keep the core distribution slim, while allowing others the flexibility to build more comprehensive distributions should they need to.
