### ISSUE TITLE
Packages for newer versions?

### ISSUE THREAD

**Issue by julia-r** [idno/known#2724]
It looks like the current version is now 1.1.5? Could you maybe provide packages for the latest (stable) version? The known homepage still has a download for 1.0.0 on it and even the [alternative packages](https://www.marcus-povey.co.uk/known/) linked in the docs are a bit outdated by now. 

Thanks :)

**Comment by lindner** [comment]
Agreed that getting on a consistent release schedule should be a priority.  Ideally the build/package/release process can be mostly automated out of Travis or some other continuous integration platform...

**Comment by mapkyca** [comment]
I'll try and put something together, in the mean time you can always use a git checkout as it is fairly stable.
