### ISSUE TITLE
Rewriting appears to be disabled. Usually this means ...

### ISSUE THREAD

**Issue by csjjpm** [idno/known#2725]
## Some other notes: set allowoverride all everywhere (I can find!)

Give us some context: 
Apache 2.4, PHP 7.2, MYSQL 8.0.11 on FreeBSD. Latest version of Known.

I've lots of other self hosted apps installed and was trying out your blog.  I can't get passed the issue of 'allowoverride none', 'we tried to fetch....'.  I've set all the chmod/chown permissions as per instructions (normal.).

In the <Directory> setting for /usr/local/www/known I had specifically set AllowOverride All.  This didn't work so I have set it gloablly in my httpd.conf file for all.  Still doesn't work.

I don't seem to have a .htaccess file to redirect and .js 

version = '1.0.0'
build = 2019102701
revision = "a8a5af7"

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by csjjpm** [comment]
The known-1.0.0.zip I downloaded (28MB) was missing a lot of files.  I grabbed a known-master.zip from github (2MB) and copied it over.  Now everything is working.

**Comment by mapkyca** [comment]
I'm concerned that you're saying that the binary is "missing a lot of files". This obviously shouldn't happen... could you give more details as to what files are missing?
