### ISSUE TITLE
Using Reply to Site on a Status Post results in Javascript error.

### ISSUE THREAD

**Issue by lindner** [idno/known#2731]
## While trying to do this:

Clicking *Reply to Site* when creating a Status post.

## I encountered this error:

A javascript error when using `known.min.js`

```
ERROR: SyntaxError: missing ) after argument list known.min.js:formatted:57
    log known.min.js:57
    errorHandler known.min.js:98
    <anonymous> known.min.js:101
```

The stack trace is swallowed, but I think that's because this is coming from the onclick javascript...

When not using `known.min.js` you see incorrectly escaped text in the URL box that has a backslash  `Add the URL that you\'re replying to` as the placeholder text.

## Some other notes:

* latest github checkout.
* Appears to be in this file `IdnoPlugins/Status/templates/default/entity/Status/edit.tpl.php`

**Comment by mapkyca** [comment]
Are you using the latest versions of core and the plugins? Pretty sure I've fixed this already...

**Comment by mapkyca** [comment]
You should also make sure you've done a `composer install` after updating, as the fix was in the status plugin itself

**Comment by cdn** [comment]
> Are you using the latest versions of core and the plugins? Pretty sure I've fixed this already...

idno/status#5

**Comment by lindner** [comment]
Thanks, I'll rebuild again.  It looks like I need to star a lot more repos
now :(

**Comment by mapkyca** [comment]
Yeah, sorry! There are a lot of plugins now :)

If you're running off a git checkout, get in the habit of doing a composer update after! I'll try and make sure I tag things a little more often as well
