### ISSUE TITLE
Postgres; Patching for split metadata tables will fail on inconsistent metadata

### ISSUE THREAD

**Issue by mapkyca** [idno/known#2746]
## While trying to do this:

When running the patch script https://github.com/idno/known/blob/master/warmup/schemas/postgres/2020042101.sql introduced by 56c761b17cc6ed6f1658752424f7f6f4257e857b

## I encountered this error:

This will fail if the metadata table contains metadata that references entities that don't exist. This can happen only in cases where something has gone wrong with object deletion at some point, and so shouldn't be widespread (this issue is part of the reason why I made this patch).

However the issue was present in an old site I rolled up last night. I fixed it for mysql (c6b887f9e9da167acddfa8e2f3776a12283298a4) by temporarily disabling the foreign key checks on the upgrade script. 

A similar fix needs to be applied to Postgres. 

## Some other notes:

I don't think doing this in Postgres is quite as simple, and I believe you need to do some sleight of hand disabling triggers on tables and re-enabling them later. Not had time to dig in to it in much detail.

/cc @Lewiscowles1986

**Comment by Lewiscowles1986** [comment]
you don't need to disable foreign keys in either MySQL or Postgres. You can tell it to ignore inserting the row on error, which would result in a working schema, as if the post does not exist, it's meta should not be moved.

**Comment by Lewiscowles1986** [comment]
I'll verify the addition of some form of 

`ON CONFLICT DO NOTHING;`

**Comment by mapkyca** [comment]
I've brute forced foreign key constraints off for insertions on mysql, which seemed to work. So really it's just Postgres that's the troublesome one.

Then we can clean up later, but I may leave that as an exercise for the reader, as I don't like patch scripts deleting data

**Comment by Lewiscowles1986** [comment]
```
CREATE TABLE IF NOT EXISTS config (
  uuid varchar(255) NOT NULL,
  _id varchar(32) NOT NULL UNIQUE,
  owner varchar(255) NOT NULL,
  entity_subtype varchar(64) NOT NULL,
  created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  contents text NOT NULL,
  publish_status varchar(255) NOT NULL DEFAULT 'published',
  PRIMARY KEY (uuid)
);
CREATE INDEX IF NOT EXISTS c__id ON config (_id);
CREATE INDEX IF NOT EXISTS c_owner ON config (owner);
CREATE INDEX IF NOT EXISTS c_entity_subtype ON config (entity_subtype);
CREATE INDEX IF NOT EXISTS c_publish_status ON config (publish_status);

CREATE TABLE IF NOT EXISTS config_metadata (
  _id varchar(32) NOT NULL,
  name varchar(64) NOT NULL,
  value text NOT NULL,
  FOREIGN KEY (_id) REFERENCES config (_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS m_value ON config_metadata (value);
CREATE INDEX IF NOT EXISTS m_name ON config_metadata (name);
CREATE INDEX IF NOT EXISTS m__id ON config_metadata (_id);
```

Just removed concurrently while testing on ephemeral resource

This is my MVP for the behaviour

```
DELETE FROM config;
INSERT INTO config (uUID, _id, OWNER, entity_subtype, contents, publish_status) VALUES 
('706ce1e3-a3db-4161-b20d-ab5650ba93a6', 1, 'bob', 'post', 'yo', 'published'),
('56312787-157b-434e-8cc2-ef4db643b7f0', 2, 'bob', 'post', 'yo', 'published'),
('d787a03b-0cca-4de9-8070-4fdcc84eda77', 3, 'bob', 'post', 'yo', 'published'),
('930e182c-d319-46be-a5ff-2758d4d551a2', 3, 'bob', 'post', 'yo', 'published'),
('a3ff1031-a9a6-4cc7-ba2c-070301ffe113', 4, 'bob', 'post', 'yo', 'published'),
('d8d3951b-57ec-44d9-bde9-f03e9e174209', 5, 'bob', 'post', 'yo', 'published')
ON CONFLICT DO NOTHING;

SELECT COUNT(*) FROM config;
```

it shows 5 inserts regardless of error in the middle of results, if I change the duplicate id 3 to 7 I get 6. 

Looks like the way to go for inserting with no foreign key errors in Postgres

**Comment by Lewiscowles1986** [comment]
Luckily I tested further... Looks like that won't work...

**Comment by Lewiscowles1986** [comment]
I think you might have to drop a sub-query into the SELECT you INSERT from.

I need the config table too

**Comment by Lewiscowles1986** [comment]
```
DELETE FROM config;
INSERT INTO config (uUID, _id, OWNER, entity_subtype, contents, publish_status) VALUES 
('706ce1e3-a3db-4161-b20d-ab5650ba93a6', 1, 'bob', 'post', 'yo', 'published'),
('56312787-157b-434e-8cc2-ef4db643b7f0', 2, 'bob', 'post', 'yo', 'published'),
('d787a03b-0cca-4de9-8070-4fdcc84eda77', 3, 'bob', 'post', 'yo', 'published'),
('930e182c-d319-46be-a5ff-2758d4d551a2', 3, 'bob', 'post', 'yo', 'published'),
('a3ff1031-a9a6-4cc7-ba2c-070301ffe113', 4, 'bob', 'post', 'yo', 'published'),
('d8d3951b-57ec-44d9-bde9-f03e9e174209', 5, 'bob', 'post', 'yo', 'published')
ON CONFLICT DO NOTHING;

DELETE FROM metadata;
INSERT INTO metadata (entity,_id,collection,name,value) VALUES
('1', 1,'config','hi','there'),
('99', 99,'config', 'hi', 'there'),
('1', 1,'config', 'hi', 'there'),
('7', 7,'config', 'hi', 'there'),
('1', 1,'config', 'hi', 'there')
ON CONFLICT DO NOTHING;

DELETE FROM config_metadata;
INSERT INTO config_metadata SELECT M._id, M.name, M.value FROM metadata M LEFT JOIN config C ON C._id = M._id WHERE M.collection = 'config' AND C._id IS NOT NULL
ON CONFLICT DO NOTHING;

SELECT COUNT(*), 'config' AS "table" FROM config
UNION
SELECT COUNT(*), 'metadata' FROM metadata
UNION
SELECT COUNT(*), 'config_metadata' FROM config_metadata;
```

**Comment by Lewiscowles1986** [comment]
I'll submit a PR
