### ISSUE TITLE
Shared hosting does not allow modification of Apache

### ISSUE THREAD

**Issue by dosch** [idno/known#2764]
## While trying to do this:
I just tried installing a fresh copy of Known 1.0 on my shared hosting platform.

## I encountered this error:
```
Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to known.min.js

You can usually fix this by setting AllowOverride All in your Apache configuration.
```
## Some other notes:
As I am on a shared hosting service, I do not have access to the Apache configuration. Can I modify .htaccess in some way to circumvent this problem?
 
* contents ```version.known``` file: 
version = '1.0.0'
build = 2019102701
revision = "a8a5af7"
*  mysql database

**Comment by mapkyca** [comment]
Alas, no. For security reasons.

If you can confirm with your hosting company whether mod rewrite is present and enabled, you could try a more recent version of Known (GitHub head), as this allows you to forcibly bypass this step and proceed if the detection has failed.

**Comment by dosch** [comment]
@mapkyca I'd love to try this, but do not know where to start. As I am on shared hosting, I can't build known on the server... 

Strangely I installed Known before, and never had this problem. Did something change recently?

**Comment by mapkyca** [comment]
Well, at some point it broke, then we fixed it. Not sure what broke, but we had a workaround.

You could use one of my later unofficial builds: https://www.marcus-povey.co.uk/known

**Comment by dosch** [comment]
Great stuff! Will check it out. Also thank you for picking up this project. I hope that you and @benwerd can revive Known. 
For now I installed 0.9.9 and upgraded to 1.0; this also allowed me to bypass the apache error.

**Comment by benwerd** [comment]
I'm closing this out because a new official build is coming in Jan.

**Comment by dosch** [comment]
that sounds like a great reason to close tickets. Thnx for your work and welcome back(?) @benwerd.
Curious to see where Known is heading in the new year!
