### ISSUE TITLE
Drop down calender and time selector for events

### ISSUE THREAD

**Issue by dosch** [idno/known#2772]
I'm always frustrated when I want to to create an event, that I have to type in data and type and remember what format will parse correctly.

A clear and well designed calender-dropdown would help a lot. See image attached as a nice example from the Kimai project.

<img width="302" alt="Screenshot 2020-06-11 at 20 40 31" src="https://user-images.githubusercontent.com/5372610/84426651-dc6a2c80-ac23-11ea-8b0a-27c9362c22d6.png">

**Comment by mapkyca** [comment]
This is actually already a thing in newer builds!
