### ISSUE TITLE
upgrade to 2020042101 went wrong

### ISSUE THREAD

**Issue by danito** [idno/known#2777]
## While trying to do this:
git pull
## I encountered this error:
```
Oh no! Known experienced a problem!
Known experienced a problem with this page and couldn't continue.

Uncaught Error: Class 'Symfony\Component\Cache\Adapter\FilesystemAdapter' not found in /var/www/virtual/nxd4n/html/Idno/Caching/FilesystemCache.php:27

The technical details are as follows:

Fatal Error: /var/www/virtual/nxd4n/html/Idno/Caching/FilesystemCache.php:27 - "Uncaught Error: Class 'Symfony\Component\Cache\Adapter\FilesystemAdapter' not found in /var/www/virtual/nxd4n/html/Idno/Caching/FilesystemCache.php:27
Stack trace:
#0 /var/www/virtual/nxd4n/html/Idno/Core/Idno.php(713): Idno\Caching\FilesystemCache->__construct()
#1 /var/www/virtual/nxd4n/html/Idno/Core/Idno.php(141): Idno\Core\Idno->componentFactory(NULL, 'Idno\\Caching\\Ca...', 'Idno\\Caching\\', 'Idno\\Caching\\Fi...')
#2 /var/www/virtual/nxd4n/html/Idno/Common/Component.php(18): Idno\Core\Idno->init()
#3 /var/www/virtual/nxd4n/html/Idno/Core/Idno.php(45): Idno\Common\Component->__construct()
#4 /var/www/virtual/nxd4n/html/Idno/start.php(126): Idno\Core\Idno->__construct()
#5 /var/www/virtual/nxd4n/html/index.php(30): require_once('/var/www/virtua...')
#6 {main}
  thrown", on page nxd4n.nixekinder.be/
```
## Some other notes:
I also have a problem with warmup/schemas/mysql/2020042101.sql 
l14:
```sql
INSERT INTO `entities_metadata` SELECT `_id`, `name`, `value` FROM metadata WHERE `collection` = 'entities';
```
When I check how many entities I have:
SELECT COUNT(*) FROM metadata WHERE collection = 'entities'" 
+----------+
| COUNT(*) |
+----------+
|   177368 |
+----------+
That's a lot to copy into entities_metadata.
Which has brought down the mysql server and I got a mail from my hoster. The table has more than 127Gb of data and they had to stop the script.
Is there something I can check to purge some data?

Give us some context: 
previous version 201906050
version.known:
version = '1.2.2'
build = 2020061101

**Comment by mapkyca** [comment]
Two issues there.

First: ```composer install```

Second: Thats... a lot of data. Part of the problem this change is to address is that oftentimes the meta fields weren't being cleaned up, so now we defer integrity to the database (where it should have been in the first place). The second problem is that metadata in the single table contains values from all entity types (entities, reader and config).

You could try removing metadata that's not attached to an entity, but you need to be careful when constructing your query, as you need to make sure that it also checks that the entity isn't in config (realistically you're not going to have anything in reader).

Perhaps try running the update script line by line and see how you get on (if for example you're getting timeouts). Back up your database first!
