### ISSUE TITLE
Better UX for site user list in admin

### ISSUE THREAD

**Issue by erinjo** [idno/Known#286]
![screen shot 2014-06-03 at 11 10 27 am](https://cloud.githubusercontent.com/assets/1192220/3164478/7a84e578-eb4a-11e3-83ff-44a0a4a725cc.png)

We're going to need a better solution in the future that makes users more visible/removes the in-box scrolling that Ben hates. :-)

This is mostly a note for me as a reminder to come back to this.

**Comment by benwerd** [comment]
Closing this - I think the admin view is okay, ish, but there is a need for user directory.
