### ISSUE TITLE
Upgraded to 1.2.2 package, and have issues displaying all content on some pages.

### ISSUE THREAD

**Issue by voss** [idno/Known#2864]
## While trying to do this:

Viewing "all content" category on the site:
![image](https://user-images.githubusercontent.com/10601/103779234-5e3ffe00-502b-11eb-9ff0-6599ebb62db9.png)

## I encountered this error:

Content is loaded but without all the necessary information to display it. Looking at view source, it looks like none of the boilerplate is loaded (menu and footers), and this also leaves out the CSS on the page. The page content also cuts off in the middle of a script.

The loaded page starts with
```
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">

        <h1Notifications</h1>
        <p class="explanation">
            The notifications screen shows you who has interacted with your content.        </p>

    </div>
</div>
```
There's no content before that.

The last two line of the page source are these:

`<script>
    var known = {"ses`

The same happens on the admin/notification section. It can be seen here: https://blog.voss.co/content/all/

The page title in the tab when loading the notifications page is displayed as "Exception".

Other pages work fine, and if I search for something, content displays fine.

## Some other notes:

Give us some context: 

* I updated from 0.9.9.a by doing a clean install with the latest package from Marcus Povey, and afterwards moving the plugins from the previous install into `IdnoPlugins`, making sure I only added Plugins that didn't come with the clean install.

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

version = '1.2.2'
build = 2020061101
revision = "bd43456"

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

* Any warnings or errors in your admin/diagnostics page?

No errors or warnings on diagnostics page. It only tells me that the version on git is never than the one I've installed. The server is running PHP 7.2.34

The apache error logs gives me errors like this:

`[Wed Jan 06 06:39:56.588926 2021] [fcgid:warn] [pid 6328:tid 3882434553600] [client REDACTED:36195] mod_fcgid: stderr: in.php","line":11,"function":"addPageHandler","class":"Idno\\\\Core\\\\Idno","type":"->","args":["/listen/([A-Za-z0-9]+)/.*","\\\\Idno\\\\Pages\\\\Entity\\\\View"]},{"file":"/html/public/Idno/Common/Component.php","line":20,"function":"registerPages","class":"IdnoPlugins\\\\Listen\\\\Main","type":"->","args":[]},{"file":"/html/public/Idno/Core/Plugins.php","line":55,"function":"__construct","class":"Idno\\\\Common\\\\Component","type":"->","args":[]}]`

**Comment by mapkyca** [comment]
Not sure what `Listen` is, but looks like it needs to have its urls adjusted for the new UUID format.

**Comment by benwerd** [comment]
@voss Hi! It looks like `Listen` was updated to use the new ID format - or at least, your site is working. Can we close this?

**Comment by voss** [comment]
<a href="https://github.com/idno/known/issues/2864" class="u-in-reply-to"></a>Hi @benwerd and @mapkyca, thanks for your replies, apologies for not having chimed in here for a while. I don't know what happened, but it looks like things are working again. I didn't touch anything as I haven't had time, so either this was just a cache issue on my end, or I was being an idiot (or both!). Thanks for taking a look!

**Comment by benwerd** [comment]
I promise you weren't being an idiot! I'm just glad to see it's working. Consequently, closing this thread.
