### ISSUE TITLE
webmentions: URL fragments seem to break post type detection

### ISSUE THREAD

**Issue by snarfed** [idno/Known#2878]
Hi all! Noticed a minor bug while welcome @benwerd back to werd.io. 😁  Hope this helps!

## While trying to do this:

Send a webmention to a Known URL with a fragment, eg `#comments`.

## I encountered this error:

Post type detection fails and the webmention is interpreted as a plain mention instead of its actual type.

## Some other notes:

Here are some examples on werd.io. First, a couple `u-like-of`s to post URLs without fragments. These were interpred fine.
* https://snarfed.org/2021-02-01_im-going-to-resume-posting-status-updates
* https://snarfed.org/2021-02-01_this-site-is-now-running-the-latest

And a couple `u-like-of`s to post URLs with `#coments` on the end. These got interpreted as mentions.
* https://snarfed.org/2021-02-01_ive-grown-to-really-dislike-knowns-filter
* https://snarfed.org/2021-02-01_my-medium-experiment

**Comment by snarfed** [comment]
#172 is slightly related, but that was a long time ago, so 🤷

**Comment by benwerd** [comment]
Thanks @snarfed! I see what's going on here. Going to take a look.
