### ISSUE TITLE
Tests fail locally for me

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2893]
## While trying to do this:

Run local unit tests using PHPUnit 9.5.2.

## I encountered this error:

8 of them, actually! I'm not sure why these are failing locally for me yet (partially because tests don't have English descriptions per #2886).

```
There were 8 failures:

1) Tests\API\BasicAPITest::testConnection
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/API/BasicAPITest.php:24

2) Tests\API\BasicAPITest::testAuthenticated
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/API/BasicAPITest.php:46

3) Tests\API\UploadTest::testUpload
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/API/UploadTest.php:32

4) Tests\Core\GatekeeperTest::testGatekeeper
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/Core/GatekeeperTest.php:17

5) Tests\Core\GatekeeperTest::testAdminGatekeeper
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/Core/GatekeeperTest.php:41

6) Tests\Core\PermalinkStructureTest::testPermalinks
Failed asserting that false is not false.

/Users/ben/Sites/known/public/Tests/Core/PermalinkStructureTest.php:34

7) Tests\Pages\HomepageTest::testHomepageLoads
Failed asserting that a boolean is not empty.

/Users/ben/Sites/known/public/Tests/Pages/HomepageTest.php:18

8) Tests\Pages\RSSTest::testValid
Failed asserting that false is true.

/Users/ben/Sites/known/public/Tests/Pages/RSSTest.php:24
```

## Some other notes:

This test run is on the very latest dev code as of the time of posting.

**Comment by mapkyca** [comment]
You on localhost? What port? Have you set `KNOWN_DOMAIN`?

**Comment by mapkyca** [comment]
Basically, they're all network tests - so the test probably isn't able to talk to your Known install. Assumes "localhost" on port 80 - if it's not that you'll need to set `KNOWN_DOMAIN`

**Comment by benwerd** [comment]
Figured it out: it's not picking up configuration, so `\Idno\Core\Idno::site()->config()->url` (which should probably be `\Idno\Core\Idno::site()->config()->getDisplayURL()`) is blank.

I missed that I needed to set a `KNOWN_DOMAIN` environment variable. I think that requires a test of its own, which I'll write right now.

**Comment by mapkyca** [comment]
Only needs `KNOWN_DOMAIN` if you're running tests outside of the defaults.

**Comment by benwerd** [comment]
Yep. Just need to help people realize that's the case. PR with descriptive test messages to follow.
