### ISSUE TITLE
Known is encoding HTML tags when posting via micropub

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#2910]
## While trying to do this:

Post using curl via micropub, where `content` contains `<p>Some text.</p><p>Some more text</p>`

## I encountered this error:

Text is rendered with encoded tags.

## Some other notes:

I'm not sure whether this is related to https://github.com/idno/known/issues/1519 but it seems to be. 

Give us some context: 

I am creating the `$body` to curl by parsing an RSS feed. Is there a way to set something in the curl that would tell Known **not** to encode HTML?

Alternatively, where would I change the `strip_tags` function that is acting on `$body` to permit `<a>` and `<p>`, which are the only tags I am interested in?

**Comment by benwerd** [comment]
This was fixed in the latest version of the status plugin.
