### ISSUE TITLE
Question: Is SQLite still officially supported?

### ISSUE THREAD

**Issue by nanawel** [idno/Known#2961]
Hi,

I can read in the documentation that this support seems to be up-to-date: http://docs.withknown.com/en/latest/install/instructions/#if-youre-using-sqlite

But trying to use it fails miserably, and I see in some old issues (c.f. #2367) indicating that SQLite has long been dropped.

What should I believe? I'd be glad to be able to use Known without any separated database server, so I'm looking forward to the answer.

Thanks in advance

**Comment by Cambridgeport90** [comment]
I think they switched it for another database server, though I can't be sure. I think it was MongoDB at one point that SQLite got replaced with. I could be wrong on that, however.

From: Anaël Ollier ***@***.***>
Sent: Tuesday, June 15, 2021 7:56 AM
To: idno/known ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [idno/known] Question: Is SQLite still officially supported? (#2961)


Hi,

I can read in the documentation that this support seems to be up-to-date: http://docs.withknown.com/en/latest/install/instructions/#if-youre-using-sqlite<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdocs.withknown.com%2Fen%2Flatest%2Finstall%2Finstructions%2F%23if-youre-using-sqlite&data=04%7C01%7C%7C45dc622737a34058a2e108d92ff48306%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637593549473590315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mgZ19tohLW2pU7Y9y9v2%2Bp3tv0f1vjsPhzc6ZtiNUcw%3D&reserved=0>

But trying to use it fails miserably, and I see in some old issues (c.f. #2367<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidno%2Fknown%2Fissues%2F2367&data=04%7C01%7C%7C45dc622737a34058a2e108d92ff48306%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637593549473590315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RiIEmwPQvsI7N%2BeLHkC5FEUEAvIDa0GcSCDvStBtTV8%3D&reserved=0>) indicating that SQLite has long been dropped.

What should I believe? I'd be glad to be able to use Known without any separated database server, so I'm looking forward to the answer.

Thanks in advance

-

**Comment by mapkyca** [comment]
SQLite is not currently supported and I've had absolutely no time to maintain it in order to keep it up with the core changes. So few people were using (afaik 0 people) it that it didn't seem worth it

**Comment by Cambridgeport90** [comment]
I have to agree with you... Known seems too big a project to warrant such a flat file for the database. Even if it were still out there, I would never use SQLite.

**Comment by nanawel** [comment]
Thanks for your quick answer.
I came accross Known searching for a robust and evolutive blog engine but that could run with SQLite. I've made my choice a bit too quickly I guess ^^

Regards
