### ISSUE TITLE
MySQL Schema - Where is it?

### ISSUE THREAD

**Issue by teamayu** [idno/Known#3002]
In your documentation instructions for installation it says:

"For now, you will need to load the SQL schema stored in /schemas/mysql/mysql.sql."

Where is this mysterious 'schemas' directory? 

Thank you.

**Comment by cdn** [comment]
https://github.com/idno/known/tree/dev/warmup, so; `/warmup/schemas/mysql/mysql.sql`

**Comment by teamayu** [comment]
Ah, got it. It's in the warmup folder. You might want to update the docs, thank you.

**Comment by benwerd** [comment]
Fixed the instructions. Sorry for the confusion and thanks for the heads up!
