### ISSUE TITLE
Unable to pull latest dev branch from github

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#3088]
## While trying to do this:

`git pull`

## I encountered this error:

```
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

## Some other notes:

Give us some context: 

`git status` shows several modified files and somewhat fewer untracked files.

`.git/config` contains:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/idno/Known.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

```
version = '1.2.2'
build = 2020061101
revision = "bd43456"
```

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

* Any warnings or errors in your admin/diagnostics page?

The Diagnostics page tells me I am behind, but the Update now link only takes me to the repo on github; it does not actually do anything to update the version.

* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by lindner** [comment]
The branch name switched to the more respectful 'dev'  (although github
seems to have standardized on 'main' instead, shrug...)

**Comment by jeremycherfas** [comment]
Is the solution to edit config to say dev instead of master?

**Comment by lindner** [comment]
I think you can add a new remote branch for dev and rebase your existing
branch from master to dev.

git remote add ....
git rebase ...

**Comment by jeremycherfas** [comment]
Done, which got me to
```
version = '1.3.1'
build = 2020120201
```
byut which introduced an entirely new (to me) error.
