### ISSUE TITLE
Wrong version number in tagged release

### ISSUE THREAD

**Issue by voss** [idno/Known#3149]
When downloading the tagged 1.5 release, both the tar.gz and the zip-file, `version.known` contains:

```
version = '1.3.1'
build = 2020120201
```
I assume that's an oversight, and that the tagged 1.5 release is 1.5?

Is it safe to change that information in the file, to reflect the correct version?

**Comment by benwerd** [comment]
Good spot! Yes, it’s safe to change. We’ll put out a minor update to fix.

Ben Werdmuller
( http://goog_1933028737 )
werd.io ( http://werd.io )

I write a newsletter about technology, media, and society. Subscribe here. ( https://newsletter.werd.io )
