### ISSUE TITLE
search query retained in content type navigation

### ISSUE THREAD

**Issue by beck24** [idno/Known#316]
Perform a search, then the content type dropdown navigation has the search parameter as part of each url.
I'm not sure if this is the expected behaviour (I didn't expect it).
To navigate to a full content type listing then I guess I have to route back through the home page, or perform an empty search.  Neither seems terribly intuitive.

**Comment by benwerd** [comment]
This was on purpose (sorry for the 13 month wait for a reply!). I definitely think there should be a discussion about how best to do this, but I'm closing this specific issue for now.
