### ISSUE TITLE
Rework interactions for hearts/faves and comments

### ISSUE THREAD

**Issue by erinjo** [idno/Known#325]
When a user clicks the fave link for a post from the stream, they automatically fave the content, while some people might just click the link to see the faves/hears - just as you would click the comment link to see the comments.

Interactions need to be clear so that users understand when they're clicking to view vs clicking to endorse.
##

**Comment by benwerd** [comment]
We've done some tweaking of this since the ticket, but it would be good to make this more seamless.

My opinion: it's a Javascript callback that toggles the heart. Make it simple.
