### ISSUE TITLE
Sub directory test is broken 

### ISSUE THREAD

**Issue by ipranjal** [idno/Known#3263]
## While trying to do this:
while I am trying to on onboard and on /begin/register/?

## I encountered this error:
There is no content being displayed

## Some other notes:
I am not using a subdirectory but the subdirectory recognises "begin" as a folder in my path it thinks that I am on a subdirectory name "begin" that makes my router thinks path "/begin/begin/register/?" as the url to match with

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by ipranjal** [comment]
commenting out subdirectory check fixes it , I would suggest let users manually set KNOWN_SUBDIRECTORY and we should stop guessing it !

**Comment by benwerd** [comment]
It's honestly amazing to me that Known supports subdirectory use. That seemed reasonable in 2013; much less so now. Let's discontinue that.
