### ISSUE TITLE
Edit title on favorite plugin

### ISSUE THREAD

**Issue by erinjo** [idno/Known#341]
![screen shot 2014-06-19 at 10 58 36 am](https://cloud.githubusercontent.com/assets/1192220/3331310/68202d1e-f7db-11e3-9be1-d3992ac6061f.png)

It's nice that it's grabbed the page title, but since this page title is less than useful, I'd love to be able to edit it.  
I'd also love to be able to add tags.

**Comment by benwerd** [comment]
Yay, it does this now!
