### ISSUE TITLE
Shorter URLs for "reply to" updates?

### ISSUE THREAD

**Issue by erinjo** [idno/Known#342]
Not a pressing issue, but is there a way to drop some of the a-href-classu-in-reply-to stuff urls when they're replies?

Example: http://amblin.io/2014/a-href-classu-in-reply-toaa-href2014congrats-on-setting-up-the-site-let-us-know-if-classu-in-reply-toalove-the-simplicity-and-cant-wait

Could be nice to have something shorter like: http://amblin.io/2014/reply-love-the-simplicity-and-cant-wait

**Comment by benwerd** [comment]
Yes ;)
