### ISSUE TITLE
Make database _id generation pluggable #suggestion

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#372]
Mongo has its own _id generation which is probably fine since the backend is supposedly scalable, however mysql currently generates _ids as md5(rand(0,9999) .time()) which doesn't have a very large amount of entropy for busy environments, and when you're scaling to multiple servers you're probably going to run into trouble.

A suggestion would be to make ID in this instance the result of a trigger_event, setting the default to be the above (see defaults for events from PR #237 238c47a0875a1f29f3ff29ea7bddaa76399080a5, which would be really cool to have merged). That way when you do reach that point you could drop in a plugin that calls snowflake or something similar.

Maybe not a *now* thing, but just a suggestion :)

**Comment by benwerd** [comment]
I'm inclined to keep IDs in core. Which isn't to say that we shouldn't improve how they're generated.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/372#event-530874297" class="u-in-reply-to"></a>With this suggestion the ID would still be core (just the ID function's output would be default), but you're right.. not a priority for now!
