### ISSUE TITLE
Markdown Extra - Parsedown Extra as parser?

### ISSUE THREAD

**Issue by petermolnar** [idno/Known#387]
I've tried the Markdown parser in Known with some specific/edge case scenarios; unfortunately it resulted in a pretty bad experience:
compare [the Known version](http://known.petermolnar.eu/2014/trimming-the-fat-tha-big-bad-cleanup-of-my-wordpress) with the [original post](https://petermolnar.eu/linux-tech-coding/wordpress-cleanup-markdown-import-twitter-import-facebook/). The Known version is a copy past of the original's Markdown.

At the original, I use [Parsedown Extra](http://www.parsedown.org/demo?extra=1) which solved things like definiton lists, code blocks ( and all the other Github elements ) and I believe Known would benefit from using it as it's parser.

I'll try to look into adding it myself but I'm very unfamiliar with the Known codebase so far.

**Comment by mapkyca** [comment]
Closing
