### ISSUE TITLE
Firefox plugin stopped working

### ISSUE THREAD

**Issue by hugoroy** [idno/Known#389]
It has been like this for some time now. It worked before but now when I click the Firefox enveloppe-arow I get:

"Firefox ne peut actuellement pas se connecter avec The deck."

(Firefox can't currently connect to my idno instance)

**Comment by benwerd** [comment]
Bumping. We're on it.

**Comment by hugoroy** [comment]
After the domain change, I disabled the old one, enabled the new one. It works now.
