### ISSUE TITLE
Issues with WYSIWYG

### ISSUE THREAD

**Issue by erinjo** [idno/Known#395]
From Lauren: while testing out the options in the post, Bold was working. She selected a word, hit the bold option, and it wasn't changing. Italics and underline didn't work. Strikethrough worked sometimes but didn't work once.  Eventually the bold option did "get unstuck."

Browser was Firefox. I haven't been able to replicate on my local version.

**Comment by benwerd** [comment]
WYSIWYG is now switched to the far more stable TinyMCE.
