### ISSUE TITLE
Post Check-Ins and Events directly to Twitter and Facebook.

### ISSUE THREAD

**Issue by schiesbn** [idno/Known#404]
Just an idea, maybe you want to pick it up. I think it would be great if I could also send Check-Ins, Events and Links directly to Facebook and Twitter. I don't see a reasons why they should be excluded from it. Maybe there are already plans to add it?

**Comment by pierreozoux** [comment]
:+1:

**Comment by pierreozoux** [comment]
As facebook and twitter are now different projects, I opened issues on respective project. We can close this one.
