### ISSUE TITLE
no rel="me" links on homepage mean known can't be used for indieauth

### ISSUE THREAD

**Issue by kevinmarks** [idno/Known#408]
eg andrewmarks.media should have the profile view 
http://www.andrewmarks.media/profile/andrewmarks on the homepage if there is a single author.

cf 
http://indiewebify.me/validate-rel-me/?url=http%3A%2F%2Fwww.andrewmarks.media%2F

and 
http://indiewebify.me/validate-rel-me/?url=http%3A%2F%2Fwww.andrewmarks.media%2Fprofile%2Fandrewmarks

**Comment by physcocode** [comment]
I tried Solo theme + Indiepub plugin still ended up having no rel=me + cant even login with my domain !

**Comment by kylewm** [comment]
@physocode what domain is that? http://pranjal.mysmiff.com  says "coming soon"

**Comment by benwerd** [comment]
All the individual themes support rel=me authentication. But you need to
specify at least one social profile (eg, a Twitter or a GitHub account).

On Tue, May 19, 2015 at 8:24 AM, Kyle Mahan <notifications@github.com>
wrote:

> @physocode what domain is that? http://pranjal.mysmiff.com says "coming
> soon"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/408#issuecomment-103548828>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by physcocode** [comment]
@kylewm the domain is pranjalp.com 
@benwerd I have alredy specified both twitter and github profile in my stream . Ill attach a screenshot !

**Comment by physcocode** [comment]
OK so i forgot updating my github and twitter profile with my latest domain pranjalp.com . This is now working as it should be ! Bravo !

**Comment by physcocode** [comment]
I think this issue should be closed
