### ISSUE TITLE
SSL browser warning with commenter images

### ISSUE THREAD

**Issue by elliottucker** [idno/Known#420]
Commenter avatar images appearing on an SSL secured site that link back to a non SSL site will cause browser warnings, i.e, you url ssl lock isn't green.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/420" class="u-in-reply-to"></a>Should be closed. /cc @benwerd

**Comment by mapkyca** [comment]
Bump @benwerd
