### ISSUE TITLE
Create curation / hootsuite style methodologies for tapping multiple plugin accts / services

### ISSUE THREAD

**Issue by HongPong** [idno/Known#441]
Here is a feature request/idea. If we can have a workflow available in this which allows different individual twitter (or other provider) accounts to be distributed / activated from different Known accounts this would make Known able to work as a very powerful syndicator. I'm thinking of a many-to-many relationship. Basically to make it so that twitter credentials can be handed around between different Known accounts, reusing their Oauth token. (this could apply to other plugins/services, but twitter is a good example to start with).  OR trigger retweets inside the A twitter.

Main feature: Such as:

"Known Account A" is a main group account. It is linked to its big Twitter acct, Facebook page via plugins. 

"Known Account B" is a subgroup. We want to have new material attributed to the subgroup (i.e. a media working group with its own brand, its own FB page, its own twitter).

It would be optimal to have Known Account A provide the permission for B to originate fresh tweets at will.

Interface would be similar to hootsuite. At post time, Acct B could see buttons "Twitter: AcctA", "Twitter: AcctB", "Facebook: AcctA" buttons.

Secondary feature: Syndicate / shared retweet powers:

It would be optimal for Known Account A to fire retweets at the leisure of Known Account B, Account C and D's individual twitters. 

Interface for Acct B could be "Retweet this item from: AcctA, AcctC, AcctD" buttons.

In hootsuite you can create a tweet from account A, then hit retweet for B C and D, and you kickstart a viral snowball efficiently.  Replicating this workflow would create a platform with very powerful abilities to amplify across 100,000 scale social media assets in a way that definitely works well for virality.

Third idea: Possibly also curated tags / topic pages, wherein certain blessed multiple accounts are the ones that can attach a post to that tag, with the tag owned administratively by an account or 2, would allow good curated channels that are accountable and have a good curated information structure to them.

Fourth idea: one-to-many relationship with plugin accts like twitter. Attach 5 twitter accts to one Known acct and include a mechanism to fire retweets from the parent tweet that is directly associated to the post.

Thanks for considering these ideas, I realize you guys have many things on your plate but we may be able to rally some PHP devs to pitch in :) Great work keep it up!!

**Comment by kylewm** [comment]
multiple syndication accounts landed in https://github.com/idno/Known/commit/a214edba3f10b6b0aa64e7f3c41fb26329f3136e (Nov 18, 2014) and has continued to be improved since then. surely there are more ideas in the original post (e.g. one account tweets, the other four accounts retweet, etc.) but I think the spirit of the request is satisfied :)
