### ISSUE TITLE
dotted field names cause comments to fail with newer versions of mongodb

### ISSUE THREAD

**Issue by finalcut** [idno/Known#447]
I have a self hosted copy of known and just attempted to write a comment to my own status update to test things out and received this error when Known tried to save the comment:

> Ooops! MongoWriteConcernException
> localhost:27017: The dotted field 'http://rawlinson.us/2014/finalcut-i-think-this-form-of-reply-might-work-i/annotations/7a643cb8859a68f18c9be85a208d9be6' in 'annotations.reply.http://rawlinson.us/2014/finalcut-i-think-this-form-of-reply-might-work-i/annotations/7a643cb8859a68f18c9be85a208d9be6' is not valid for storage.

**Comment by finalcut** [comment]
Just an update that this is still not working.  I just recieved this error when trying to leave a comment on my own link - note I do not have public comments turned on.

```
localhost:27017: The dotted field 'http://rawlinson.us/2015/are-all-terrorists-muslims-its-not-even-close-1xrt806/annotations/a6c13299574ef36b0f97b36160c35684' in 'annotations.reply.http://rawlinson.us/2015/are-all-terrorists-muslims-its-not-even-close-1xrt806/annotations/a6c13299574ef36b0f97b36160c35684' is not valid for storage.
```

**Comment by finalcut** [comment]
I'm bumping this because it's still broken with the same error message.

I'm using self-hosted known 0.7.8.5.1  (I did a git pull just this morning on master)

**Comment by kylewm** [comment]
For anyone else trying to reproduce this issue, this affects versions of Mongo 2.6+. (Ubuntu 14.04 has a very old version, I just discovered)

**Comment by kylewm** [comment]
Did a little bit of research, this looks annoying to fix in a general way. [Mongo documentation recommends](http://docs.mongodb.org/manual/faq/developers/#faq-dollar-sign-escaping) replacing $ and . with their Unicode full-length equivalent (U+FF04 and U+FF0E).

This seems like it could be a bit of a debugging nightmare. e.g. if you search for "foo.bar" and it doesn't find "foo\uff0ebar"... ~'s as @finalcut suggested above would probably be better provided the key is only used for querying and doesn't need to be totally lossless.

**Comment by misuba** [comment]
I've just hacked @finalcut's fix in here, with an if clause around it that special-cases it to Mongo. This required me to save the unmodified URL and pass it in as the annotation's permalink... which in turn meant I had to modify the default annotations/replies template to pass the permalink down into the edit template... which still didn't make the Delete links on comments work.

And nevermind the mess this could make for some export/import processes down the line. But comments can now happen, and for my purposes at least, it's easy enough to delete things from the Mongo shell if it comes to that. I can post a gist if people want.

I still haven't verified that brid.gy will do its thing, but I expect it will.

**Comment by finalcut** [comment]
I'm a little disappointed that this still doesn't work. In Sep 2014 you said you had a plan to fix it.  Is this fix being planned at all?

**Comment by kylewm** [comment]
Thanks for bumping this issue. Let's fix it.

I still really don't like the idea of replacing with Unicode full width '.' and '$' characters. I'd suggest doing something where if it breaks, it'll be really obvious that it's broken. How about substituting with `&period;` and `&dollar;`

If we convert `.` => `&period;` and $ => `&dollar;` on insert, and in `query_params`, and convert back in results, it should Just Work&trade;. I'll give it a shot this morning.

**Comment by billrawlinson** [comment]
I know that Ben mentioned the replacement stuff broke things for people on
MySQL, and you're probably already aware of this, but the replacement
should only happen if the user is using Mongodb.

William Rawlinson / Staff Engineer
304-521-1171/ bill.rawlinson@sbcs.com

Strictly Business Computer Systems
http://www.sbcs.com

**Comment by kylewm** [comment]
Occurs to me that URL %-encoding makes more sense than HTML &-encoding

**Comment by kylewm** [comment]
Escaping the queries is probably too difficult for now. If there were a query like

```php
array('annotations' => array(
    'like' => array(
        'http://kylewm.com/2016/the-slug' => array(
            '$elemMatch' => array(
                'date' => array(
                    '$gt' => '2016-02-03 11:06'
                )))))
```

it's not obvious which fields to encode and which to leave as is. But this is purely hypothetical/not something that happens in the code, so I will just leave queries alone with a TODO for now.
