### ISSUE TITLE
Installer defaults to MySql if both mysql and mongo extensions are installed

### ISSUE THREAD

**Issue by finalcut** [idno/Known#448]
While installing the self hosted version of Known the installer insisted on using MySQL even though I had mongo installed also.  

In order to force Known to use mongo I had to create a config.ini that contained the default mongo setup that was implied in the [documentation](http://docs.withknown.com/en/latest/install/instructions.html):

```
dbstring=mongodb://localhost
dbname=Known
```

**Comment by benwerd** [comment]
We're not going to fix this - MongoDB installations require a lot more technical skill, and for this and a number of reasons, we're going to continue to require that these are run manually.

**Comment by finalcut** [comment]
I would suggest then that you make this caveat clear in the documentation.
