### ISSUE TITLE
Disconnect and re-connect social media account

### ISSUE THREAD

**Issue by yafflepaws** [idno/Known#449]
Hi,

I just tried out the hosted beta and came to a point where I needed to disconnect the Twitter and Facebook accounts I'd linked (personal ones to test it worked) and re-connect to corporate ones for actual usage.

I didn't see an option to do this via the Settings interface. Did I miss it?

Thanks,
Patrick

**Comment by physcocode** [comment]
outdated

**Comment by benwerd** [comment]
Closing this - the interface lets you click on an account to remove it.
