### ISSUE TITLE
Editor: images

### ISSUE THREAD

**Issue by patrickpawsey** [idno/Known#450]
Hi,

Using the editor to write posts for a site on the hosted beta, I noticed that:

1) There's no upload progress as an image is uploaded, which is a bit of a surprise as it doesn't feedback that it's uploading till it pops up!

2) You can't resize the editor window (I know you can full-screen but sometimes you want to make it bigger but not so big) which also relates to..

3) Large images at the bottom of the post can go off the screen and thus lose their resize handle!

4) It would be great to have options to set padding on the image in the editor (I guess you can set inline styles via the code view but for 'normal' users some more controls would be great)

I realise these are largely to do with Summernote Editor but they were my first impressions having used to do 'live' blogging.

Amazing platform so far - thanks!

Patrick

**Comment by benwerd** [comment]
We've completely changed our editor, which is now more stable for both images and embeds. Thanks!
