### ISSUE TITLE
Plugins for free and federated networks

### ISSUE THREAD

**Issue by schiesbn** [idno/Known#459]
Currently Known provides plugins for many proprietary and centralized networks (facebook, twitter, fouresquare,...). Would be great if you would also provide plugins to share content and free and decentralized networks, such as:

- GNU Social (formally Status.Net / Identi.ca)
- Pump.io
- Diaspora
- Friendica
- ....

**Comment by Phyks** [comment]
I had a look at Diaspora, and they have no working API at the moment… Which is kind of problematic… The only way I found is https://github.com/cocreature/diaspy which is unofficial and does not seem to be a nice and stable solution…

**Comment by Phyks** [comment]
FWIW, I made some progress towards Diaspora cross-posting. The plugin is still under WIP (status updates working right now) and is available here: https://github.com/Phyks/knowndiaspora.

This is not really resilient right now, and it will raise exceptions and so on invalid credentials. :/

**Comment by Phyks** [comment]
Actually, I should support all the content types supported right now. It might not be fully user-friendly (might be some unwanted exceptions raised on edge cases such as invalid credentials) but it should do it.

@benwerd Is there a way to run a command on plugin deletion? I mean, is there a way to delete the user credentials from the settings after plugin deletion? Or is is handled automatically by Known? Thanks

**Comment by benwerd** [comment]
There isn't and should be.

**Comment by benwerd** [comment]
We're probably not going to be able to add these ourselves as a project, but we'd love to continue to help people to build them.
