### ISSUE TITLE
feature: Bookmark - show url

### ISSUE THREAD

**Issue by hugoroy** [idno/Known#462]
I think it would be nice to show the URL of the page that's bookmarked, or at least some indication about the domain name (a bit like hacker news).

For instance see: http://fslegal.withknown.com/2014/patent201409finding-limits-ineligibilityhtml where it is not obvious at all that this is a bookmark (although this also has to do with the theme choice of colors itself)

**Comment by mapkyca** [comment]
Closing in favour of #1110
