### ISSUE TITLE
Implement measures against being used as a DDOS vector

### ISSUE THREAD

**Issue by barnabywalters** [idno/Known#463]
<small>(is vector the right word? It sounds good and securityish)</small>

As per http://indiewebcamp.com/DDOS#Webmention, any sites supporting webmention can potentially be used as part of a DDOS unless measures such as request validation, expiring endpoints or hashcash are put in place to prevent it.

Although this attack hasn’t been deployed against webmention so far, Known potentially is more appealing as there are now many webmention-supporting sites with the exact same URL structure, so it might be worth putting some measures in place to prevent this from happening.

**Comment by mapkyca** [comment]
Closing, as a dupe of #432
