### ISSUE TITLE
Share buttons not appearing on Samsung Note

### ISSUE THREAD

**Issue by erinjo** [idno/Known#479]
A user reported that the social share buttons aren't appearing in Chrome on a Samsung Note3 but are appearing in the stock Note3 browser.

I tested a Samsung Galaxy Note 10.1with the stock browser that loads in BrowserStack and the share buttons also did not appear there.

**Comment by mapkyca** [comment]
Old ticket, still an issue?

**Comment by mapkyca** [comment]
~~spring~~ winter cleaning. Closing for now...
