### ISSUE TITLE
Make Export (and future import) scripts executable from command line

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#488]
Reason: set_time_limit(0) will not be enough for large sites, as you're going to hit the apache execution limit which can't be changed. 
##

**Comment by benwerd** [comment]
We have a CLI interface now. Would be interesting to think about in that context.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/488#issuecomment-57281943" class="u-in-reply-to"></a>Haven't looked at CLI (but will do when I get the chance), but the biggest problems I've seen so far is the general assumptions Known has that it's web based - referencing $_SERVER variables etc. Not sure if this is still a thing on CLI, but worth mentioning...

**Comment by mapkyca** [comment]
Possible now, not built. Closing

**Comment by johanbove** [comment]
@mapkyca Since @jgmac1106 recently lost the data of his sons Known site; how would a Known site admin run the CLI tools to set up a regular backup schedule? Can the /admin/export action be automated?

**Comment by mapkyca** [comment]
I'm sorry to hear that, are you sure that he's lost everything? No backups?

Native import/export is not bulletproof and I've just had no time (and nobody has been prepared to pay for it, so it clearly wasn't a priority) to look into it.

Assuming you're on mysql, I'd use mysqldump to dump the database and then copy the upload directory. Everything else can be replaced.

**Comment by lindner** [comment]
I believe you can run:

  php known.php export

and it will create /tmp/export.zip for you.

**Comment by mapkyca** [comment]
Yep, export works great. The import however....

Needs work to do the full loop.
