### ISSUE TITLE
Documentation - installation instructions need to reflect renaming .htaccess and creating config.ini

### ISSUE THREAD

**Issue by danyork** [idno/Known#496]
When I finished the `/warmup/settings.php` I was greeted with

----

Saving the configuration file
You're almost there! Unfortunately, Known couldn't save the configuration file. This is common: it usually means your server is more secure!

To continue:

Rename the file called htaccess.dist at the root of your Known installation to .htaccess.
Create a new file called config.ini at the root of your Known installation, with the following contents.
Once you've saved it, just reload this page to continue.

----

The installation instructions should reflect that these changes might need to be made.

**Comment by physcocode** [comment]
this has been fixed in the latest installation process !
