### ISSUE TITLE
"Stars" link does nothing

### ISSUE THREAD

**Issue by dougmckown** [idno/Known#500]
The item at the bottom of a post (next to "Comments") labeled "Stars" does nothing when clicked (it appears to be linked to the same thing that "Comments" is linked to.)

0.6.3/self-hosted

**Comment by Phyks** [comment]
:+1:

But then, what is the correct way to "star" an article ? I wanted to "star" [this article](http://known.cphyc.me/2015/i-just-installed-known-on-my-website-now-cross-posting-on#comments) for instance, and did not manage to star it. The way I understood the UI, I tried commenting on it, but I had to post a text with it, and did not result in a "star" / "like" at all =(

Thanks

**Comment by kylewm** [comment]
Nowadays clicking the star icon itself creates a (local) like; clicking the "n stars" text opens the `#comments` section of the post. I think this is fairly intuitive.

If we want to talk about cross-site liking and commenting, let's track that in #723
