### ISSUE TITLE
Quill can't find syndication links

### ISSUE THREAD

**Issue by jonpincus** [idno/Known#519]
When posting to a known site, Quill can't find any syndication links.  The message:

No syndication targets were found on your site. You can provide a list of supported syndication targets that will appear as checkboxes here.

According to https://quill.p3k.io/docs#syndication :

Your Micropub endpoint will need to respond to a GET request containing a query string of q=syndicate-to. This request will be made with the access token that was generated for this app, so you can choose which syndication targets you want to allow this app to use.

**Comment by kylewm** [comment]
I'm interested in trying to fix this. There's [some code](https://github.com/idno/Known/commit/6405fbbb71ecaa255b7a6b2934cbc9f470500abb#L28) that looks like it should get a list of endpoints but it's always empty for me (self-hosted or *.withknown.com). Will keep digging.

**Comment by kylewm** [comment]
Best guess: syndication plugins register services (`Syndication::registerServiceAccount`) based on the current user during initialization, but for micropub requests there is no current user.

Micropub/Endpoint calls `Session::refreshSessionUser` to log the user based on an access token, but that happens way after all the plugins have been initialized.

I can think of a few approaches, all pretty bad:

1. Log a user in via micropub access token earlier in the initialization procedure, before any plugins are initialized. Would require micropub code outside of a plugin. :-1:
2. Syndication plugins all listen for user/auth event and re-registerServiceAccounts in response. Requires a change to every syndication plugin :unamused:
3. Micropub dumps and reloads plugins. Doesn't seem feasible; in particular I don't think there is a mechanism for destructing a plugin and deregistering its event hooks and such :-1:

**Comment by kylewm** [comment]
hmm, and Convoy doesn't register service accounts locally at all. maybe that's a clue...

**Comment by benwerd** [comment]
That's definitely a clue. But even with local accounts, the micropub implementation probably won't support syndication, in part due to a variable conflict. I think we should be able to expose accounts from Convoy though.

**Comment by kylewm** [comment]
> the micropub implementation probably won't support syndication

like it won't right now, or it won't ever? If the latter, I'm a little confused because it seems like syndication should be possible using the same hook the native UI triggers.

**Comment by kylewm** [comment]
@benwerd do you mean it won't work right now, or it won't/can't work ever? I'm curious what you mean about a variable conflict, I'm not familiar with that term.

I tried changing it so the list of accounts is populated on demand, and that basically worked. I'll see if I can do that in a backwards compatible way (so it doesn't break *all* the syndication plugins), and send a PR to get your feedback.

Just for bragging rights, here's a micropubbed post, syndicated to twitter and facebook (using plugins, Convoy doesn't work yet)

![screenshot from 2015-12-21 18-41-42](https://cloud.githubusercontent.com/assets/950127/11946724/88b6130c-a812-11e5-98a9-3671f3b00dea.png)

**Comment by benwerd** [comment]
I definitely meant won't work right now - although you went and proved me
wrong :)

On Monday, December 21, 2015, Kyle Mahan <notifications@github.com> wrote:

> @benwerd <https://github.com/benwerd> do you mean it won't work right
> now, or it won't/can't work ever? I'm curious what you mean about a
> variable conflict, I'm not familiar with that term.
>
> I tried changing it so the list of accounts is populated on demand, and
> that basically worked. I'll see if I can do that in a backwards compatible
> way (so it doesn't break *all* the syndication plugins), and send a PR to
> get your feedback.
>
> Just for bragging rights, here's a micropubbed post, syndicated to twitter
> and facebook (using plugins, Convoy doesn't work yet)
>
> [image: screenshot from 2015-12-21 18-41-42]
> <https://cloud.githubusercontent.com/assets/950127/11946724/88b6130c-a812-11e5-98a9-3671f3b00dea.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/519#issuecomment-166489797>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
The pull request above addresses this for local plugins, but I still need to work out how to make it work with hosted and Convoy.

I'm considering firing an event "indiepub/query/syndicate-to" from the IndiePub plugin that Convoy would subscribe to and process...

**Comment by kylewm** [comment]
I think this one can be closed now, yay

**Comment by benwerd** [comment]
:tada:  :D
