### ISSUE TITLE
Suggestion: truncate long posts

### ISSUE THREAD

**Issue by dougmckown** [idno/Known#522]
It would be nice if long posts and status updates were automatically truncated to five or so lines with a "Read more..." link. 
##

**Comment by mapkyca** [comment]
Going to close, as I don't believe anyone has time to get to this. 

Could probably be implemented as a plugin/theme by overriding the output templates.

Pull requests considered :)

**Comment by physcocode** [comment]
@dougmckown this has already been discussed and I previously sent a pull request to add this capabilities but with suggestion of @benwerd it was closed and it was divided to release as a new plugin . I don't release it as it clashed with current "status" plugin provided with core . You can find my pull request in the list of closed request and get some idea !
