### ISSUE TITLE
Script provisioning of first user

### ISSUE THREAD

**Issue by uboslinux** [idno/Known#524]
Is there a way of scripting the provisioning of the first user instead of going through the setup screens via http, hoping that I'm the first user who sees those after install and not some spam bot :-)
##

**Comment by benwerd** [comment]
Bumping this, for Installatron and other reasons. We've had a command line interface for a while, but it would be nice to be able to add users through it.

**Comment by physcocode** [comment]
somewhat related to #189

**Comment by mapkyca** [comment]
Going to close this, but with a pointer to my Known console tools (https://github.com/mapkyca/KnownConsoleTools) which now has a tool for creating users that can be used for such scripting.
