### ISSUE TITLE
Getting Started wizard does not report mysql missing when mysql is not installed

### ISSUE THREAD

**Issue by andyseubert** [idno/Known#532]
The install was very straight forward once I got going. 
I cloned the project from github and followed the instructions at
http://docs.withknown.com/en/latest/install/instructions.html

because I was torn between mongodb and mysql I did not install mysql at first.

I also missed installing the mod_rewrite module for apache2 and the first page let me know that which was really nice for it to check the dependencies for me.

However, not listed in the dependencies was mysql, so the configuration utility let me continue to enter mysql credentials, and the name of the database and submit at which point it was unable to connect to the database and stopped.

I felt rather sheepish because I obviously rushed head-long into the installation of the site and skipped the now-obvious step of installing mysql, creating the database, and so on, but the configuration thing seemed to imply that it would handle all of that.

Thanks for your excellent work.

**Comment by Phyks** [comment]
Should be able to workaround it nicely using https://php.net/manual/en/function.function-exists.php or https://php.net/manual/en/function.apache-get-modules.php (preference for the first one which is webserver-agnostic). As mysql is a dependency for php-mysql on well behaving packet managers, I think we can assume that MySQL is installed if the associated PHP functions are available.
