### ISSUE TITLE
Warmup fail

### ISSUE THREAD

**Issue by makesewdo** [idno/Known#563]
On install, goes all the way, doesn't create database.

When database manually created, doesn't install tables.

Error:

```SQLSTATE[42S02]: Base table or view not found: 1146 Table 'idno.config' doesn't exist```

(issue actually filed by @mapkyca)

**Comment by benwerd** [comment]
(The speculative fix seems to have improved this.)

**Comment by Asherehsa** [comment]
I just tried to install Known for the first time and ran into this same issue. I uploaded the config.ini file and get forwarded to /begin/register?set_name= but just get this database error. Should I try running some script? Create the tables manually?

It doesn't look like the tables were even created, when I run SHOW TABLES; I get back:
    `Empty set (0.00 sec)`

**Comment by benwerd** [comment]
@Asherehsa Sounds like you have an .htaccess issue. Did your .htaccess file get written / is it present?

**Comment by Asherehsa** [comment]
@benwerd You were right, I had thought it might be a problem with the .htaccess so deleted it. Re-uploaded it and got the welcome page! Thank you.

**Comment by benwerd** [comment]
Whew! Let me know how it goes.

On Monday, October 5, 2015, Asher <notifications@github.com> wrote:

> @benwerd <https://github.com/benwerd> You were right, I had thought it
> might be a problem with the .htaccess so deleted it. Re-uploaded it and got
> the welcome page! Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/563#issuecomment-145745423>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by davidmead** [comment]
I'm running into a similar issue with install.

* Downloaded `Known 0.8.4 "Giotto"`
* Unzipped and FTP'd across to `davidjohnmead.com/blog`
* Got the setup page
* Filled in the MySQL db information (created the db before hand)
* Get the error "Ruh roh This resource doesn't exist. We're sorry." on `http://davidjohnmead.com/blog/`

![screen shot 2015-10-06 at 8 48 09 am](https://cloud.githubusercontent.com/assets/1266930/10308882/fef8d33a-6c06-11e5-9e20-215794143361.png)

The `htaccess.dist` is in the folder, and the `config.ini` has the correct db info in it. Don't see any other `.htaccess` files though.

This is on a shared Media Temple GRID server.

**Comment by danito** [comment]
Shouldn't you not rename the htaccess.dist to .htaccess?


On Tue, Oct 6, 2015 at 2:50 PM, David Mead <notifications@github.com> wrote:

> I'm running into a similar issue with install.
>
>    - Downloaded Known 0.8.4 "Giotto"
>    - Unzipped and FTP'd across to davidjohnmead.com/blog
>    - Got the setup page
>    - Filled in the MySQL db information (created the db before hand)
>    - Get the error "Ruh roh This resource doesn't exist. We're sorry." on
>    http://davidjohnmead.com/blog/
>
> [image: screen shot 2015-10-06 at 8 48 09 am]
> <https://cloud.githubusercontent.com/assets/1266930/10308882/fef8d33a-6c06-11e5-9e20-215794143361.png>
>
> The htaccess.dist is in the folder, and the config.ini has the correct db
> info in it. Don't see any other .htaccess files though.
>
> This is on a shared Media Temple GRID server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/563#issuecomment-145847154>.
>



-- 
Daniel Nix

**Comment by davidmead** [comment]
@danito I wouldn't have thought so. I thought Known created those when it's setting up.

**Comment by danito** [comment]
in some cases you don't want this. 
@benwerd I think  #969 can be closed.

**Comment by Asherehsa** [comment]
@davidmead I saw in the documentation that you need to run Known from a subdomain (not directory).

**Comment by davidmead** [comment]
I did check with @benwerd in IRC yesterday @Asherehsa, and he said you could do that now. I do have a version running on a sub-domain, but I want to move it over.

**Comment by benwerd** [comment]
To confirm, @Asherehsa and @davidmead, you can run it in a subdirectory. If .htaccess hasn't been created, you _definitely_ want to copy htaccess.dist to .htaccess.

**Comment by davidmead** [comment]
Thanks @benwerd. I couldn't rename the `htaccess.dist` to `.htaccess` in my FTP client. Says there already one there, though it's not showing up.

Using the file manager on the server I can see it and it looks exactly the same as the `htaccess.dist` - Any ideas?

**Comment by davidmead** [comment]
Just an idea @benwerd, but does the subdirectory need to have Group Write settings enabled?

**Comment by benwerd** [comment]
If .htaccess is there, I wouldn't worry about it. Perhaps try adding the URL explicitly to config.ini?

url = "http://davidjohnmead.com/blog"

**Comment by davidmead** [comment]
Uhm. Nope. @benwerd 

![not_found__and_config_ini_-_davidjohnmead](https://cloud.githubusercontent.com/assets/1266930/10317781/13673a50-6c34-11e5-857e-2500b40b4b90.png)

**Comment by benwerd** [comment]
Fascinating.

Would you mind adding a little debugging? In /index.php, underneath this:

    if(substr($path, -1) == '/') {
        $path = substr($path, 0, -1);
    }

Could you add

    echo "Path is $path"; exit;

temporarily, and let me know what it says?

**Comment by davidmead** [comment]
I get the following:

`Path is /blog`

**Comment by benwerd** [comment]
So that's exactly correct. I wonder if, for some reason, CGI mode is preventing Known from getting the correct variables to construct the page routes. Hmm.

**Comment by davidmead** [comment]
My only other PHP setting option is 5.3.29 FastCGI on that domain.

**Comment by danito** [comment]
Can you post your .htaccess here? Also the one from the root if any. I had the problem that both outruled each other.

**Comment by davidmead** [comment]
@danito 

Here's the one from the sub-directory
https://gist.github.com/davidmead/27a656ba40d62100f094

and here's the one from the root
https://gist.github.com/davidmead/29f44cbf9fb239205f6f

**Comment by danito** [comment]
Maybe you should except your /blog (known) subdirectory from the root rules.
Add 

RewriteCond %{REQUEST_FILENAME} !blog

After the !-d rule in the root .htaccess

It helped on my installation with other application on it.

**Comment by davidmead** [comment]
I'll try that @danito.

Should I blow away the `config.ini` in `/blog` after putting that in the root `.htaccess` and try the install again?

**Comment by danito** [comment]
I don't think so, I think I had luck and after that the rewrite rules wheren't applied on my known subdirectory I had full access to it. But I don't know how it will behave in your case.

**Comment by davidmead** [comment]
@danito No luck. Tried just adding that to the root `.htaccess`, then tried creating the `config.ini` again - nothing. In the end I deleted virtually everything on the root, apart from the `/blog/` and another folder.

Still doesn't work.

**Comment by benwerd** [comment]
I'm absolutely 100% convinced that this has something to do with routes not working in CGI mode. Does anyone have access to a CGI mode setup to test?

**Comment by mapkyca** [comment]
Only fastcgi, but I'm not sure that's the same (but that's what travis is using)

**Comment by benwerd** [comment]
We found and fixed the bug with FastCGI. It does work now.
