### ISSUE TITLE
Problems when Known behind an SSL offloader

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#579]
I'm using an SSL offloader (haproxy) which proxies requests to a Docker container that exposes port 80. This means Known probably "thinks" it is serving http, whereas this http is only between it and haproxy, and to the outside world, all traffic and URLs are https. I attached a screenshot.
![known-begin](https://cloud.githubusercontent.com/assets/408412/5103006/89c88274-6fca-11e4-95ea-d2e6a431c616.png)

This is probably also what's causing https://github.com/ehdr/docker-known/issues/1

Note that, for reference, running WordPress behind an SSL offloader is for instance similarly impossible unless you install the 'https' plugin. Maybe you can add a variable like 'force_https' to config.ini, which would make all image URLs and all POST targets have https.

**Comment by Gomez** [comment]
I still have the same problem, but "Website URL" is gone. The installation screen shows "insecure site" but its on https. I use known 0.8.5 with an nginx ssl offloader.

**Comment by kylewm** [comment]
@Gomez can [Known looks for](https://github.com/idno/Known/blob/master/Idno/Core/Idno.php#L790) the incoming scheme, or for the header `X-Forwarded-Proto` so you may need to add 

```
proxy_set_header X-Forwarded-Proto $scheme;
```

to your server block

**Comment by Gomez** [comment]
@kylewm Thanks, solved it!

**Comment by benwerd** [comment]
Worth adding:

My understanding is that X-Forwarded-Proto is the standard way to do this (supported by AWS and others). If there are other ways, let us know.
