### ISSUE TITLE
Ability to configure homestream

### ISSUE THREAD

**Issue by benwerd** [idno/Known#59]
Right now the homestream is just a series of posts in reverse-chronological order. Users should be able to define what appears here - eg, blog posts, photos, or some combination of items. Also see the ideas in #55.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/59" class="u-in-reply-to"></a>Mostly fixed now I think, but any comments on #626?
