### ISSUE TITLE
Write some unit tests already

### ISSUE THREAD

**Issue by benwerd** [idno/Known#60]

**Comment by mapkyca** [comment]
Todo:

* [ ] Bootstrap database
* [ ] Test database
etc

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/60" class="u-in-reply-to"></a>Other suggestions:

* [ ] Check APIs
* [ ] Check base urls
* [ ] Check subdir installs
* [ ] Test core plugin functionality
* [ ] Plugin tests

**Comment by mapkyca** [comment]
I'd say this can be closed, yesno?

**Comment by kylewm** [comment]
Test tagging with #956

**Comment by benwerd** [comment]
;)
