### ISSUE TITLE
POST of /admin/twitter/ seems to go to http

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#608]
I now have Known 0.6.5 working behind a TLS offloader, but still running into problems when trying to set up POSSE to Twitter. It seems to try to post to http://michielbdejong.com/admin/twitter/ instead of https://michielbdejong.com/admin/twitter/ when I submit the API key and API secret.

Also, the callback URL you set for your Twitter app should be with https, this is also displayed with http in the cut-and-paste box.

*Work around:* when creating the Twitter app, use https in the callback URL, and when saving the API key+secret, first right-click "inspect element" on the "Save" button, and edit:
````
<form class="form-horizontal" method="post" action="http://domain.com/admin/twitter/">
````
to
````
<form class="form-horizontal" method="post" action="https://domain.com/admin/twitter/">
````
before submitting the form.

**Comment by michielbdejong** [comment]
It's weird, I have 'Website URL' in /admin set to the full URL with https, but nonetheless, [\Idno\Core\site()->config()->url](https://github.com/idno/Twitter/blob/master/templates/default/admin/twitter.tpl.php#L22) and [$event->data->object->getShortURL()](https://github.com/idno/Twitter/blob/master/Main.php#L59) on the POSSE note both seem to return the URL with the wrong protocol on it.

In which place should this be fixed? I can have a go at it.

**Comment by benwerd** [comment]
We introduced site()->config()->getDisplayURL() which should solve this problem. This _should_ be set in most places, but I'll go back and check for site()->config()->url in particular.

**Comment by michielbdejong** [comment]
Confirmed fixed in latest version of https://github.com/idno/Twitter
