### ISSUE TITLE
Upgrade Error: Unable to post images after upgrading

### ISSUE THREAD

**Issue by absolonkent** [idno/Known#612]
After updating to 0.6.5 on my Dreamhost hosted self install of WithKnown I'm receiving an error when trying to update the user profile photo or creating a photo post. Warning shows:

Warning: mkdir(): No such file or directory in /home/user/mydomain.com/Idno/Files/LocalFileSystem.php on line 78

Warning: copy(/home/user/mydomain.com/Uploads/mydomain.com/1/3/0/a/130aad762070cf83875cef0de566b5a7.file): failed to open stream: No such file or directory in /home/user/mydomain.com/Idno/Files/LocalFileSystem.php on line 82

This was not an issue prior to the update to 0.6.5. I removed the entire install and reset the mysql database, but the issue persists. I'm unsure if there was a code change that broke the upload for me. Any assistance that could be provided would be appreciated.

**Comment by benwerd** [comment]
Closing this as we haven't seen it again. I _think_ it was a permissions issue.

**Comment by absolonkent** [comment]
Thank you. The issue has been resolved.
