### ISSUE TITLE
Allow posting of bookmarks to Facebook and Twitter

### ISSUE THREAD

**Issue by bmann** [idno/Known#617]
I'm not sure why bookmarks can't be syndicated?

**Comment by chrisaldrich** [comment]
This issue could be closed, though I'll note the following quirk:

My withknown hosted site allows for syndication of bookmarks to both twitter and facebook, however,

My self-hosted site only seems to be allowing syndication of bookmarks to facebook and doesn't allow for syndication to twitter. (Using 0.7.7.1 with Twitter plugin configured and working on several other post types.)  Did some code for sharing bookmarks to Twitter disappear in a recent release?

If I can overcome this, I have several senior academics/researchers who'd like to use the platform (both hosted & self-hosted) as a research journal/link blog platform. :)

**Comment by benwerd** [comment]
This should be all sorted now, but we need to make another release to catch up. We're on-schedule to do this by the end of the month.

**Comment by chrisaldrich** [comment]
Thanks Ben, though based on your post timing, I presume you meant the end of May?
I've upgraded to 0.7.8 today and still am not seeing the link to syndicate bookmarks to twitter.

**Comment by beck24** [comment]
You need to update the twitter plugin to see the bookmarks-to-twitter option

**Comment by chrisaldrich** [comment]
Thanks @beck24. I thought I had done so, but apparently there were one or two files that had been tweaked since my last visit/download. This can now be closed!

**Comment by benwerd** [comment]
Closing as fixed.
