### ISSUE TITLE
Searching for #Known shows nothing

### ISSUE THREAD

**Issue by bmann** [idno/Known#618]
I have several posts tagged with #known, and yet clicking on the tag shows nothing - http://bmann.ca/content/all/?q=%23Known

Whereas searching for #webmention http://bmann.ca/content/all/?q=%23webmention or #wordpress http://bmann.ca/content/all/?q=%23WordPress works as expected.

Hmmm. Except searching for #wordpress also brings up anything that mentions just "wordpress" (no tag) in the body content. I'd prefer to see explicitly searching for a #tag only showing #tag results.

**Comment by schiesbn** [comment]
Why not add a extra table with a mapping between tags and posts, status updates etc? This table could be updated when a new article gets posted/edited/deleted. This way you don't need to do a full-text search but would just search the tags table and display all the content the tag points to.

**Comment by danito** [comment]
There's an entry "tags" for each entity in the "name" column in the metadata table, but it doesn't seem to be used...

**Comment by benwerd** [comment]
Closing this because we actually have a workaround for the word "known" and a few other things.

Regarding tags, that's absolutely true, and we should remove the column.
