### ISSUE TITLE
Unable to log in after copying/pasting post from MS Word

### ISSUE THREAD

**Issue by bcwh** [idno/Known#622]
Earlier today, I tried to copy and paste something I wrote in MS Word (2011 Mac) into a post entry on my 0.6.5 release Known instance.

It generated an httpd error that I'll be happy to send privately to the developers, as it contains some sensitive data.

All my sessions on all my devices expired immediately after pasting this entry. Didn't even publish it. I can no longer successfully log into that Known instance.

Going to restore databases from yesterday's back-up shortly. I'll save a copy of the MySQL database with the issue in case it's of interest to anyone.

I'm able to reset the password successfully. Logging in even creates new session entries in the database. It's not presenting any errors, just silently failing to log in. 

Make sure to paste without formatting next time?

**Comment by benwerd** [comment]
Sorry for the very late reply here. It turns out the hashtag regular expressions were not behaving correctly (and were triggering on some complicated code that, eg, Word HTML contains). It should all be fine these days.
