### ISSUE TITLE
Portrait-oriented photo appears landscape on Twitter

### ISSUE THREAD

**Issue by timweston** [idno/Known#623]
I'm running self-hosted Known 0.6.5. When I post a portrait-oriented photo to my site and have it sent to Twitter, the photo appears on Twitter in landscape orientation. Sample photos:

Known: http://timw.io/2014/testing-portrait-photo-from-withknown-site-to-twitter
Twitter: https://twitter.com/timweston/status/541557894932488194

Posting to Known from an iPhone, in case that makes any difference.

**Comment by mapkyca** [comment]
Still an issue?

**Comment by mapkyca** [comment]
~~spring~~ winter cleaning. Closing for now.
