### ISSUE TITLE
Error when posting

### ISSUE THREAD

**Issue by davidmead** [idno/Known#629]
Posted a status update from [my blog] (http://blog.davidjohnmead.com/2014/its-alive-is-where-ill-be-posting-from-now-using), clicked to share it with Twitter and Facebook and clicked publish.

The page, http://blog.davidjohnmead.com/status/edit, returned this error:

````
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/mention-client-php/src/IndieWeb/MentionClient.php on line 248

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/mention-client-php/src/IndieWeb/MentionClient.php:248) in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/Common/Page.php on line 519
````

I refreshed the page, it submitted the form (I assume) again but still had this error. Editing the URL to http://blog.davidjohnmead.com/ revealed it had been posted twice.

![screen shot 2014-12-15 at 12 59 31 pm](https://cloud.githubusercontent.com/assets/1266930/5441033/60ed5974-845b-11e4-929a-e872457e7dbb.png)

Facebook shows it once, then a second time with an instagram image from the previous entry. 
![screen shot 2014-12-15 at 12 55 45 pm](https://cloud.githubusercontent.com/assets/1266930/5441029/56c83c5c-845b-11e4-9f1c-31f04cc158f3.png)

Twitter only seems to have posted it once.
![screen shot 2014-12-15 at 12 56 16 pm](https://cloud.githubusercontent.com/assets/1266930/5441031/5bfb601e-845b-11e4-8729-801e5852ef46.png)

**Comment by mapkyca** [comment]
Is this still an issue?

**Comment by benwerd** [comment]
This isn't an issue due to a change in Known. Closing.
