### ISSUE TITLE
Error when replying

### ISSUE THREAD

**Issue by davidmead** [idno/Known#635]
Replying to a post on Twitter returns these errors, after clicking 'publish'.

````
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/mention-client-php/src/IndieWeb/MentionClient.php on line 248
````
````
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/mention-client-php/src/IndieWeb/MentionClient.php on line 259
````
````
Warning: Cannot modify header information - headers already sent by (output started at /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/mention-client-php/src/IndieWeb/MentionClient.php:248) in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/Common/Page.php on line 519
````
I assume it's related to #614 and #629

**Comment by benwerd** [comment]
So in the same way that I'm talking about progressive enhancement to add queueing functionality to Known where you might not have the ability to run your own queue server, I'm thinking about farming off webmentions to a central service if you want. That way you don't need to worry about open_basedir or Apache configuration, we handle all the tricky bits, and you still get to own your own data on your own server.

**Comment by davidmead** [comment]
I think that makes a lot of sense. Especially if you hope Known to be
adopted outside the indieweb community on shared servers.

David Mead

http://twitter.com/davidmead
http://davidjohnmead.com
http://dmwebsites.com

**Comment by benwerd** [comment]
We're leaning towards it as a strategy for Known the company. Then people who wanted to use a different publishing platform could potentially use the services too!

**Comment by mapkyca** [comment]
Pretty sure this is fixed, closing.
