### ISSUE TITLE
Password in cleartext at the end of installation

### ISSUE THREAD

**Issue by Phyks** [idno/Known#636]
Hi,

At the end of installation, the config file to copy is displayed. With it, there is potentially the MySQL database password, in cleartext.

I think user should be warned that next page will display passwords in cleartext. Better, there should be more javascript on this part, in my opinion, to hide the config file and reveal it upon click or something like this.

Moreover, as the config file is not physically written to the server, and the user has to do it manually, why not moving this full part to full javascript and avoid useless communications between client and server ?

Thanks

**Comment by benwerd** [comment]
Subfolder installations are now possible.
