### ISSUE TITLE
Gatekeepers shouldn't forward

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#639]
Gatekeeper methods set a response code prior to a forward, this is pointless as it causes the error code to be lost. 

Instead of forwarding, gatekeepers should either throw an exception and display an appropriate error page, or include the session/login template rather than forward. 

This will preserve the error code response, and mean we don't have to make a special case for API queries.

Refs #591

**Comment by benwerd** [comment]
Ooh. Maybe. I'm worried about this being a potentially breaking change, but it makes sense, particularly for API use, as you point out.

**Comment by mapkyca** [comment]
#638 addresses this's for Apis, but I maintain this is probably an inconsistent since Apis and web should follow the same flow where at all possible.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/639" class="u-in-reply-to"></a>Further thoughts on this?
