### ISSUE TITLE
Plugin list

### ISSUE THREAD

**Issue by Phyks** [idno/Known#645]
Hi,

There are some plugins available in this repo, under the IdnoPlugins folder. But some other plugins are available around here and it's a bit difficult to find them.

Maybe a public editable wiki page containing links to community plugins could be a good idea ?

**Comment by benwerd** [comment]
We're absolutely going to include a plugin directory on withknown.com! Coming soon. Sorry for the wait in the meantime :)

**Comment by Phyks** [comment]
This would be really nice ! Thanks =)

**Comment by pierreozoux** [comment]
:+1: Yes, indeed!

**Comment by pierreozoux** [comment]
Do you plan to have a web interface for that? Directly from your known?
Like this way you could manage your themes and plugins a la wordpress :)

**Comment by benwerd** [comment]
It'd be cool, right? That only works on WP sites that have FTP access - but that's a lot of them.

**Comment by pierreozoux** [comment]
you don't need FTP access, just the wordpress process needs write access to the plugin/themes dir.

**Comment by physcocode** [comment]
Agreed with @pierreozoux we even have option to upload plugin via wordpress admin interface and it handles the rest !

**Comment by benwerd** [comment]
There's now a page for plugins on the documentation site: http://docs.withknown.com/en/latest/plugins/

I agree about having something more. But this is a start!
