### ISSUE TITLE
Photos to support album groupings

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#646]
Albums/collection support to organise, separate from tags.
##

**Comment by benwerd** [comment]
Yes. Lots of people have asked for this. Usability is important here - and of course, collections make sense for _all_ content, not just photos.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/646" class="u-in-reply-to"></a>Aye, that'd be cool. Perhaps a collection collection with typeable entity containing 1-n uuids. 

Might be able to merge ACLs into this mechanism as well...

For that matter ACLs and Collections could have a very similar UX - perhaps something along the lines of G+ circles? I think this was mooted before...

**Comment by beck24** [comment]
Was just looking to see if there was an existing plugin for photo album/groupings.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/646" class="u-in-reply-to"></a>Nothing yet, as far as I know, but it'd be awesome to have a plugin for it!

**Comment by mapkyca** [comment]
Closing, not a core thing, however the concept of object collections would be interesting.

**Comment by mapkyca** [comment]
Although, it would be pretty easy to do... change the photo object to either contain photo data or an array of uuids of subphoto objects which are not automatically syndicated. UX is the hard part here, since you'd need a snazzy way of uploading multiple photos, tagging them and ordering etc...
