### ISSUE TITLE
If your session is logged in when you update a plugin your credentials can be old/ in the wrong format

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#659]
Basically another effect of not fixing #49 which hasn't been addressed by #74 

So, when syndication plugins move from the old style to the new (or any other change that effects the current user but doesn't trigger the update), you can run in to problems until you log out and back in again.

Minor/edge case, I guess, but perhaps there needs to be an upgrade event triggered that refreshes/logs people out when fired. Perhaps as part of some future UI plugin installer/upgrader.

**Comment by benwerd** [comment]
This _should_ have been fixed by the latest iterations of those plugins, which handle both the old and new style of auth settings. But I'll check.

**Comment by mapkyca** [comment]
This should be fixed by #49
