### ISSUE TITLE
Pictures and Twitter cross posting failures: undefined index etc

### ISSUE THREAD

**Issue by hugoroy** [idno/Known#664]
Sorry for the title of this issue, I did not really know how to entitle it!

In the logs:

    [Thu Jan 01 20:15:32 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] PHP Warning:  exif_read_data(phpF8sBpK): File not supported in /var/www/IdnoPlugins/Photo/Photo.php on line 80, referer: https://hugoroy.eu/
    [Thu Jan 01 20:15:33 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] Known (hugoroy.eu): DEBUG - {"_id":{"$id":"54a59cd4da28960050beb120"},"url":"https:\\/\\/hugoroy.eu\\/file\\/54a59cd4da28960050beb120\\/Capture+d%27%C3%A9cran+de+2015-01-01+20%3A12%3A47.png","mime-type":"image\\/png","length":3522381} 4 [/var/www/Idno/Entities/File.php:303], referer: https://hugoroy.eu/
    [Thu Jan 01 20:15:33 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] PHP Notice:  Undefined index: mime_type in /var/www/IdnoPlugins/Twitter/Main.php on line 227, referer: https://hugoroy.eu/
    [Thu Jan 01 20:15:33 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] PHP Notice:  Undefined index: filename in /var/www/IdnoPlugins/Twitter/Main.php on line 227, referer: https://hugoroy.eu/

When trying to post 
https://hugoroy.eu/2015/guess-what-nobody-waited-for-this---2015munchs-work-now-in-the-public-domain
(originally, the URL in the "description" was in the "title" of
ths post)

**Comment by benwerd** [comment]
It was trying to extract EXIF data from a PNG. I've made a small change that should prevent this from happening.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/664" class="u-in-reply-to"></a>PNG has "metadata chunks", which might be worth exploring. See... https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg

**Comment by benwerd** [comment]
FYI: all the social media plugins have had major updates today, which dovetail with changes in the core to support multiple accounts and more.
