### ISSUE TITLE
"Settings" and "Administration" maybe don't need to both exist

### ISSUE THREAD

**Issue by benwerd** [idno/Known#67]

**Comment by physcocode** [comment]
Bumping this ! the current setting administration page division is exactly the way it should be !

**Comment by benwerd** [comment]
This is actually still an open issue. We're looking at changing the way this works.

**Comment by physcocode** [comment]
Setting is for non-admin right? So why do we need merging with admin panel ?

**Comment by benwerd** [comment]
Closing for now. We do need both account settings and site configuration - but we still will probably change the way they work.
