### ISSUE TITLE
Add in-reply-to to long form post

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#671]
Sometimes it's possible to send long form posts as a reply

**Comment by benwerd** [comment]
I'm going to close this, but there's a much larger conversation about switching from distinct content types to allowing posts to have a combination of lots of things.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/671#issuecomment-125433363" class="u-in-reply-to"></a>That's be cool, but the UX would be tricky to get right...
