### ISSUE TITLE
Url detection on Firefox tools seems a little off... e.g. https://github.com/idno/idno/issues gets detected as https://github.com/idno/idno

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#672]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues" class="u-in-reply-to"></a>Url detection on Firefox tools seems a little off... e.g. https://github.com/idno/idno/issues gets detected as https://github.com/idno/idno

**Comment by benwerd** [comment]
This is to do with a bug in Firefox relating to the URL bar and the history
API. It is annoying.

**Comment by mapkyca** [comment]
Pain in the bum.

**Comment by benwerd** [comment]
Quite. It doesn't happen on "real" URLs, but an increasing number of sites are emulating pages in JavaScript, and it doesn't like that quite as much.

**Comment by mapkyca** [comment]
Interesting... Document.url and chrome's tab api seem to have no trouble. I'm guessing it'll be fixed in later versions...

**Comment by mapkyca** [comment]
Although I seem to recall plans to retire their social api, or am I wrong?

**Comment by benwerd** [comment]
I haven't heard that, but it'd be relatively easy to convert this into an extension / just rely on the bookmarklet.

**Comment by mapkyca** [comment]
I do usually, or my chrome ext for chrome, but ff social seems more native :)
