### ISSUE TITLE
Slow posting

### ISSUE THREAD

**Issue by Phyks** [idno/Known#674]
Hi,

When submitting any post, it takes a while to reload the page. Not much, but still sensible time (I would say around 10 seconds although I do not have precise timing). This is happening if there are webmentions to send, but not only, so I guess this is not coming only from the "contact other servers" part.

Are you experiencing the same behaviour (and in this case it is normal) or is it a bug on my instance and I should time it to see what is taking so long ?

Thanks

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/674" class="u-in-reply-to"></a>There's a fair amount of processing that goes on when you make a post, and yes, if there are URLs in there, it can take a little while longer as those are pinged + if you're syndicating (there are plans to do this asynchronously in future).

So, in a nutshell, it's normal that it takes a little while, how long depends on a number of factors - speed of your server, what it's doing, how long the syndication server takes to respond to a syndication request, etc...

**Comment by Phyks** [comment]
More on this bug. I found that the database storage is quite fast. When I post something (let us say a bookmark), the page takes a long long time before reloading, but if I open a new tab and have a look at my Known instance, the post is already posted. Which means this is something happening *after* the database storage that is taking a long long time.

I thought it was pingback sending, but even on articles without any external links, I have the same behaviour, which looks like a timing-out request.

Is there any tools in Known (or usable with Known) to trace what is happening, so I can eventually fix it or report it? (I already know this is on the server side)

Moreover, is it an expected and reproducible behaviour or does it have to do with my server configuration?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/674" class="u-in-reply-to"></a>Thought... could this be the ye olde apache output buffer bug? I can't remember if bonita chunks its echo or not...

**Comment by pierreozoux** [comment]
Yes, I totally agree on this.
I wanted to report before, but as I see this issue :)

So Posting is slow, and I regularly get timouts (the timout are default, so I believe 30s). I think my setup is fast, but maybe I'm missing something. (ownClouds and WordPress running on the same infra is a lot faster)

I also noticed that site configurations are really slow (like 20sec). To deactivates plugin for isntance, it is a pain.

For post I think one way to optimize is to have some kind of "delayed job" in place.

I can make a video to show you if needed.

But showing my blog is blazing fast, so I didn't bother before ;)
https://blog.indie.host/

**Comment by danito** [comment]
So I'm not the only one. It takes 20+ seconds to post a status (without url and without syndication. If someone has any idea to trace this down, I'm more than happy to debug.

**Comment by kylewm** [comment]
@danito you might try disabling PubSubHubbub. Normally Superfeedr returns almost instantly, but I've definitely seen it hang.

One complication is you have to tweak the code a little bit to allow it to clear the hub setting. Remove the `if (!empty)` conditional from this line https://github.com/idno/Known/blob/master/Idno/Pages/Admin/Home.php#L90 so that it's just:

```php
\Idno\Core\Idno::site()->config->config['hub'] = $hub;
```

Then you should be able to remove the hub in Site Configuration.

**Comment by benwerd** [comment]
@danito Did removing the hub solve your problem? If not, it may be worth taking a copy of the very latest code. There are some performance fixes that may help.

**Comment by danito** [comment]
did an update a couple of hours ago, will have a look again today.

**Comment by danito** [comment]
L90 is now 
if (!empty($title)) \Idno\Core\Idno::site()->config->title = $title;
Not sure if this is still linked to the hub?
https://github.com/idno/Known/blob/master/Idno/Pages/Admin/Home.php#L96 is already without the check :
                \Idno\Core\Idno::site()->config->hub = $hub;
Anyway with the hub field emtpy or with the link to known.superfeedr.com it's now a lot quicker than before (less than 4 seconds), but I can't see any difference.
Ok to close.

**Comment by physcocode** [comment]
we should close this cause there have already been many optimisation in 0.9

**Comment by physcocode** [comment]
bump and dump
