### ISSUE TITLE
When deleting a comment, the comment is not actually deleted on the other side

### ISSUE THREAD

**Issue by Phyks** [idno/Known#680]
Hi,

I posted a comment on someone's else Known instance (http://known.cphyc.me/2015/i-just-installed-known-on-my-website-now-cross-posting-on#comments) and then deleted it on my instance.

No problem on my instance, everything was deleted nicely. But the comment was not deleted on the other side, whereas I was expecting it to be.

Not sure if it is normal or not. I don't know whether it may be linked or not, but in my logs, I have some errors with the MentionClient:

* Array to string conversion on line 69, 93 and 144
* `curl_init` expects parameter 1 to be string, array given on line 292
* `curl_setopt` expects parameter 1 to be resource, null given on line 294, 295, 296
* `curl_exec` expects parameter 1 to be resource, null given on line 298

The last two points seems to be errors in `curl_init` not being caught.

Thanks !

**Comment by mapkyca** [comment]
Replaced by #681 as this has more discussion.
