### ISSUE TITLE
Sending deletion queries with Referer on 404

### ISSUE THREAD

**Issue by Phyks** [idno/Known#681]
Hi,

As far as I know, deleting an entry is a tricky problem, especially if the other hand is not responding at the moment. Known should maintain a queue and retry later, or have a daemon to handle it, which is not straightforward. 

For now, a simple user (not power user) has no way to request the deletion another time. This can be a problem as in issue #680. 

I thought that known could use the referer to ask for a deletion. If a logged in user comes on a page that no longer exists, from an external link, why not simply send the REFERER a query to delete the link if it was referenced as a comment /like on this particular other page ?

What do you think about it ?

Thanks

**Comment by benwerd** [comment]
I'm a little worried about scope for abuse here (not to mention the fact that referers aren't always available, depending on your host setup). I do think there's a wider issue about Known needing a queue, which would dramatically improve certain kinds of functionality. Doing that in an effective way that works across hosts is an interesting problem.

**Comment by Phyks** [comment]
I do not see any possible abuse here, as the user has to be logged in and land on a 404 page due to a missing post (and could be prompted for confirmation). But I agree about the fact that referers are not always available.

Of course, that may be easier to implement than a queue, but will not be as functional as a queue!

**Comment by kylewm** [comment]
@Phyks webmention has a well-defined way for handling deletes. the deleted URL should return "410 Gone", and should send a webmention notifying the source that the comment was deleted.

See http://indiewebcamp.com/deleted for more details.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/681" class="u-in-reply-to"></a>Sending webmention on delete (like we do on update) is probably ok, it is of course up to the recipient to handle it as they see fit - in this respect the delete ping could be thought of as being very much advisory only.

**Comment by Phyks** [comment]
@kylewm Ok, so that is not something already implemented in Known I think. Else, I think we can close this issue safely.

**Comment by kylewm** [comment]
@Phyks, Known *does* support delete-by-webmention. Do you have a particular instance that's not working?

**Comment by Phyks** [comment]
Ok. Actually, this is a quite old issue that I've just found was still open today.  I do not remember the full details about the use case that made me open it. If Known supports delete-by-webmention, then I guess this should be safely closed :)
