### ISSUE TITLE
Ability to log to a file/view logs in admin

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#684]
Many people are using hosts that don't give them access to logs, which makes debugging things like webmentions can be tricky.

It would be cool if the admin could select to (temporarily) have a debug mode that echos log output to a file... probably can't do anything with apache, but the known specific logs would be possible.

We'd probably want to add more logging to various endpoints (maybe a generic "I am loading page X") start.

**Comment by benwerd** [comment]
This is something that should be thought about very carefully - potentially there's scope for a new collection here, but I don't want to make the database requests too heavy.

**Comment by mapkyca** [comment]
Closing this, as there are probably better ways of doing it.
