### ISSUE TITLE
feature request : bookmark/share to readability

### ISSUE THREAD

**Issue by jpcaruana** [idno/Known#687]
It would be great to be able to bookmark to readability.com from known when using the bookmark feature.
I imagine a "share" button on the bookmark page, as on the status update with fb/twitter.

API: https://readability.com/developers/api/reader
##

**Comment by benwerd** [comment]
A readability plugin would be fun. Anyone in the community want to try and tackle this?

**Comment by jpcaruana** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/687" class="u-in-reply-to"></a>maybe https://github.com/timmmmyboy/Diigo could be a good start for this, but I couldn't find any PHP wrapper for readability API (and I don't know PHP)

**Comment by mapkyca** [comment]
Closing, not a core thing, but community plugin would be cool!
