### ISSUE TITLE
Images in stream are not cached

### ISSUE THREAD

**Issue by mck182** [idno/Known#689]
Hey guys,

first of all - thanks a lot for Known! It's really awesome :)

I've deployed it on my server and noticed that images in the posts on the homepage are not really cached and each time they are redownloaded.

As my server has bandwidth cap, I wanted to fix this and I kinda succeeded. I don't really know the idno system well enough (and have been away from web development for eons) to make any proper changes, but here's very crude diff. Nevertheless, it should illustrate the idea and I'm sure you can make it into a proper patch.

With this it works for me - all requests for posts images get 304 response on second load onwards, so they're not redownloaded every time.

The issue seems to be that currently the 304 is returned too early, without the other headers being set, that makes the browser redownload it on next load. Maybe that's actually wanted, I dunno :)

I also found out that this works only when the files are placed in the upload dir. I've no idea about the other ways of uploaded files.

Maybe the patch is actually garbage and I don't understand the cache system well enough (been reading on it only in the past hour), but I thought I'd share it anyway, maybe it will do some good :)

```
diff --git a/Idno/Pages/File/View.php b/Idno/Pages/File/View.php
index 2efe53e..70c8063 100644
--- a/Idno/Pages/File/View.php
+++ b/Idno/Pages/File/View.php
@@ -36,19 +36,13 @@
                     }
                 }

-                $headers = getallheaders();
-                if (isset($headers['If-Modified-Since'])) {
-                    if (strtotime($headers['If-Modified-Since']) < time() - 600) {
-                        header('HTTP/1.1 304 Not Modified');
-                        exit;
-                    }
-                }
-
                session_write_close();  // Close the session early

+                $id = $this->arguments[0];
                 //header("Pragma: public");
                 header("Pragma: public");
                 header("Cache-Control: public");
+                header('Last-Modified: '.gmdate(DATE_RFC1123, filemtime(\Idno\Core\site()->config()->uploadpath  .  \Idno\Core\site()->config()->pathHost() . '/' . $id[0] . '/' . $id[1] . '/' . $id[2] . '/' . $id[3] . '/' . $id . '.file')));
                 header('Expires: ' . date(\DateTime::RFC1123, time() + (86400 * 30))); // Cache files for 30 days!
                 if (!empty($object->file['mime_type'])) {
                     header('Content-type: ' . $object->file['mime_type']);
@@ -57,6 +51,15 @@
                 }
                 //header('Accept-Ranges: bytes');
                 //header('Content-Length: ' . filesize($object->getSize()));
+
+                $headers = getallheaders();
+                if (isset($headers['If-Modified-Since'])) {
+                    if (strtotime($headers['If-Modified-Since']) < time() - 600) {
+                        header('HTTP/1.1 304 Not Modified');
+                        exit;
+                    }
+                }
+

```

**Comment by mck182** [comment]
I'm afraid simply moving the 304 redirection is not enough. The thing is that the image needs to send the "Last-Modified:" header first, otherwise the browser will not send "If-Modified-Since" as it does not know when it was "Last-Modified" and so the check cannot be done.

I've tested the committed patch, unfortunately the server still replies 200 for post images rather than 304 (and so the images are being redownloaded every time).

**Comment by physcocode** [comment]
this patch just improved loading time and decreased server load ! a super +1 for this !
