### ISSUE TITLE
Permalink on syndicated photos?

### ISSUE THREAD

**Issue by davidmead** [idno/Known#697]
When adding a photo and syndicating it to Twitter only the title and image is passed. Nothing from the caption and no permalink back to my blog as with status updates or posts.

Is this intentional? If so, is there a way to add it manually on the self-hosted version?

**Comment by benwerd** [comment]
All content can have a link attached on the self-hosted version. It's a
setting in Site Configuration.

On Fri, Jan 9, 2015 at 11:03 AM, David Mead <notifications@github.com>
wrote:

> When adding a photo and syndicating it to Twitter only the title and image
> is passed. Nothing from the caption and no permalink back to my blog as
> with status updates or posts.
>
> Is this intentional? If so, is there a way to add it manually on the
> self-hosted version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/idno/issues/697>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
