### ISSUE TITLE
Choose different syndication methods for entries

### ISSUE THREAD

**Issue by davidmead** [idno/Known#698]
I noticed that Foursquare is the only option for syndicating a check-in.

One of the reasons I'm looking to start checking in again is this way I don't need Foursquare/Swarm.

Is there a way to add the Twitter & Facebook options on the check-in page? Or choose in the site configuration, which syndication silos we would like to have on the content types?
##

**Comment by benwerd** [comment]
This is something we'd need to add to those syndication plugins. It's
tempting to make networks like Facebook, Twitter and LinkedIn be catch-alls
for every content type.

On Fri, Jan 9, 2015 at 11:07 AM, David Mead <notifications@github.com>
wrote:

> I noticed that Foursquare is the only option for syndicating a check-in.
>
> One of the reasons I'm looking to start checking in again is this way I
> don't need Foursquare/Swarm.
>
> Is there a way to add the Twitter & Facebook options on the check-in page?
> Or choose in the site configuration, which syndication silos we would like
> to have on the content types?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/idno/issues/698>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Closing, really old.
