### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by benwerd** [idno/Known#7]
When, eg, someone comments on one of my entities, I want to see notifications. These can also be piped to third party software like Firefox, and sent via email.
##

**Comment by mapkyca** [comment]
Bumping this.

See #343, I'm going to start needing the distributed social side of things soon, so it'd be good to get a direction here.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7" class="u-in-reply-to"></a>Bumping this with the comment that Chrome and now Firefox (https://support.mozilla.org/en-US/kb/push-notifications-firefox?as=u&utm_source=inproduct) support the notifications service worker.

We must be able to find some use for this... ;)

**Comment by benwerd** [comment]
The challenge is that service workers require TLS, and I'm not ready to
require that support for shared hosting users.

But! It could be an added bonus for those that do. This doesn't negate the
need for a real notifications screen, but it could be a handy way to tell
users they have a new notification.

On Friday, January 29, 2016, Marcus Povey <notifications@github.com> wrote:

> <https://github.com/idno/Known/issues/7>Bumping this with the comment
> that Chrome and now Firefox (
> https://support.mozilla.org/en-US/kb/push-notifications-firefox?as=u&utm_source=inproduct)
> support the notifications service worker.
>
> We must be able to find some use for this... ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/7#issuecomment-176860045>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
Although: Reclaim Hosting just integrated Let's Encrypt (kudos
@timmmmybot!) so I have fewer qualms. I think it's good to give secure
users more features when their environment supports them.

On Friday, January 29, 2016, Marcus Povey <notifications@github.com> wrote:

> <https://github.com/idno/Known/issues/7>Bumping this with the comment
> that Chrome and now Firefox (
> https://support.mozilla.org/en-US/kb/push-notifications-firefox?as=u&utm_source=inproduct)
> support the notifications service worker.
>
> We must be able to find some use for this... ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/7#issuecomment-176860045>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7" class="u-in-reply-to"></a>As you know, I take a hard line view that folk shouldn't support legacy protocols at the expense of useful functionality.

That said, it could degrade gracefully - on page icon for all, but transparent notifications for those who've fixed their hosting.

**Comment by timmmmyboy** [comment]
I noticed Dreamhost also added Let's Encrypt support. Here's hoping we see more and more offer it (though the cynic in me suspects those that push certs as an upsell may not, good reason for folks to move to a better host though)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7#issuecomment-176947651" class="u-in-reply-to"></a>Basic cert upselling has had its time. There's still room for company / individual certification, but basic is done. 

Which is fine, because anything else is like making seatbelts a value added extra.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7#issuecomment-176947651" class="u-in-reply-to"></a>... Or maybe even breaks, since not encrypting can not only screw you, but everyone who happens to visit your site.

**Comment by kylewm** [comment]
I started thinking about how to represent Notifications in the datastore. They need to have enough semantic information that you can eventually collapse similar notifications ("Fred and 25 other people liked this"). The data is an awful lot like ActivityStreamsPosts, except that `object` won't usually be an Entity ... Few possible notifications:

*  "Ann replied 'XYZ' Bob's post 'QRS'" &rarr; actor=Ann, verb=reply, object={content: XYZ, url: ...}, target=uuid of QRS
* "Chris registered an account" &rarr; actor=Chris, verb=register, object=false, target=site url
* "Desmond started following this site" &rarr; actor=Desmond, verb=follow, object=false, target=site url
* "Erica mentioned you in a post 'TUV'" (front page or profile page mention) &rarr; actor=Erica, verb=mention, object={content: 'TUV', url: ...}, target=site URL

That said, my gut reaction is that it doesn't make sense to try to represent notifications with ActivityStreamsPosts, and they should (continue to) be their own separate type that just happens to have a lot of properties in common with ASPs

Also it often makes sense to have "actions" associated with a notification. If someone applies for registration, the actions could be approve/reject, if someone replies it'd be nice to have a quick way to like or reply to their reply. However, I think that's safely left in the message template and doesn't need to be part of the Notification definition.

**Comment by kylewm** [comment]
A question I have is how long to keep notifications in the DB. Should we have a garbage collector that deletes notifications that have been read and are more than a week old or some such?

**Comment by kylewm** [comment]
Similarly, should the first page of notifications expand/contract depending on how many unread notifications there are? If they have 15 unread, it's a little annoying to only show the first 10.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7#issuecomment-182938392" class="u-in-reply-to"></a>My personal feeling is that notifications are data, and should be kept. That's not to say they should always be displayed... feel we should only show unread messages in the main notification pane, or perhaps unread + just read.

**Comment by kylewm** [comment]
> My personal feeling is that notifications are data, and should be kept


:+1: You're right, and throwing it out is a premature optimization.

I hate to say it but this is where it'd be nice to have separate tables for different data types. It'd suck to have a bunch of Notifications in your DB slowing down queries for Posts...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/7#issuecomment-182978172" class="u-in-reply-to"></a>I'm not overly concerned - it'd only be an issue for large multiuser sites, which are the edge rather than common distribution, that said there's a case for using a separate collection for notifications to avoid rebuilding indexes all the time.

**Comment by mapkyca** [comment]
Is this still outstanding...? Pretty sure I remember notifications being coded...?

**Comment by mapkyca** [comment]
Ok, since I've received notifications, I'm going to close this one ;)
