### ISSUE TITLE
Embed code for posts #plugin #idea

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#70]
Low priority but would help in a project I've got in the pipeline... it'd be quite nice to be able someone (everyone/author/named users/nobody) to take a posting and embed it in - say - a wordpress blog, so someone can write a narrative around the story.

Very similar to how fitter and twacebook do it. Probably just something that extends the base template for the post...

**Comment by benwerd** [comment]
Awesome that this was done as a plugin.
