### ISSUE TITLE
Email in profile links

### ISSUE THREAD

**Issue by Phyks** [idno/Known#702]
Hi,

Setting an email in the profile, as @benwerd does on http://werd.io/ is not straightforward, as one has to manually set a "mailto:email_address" link in his profile.

Moreover, the email appears in plain HTML on the profile page, which may be really nice for spammers. Github, for instance, displays the email with JavaScript, to prevent spammers from collecting it.

Another method could be to reverse the input URL, so that a human could still read it and copy/paste it, with minor modifications to do, and de-reverse it in JavaScript.

What do you think ?

**Comment by benwerd** [comment]
Seems like a decent idea. I'd happily copy Github's approach - but are we sure that spammers aren't using spiders based on Webkit or similar that render JavaScript?

**Comment by Phyks** [comment]
My email has been around on the web for two years, on Github in my profile, and on my website using the other idea (rtl). I never received any spam, although I am not using powerful antispam. So, I tend to think it makes it really harder for spammers and not worth it, but I may be wrong.

**Comment by mapkyca** [comment]
Closing. Seems to have been done..

You can add mailto:foo@bar.com as a profile link in the separate boxes.
