### ISSUE TITLE
photo posts use "p-photo" incorrectly on the h2 heading/caption when it should be a "p-name"

### ISSUE THREAD

**Issue by tantek** [idno/Known#705]
photo posts use "p-photo" incorrectly on the h2 heading/caption when it should be a "p-name", e.g. http://werd.io/2015/scotch-eggs-hit-the-hipster-scene

Looks like changes are needed in:

IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
Themes/Black/css/default.css
Themes/Green/css/default.css
Themes/Kandinsky/css/default.css
Themes/Fauvists/css/default.css

**Comment by tantek** [comment]
Needs pull requests:
https://github.com/idno/idno/pull/706
https://github.com/idno/idno/pull/707
https://github.com/idno/idno/pull/708
https://github.com/idno/idno/pull/709
https://github.com/idno/idno/pull/710

**Comment by benwerd** [comment]
Closing as fixed!
