### ISSUE TITLE
Titles with non-ascii characters get transformed into strange urls

### ISSUE THREAD

**Issue by mck182** [idno/Known#711]
The title-to-url conversion should use some accent stripping mechanism. For example "čáu školo" gets "u-kolo" url while it should be "cau-skolo". Other non-letter characters should be removed, obviously.

I'm pretty sure there are many existing solutions to this around the web, so should be easy.

Btw. can I ask where is the code actually doing the title-to-url converstion? I don't mind patching it myself and I'm happy to contribute it back if I manage to get it done nicely.

**Comment by physcocode** [comment]
@mck182 surely @benwerd  may have been stripping special characters in URL soon (maybe) special character from username would be removed for security reason  , @benwerd and @mapkyca is working on a elegant solution

**Comment by benwerd** [comment]
This has now been fixed.
