### ISSUE TITLE
Cropped email input on signin in mobile mode

### ISSUE THREAD

**Issue by Phyks** [idno/Known#713]
Hi,

In the smallest mode (below 765px wide I think), the email input field on the signin page is cropped. See attached picture for more details:
![capture d ecran - 12012015 - 19 22 50](https://cloud.githubusercontent.com/assets/3856586/5708383/b4787e84-9a90-11e4-8d03-ba886a88fce1.png)

**Comment by mapkyca** [comment]
Seems fine to me (iphone/safari), so I'm guessing this has been fixed...?

**Comment by physcocode** [comment]
works on crome/android too.
