### ISSUE TITLE
webmention behind TLS offloader requires setting url explicitly in config.ini

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#724]
As reported in https://indiewebcamp.com/Known#The_target_page_does_not_exist there is a problem with webmention when running Known behind a TLS offloader.

The `detectBaseURL` function thinks the public URL is on http, meaning webmentions for any posts on https URLs are rejected.

Workaround: add a line `url = 'https://domain.com/'` to your config.ini

**Comment by benwerd** [comment]
Sometimes TLS offloaders send an extra header. Is this true in your case? Maybe we can key off of that.

**Comment by michielbdejong** [comment]
It adds `X-Forwarded-Proto: https`, yes.
