### ISSUE TITLE
Space in profile's username makes it impossible to edit

### ISSUE THREAD

**Issue by snolahc** [idno/Known#725]
Hi,

when you enter a username with a space within it, like "Your Name", it's impossible to edit it.
The option doesn't show on the profile page, and the link "Edit your profile" in Settings leads to the front page.
(Debian7/Apache2/php5-fpm)

Thanks !

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/725" class="u-in-reply-to"></a>Handles shouldn't have spaces... that's why the regex isn't matching. 

I'll file a separate bug for this...

**Comment by mapkyca** [comment]
Closed by #726
