### ISSUE TITLE
Strip spaces and funky characters from usernames.
Closes #725

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#726]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues" class="u-in-reply-to"></a>Strip spaces and funky characters from usernames.
Closes #725

**Comment by benwerd** [comment]
Question for the crowd: should we strip them or should we use percent-encoding? Modern browsers reinterpret the latter seamlessly, in order to support non-Latin charsets in URLs. It'd be nice to be able to support, eg, Chinese usernames.

**Comment by mapkyca** [comment]
My thoughts would be to err on the side of caution and strip; usernames as ASCII is assumed in lots of places, but more importantly percent encoding will need to be carefully sanitised to avoid Xss.

Of course,we could strip for now then work on a better solution...

**Comment by physcocode** [comment]
We should surely strip them of @benwerd 

+1 @mapkyca

**Comment by physcocode** [comment]
@mapkyca  cant we just encode them rather than stripping them off? will support special usename + will prevent XSS what about this idea ?
