### ISSUE TITLE
mixed (insecure) display content

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#733]
Hi,

I get the following error on this blog: https://bertrand.click
```
Loading mixed (insecure) display content "http://bertrand.click/file/250cdfc2149731ab4ff5a07463bf74ab" on a secure page[Learn More] bertrand.click
```

I even tried by setting up the `url` variable in `config.ini` without much success. Do you have an idea, where does it come from?

Thanks a lot!

**Comment by michielbdejong** [comment]
@pierreozoux You're running it behind haproxy, right? Which version of Known are you using? (several issues related to this were fixed in 0.7)

**Comment by pierreozoux** [comment]
Yes, running behind HAproxy at the latest version (0.7), still mixed content.

**Comment by benwerd** [comment]
Very sorry to see this! I'm wondering if there's an issue with embedded
files in blog posts that were created when the site was running without a
certificate, or with the new editor. It'd be interesting to know if new
blog posts have the same issue.

On Thu, Feb 5, 2015 at 10:09 AM, Pierre Ozoux <notifications@github.com>
wrote:

> Yes, running behind HAproxy at the latest version (0.7), still mixed
> content.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/733#issuecomment-73095906>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by pierreozoux** [comment]
It looks like on the site, new posts are fine.

Should I do a migration on the database?

**Comment by benwerd** [comment]
A migration won't help here - we'll add a function to make sure these embedded links obey the same displayURL rules as elsewhere in the system.
