### ISSUE TITLE
Website: hosting provider page

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#735]
Hi,

(Do you have a repo for the public site withknown.com ?)

I think it would be a great idea to have a page with all the hosting providers out there.
Wordpress does the same, and I believe it's good practice:
https://wordpress.org/hosting/
https://wordpress.com

Cheers!

Pierre

**Comment by benwerd** [comment]
YES. This is on the cards. I'm going to close this here, because our site isn't open source, but let's talk via email.

**Comment by pierreozoux** [comment]
Where are these cards? :)

No rush, it's not really to put IndieHosters there, but it was more to be more precise in this page:
https://indiehosters.net/applications/known.html (`list of other providers`)
Compared to wordpress:
https://indiehosters.net/applications/wordpress.html

(Btw the website is stll beta, we are still working on it :/ )
