### ISSUE TITLE
event plugin - date picker

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#739]
It would be a nice to have :)
##

**Comment by benwerd** [comment]
Yes. The event plugin's UI needs a revamp - we're holding back on quite a few changes until we upgrade to Boostrap 3 across the board.

**Comment by nekr0z** [comment]
While that is not implemented, and hint on the accepted date/time format would be highly appreciated in UI.

**Comment by benwerd** [comment]
The event content type is still very beta, and I think it's about time we did something more with it. A date picker is good.

FYI, for now: it should accept natural language. eg, "today 3pm" or "Jan 5 2016".

**Comment by nekr0z** [comment]
The trouble with "natural language" is that what's natural in USA would not be natural in other countries, let alone other languages. Take me: am/pm thing is perhaps the most counter-intuitive concept regarding time for a person who was born and has always been living in 24-hour world.

Just out of curiosity: would it accept what's "natural language" to a Russian, say "23.05.2015 18:30"?

**Comment by benwerd** [comment]
Theoretically: yes. In practice: we need to do more to internationalize. I
agree completely about supporting different conventions. Known should not
be an ethnocentric app.

On Fri, May 22, 2015 at 11:24 AM, Evgeny Kuznetsov <notifications@github.com
> wrote:

> The trouble with "natural language" is that what's natural in USA would
> not be natural in other countries, let alone other languages. Take me:
> am/pm thing is perhaps the most counter-intuitive concept regarding time
> for a person who was born and has always been living in 24-hour world.
>
> Just out of curiosity: would it accept what's "natural language" to a
> Russian, say "23.05.2015 18:30"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/739#issuecomment-104737170>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
