### ISSUE TITLE
Post time no longer inline

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#742]
The abstract time for each post is now split over multiple lines.

e.g. 

15
minutes 
ago

instead of

15 minutes ago

**Comment by mapkyca** [comment]
Closing this as it seems to be a side effect of using icon- with the new fontello stuff.

**Comment by erinjo** [comment]
Can you share a screenshot? I don't think we've seen this before.

**Comment by mapkyca** [comment]
It's because fontello sets a width: 1em for all icon-* classes, and I was applying the class directly to an <a>, instead of an empty attribute within it (e.g. <a><i class="icon-...."> </i>blurb</a> ). 

My fault, but only showed up due to the change.
