### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#743]
Something in the last week has broken login, at least on my local install.

Now getting "Oops! It looks like your password isn't correct. Please try again." when logging in with the browser saved password.

**Comment by mapkyca** [comment]
Performing a password reset seems to have sorted it, but I'd like to know what changed...

**Comment by benwerd** [comment]
Oh, weird. I don't believe we've changed anything to do with that mechanism. Hmm.

**Comment by mapkyca** [comment]
It was definitely something in a recent commit - if I logged in and logged out of my previous head (da2660b22df99fd0be7e415ab1d0862961f174eb) it was fine.

Both sites mongo, if that makes a difference.

**Comment by mapkyca** [comment]
Hmm... going to close this as while it occurred on my test sites it didn't on a mysql test site or the live mongo site.
