### ISSUE TITLE
Config.json missing from known-fontello package

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#744]
Refs #741 

So authors can extend fontello package in their own themes and/or send pull requests to add additional icons.

**Comment by mapkyca** [comment]
Note... simply including your own fontello package is a no-go in most cases as icon-* is namespaced to known, so you either need to install all known fonts + your own in your theme (and keep it up to date with head), or extend the core known fontello library.

Either way it makes writing themes and plugins tricky, since there's no common library you can rely on. 

I'm sure there must have been a reason for this change, and no doubt it's a good one, but it breaks a lot so +1 vote for reverting back to font-awesome bundled with bootstrap.

**Comment by benwerd** [comment]
FYI: the roadmap for this is to move to Bootstrap 3 for the next version (which will require some widespread UI changes), and then move once again to a more permissive font library. Part of the reasoning here was to get interim access to some of the service icons.

**Comment by mapkyca** [comment]
Totally get why having known extensions to the font library is a good thing (for one thing, if we can get the open font thingy added to fontello you can have a known icon :) ). 

Bootstrap 3 font icons use a different namespace, so there's scope for having an icon-* handler for backwards compatibility.

**Comment by benwerd** [comment]
Bootstrap 3 has zero backwards compatibility, so I'm inclined to move to a known-* namespace and break everything just once :)

**Comment by mapkyca** [comment]
Namespacing will at least let plugin/theme writers to extend without breaking things, but so long as it's a consistent and broad set of font icons it should be ok.

Adding #745 will let people send pull requests if you miss any.

**Comment by mapkyca** [comment]
Bumping this, looks like config.json needs to be explicitly added by someone who has it in their working directory...

**Comment by mapkyca** [comment]
Bump cc/ @benwerd @erinjo

**Comment by mapkyca** [comment]
Closing, seemingly no longer relevant.
