### ISSUE TITLE
Syndicate to google groups.

Chalk this up as a wishlist item, but it'd be quite cool to be able to reply to a google group, and

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#748]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues" class="u-in-reply-to"></a>Syndicate to google groups.

Chalk this up as a wishlist item, but it'd be quite cool to be able to reply to a google group, and even cooler to have replies pushed back.

Handy for the known discussion group as well.

**Comment by benwerd** [comment]
This has been brought up a couple of times: Google Groups and Facebook Groups.

**Comment by herbsmn** [comment]
I'm curious, what are the main blockers to getting this feature?

**Comment by benwerd** [comment]
Largely time and money. We'd love to see this as a community contribution!

**Comment by herbsmn** [comment]
Makes complete sense! Keep up the great work that you are doing on this amazing project.

**Comment by mapkyca** [comment]
Closing, this is definitely a third party plugin.
