### ISSUE TITLE
Email troubles with ssmtp

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#751]
Hi,

I'm using ssmtp to deliver emails.
This is well configured in `php.ini` (it is working with wordpress).

After investigation, I noticed that `Swift` wasn't even calling my bin...

I would love to have ssmtp support ;) But I can understand that it's not such a priority. On top of that it looks like an issue [from Swift](https://github.com/MPOS/php-mpos/issues/2059).

As a workaround, can I setup `smtp_host` and `smtp_port` from `config.ini` I tried to look into the code, but didn't find my answer.. (and my skills on php are quiete limited ;) )

Thanks a lot!

**Comment by benwerd** [comment]
You can definitely set up smtp_host, smtp_port, smtp_username and smtp_password in config.ini. (None are required, so you can mix and match as necessary.)

It'd be nice to support ssmtp. We'll see what we can do there - maybe there's an email project that we can use instead.

**Comment by mapkyca** [comment]
Still an issue?

**Comment by pierreozoux** [comment]
Oops. sorry I forgot to close! It is indeed fixed with config.ini as https://github.com/indiehosters/known/blob/master/docker-entrypoint.sh#L53-L57
