### ISSUE TITLE
Soundcloud connection not showing

### ISSUE THREAD

**Issue by davidmead** [idno/Known#754]
In the 'settings' section, the Soundcloud connection isn't showing, even though when I "add a new connection" it shows my current one on Soundcloud and I get a confirmation message that it has connected.

![screen shot 2015-02-09 at 1 51 25 pm](https://cloud.githubusercontent.com/assets/1266930/6113136/f248dd66-b062-11e4-9ae4-b7fa6e9419a3.png)

**Comment by benwerd** [comment]
This should now be fixed in the latest SoundCloud plugin.

**Comment by davidmead** [comment]
Just pulled the latest for this plugin and it shows now @benwerd.

Thanks.
