### ISSUE TITLE
Angle brackets break up status updates

### ISSUE THREAD

**Issue by petermarshall** [idno/Known#756]
A status update with a < angle bracket character in it is cut off after that point.

For example, if I write
*I really <3 ice cream*
it comes out as just
*I really*
without the bit at the end.

I'm guessing this has something to do with how you detect and remove HTML in status updates?

**Comment by physcocode** [comment]
yes it did broke on 0.7.1 http://pranjal.mysmiff.com/2015/a-test

**Comment by physcocode** [comment]
A test <3 update 
lead to 
A test

**Comment by mapkyca** [comment]
Syndication or post? 

If the former it's probably a missing htmlentities somewhere...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/756" class="u-in-reply-to"></a>Looks like this was introduced by 0e219fa

**Comment by physcocode** [comment]
Anyway it break on most and not syndication +1
