### ISSUE TITLE
Cannot add returns to comment on Check In

### ISSUE THREAD

**Issue by davidmead** [idno/Known#758]
When trying to add a photo in the comment field on the check in form, I found it kept posting when I hit enter/return.

I had to resort to typing a `<br />` then adding the HTML from Flickr to pull in the photo. 

Can this be changed?

**Comment by benwerd** [comment]
It's a text field, which in the browser is one line. Definitely see the point of changing this to textarea.

**Comment by kylewm** [comment]
Fixed in de64b44c80e9bc32864b213da4b955df19998576 I believe
