### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by aaronpk** [idno/Known#76]
It seems that Idno is designed to use different data stores using this class: https://github.com/idno/idno/blob/master/Idno/Core/DataConcierge.php, is that correct? If so, it should be possible to swap that out with a wrapper that stores things in Postgres. Do you see any issues with that? I would be more comfortable running this under Postgres or MySQL to avoid introducing a new piece of technology on my stack.

(http://aaron.pk/r4Rq3)

**Comment by Phyks** [comment]
I may be wrong, but, as you are using PDO for the MySQL layer, I think most of the code can handle another SQL backend than MySQL right now, no ?

I don't have a good overview of the whole code, but I think that changing the `$connection_string` variable in https://github.com/idno/idno/blob/b748d7765e2a0999fe2bf90f79a816aede366a74/Idno/Data/MySQL.php#L22 could be enough, no ?

If this is the case, maybe it could be a good idea to add a `\Idno\Core\site()->config()->dbtype` config option, which would be `mysql` by default and could be set accordingly for any other SQL backend (SQLite / pgsql for example).

**Comment by aaronpk** [comment]
Unfortunately adding Postgres support isn't as easy as switching the PDO driver, because Postgres has significantly different syntax from MySQL (mostly around quote styles, e.g. `"foo"` for table names and `'foo'` for strings, whereas MySQL uses `"foo"` or `'foo'` for strings and \`foo\` for table names). It would take adding a new file for Postgres support similar to the [MySQL file](https://github.com/idno/idno/blob/b748d7765e2a0999fe2bf90f79a816aede366a74/Idno/Data/MySQL.php) you found. 

(http://aaron.pk/r4Zx1)

**Comment by mapkyca** [comment]
Completely unrelated to this ticket, @aaronpk ... does github accept webmentions now?

**Comment by benwerd** [comment]
I wrote that MySQL driver! I'll adapt it to Postgres sometime before the summer, unless someone wants to take that on.

I assume @aaronpk is syndicating to GitHub :)

**Comment by Phyks** [comment]
@aaronpk I'm not convinced there is much more to do. At least I have always used non quoted standard SQL names and never encountered any problem with psql vs mysql compatibility. 

I may not have played enough with psql, but [this SO post](http://stackoverflow.com/questions/13037319/php-pdo-compatibility-between-mysql-and-postgresql-quoting-field-names) seems to say the same.

**Comment by mapkyca** [comment]
Note to self, write a GitHub driver.

**Comment by benwerd** [comment]
Bumping this. I'd love to include Postgres support.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/76" class="u-in-reply-to"></a>Apropos my previous comment on this thread: https://github.com/mapkyca/KnownGithub

Regarding Postgres, the sqlite extension only took a couple of hours, so this would be fairly straightforward I imagine...

**Comment by kylewm** [comment]
Is there something like SQLAlchemy or Korma (Clojure) for PHP that can abstract out the variations in SQL syntax between these three RDBMS? (i.e. without introducing a big ugly ORM)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/76" class="u-in-reply-to"></a>Maybe... 

Had a little play with postgres this evening, and it's syntax makes me want to drive forks through my eyes. 

But I admit that might be frustration talking.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/76" class="u-in-reply-to"></a>Personal view: we've got enough db backends :)

**Comment by aaronpk** [comment]
A while back I did a conversion of a large codebase from MySQL to Postgres. If you're not doing fancy database-specific things like triggers, the biggest difference is quotation style. MySQL allows `'` or `"` around string values, and backtick to indicate table names. Postgres requires `"` for table names and `'` for strings. Additionally, string and date functions are different in many cases. Overall it was quite a project but not that bad. If you're using a real ORM then it takes care of all of that for you.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/76#issuecomment-125782856" class="u-in-reply-to"></a>I just seem to get type errors all the time, so I'm guessing there's something up with my schema defs. 

At this point frustration is overriding my sense of academic curiosity, so I'm going to call it a day unless the consensus is that this is something that's needed (in which case someone else can pick it up ;) )

**Comment by kylewm** [comment]
Is there a reason to write MySQL, SQLite, and Postgres as totally separate backends, instead of abstracting the bits of SQL syntax that are different between them? I'd expect 90% of the code between the three should be the same (which would make versioning and stuff way easier)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/76#issuecomment-125992445" class="u-in-reply-to"></a>Perhaps an sql superclass?

Doesn't help trying to get postgres queries to behave though ;) Made some progress, but currently can't work out why sessions won't stick... 

Not sure why I can't just leave it alone... get that feeling that I'm "almost there"...
