### ISSUE TITLE
Search results are incomplete

### ISSUE THREAD

**Issue by ericlevin** [idno/Known#760]
I created a status update:

>#IBM is cool

When I search for IBM or when I click the hashtag #IBM I get no search results returned.

Running v0.7.1

**Comment by benwerd** [comment]
Right now Known uses the MySQL fulltext engine. By default, that engine has
a 4-character lower limit on searchable words.

This is a tough one for us, but we have some ideas about how to provide a
better search engine for self-hosters. (We're also going to upgrade our
engine on the hosted service.) In the meantime, changing your MySQL
settings should help.


On Fri, Feb 13, 2015 at 10:23 AM, ericlevin <notifications@github.com>
wrote:

> I created a status update:
>
> #IBM is cool
>
> When I search for IBM or when I click the hashtag #IBM I get no search
> results returned.
>
> Running v0.71
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/760>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by ericlevin** [comment]
Mysql settings changed.

I added the following to my.cnf:

ft_min_word_len = 3

I then restarted mysql and then ran “repair table entities quick;” on my known database.

Working as expected now!
​​​​​
Eric Levin
PEAK6 Investments, L.P. | 141 W. Jackson Blvd. | Suite 500 | Chicago, IL 60604
O: 312-444-8431 | M: 847-477-2622
elevin@peak6.com<mailto:elevin@peak6.com>

**Comment by physcocode** [comment]
@benwerd shoud'nt we force the ft_min_word_len = 0  in mysql config of server running known ?

**Comment by benwerd** [comment]
You could, but we can't set that from the Known end, and many self-hosters have no control over it. I think using something like an ElasticSearch is a more scalable option for better search - and we can potentially provide that to people who can't run their own.

**Comment by physcocode** [comment]
@benwerd we canbhave an option to just leave it on sphinex maybe ..

**Comment by Phyks** [comment]
@benwerd I think one of the force of Known, especially when talking about it to people without much coding background, is that it is *really* simple to install, just like Wordpress, and it is really simple to get a fully decentralized part of the web.

Then, using the MySQL fulltext engine is part of this simplicity, and is directly available to basically anyone on any host. Tweaking MySQL parameters might be achievable by some people, depending on the host.

IMHO, this tweak should be put somewhere in the doc, in an "advanced configuration" section. Using elasticsearch might be another solution, but it might damage this simplicity of installation / fully decentralized system, as they will need your Elasticsearch instance to search, and if it is down for whatever reason, it will be a problem. Plus isn't it a bit overkill for research in Known? :)

**Comment by physcocode** [comment]
@Phyks we can at least introduce as a plugin ? Without overkilling core ! An optionl plugin for those whobare intrested and capable !

**Comment by Phyks** [comment]
@physcocode sure! Sorry, I misunderstood it and thought it was to be implemented in the core, as a replacement for MySQL Fulltext engine.

**Comment by physcocode** [comment]
@Phyks i too think @benwerd is talking baut replacement but i am on a sid of plugin that intigrate powerful things like sphinex and Elastic search ! 

@Phyks i am totaly with you that we should not make core fancy killing the simplicity

**Comment by benwerd** [comment]
This should now behave considerably better.
