### ISSUE TITLE
Not syndicating to Facebook

### ISSUE THREAD

**Issue by davidmead** [idno/Known#763]
I've noticed that no post that I've chosen to syndicate to Facebook has actually be posted there since the end of January.

Nothing has changed on my settings or site configuration pages at blog.davidjohnmead.com, also the app on Facebook I've created is still there.

Anything changed in the way Known sends these? Any relation to #755?

**Comment by benwerd** [comment]
It's not related to #755. Worth checking that you've got the latest Facebook plugin though - there was a change in how tokens are stored, and for a while there was an issue with an edge case involving backwards compatibility. (If that's the case, re-connecting may help.)

**Comment by davidmead** [comment]
Thanks @benwerd. I did disconnect and re-connect a couple of times, as well as clearing cache etc.

Seems to be syndicating again. Could've been the backwards comp. issue.
