### ISSUE TITLE
Stale tokens on multiple sessions

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#764]
* I log in on my computer, authenticate with Facebook.
* I log in on my phone.
* Facebook expires, so I re authenticate on by computer
* BANG. Computer's session user has a valid token, but phone user does not.

We probably need a way of marking data as stale in the session. Or, a better way, would be to finally fix #49, which would fix this as well as numerous other session problems.

**Comment by benwerd** [comment]
Hmm - I actually thought this would be fixed, because the session user is now regenerated on each pageload. I guess it may need more of a push.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/764#issuecomment-74563884" class="u-in-reply-to"></a>Is that a recent change? If so, I might not have updated my site since it was applied. 

Still think #49 is a good thing to work towards - storing objects in the session is a bad idea for many reasons.

**Comment by benwerd** [comment]
It is, but I agree. I've been tied up in payment systems lately (yuck) but
lots of changes on this to come.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/764#issuecomment-74571071" class="u-in-reply-to"></a>There's a special kind of headache that I only get when writing payment systems.

**Comment by benwerd** [comment]
There's also a special kind of headache that's relieved when I can pay my
rent. So, you know. Swings and roundabouts. ;)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/764#issuecomment-74590201" class="u-in-reply-to"></a>There is that, of course.

**Comment by benwerd** [comment]
Did updating improve the situation for you?

**Comment by mapkyca** [comment]
Will update and keep you posted!

**Comment by benwerd** [comment]
Any joy?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/764" class="u-in-reply-to"></a>Seems to be working, will reopen if it reoccurs...

**Comment by benwerd** [comment]
Very cool!
