### ISSUE TITLE
fail to post on FB with firefox plugin: Session has expired 

### ISSUE THREAD

**Issue by jpcaruana** [idno/Known#765]
Hi,

when I try to post on FB via firefox plugin, i get the following error:

    There was a problem posting to Facebook: Error validating access token: Session has expired 

What's wrong ?

https://developers.facebook.com/blog/post/2011/05/13/how-to--handle-expired-access-tokens/  says: 

This scenario refers to the use case where a user has authorized your app in the past, but the access token that you were issued has expired. 
When you redirect the user to the auth dialog, the user is not prompted for permissions if the user has already authorized your application. Facebook will return you a valid access token without any user facing dialog.

**Comment by jpcaruana** [comment]
There was a problem posting to Facebook: Error validating access token: Session has expired on 15 février 2015 09:49. The current time is 17 février 2015 09:25.

**Comment by benwerd** [comment]
Is this on the hosted service or on your own site? Either way, Known _shouldn't_ let you try to syndicate to Facebook if the token has expired. Reconnecting should fix the problem, but definitely make sure you have the latest version of Known and the Facebook plugin.

**Comment by jpcaruana** [comment]
It is on my own site.

how can I know what version of known and the fb plugin I am using ?

**Comment by benwerd** [comment]
Click Site Configuration, and About. The latest is version 0.7.1.

You can always get the latest here: https://withknown.com/developers

**Comment by jpcaruana** [comment]
ok thanks : I haven't seen where it is. maybe the version can be displayed in the bottom pages when we are logged in ?

    Version: 0.6.5 

I'll update and try again

**Comment by jpcaruana** [comment]
thanks : the update made it for me !
