### ISSUE TITLE
Meetup support

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#766]
Obvious one really, add meetup support for events.

They have an API (http://www.meetup.com/meetup_api/) so should be fairly straightforward.

I might write it if I get time, but if someone else gets to it first then that's also cool
##

**Comment by pierreozoux** [comment]
:+1: 

I do it by hand for now:
https://tokoloho.co/2015/i-have-something-to-hide

**Comment by benwerd** [comment]
Extensive syndication for events would be a good thing. Facebook events are
still missing, too. Definitely agree here.

On Thu, Feb 19, 2015 at 7:00 AM, Pierre Ozoux <notifications@github.com>
wrote:

> [image: :+1:]
>
> I do it by hand for now:
> https://tokoloho.co/2015/i-have-something-to-hide
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/766#issuecomment-75065850>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by physcocode** [comment]
I am working on this ! This should be a plugin r8 ? Can anyone explain me how known uses symphony event dispacher to handel events ? 

PS : i am talking abou the events to be triggered in core and not about the RSVP events

**Comment by mapkyca** [comment]
Closing, this is a plugin not a core thing
