### ISSUE TITLE
Firefox plugin: difficult to edit

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#767]
Hi,

I'm sure you already hit this one. You are writing a "share" from the firefox plugin, and want to find to copy from another tab, and the text you entered disappear.

I know, it's not really a big deal, but it's pretty annoying :)

Do you have an idea how we could solve that?

Thanks!

Pierre
##

**Comment by benwerd** [comment]
This is partially a limitation of the Facebook API - the window
automatically vanishes when you click away. But hopefully we can save the
state so it's in the same place if you reshare from the same page. It's
definitely annoying!

On Thu, Feb 19, 2015 at 7:03 AM, Pierre Ozoux <notifications@github.com>
wrote:

> Hi,
>
> I'm sure you already hit this one. You are writing a "share" from the
> firefox plugin, and want to find to copy from another tab, and the text you
> entered disappear.
>
> I know, it's not really a big deal, but it's pretty annoying :)
>
> Do you have an idea how we could solve that?
>
> Thanks!
>
> Pierre
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/767>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
