### ISSUE TITLE
Support OExchange

### ISSUE THREAD

**Issue by benwerd** [idno/Known#769]
Modify the share functionality (used in the bookmarklet and the Firefox Social API integration)  to use the OExchange specification.

http://www.oexchange.org/spec/
##

**Comment by benwerd** [comment]
withknown.com now supports OExchange in a way that's useable with all hosted and self-hosted Known sites. Next step is to build this directly into Known, too.

**Comment by mapkyca** [comment]
Closing in favour of #1110
