### ISSUE TITLE
Unable to bookmark a page whose title has charset=iso-8859-1

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#770]
This URL is unbookmarkable:  http://moto.caradisiac.com/Securite-routiere-vous-dormiez-He-bien-salivez-maintenant-696

I tried, ant it sent me to: http://michielbdejong.withknown.com/2015/scurit-routire-vous-dormiez-h-bien-salivez-maintenant---actualit which is a 404, and http://michielbdejong.withknown.com/content/bookmarkedpages/ is still empty

Bookmarking the same URL, but with https, does work:

http://michielbdejong.withknown.com/2015/securite-routiere-vous-dormiez-he-bien-salivez-maintenant-696

I think what happens is:
* it tries to create a slug from the page title
* since the page has `meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"`, it fails to correctly retrieve its title ('Sécurité routière: vous dormiez ? Hé bien salivez maintenant ! - Actualité - Insolite - Sécurité routière - Caradisiac Moto - Caradisiac.com').
* when trying the URL with https, the title retrieval fails altogether and so the slug is taken from the URL instead of from the title.

Although most of the web is now probably utf-8, there are some parts of the world (I think this is especially in France), where people still use funny charsets.  :)

**Comment by benwerd** [comment]
Thanks for the report! We'll take a look.

**Comment by benwerd** [comment]
Is the new behavior any better for you?

**Comment by michielbdejong** [comment]
Oh right, just read the [v0.7.5 release notes](https://github.com/idno/Known/releases/tag/v0.7.5). Will install it, test, and confirm. Thanks!
