### ISSUE TITLE
User password gets unintentionally changed during user Settings update

### ISSUE THREAD

**Issue by neilr8133** [idno/Known#772]
When a user edits their Settings (/account/settings) it looks like the password is pre-filled to be their current email address; instructions on the side of the field say "Leave this blank if you don't want to change it."

I suggest this is a very poor design for the following reasons:
1) The new password (their email address) is not something they would know without looking at the code
2) Users don't (and shouldn't) expect their password to change without explicit action on their part
3) This behavior is inconsistent with other sites, which default to leaving the password the same
4) By requiring that users actively do something to PREVENT their password from changing, it is far more likely that something "unexpected" (by the user) will happen (not clearing the field; not clearing the whole field; etc) and they will get locked out of their account.

I suggest that the behavior be changed in the following way:
* The "Your password" field at /accounts/settings/ should initially is presented as empty
* The password is changed only if new text is entered in the password field.

Thank you.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/772" class="u-in-reply-to"></a>That's a rather annoying "feature" of the templating library, basically there's no segregation between views, so 'value' is inherited.

**Comment by benwerd** [comment]
More importantly, it's a bona fide bug in Known, and it will be fixed
today. Thanks for pointing it out.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/772" class="u-in-reply-to"></a>Meanwhile patch #773 should fix it for now...

**Comment by benwerd** [comment]
Applied. Thanks!

On Fri, Feb 27, 2015 at 9:22 AM, Marcus Povey <notifications@github.com>
wrote:

> <https://github.com/idno/Known/issues/772>Meanwhile patch #773
> <https://github.com/idno/Known/pull/773> should fix it for now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/772#issuecomment-76433038>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
HTH :)
