### ISSUE TITLE
TLS email (on non-standard port) silently "Timed out" but reports "Invitation sent"

### ISSUE THREAD

**Issue by neilr8133** [idno/Known#775]
(Debugging is still ongoing but I'm creating this bug to collect whatever information we find about it.)

With Known configured to connect to my ISP mailserver on their non-standard TLS port (587 instead of 465), invitations were reported as sent but never arrived.  After working with mapkyca in IRC we uncommented lines 162/163 in Core/Email.php and then sending invitations resulted in the following messages in the browser UI:

× Something went wrong and we couldn't send the email.
× Connection to tcp://mobile.charter.net:587 Timed Out
× Your invitation was sent.

We're still trying to debug the cause of the timeout, but the UI shouldn't silently swallow failures and then report success :-)

**Comment by mapkyca** [comment]
Yeah, exceptions should really be permitted to bubble up and be caught by the action doing the sending closest to the ui. If I get time I'll fire a patch over.

Regarding the wrong port, 587 is actually the right port but if you're using starttls, which may be the problem. Swift is trying to connect using plain old tls. So, we need an extra option on the drop down... That is if swift supports starttls, which I'm not sure it does.

Will try and patch.

**Comment by mapkyca** [comment]
Ok, you could try the patch in #777, or if you want to debug further, the crux of the patch for you would be to change ```$transport->setEncryption('tls');``` to ```$transport->setEncryption('ssl');``` in Idno/Core/Email.php.

If this works then #777 can be safely applied.

**Comment by mapkyca** [comment]
For the benefit of the tape, @neilr8133 reports in the channel that patch #777 worked for him, which is good :)
