### ISSUE TITLE
Give Email a pluggable factory

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#779]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues" class="u-in-reply-to"></a>Give Email a pluggable factory
##

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/779" class="u-in-reply-to"></a>So plugins can replace the current email entity with different handlers (e.g. text only or encrypted)

**Comment by benwerd** [comment]
Makes complete sense.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/779" class="u-in-reply-to"></a>*might* be handy to implement it around an event trigger, that way other entities could hook into the mechanism to provide extensions to other subsystems.

**Comment by mapkyca** [comment]
Going to close, as we do have the email/send hook, which at least allows my usecase (e.g. mapkyca/KnownPGPEmail )

**Comment by mapkyca** [comment]
Actually, a plugable factory is probably still useful (e.g. sending through postmark or whatever)

**Comment by mapkyca** [comment]
Closing, nobody has needed it yet. Will build out (or accept a PR) when someone has a specific usecase (ie. building postmark support) which can't be handled another way (e.g. by using different SMTP settings)
