### ISSUE TITLE
release: have a latest zip file

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#780]
It would be handy to have this:

http://assets.withknown.com/releases/known-latest.zip

To avoid this:

https://github.com/pierreozoux/IndiePaaS/commit/7f09f11cab1c871ab258c577be1370b40d6d2ed5

Danke!

**Comment by benwerd** [comment]
We've started doing this as of today :)

**Comment by pierreozoux** [comment]
Muito bem!

:+1:
