### ISSUE TITLE
Stamen - Content Partially Encrypted Warning

### ISSUE THREAD

**Issue by markwaters** [idno/Known#786]
I am running a HTTPS only install of known.
If I have a checkin post with the stamen map on the page then firefox shows a 'Content Partially Encrypted' warning.
If I show just images the warning goes away.
From the Firefox Info / Media page I can see the links to stamen.com are HTTP and not HTTPS.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/786" class="u-in-reply-to"></a>Yeah, it's an issue with the library js. I gave it a little kick about some time ago, and it doesn't seem as simple as changing the url.

Will have another crack once I can...

**Comment by markwaters** [comment]
Working perfectly for me too , thanks guys!
