### ISSUE TITLE
cannot re-connect to facebook

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#800]
Today my Facebook token expired. I removed the connection and try to re-add it, but it's not doing anything (I keep getting the green 'Click here to connect Facebook to your account' button).

After that, I removed the 'https://michielbdejong.com/' app from Facebook settings.

Then I tried again and got 'Your app may break after April 30, 2015
Some of the permissions below have not been approved for use by Facebook.
Submit for review now or learn more.'

I guess I need to re-create my Facebook app and re-add the app id in Known site configuration?

**Comment by benwerd** [comment]
Is there anything in your server error log? You shouldn't need to recreate
the app.


On Fri, Mar 20, 2015 at 8:11 AM, Michiel de Jong <notifications@github.com>
wrote:

> Today my Facebook token expired. I removed the connection and try to
> re-add it, but it's not doing anything (I keep getting the green 'Click
> here to connect Facebook to your account').
>
> After that, I removed the 'https://michielbdejong.com/' app from Facebook
> settings.
>
> Then I tried again and got 'Your app may break after April 30, 2015
> Some of the permissions below have not been approved for use by Facebook.
> Submit for review now or learn more.'
>
> I guess I need to re-create my Facebook app and re-add the app id in Known
> site configuration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/800>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by michielbdejong** [comment]
No errors. On Facebook it say it's connected as an app. When it comes back from the auth dance, this is what Known does (from Apache access log, I removed a few characters from the code before posting it here):
````
172.17.0.17 - - [22/Mar/2015:20:41:16 +0000] "GET /facebook/callback?code=AQAhvHBCdn3G_Q6HTpIYZPVQawQZEC7sdhbOHYCkdPLfTKHhjbjunNkuUigDpZjGxRMgtU6BI22nApD3AreXFBdmrPbyQaCpYr_25XYY61CJywAP32l61cXDiLm55k4-1e9SqP8RO8p7FjoJkx7j_R0YxPccIdE9HCX-Jwd6eLO6ntmeXS3QN__2eoy3gAAl1xZK2ApH3_1ErZsW-vqHNG830s0FqnOajGIrSTG-Km3H_HJfqJZbVzLsNLpJZLr_P_s5_abCNLkBSfFLtCV8ey8cHvsxzwyy-5nWVK_EpXdB5GU2r-0XhRQVenOxUAEU&state=f9954a4d3f3c632308538bb399dd98 HTTP/1.1" 302 757 "https://michielbdejong.com/account/facebook/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"
````

**Comment by mapkyca** [comment]
Is this still a problem?

**Comment by physcocode** [comment]
its the new platform policy affecting the old app

I have been through it . Permission like writing on wall actually need prior permissions from Facebook . And Facebook do not give you permission till you remove the link back to your original post !

**Comment by kylewm** [comment]
> Permission like writing on wall actually need prior permissions from Facebook . 

It's worth noting that you only have to apply for and get approval for permissions if people other than you (the Facebook app's "Developer") are using them. i.e., only for multiuser sites.

**Comment by physcocode** [comment]
@kylewm  yep i am talking about this case :)

**Comment by kylewm** [comment]
@physcocode I know, I was mentioning it for others' reference.

**Comment by mapkyca** [comment]
Closing, as afaik this is resolved. Let me know if I'm wrong...
