### ISSUE TITLE
API Response is confusing

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#808]
Successful post returns the object, but also has some gumph like "action": "annotation/post"

e.g.

```
{
    "action": "annotation/post",
    "class": "stars",
    "confirm": false,
    "confirm-text": "Are you sure?",
    "data": {
        "object": "http://mapkycacom.icewing.dev.hub/2015/this-is-a-longer-test-some-other-stuff-which-should-3",
        "type": "like"
    },

...
```
##

**Comment by mapkyca** [comment]
Additionally, GET on /status/edit for example produces a bunch of confusing data in fields, including a seemingly random "username" field, and a "service" field that seemingly is just the last value from the "services" array.

**Comment by mapkyca** [comment]
Additionally "name": "marcus povey" on a GET to status/edit.

I can't quite establish where this is being generated, but I suspect its down to $vars being serialised by the json page shell. 

If this is true, then it's a bug in Bonita (benwerd/bonita#3), which causes variables to bleed across scope making issues like this common. I maintain that this is a recipe for disaster.

**Comment by mapkyca** [comment]
Additionally, take end.tpl.php, which will output annotations etc.

In an API view, only the *last* set of annotations can ever be displayed.

Perhaps there needs to be a better way to generate non-html views other than rendering $vars....

**Comment by mapkyca** [comment]
Referencing the annotations, I'm wondering if in this instance it's actually a spillover, perhaps the default object's json export should include annotations instead.

**Comment by benwerd** [comment]
Is this still an issue do you think?

**Comment by mapkyca** [comment]
Less so, but sometimes... I think theres a fundamental problem with variable scope in the bonita framework which causes lots of unintentional leakage

**Comment by kylewm** [comment]
API responses also always have "messages", usually an empty list. this definitely confused me the first time I saw it.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/808" class="u-in-reply-to"></a>I'd be tempted to unset the empty array, aye...

**Comment by mapkyca** [comment]
Closing, as this is really a bonita issue.
