### ISSUE TITLE
Longform post no longer working

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#809]
Latest head, all buttons work except the longform post, which doesn't show.

Fails in both firefox and chrome.

**Comment by benwerd** [comment]
Check that you have all externals. We switched to TinyMCE, and added some code highlighting libraries.

**Comment by benwerd** [comment]
Confirmed as working on clean full checkout of head.

**Comment by mapkyca** [comment]
Hmm... no submodules...

**Comment by benwerd** [comment]
We killed submodules. Worth comparing your externals directory with the one on GitHub to make sure - in particular, TinyMCE.

**Comment by benwerd** [comment]
(Is there anything in your JS console?)

**Comment by mapkyca** [comment]
Complaints about navigationWorker not existing

**Comment by benwerd** [comment]
Odd. Sounds like the Bootstrap js isn't loading for some reason. Are you on
a theme with a custom shell?

**Comment by mapkyca** [comment]
Looks like it was the markdown processor causing trouble, not sure why that's started.
