### ISSUE TITLE
Installer doesn't warn about unwriteable Upload directory

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#812]
Did a fresh install, uploaded a profile picture.

Profile pictures are broken.

Visiting the URL of the image gives a 302 redirect to the homepage

**Comment by mapkyca** [comment]
I was being dumb, it was a permission problem on the upload directory. Still, the installer didn't check or warn.

**Comment by benwerd** [comment]
Yes. This. Will fix.

There's a related issue about upgrading - a lot of people have overwritten their upload directory by FTPing files up. We'll have to fix that.

**Comment by davidmead** [comment]
Overwriting the 'Uploads' folder is something I'm guilty of @benwerd

**Comment by mapkyca** [comment]
Closed, I believe...
