### ISSUE TITLE
Short hash tags are linked but not searchable

### ISSUE THREAD

**Issue by michielbdejong** [idno/Known#814]
Clicking the four-letter hash tag on https://michielbdejong.com/2015/testing-hash-tag-abcd brings you to a search page that works.

Clicking the three-letter hash tag on https://michielbdejong.com/2015/testing-hash-tag-abc brings you to a search page that doesn't (it has zero results).

This is probably because the string 'abc' is too short to index?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/814" class="u-in-reply-to"></a>Going to assume you're on the MySQL backend.

Basically yep, mysql has a default minimum string length to search. This can be changed in mysql's config, but it defaults to > 3.

**Comment by michielbdejong** [comment]
Yes, MySQL backend. OK, so maybe display a special message on the results page when:

* there were no matches
* the search string had less than four characters

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/814" class="u-in-reply-to"></a>I'm wondering if we can do better than that... perhaps a tag -> object lookup table rather than a fulltext search would work better.

**Comment by michielbdejong** [comment]
but then you can only search for hash tags and no longer for just any occurrences of words

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/814#issuecomment-85124113" class="u-in-reply-to"></a>True, but I've never liked FTS :D

Was thinking tag->object + existing fts, reason being is that it seems more likely that people would use short tags rather than search for every occurrence of a short word like "the" or "and".

Still leaves us with the "sex" problem, but it might be a reasonable workaround.

Of course, it might be better to replace FTS with a dedicated tool which maintains its own (ACL aware) lookup table. Mysql presents the Known problem as well (where "known" is, rather embarrassingly, a kill word).

**Comment by benwerd** [comment]
I think being able to plug in something like ElasticSearch would be a more
durable solution. Full-text search is really useful in lots of situations,
and hashtags are really topic identifiers at best. Sometimes I need to be
able to go and find whatever it was I said about open source business
models at a particular event, etc etc. More and more people are using Known
as a personal Evernote.

A lot of people can't run more modern components like ElasticSearch as part
of their web stack, so we've thought about offering these as progressive
enhancements: things you can run on our servers as an add-on, if you don't
have the ability. Websockets and notifications also fit into this camp.



On Mon, Mar 23, 2015 at 11:46 AM, Marcus Povey <notifications@github.com>
wrote:

> <https://github.com/idno/Known/issues/814#issuecomment-85124113>True, but
> I've never liked FTS :D
>
> Was thinking tag->object + existing fts, reason being is that it seems
> more likely that people would use short tags rather than search for every
> occurrence of a short word like "the" or "and".
>
> Still leaves us with the "sex" problem, but it might be a reasonable
> workaround.
>
> Of course, it might be better to replace FTS with a dedicated tool which
> maintains its own (ACL aware) lookup table. Mysql presents the Known
> problem as well (where "known" is, rather embarrassingly, a kill word).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/814#issuecomment-85139688>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
Fixed for now.
