### ISSUE TITLE
Page Title in Bookmarks clears up during editing

### ISSUE THREAD

**Issue by korayal** [idno/Known#817]
The entered page title generates the URL but it is not displayed on the title.

![capture](https://cloud.githubusercontent.com/assets/313801/6790920/e0df1d20-d1b3-11e4-8b4d-7f7ab3a8ed66.jpg)

On the page above, the title was "Scala Collections Tips & Tricks" (which should be displayed instead of the URL) but when I click on "edit" the Page Title textbox is empty.

**Comment by benwerd** [comment]
Fixed in latest commit.
