### ISSUE TITLE
Change how API key validation works

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#831]
Problem:

API keys are passwords, and are stored cleartext in the database, and are generated automatically for a user. 

When an attacker gets read access to the database (or sniffs the traffic between the load balancer, web server or database server which is all unencrypted) they'll get access to all user accounts. This basically makes the effort gone to hashing passwords entirely pointless.

Solution:

Due to the way that the API works, it's pretty hard to simply hash the api key. Certainly, the api key should not be generated automatically, it should be explicitly generated by the user (to limit scope of a compromise).

That the signature is formed from hashing together the uri with the key means we can't simply store the key hashed and do a lookup, so I'm unclear at this point how the current HMAC signing authentication can be preserved. I'm starting to think we might be getting into ZKP territory, but I'll have a think.

Anyway, discuss.
##

**Comment by benwerd** [comment]
This is one of those situations where I think it's helpful to look at other
peoples' API best practices. What are Twitter et al doing?

(Answer: OAuth and regenerating keys. Maybe there's something in there we
can pick up and use.)


On Mon, Mar 30, 2015 at 6:16 AM, Marcus Povey <notifications@github.com>
wrote:

> Problem:
>
> API keys are passwords, and are stored cleartext in the database, and are
> generated automatically for a user.
>
> When an attacker gets read access to the database (or sniffs the traffic
> between the load balancer, web server or database server which is all
> unencrypted) they'll get access to all user accounts. This basically makes
> the effort gone to hashing passwords entirely pointless.
>
> Solution:
>
> Due to the way that the API works, it's pretty hard to simply hash the api
> key. Certainly, the api key should not be generated automatically, it
> should be explicitly generated by the user (to limit scope of a compromise).
>
> That the signature is formed from hashing together the uri with the key
> means we can't simply store the key hashed and do a lookup, so I'm unclear
> at this point how the current HMAC signing authentication can be preserved.
> I'm starting to think we might be getting into ZKP territory, but I'll have
> a think.
>
> Anyway, discuss.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/831>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Well, there's my oauth server plugin, which I think we talked about bringing in to core in the past.

The "correct" way would be client side x.509 or similar, but that'd be like stabbing yourself repeatedly in the hand with a pencil.

**Comment by mapkyca** [comment]
I'm also wondering if we should consider sand boxing the api, for example no admin level access or no settings changing

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/831#issuecomment-87794582" class="u-in-reply-to"></a>I'm not entirely sure we can call this resolved - the current API key method is still a massive vulnerability.

**Comment by benwerd** [comment]
Reopening, with the caveat that I want this to be in line with best practices on the web.

OAuth scoping might help with the admin issue.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/831" class="u-in-reply-to"></a>Bumping. 

Could we consider killing the api key and (perhaps) adopting my OAuth server code into core for v 1.0?

**Comment by mapkyca** [comment]
Thinking about this some more, and this isn't a password, it's a token... which is subtly different since it's not user defined and has more entropy. It's not hashed, granted, but it can only be used to make API calls (although that's actually quite a bit of everything is an api) 

Definitely should limit scope to non-admin, unless we want to go the oauth scoping route.
