### ISSUE TITLE
Method to get a text representation of an email

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#832]
HTML emails break many things, it'd be good if there was a plain text component, either as multipart or as a config hook.

**Comment by benwerd** [comment]
Sounds like a reasonable feature, but what do HTML emails break in 2015?!

On Mon, Mar 30, 2015 at 8:31 AM, Marcus Povey <notifications@github.com>
wrote:

> HTML emails break many things, it'd be good if there was a plain text
> component, either as multipart or as a config hook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/832>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Encryption, text processing, anyone who checks email on the move over ssh, render differently on different devices, privacy risk on ios, etc.

Also, it makes email big for no added value.

The last is a personal preference.

**Comment by benwerd** [comment]
All fair play. Interesting app idea: an email reader that works over ssh
but supports rich text emails.



On Mon, Mar 30, 2015 at 11:50 AM, Marcus Povey <notifications@github.com>
wrote:

> Encryption, text processing, anyone who checks email on the move over ssh,
> render differently on different devices, privacy risk on ios, etc.
>
> Also, it makes email big for no added value.
>
> The last is a personal preference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/832#issuecomment-87789048>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by Phyks** [comment]
:+1: for a text version of emails.

I read my emails in text, for personnal reasons, and notifications are quite nice except the article quote which does not have any line breaks.

**Comment by mapkyca** [comment]
Add to this, HTML only email tend to break accessibility stuff for the vision impaired.

The "correct" way to do this is to use multipart encoded email, with a text/plain primary segment. However, this is getting into mail client territory, so I wonder if there's a way to sidestep...

**Comment by benwerd** [comment]
Hmm hmm hmm. There's no reason why we couldn't include text email templates and create the multipart email - after all, we're using a built-in mail client already. Probably better than stripping tags or using some kind of algorithm.
