### ISSUE TITLE
[Bookmarks] Title is not saved after editing

### ISSUE THREAD

**Issue by jbpiacentino** [idno/Known#833]
Editing a bookmark's title and saving it does not save the title. Only the URL remains.

MySQL, Known 7.5

**Comment by benwerd** [comment]
Thanks for the report - we're going to fix this for 0.7.6, which will be
out this week.

On Mon, Mar 30, 2015 at 10:47 AM, jbpiacentino <notifications@github.com>
wrote:

> Editing a bookmark's title and saving it does not save the title. Only the
> URL remains.
>
> MySQL, Known 7.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/833>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Might be related to #817

**Comment by benwerd** [comment]
Fixed in latest commit.

**Comment by jbpiacentino** [comment]
I'm still experiencing the issue with 0.7.7.
