### ISSUE TITLE
Can't install on Different Port

### ISSUE THREAD

**Issue by jarofgreen** [idno/Known#835]
I just tried to install on a dev server. Because it's a virtulised dev server, I put it on a different port.
   
    http://serverurl:20168/

However the site is full of references to the root URL without the port, so it's not working :-(

    http://serverurl/external/bootstrap/assets/css/bootstrap.css

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/835" class="u-in-reply-to"></a>Looks like we need to patch Config getDisplayURL() and detectBaseURL() to handle non standard ports.

Should be fairly straightforward.

**Comment by benwerd** [comment]
Did the attempted fix solve the issue?

**Comment by jarofgreen** [comment]
Yup, seems fine.

**Comment by jarofgreen** [comment]
When will this be merged onto the main branch and released, please?
