### ISSUE TITLE
Problem with exporting

### ISSUE THREAD

**Issue by davidmead** [idno/Known#838]
I'm getting this error on http://blog.davidjohnmead.com/admin/export/generate/ when I try and export from my self-hosted site.

> **Ooops! PharException**
phar zip flush of "/var/tmp/blog_davidjohnmead_com.zip" failed: unable to write local file header of file "entities.json" to zip-based phar "/var/tmp/blog_davidjohnmead_com.zip"

![screen shot 2015-04-01 at 2 37 41 pm](https://cloud.githubusercontent.com/assets/1266930/6948578/c126daf2-d87c-11e4-994e-c3b85f7be798.png)

Any ideas?

**Comment by davidmead** [comment]
Actually seems to be on re-generating the archive file.

**Comment by kylewm** [comment]
Assume this was the same issue as  #930 and is therefore resolved
