### ISSUE TITLE
brid.gy link incorrect

### ISSUE THREAD

**Issue by beck24** [idno/Known#840]
Very very minor thing...
On the page /account/bridgy there is a blurb about brid.gy which links to https://brid.gy
The page is only accessible via https://**www**.brid.gy

I wanted to learn more about brid.gy and clicked on the link and was mildly confused for a sec

![screen shot 2015-04-02 at 10 52 36 am](https://cloud.githubusercontent.com/assets/738363/6969839/6d7b44ba-d926-11e4-95a2-9a9e4d8e37cf.png)

**Comment by benwerd** [comment]
Oops! We'll fix that. Thanks!

On Thu, Apr 2, 2015 at 10:56 AM, Matt Beckett <notifications@github.com>
wrote:

> Very very minor thing...
> On the page /account/bridgy there is a blurb about brid.gy which links to
> https://brid.gy
> The page is only accessible via https://*www*.brid.gy
>
> I wanted to learn more about brid.gy and clicked on the link and was
> mildly confused for a sec
>
> [image: screen shot 2015-04-02 at 10 52 36 am]
> <https://cloud.githubusercontent.com/assets/738363/6969839/6d7b44ba-d926-11e4-95a2-9a9e4d8e37cf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/840>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
