### ISSUE TITLE
Tag search not showing some entities with matching tags

### ISSUE THREAD

**Issue by beck24** [idno/Known#844]
I have two posts tagged with the tag ```withknown```

http://known.mattbeckett.me/2015/procrastination-reigned-today-instead-of-real-work-i-joined-the
http://known.mattbeckett.me/2015/embedlycards---a-plugin-for-known

When you click on the ```withknown``` tag on either post the results show only the status update and not the bookmark.

http://known.mattbeckett.me/tag/withknown

This is a MySQL installation if that makes a difference.

**Comment by benwerd** [comment]
We're thinking hard about burning MySQL search to the ground.

A better solution is definitely needed. One option is to have an explicit tag metadata field, but in a lot of ways I'd like to move to ElasticSearch or another robust search engine.

**Comment by beck24** [comment]
http://known.mattbeckett.me/tag/plugin

The bookmark shows for the ```plugin``` tag however, maybe it's a case of only the first tag in the post being searchable?

**Comment by beck24** [comment]
I gave up on mysql search in elgg, I use solr for everything search in all my projects

**Comment by benwerd** [comment]
Right. MySQL search in Elgg was similarly borked. It's just a bad feature.

**Comment by physcocode** [comment]
@benwerd can we just give a alternative like ElasticSearch as a plugin insted of ovetboarding the core ? Like a search plugin designed by evan for elgg !

**Comment by benwerd** [comment]
@physcocode Yes. We're actively exploring this as an addition to Convoy, too.

**Comment by benwerd** [comment]
Closing this with the latest commits. Let me know if it's still a problem.
