### ISSUE TITLE
Posts word count not working

### ISSUE THREAD

**Issue by beck24** [idno/Known#845]
If using a straight textarea the word count doesn't change at all, if using the rich text input the word count is doubled.

![screen shot 2015-04-04 at 1 35 36 am](https://cloud.githubusercontent.com/assets/738363/6992029/27d47198-da6b-11e4-94d5-0294f18eeee6.png)
![screen shot 2015-04-04 at 1 36 18 am](https://cloud.githubusercontent.com/assets/738363/6992028/27d1e496-da6b-11e4-8a1d-fe62bcf27f2b.png)

**Comment by benwerd** [comment]
Should be fixed in the latest commit!
