### ISSUE TITLE
Registration irks

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#846]
Registering new account:

* Doesn't allow for duplicate email addresses (may be designed, but shouldn't be a problem if usernames are unique)
* Reg details don't persist on registration fail, so you have to enter it again.

**Comment by benwerd** [comment]
Not going to fix the first one - lots of people find usernames confusing, as it turns out, so logging in with an email is necessary. The second point is fair.

**Comment by misuba** [comment]
Also, registering users on self-hosted Known requires setting up email service, which I for one am unwilling to do with my VPS. If there is interest in a form that adds trusted users directly to a multi-user site, I can clean up my branch and submit it?

**Comment by benwerd** [comment]
Sounds good!
