### ISSUE TITLE
Login Form - make email field type "email"

### ISSUE THREAD

**Issue by jarofgreen** [idno/Known#849]
Current release, it has type "text".

Setting type "email" would make it so much easier to type in an email address in the soft keyboard on mobile phones.

**Comment by beck24** [comment]
what about people who use their usernames to log in?

**Comment by jarofgreen** [comment]
The placeholder text says "Your email address" only, so I didn't know that was on option.

Huh. What I do on https://opentechcalendar.co.uk/you/login is have 2 fields, username or email. Behind the scenes we actually except either in either - since usernames can't have a @ it's trivial to tell the difference.

Any advances on UI suggestions appreciated; I know having 2 fields is a bit clunky but typing in an email address into a text field is a pain; i've seen phones that try to helpfully autocorrect "a@b" to "A. B"

**Comment by davidmead** [comment]
I didn't know I could use my `username` in that field either @jarofgreen. Only found out when I changed the email address and got locked out ;-)

Without being too picky, there should be a label on that field and the placeholder text should be "username or email address" if it can accept both.

As that's the case changing to solely an email type doesn't work. Most browsers, including mobile, remember logins and have pre fill so you should get the option as you type as to which one to use.

You could change it to just "username" as it seems people use their email address as their username.

**Comment by jarofgreen** [comment]
Thanks for making the label more clear! But I still think there is a UI issue here, sorry. Typing is an email address on a soft phone keyboard not in email mode is a real pain. But I agree if that field also accepts usernames, you can't just change the type to "email", so don't know what the answer is. (Tho if most ppls usernames are also an email address, then this issue applies doubly!)
