### ISSUE TITLE
Getting 405 Method Not Allowed on Twitter Brid.gy connection

### ISSUE THREAD

**Issue by timmmmyboy** [idno/Known#850]
When I click the link to connect Twitter to Brid.gy I get the following error:
```405 Method Not Allowed
The method GET is not allowed for this resource. ```

It's possible this is due to the connection already being done on the Brid.gy site, but I didn't get the same type of error for Facebook so I figured I'd add it here (although the error is from the Brid.gy site so possibly their issue and not yours?)

**Comment by benwerd** [comment]
Oh no! You're absolutely right.

We've fixed this in code.

**Comment by timmmmyboy** [comment]
Working perfectly now. Thanks!

**Comment by benwerd** [comment]
We've also pushed out a new release that includes this revised code.

**Comment by timmmmyboy** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3890972/7093694/5e1599f8-df89-11e4-866e-120720b9edbc.gif)

:) Thanks again
