### ISSUE TITLE
404 on /begin with defalt Apache config AllowOverride off

### ISSUE THREAD

**Issue by kylewm** [idno/Known#858]
Ubuntu configuration has "AllowOverride off" for /var/www which disallows .htaccess from rewriting urls, which means that lots of users hit a 404 immediately after installation succeeds.

It's an [easy enough fix](http://indiewebcamp.com/Known#Fix_404_Not_Found_on_.2Fbegin) but it seems to bite lots of people (informal observation based on questions in #knownchat).

If it's possible to detect this error during installation and give a helpful warning, I think that would be ideal.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/858" class="u-in-reply-to"></a>There's no good way to detect for this *specifically*, but perhaps a test to see if /begin/register or similar returns a 404 on warmup

**Comment by benwerd** [comment]
An obvious solution would be to try and load a piece of JavaScript that
lives at a rewritten URL as part of the /warmup process. Or at least,
that's what I've been thinking.

On Thu, Apr 23, 2015 at 6:07 AM, Marcus Povey <notifications@github.com>
wrote:

> <https://github.com/idno/Known/issues/858>There's no good way to detect
> for this *specifically*, but perhaps a test to see if /begin/register or
> similar returns a 404 on warmup
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/858#issuecomment-95578046>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
You're thinking a JS file (or some other static resource) instead of /being/register to avoid false positives from other php configuration errors?

**Comment by benwerd** [comment]
Yeah, because then it could actually reliably set the prerequisite page -
the installer could fail to continue if you don't have it set up.

On Thursday, April 23, 2015, Kyle Mahan <notifications@github.com> wrote:

> You're thinking a JS file (or some other static resource) instead of
> /being/register to avoid false positives from other php configuration
> errors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/858#issuecomment-95644536>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
what do you think of this idea from StackOverflow? it's specific to AllowOverride and wouldn't detect rewrite problems in general. add a SetEnv in the .htaccess

```
SetEnv HTACCESS on
```

and check that it's set in the setup (iff we're running on apache)

```php
if ( !isset($_SERVER['HTACCESS']) ) {
  // No .htaccess support
}
```

http://stackoverflow.com/a/10531400/682648

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/858#issuecomment-95783700" class="u-in-reply-to"></a>Trouble is that AllowOverride isn't a strict binary, so you can have an override combination that allows the setenv but not the rewrite.

My vote would be for the JS test - perhaps what elgg did, have a specific rewrite rule for rewrite a rewrite test (e.g. a file called bar.php which we rewite to foo.php) and then test that is specifically reachable.

**Comment by kylewm** [comment]
This should be fixed now, when installing with AllowOverride None, the settings page will give an error

<blockquote>
Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf
which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect
to default.js, but got this response instead: ...
</blockquote>
