### ISSUE TITLE
session.hash_function sha256 doesn't exist

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#861]
Reported on IRC: PHP 5.6 but doesn't support sha256

This is odd to say the least, since MD5 and SHA1 are obsolete, but it might be that sha256 support which, although bundled with PHP since 5.1, may be switched off in this instance.

Might be worth detecting the algo support in install and/or making the option configurable.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/861" class="u-in-reply-to"></a>... phpinfo() run on the shared host shows hash module enabled, and sha256 supported.

Odd....

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/861" class="u-in-reply-to"></a>Anywho... sent a PR to make the option configurable, with a fallback if not supported.

While I dislike adding config options for everything, this will address the specific shared host problem as well as let people in high security environs use things like sha512. 

That said, if we find out the root cause for sha256 being missing in this instance we should probably remove the config option.

**Comment by rikmendes** [comment]
i just upgraded my Known instance from git and I get back this error. 
it can be seen here : http://www.rmendes.net/ Warning: ini_set(): session.configuration 'session.hash_function' must be existing hash function. sha256 does not exist. in /rmendes.net/Idno/Core/Session.php on line 28

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/861#issuecomment-115655415" class="u-in-reply-to"></a>Have you tried setting session.hash_function to something else in your config.ini? Eg. session.hash_function = 'md5'

It defaults to sha256 (which most PHP installs have in their default install and is the recommended hash), but seemingly some folk have disabled.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/861#issuecomment-115655415" class="u-in-reply-to"></a>Sorry: session_hash_function = 'md5'

**Comment by rikmendes** [comment]
right now, only way i could actually log in is by commenting the line 28 of the sessions.php file. 
that line is : init_set('session.has_function', $hash);

**Comment by rikmendes** [comment]
session_hash_function = 'md5' works fine...not sure why dreamhost has not sha256 enabled
but i think i will move this site to a vps soon enough so i can have what's needed.

**Comment by benwerd** [comment]
Weird! md5 is not recommended, but I'm glad it works. I wonder if not
having sha256 is a misguided CPU throttling thing.

On Fri, Jun 26, 2015 at 5:35 AM, Rick Mendes <notifications@github.com>
wrote:

> session_hash_function = 'md5' works fine...not sure why dreamhost has not
> sha256 enabled
> but i think i will move this site to a vps soon enough so i can have
> what's needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/861#issuecomment-115662802>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/861#issuecomment-115666302" class="u-in-reply-to"></a>Quite possible. A lot of hosts have very conservative configurations, sticking on php 5.2/3 for example...

**Comment by jeremycherfas** [comment]
I had the same issue with a shared server on DreamHost, and setting `session_hash_function = 'md5'` in `config.ini` fixed it for me.
