### ISSUE TITLE
Status update of over 160 characters to Twitter - different error code?

### ISSUE THREAD

**Issue by trilliums** [idno/Known#863]
Is it perhaps possible to give out a different error message that's more descriptive to the actual problem when trying to post a status update to Twitter that's over 160 characters instead of the below message?

Oh no! Known experienced a problem!
Known experienced a problem with this page and couldn't continue. The technical details are as follows:
Fatal Error: /var/www/sensible.mn/IdnoPlugins/Twitter/Main.php:97 - "Call to undefined method IdnoPlugins\Status\Status::getSyndicationURL()", on page sensible.mn/status/edit

**Comment by benwerd** [comment]
This is actually a different problem.

It looks like you've taken your Twitter plugin from GitHub. That code needs the very latest GitHub code - we just introduced the getSyndicationURL method, which it can't find in your installation.

**Comment by trilliums** [comment]
I re-downloaded the latest Twitter plugin from Github, just to be sure, pushed it to the server, and tested with a status that was over 160 characters and one that was under 160 characters. The one that was over gave the same error and the one that was under was able to push through without issues.

**Comment by benwerd** [comment]
Yes. You need to update Known core.

What's happening is that over 140 characters, the tweet gets a URL to the original post appended using getSyndicationURL(). The core needs to be updated so you can use that function.
