### ISSUE TITLE
Pubsubhubbub should send pings for all feed URLs

### ISSUE THREAD

**Issue by kylewm** [idno/Known#866]
I'm trying to track down why I don't get PuSH notifications for Known sites in Woodwind. Each page lists its own push topic, e.g. my homepage is:
```
Link: <http://known.kylewm.com/>; rel="self"
```

but the [PubSubHubbub::publish](https://github.com/idno/Known/blob/master/Idno/Core/PubSubHubbub.php#L230) function only pings with `hub.url=http://known.kylewm.com/content/all/?_t=rss`, so I never get notified for the homepage feed.

The "right" solution would be to send a ping for each feed that may have changed (within reason). e.g. when you add a new status, it would send pings for each of:

```
/
/content/statusupdate
/content/all
/?_t=rss
/content/statusupdate?_t=rss
/content/all?_t=rss
```

I think it would also be possible (but less correct) to just use one topic url for every feed, e.g. `http://known.kylewm.com/content/all`, and ping only that one when any of them update. You would have more false positives that way where Superfeedr would request a page and get no new updates.

(I'm volunteering to code/test this, just wondering if you have a preference for how it should work)

**Comment by benwerd** [comment]
Iiiiiiiiinteresting. Hmm. In some ways pinging for the different URLs makes sense, but at the same time, we don't have any way to really detect search feeds and so on. So, indeed: having a single topic is probably the way to go.

Thanks for pointing this out!

**Comment by kylewm** [comment]
To be clear, the single topic option *is* a hack, and it would mean sending the wrong `Link: rel=self` header everywhere. I don't know if there are any other implications of that.

**Comment by kylewm** [comment]
I thought about it a little more and I can't recommend doing a single topic for every feed. I don't want to be responsible for incorrect "Link rel=self"s in every  page of every Known site :stuck_out_tongue: 

also in the degenerate case if there were millions of subscribers to millions of search feeds, it would be bad behavior to ping all of them every time any item was posted to /all. Best case, it's unfriendly to superfeedr, worst case they would start throttling us and disbelieving our notifications. 

So I'm planning to work on a PR that pings the handful of feeds that we know about, and just doesn't advertise a PuSH hub for others (like individual pages or search feeds). If that sounds bad, lmk.

**Comment by kylewm** [comment]
Sooo, should I send pings on "saved" for only ActivityStreamPosts, everything but ActivityStreamPosts, or both? I'm thinking the former because feeds are made up of ActivityStreamPosts (right?)

(Unrelated good news: I learned we can send multiple URLs to Superfeedr with just one POST request)
