### ISSUE TITLE
known package manager 

### ISSUE THREAD

**Issue by physcocode** [idno/Known#870]
Was just thinking about writing a CLI for known , command interface for known to performe simple operation like updating known core and installing plugins and themes for known .this idea is roughly inspired from 'grav's GPM ' 
Wanted to conform with @benwerd before starting work on it !

**Comment by pierreozoux** [comment]
:+1: This would be amazing :) (I guess like wp cli :) )

**Comment by physcocode** [comment]
Yeah and indeed its not a boom big task what we need to to is set up a cli via symphony component maybe then trigger event that would download plugin fr known's url and add it to plugin directory . 
Easy enough if proper conventions are used for plugins URL's !

**Comment by pierreozoux** [comment]
What about `composer`? I'm not a php dude, but I think it is also an option :)

**Comment by physcocode** [comment]
Composor is a php package manager (we cant install known plugins via composer) what i am talking baut is known's own CLI !

**Comment by physcocode** [comment]
PS : this is feature only for self hosted knowj instance !

**Comment by benwerd** [comment]
This isn't a priority for Known core, but I'd love to see it as a project!
