### ISSUE TITLE
Minify static ressources

### ISSUE THREAD

**Issue by paulcmal** [idno/Known#873]
Some ressources like JS and CSS shipped with Known are already [minified](https://en.wikipedia.org/wiki/Minification_%28programming%29), but some are not.

Minification could spare some network usage and therefore allow Known to be loaded faster. On my own [test instance](https://cmal.info), for instance, I've reduced the size of files loaded by the browser on the homepage by 17%, from 960KB to 800KB (this includes a background image and a profile picture).

Could maybe all the JS and CSS ressources included in Known be also available in minified forms? Also, could these minified versions be used by default when loading the web pages?

You may find scripts online (like [here](http://www.tero.co.uk/scripts/minify.php)) to help you automate the process.
##

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/873" class="u-in-reply-to"></a>Can't you trigger minify from travis scripts? Seem to remember that you could...

**Comment by benwerd** [comment]
Re: automation, probably, but it would be better to do it manually for now,
I think. It's a good idea. Note that Known now supports hosting static
resources offsite, and we should probably make more of this.

On Tuesday, April 28, 2015, Marcus Povey <notifications@github.com> wrote:

> <https://github.com/idno/Known/issues/873>Can't you trigger minify from
> travis scripts? Seem to remember that you could...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/873#issuecomment-97124354>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benborges** [comment]
please enlight me : what's the point of hosting static resources offsite ? ain't the goal to self host ?

**Comment by filtercake** [comment]
@benborges  

- [Reasons to use a Content Delivery Network](http://www.sitepoint.com/7-reasons-to-use-a-cdn/)

maybe sth like this is what you're looking for?

**Comment by mapkyca** [comment]
Depends on #1178

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/873" class="u-in-reply-to"></a>I wonder if we could use something like https://github.com/tedivm/JShrink to do this on the fly.

We'd need to introduce a redirect for javascript, much like we had for the machine version caching, which @benwerd removed last year (not sure why)
