### ISSUE TITLE
Photos don't return to object

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#874]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues" class="u-in-reply-to"></a>Photos don't return to object

**Comment by benwerd** [comment]
I'm not sure what that means?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/874" class="u-in-reply-to"></a>Returns to content/all, should return to object. Breaks API

**Comment by benwerd** [comment]
Got it. This is one situation where the web view and the API view should actually have different user flows.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/874" class="u-in-reply-to"></a>Possibly, although I do dislike exceptions. 

Perhaps there's call for some sort of "success handler", to handle this consistently across objects?

**Comment by benwerd** [comment]
That could definitely work.

**Comment by benwerd** [comment]
I'm actually wondering if we shouldn't have a "return to" variable that specifies an internal location to redirect to (eg the home feed), and let the system redirect to the object if this isn't specified. That would keep the flow consistent while also allowing us to direct the user to the main stream (which in the web view is much less confusing, it turns out, than redirecting to the object).

**Comment by mapkyca** [comment]
Not a terrible idea, so long as urls were relative and stripped of their query vars

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/874" class="u-in-reply-to"></a>Additional to this, when editing an old post forwarding to content/all doesn't make sense, neither does it make sense if you use a filtered home page.

**Comment by benwerd** [comment]
Right - so the "return to" variable in most cases could point to the main stream, or an object if you were editing it, or something else. (The filtered stream is a difficult user flow.)

**Comment by mapkyca** [comment]
Patch submitted has a forward to var which is set to content/all for new entities, but defaults to object if missing or existing object.

**Comment by mapkyca** [comment]
What this means is form submitted content returns to the stream, but api will return the object unless you explicitly override.
