### ISSUE TITLE
Twitter text for Bookmarks

### ISSUE THREAD

**Issue by korayal** [idno/Known#875]
There is no back reference to the bookmark url in Known, so we can't collect the favorites or replies to them in our Known site. 

Also I think using the comment text instead of title in the twitter/fb posts would be better.

**Comment by kylewm** [comment]
That's not true, Bridgy can still collect favorites and replies to posts when there is no backreference in the Tweet. See https://indiewebcamp.com/posse-post-discovery for details.

**Comment by korayal** [comment]
Yes, after checking my post now, I saw that my back reference was collected:

http://ayak.org/2015/easy-scalability-with-akka---michael-nash-boldradius-blog

I think bridgy didn't fetch them at that time yet. 

How about my second suggestion?

**Comment by kylewm** [comment]
I don't have a strong opinion either way...and ultimately Ben or Erin would need to weigh in.

I will say it's always a bit of a challenge to know what to post to twitter given the length constraints. For example https://adactio.com/links/ syndicates to https://twitter.com/adactioLinks with just the titles.

**Comment by korayal** [comment]
Right, it would definitely break that kind of usage. In Drupal there is an option to clip some part of the body text as summary. 

Maybe we could have an extra optional field for social media shares. Which would help us not to limit ourselves when giving a title, or forming a body text when needed.

**Comment by benwerd** [comment]
Closing this, but I'd say the discussion on what to share to social media is definitely open. For me, Facebook is the canonical example of this, where I'll often be sharing the link title - but the link title is also immediately displayed underneath by Facebook.
