### ISSUE TITLE
Problem with using recent .zip file to update

### ISSUE THREAD

**Issue by davidmead** [idno/Known#880]
So I just used the latest .ZIP file to update my self-hosted Known.

I had to go through and pull local versions of certain files as I was getting errors like...

`Parse error: syntax error, unexpected '}' in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/Pages/Search/Tags.php on line 31`

When I replaced those I know get this when I log into to the site.

![screen shot 2015-05-04 at 4 44 41 pm](https://cloud.githubusercontent.com/assets/1266930/7462131/48cbe140-f27d-11e4-8766-90efb5634986.png)

Any ideas?

**Comment by benwerd** [comment]
There seems to be an issue in your theme. Viewing the source, it looks a lot like it's echoing from line 116 of templates/default/content/end.tpl.php. Would you mind pasting in that code snippet in your active theme?

It should look like this:

    } else {

        if (\Idno\Core\site()->session()->isLoggedOn()) {
            echo $this->draw('entity/annotations/comment/mini');
        }

    }

**Comment by davidmead** [comment]
I found it on line 130:

        } else {

            if (\Idno\Core\site()->session()->isLoggedOn()) {
                echo $this->draw('entity/annotations/comment/mini');
            }

        }
    }

?>
ion()->isLoggedOn()) {
                echo $this->draw('entity/annotations/comment/mini');
            }

        }
    }

?>


I included the stuff that seems to be half commented out under it.

**Comment by benwerd** [comment]
I've confirmed that this was _not_ present in the zip and is not in the codebase. So something else happened, perhaps during transfer?

**Comment by davidmead** [comment]
Hmm. Maybe it tried to merge the file instead of replacing it.

I'll do a fresh pull from GitHub and replace everything except:

* config.ini
* .htaccess files
* uploads folder

See if that rectifies it.

**Comment by benwerd** [comment]
Hopefully it will. Let us know.

**Comment by davidmead** [comment]
Pulled everything down afresh from GitHub and pushed it. Everything seems fine again.

Thanks for looking into it.
