### ISSUE TITLE
Syndication buttons not showing on phone

### ISSUE THREAD

**Issue by davidmead** [idno/Known#884]
Just noticed that the syndication options aren't displaying properly on my phone (Nexus5). Working fine on tablet & desktop sizes.

![2015-05-07 22 09 51](https://cloud.githubusercontent.com/assets/1266930/7538830/df97b34c-f570-11e4-8bb2-a58a3ae2e0cc.png)

Anyone else seeing this?

**Comment by nekr0z** [comment]
Can't confirm, buttons look and work perfectly well on my HTC M8.

**Comment by davidmead** [comment]
Thanks for checking @nekr0z. I pulled from GitHub last night and it all seems to be working now.
