### ISSUE TITLE
Known Chrome extension broken ?

### ISSUE THREAD

**Issue by benborges** [idno/Known#885]
concerns latest Known only. older Known extension install are working just fine

When i click the big K icon on Chrome i get the popup with Share, Reply, Bookmark, RSVP
until here it's all fine. 

when you switch to Reply or Bookmark or RSVP, the little window popup refresh but always come back to Share, there is no way to select the type of post. 

if necessary i can do a short video of what I see on my side, so that it could help better understand
the issue?

**Comment by benborges** [comment]
so in short if you use it to share a status, it works fine. but there is no way to switch between the type. 
ps: also it seems the Bit.ly plugin for chrome mess up with Chrome extension when activated. 
it seems to want to create a shortened URL when you open the K Chrome extension and display
a yellow notice that it can't shorten the url. (not sure why that plugin wants to shorten a URL before it's a post..)

**Comment by benwerd** [comment]
The Chrome extension is not a core plugin, so I'm going to cc @mapkyca (the author) and suggest you file an issue at the target repo: https://github.com/mapkyca/KnownChrome

**Comment by benborges** [comment]
my bad, i should have filled this directly there, i'll do the same for my other issue. can be deleted sorry.
