### ISSUE TITLE
permalink slug generation for international alphabets

### ISSUE THREAD

**Issue by kylewm** [idno/Known#886]
We've been working with @nekr0z today to resolve some Bridgy issues, and noticed Known is generating strange permalink URLs for his posts that are written in Russian, e.g. http://www.evgenykuznetsov.org/2015/--- and http://www.evgenykuznetsov.org/2015/--2

fwiw, Wordpress %-encodes utf-8 characters e.g. https://kylewm.wordpress.com/2015/05/08/%D1%81%D0%B5%D0%B7%D0%BE%D0%BD-%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82/

**Comment by benwerd** [comment]
Nice catch! Will correct. I've been doing a lot of unicode work lately, eg
with hashtags, and this is an important addition.

On Fri, May 8, 2015 at 1:19 PM, Kyle Mahan <notifications@github.com> wrote:

> We've been working with @nekr0z <https://github.com/nekr0z> today to
> resolve some Bridgy issues, and noticed Known is generating strange
> permalink URLs for his posts that are written in Russian, e.g.
> http://www.evgenykuznetsov.org/2015/--- and
> http://www.evgenykuznetsov.org/2015/--2
>
> fwiw, Wordpress %-encodes utf-8 characters e.g.
> https://kylewm.wordpress.com/2015/05/08/%D1%81%D0%B5%D0%B7%D0%BE%D0%BD-%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/886>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by nekr0z** [comment]
This seems to be an extreme case of #711 that is bad in itself, but gets really ugly in languages that don't use ASCII characters at all (any language with Cyrillic or Arabic script for example).

**Comment by benwerd** [comment]
@kylewm Great tip about WordPress. It looks like PHP's rawurlencode() will do a lot of this for us - just need to correctly make a rule about what does and doesn't get encoded.
