### ISSUE TITLE
Known need a Draft function

### ISSUE THREAD

**Issue by benborges** [idno/Known#888]
I just lost a huge post i was writing because i dragged a picture to the post itself thinking it would upload the image, but instead it opened the image on top of the tab i was using to write my post. 

when i used the back browser function, I got back the title of the post i was writing but all the content of the body is simply gone and there is no way to get it back. there isn't any Draft section where one could find existing post being drafted to my know how. 

until this is possible i will take the habit to compose outside of Known and then only paste it & publish it. 
but it would really great to have this function, allowing users to compose a post calmly without any fear that it might be gone because of a wrong step. 

what do you think ? 
##

**Comment by physcocode** [comment]
For the time i would suggest even preserving the body with the title a quick fix until whole publish feature is up 

Cc @ben

**Comment by benborges** [comment]
Indeed, that would be enough for the time being !

**Comment by mapkyca** [comment]
Bumping since this has brought up recently in discussion numerous times...

**Comment by kylewm** [comment]
JS periodically saving to localStorage seems like it'd be the easiest short term fix (since it doesn't require supporting drafts more generally on the backend)... The main issue I'm not sure of is when to clear out the stored field data. Clearing on submit would not be good enough for the case where the session has timed out, or submitting fails for some other reason. I suppose a successful save could redirect to /?clearLocalStorage=true, but that seems super hacky. Better ideas?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/888" class="u-in-reply-to"></a>Didn't text entry do that already? I remember having problems with it remembering to earnestly in the past, so perhaps it was removed.

Perhaps a fudge would be to override the submit and post the form via ajax. You could then analyse the return result - reset the storage if you got an ok back, reset storage and set the window location to the object, all other results display an error and stay on the same page...

**Comment by benwerd** [comment]
There have been a couple of mechanisms for this, but none of them have
worked satisfactorily. They're also not the same as a real draft / preview
function, and I think the ultimate mechanism needs to support this.

I also think refreshing form tokens using JS would be smart, so pages can
never time out if they're being actively used by a human.

On Sunday, August 30, 2015, Marcus Povey <notifications@github.com> wrote:

> <https://github.com/idno/Known/issues/888>Didn't text entry do that
> already? I remember having problems with it remembering to earnestly in the
> past, so perhaps it was removed.
>
> Perhaps a fudge would be to override the submit and post the form via
> ajax. You could then analyse the return result - reset the storage if you
> got an ok back, reset storage and set the window location to the object,
> all other results display an error and stay on the same page...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/888#issuecomment-136163276>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
