### ISSUE TITLE
Image orientation not normalized in preview 

### ISSUE THREAD

**Issue by beck24** [idno/Known#892]
![screenshot_2015-05-11-23-31-17](https://cloud.githubusercontent.com/assets/738363/7581345/cbb07dfa-f836-11e4-8148-90d5d4d18044.png)

Uploading an image from mobile shows the incorrect orientation depending on the exif data.  When posted it is corrected, but I wasn't sure it would be from the preview.
##

**Comment by benwerd** [comment]
Interesting. Does this happen across all your mobile browsers, or just in Firefox?

**Comment by beck24** [comment]
Not sure, I've only used FF and just noticed this.  I'll run some tests and let you know.

**Comment by beck24** [comment]
Same thing in the default android browser.  It's the only other browser I have installed currently.

![screenshot_2015-05-14-12-26-42](https://cloud.githubusercontent.com/assets/738363/7639939/9fa3ef62-fa34-11e4-8ecb-1d94c10da707.png)

**Comment by benwerd** [comment]
Okay, looks like quite a few browsers don't do this automatically. We're going to bring in an outside project to make this happen; likely Javascript-Load-Image: https://github.com/blueimp/JavaScript-Load-Image

**Comment by mapkyca** [comment]
Still an issue? Ref #1137
