### ISSUE TITLE
Email Configuration and Settings UX/UI

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Known#894]
This could be tagged as a suggested "new feature" for improved UX/UI:

The page http://DomainName.com/admin/email could include a "Test Settings" button and script, to trigger an actual email to test the input settings for future email notifications.

It could also include a UI button to direct to https://DomainName.com/account/settings/notifications/ to change the settings there.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/894" class="u-in-reply-to"></a>Largely handled, I think, by a pull request I submitted a while ago (which as just been merged: https://github.com/idno/Known/pull/778#event-303353394)

**Comment by benwerd** [comment]
Closing this - everything suggested is in place. Thanks @mapkyca for the testing code!
