### ISSUE TITLE
Bookmarklet behaves oddly if you're logged out

### ISSUE THREAD

**Issue by benwerd** [idno/Known#897]
Logging in no longer forwards properly. Trying to figure it out, but more eyes would be awesome!

**Comment by kylewm** [comment]
Hmm, it seems to work for me on my hosted account and on local dev account. I log out, visit some page I want to reply to, click the bookmarklet, login, and taken to the share page with details filled in.

**Comment by benwerd** [comment]
Fixed this. It was specifically an issue with walled garden sites.
