### ISSUE TITLE
Error creating new Users

### ISSUE THREAD

**Issue by benborges** [idno/Known#899]
When a user try to Join my Known site, after filling the register fields, i get this : 

Oh no! Known experienced a problem!

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /www/IdnoPlugins/Subscriptions/templates/email/subscriptions/email.tpl.php:1 - "Call to a member function getURL() on boolean", on page 1-m.cc/account/join/

**Comment by benborges** [comment]
After a git pull to last version, instead i get : No email addresses were found or all the people you invited are already members of this site.

when I try to invite new users to my instance...

any explanation ?

**Comment by kylewm** [comment]
Subscriptions does not appear to be a core plugin. Perhaps try removing or disabling https://github.com/idno/Subscriptions ... it looks to be rather out of date (ref: https://github.com/idno/Subscriptions/issues/2#issuecomment-76767157)

**Comment by benwerd** [comment]
Horrendously out of date, in fact. I'm going to close this, but will work on fixing that plugin and making it more generally available.
