### ISSUE TITLE
Exif no longer stripped of images

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#904]
Presumably for reasons of image rotation, which is of course important, but wondering if there might be something else going on since thumbs have the exif available at generation.

**Comment by mapkyca** [comment]
Bumping for details of reasoning...

**Comment by benwerd** [comment]
It is indeed rotation. Need to make that stable as hell and then we can put it in.

**Comment by mapkyca** [comment]
I'm confused as to why it's a problem, we pass exif to thumbnail generation, so not sure how it's being lost.

**Comment by jeremycherfas** [comment]
I'm still seeing a problem with failure to rotate, in a direct upload from my phone, which definitely includes EXIF on rotation. As [here](https://vaviblog.com/2016/morning-coffee-in-the-park-almost-springlike).

Anything I can do?
