### ISSUE TITLE
We're getting session timeouts again

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#909]
Not sure why, but it doesn't appear to be the validation code as no exceptions are thrown.

**Comment by benwerd** [comment]
I returned sessions to MongoDB for users on that back-end, which might be part of the reason. I've noticed the same.

**Comment by mapkyca** [comment]
Sounds likely. Sure there was a good reason, but file based sessions seem much more robust (Debian Pgp cron job not withstanding)

**Comment by benwerd** [comment]
Alas, they don't work if you extend to more than one server, which is increasingly common.

**Comment by mapkyca** [comment]
The typical solution to this is client side encrypted sessions. Certainly what ruby does...

**Comment by mapkyca** [comment]
Or the very least, we shouldn't ignore the session path config option - if set use file sessions.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/909" class="u-in-reply-to"></a>Can you point me at the commit that brought this in? I want to see if I can work around it...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/909" class="u-in-reply-to"></a>Ahh... 3160be9c4f117b931ef5eabab8ca6f0fd3e899ef
