### ISSUE TITLE
Don't store user messages in session

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#91]
It makes the session big, and means we're updating the session regularly, which is a bad thing if we want to store sessions somewhere else.

**Comment by benwerd** [comment]
Re-bumping, and acknowledging that this is an issue.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/91" class="u-in-reply-to"></a>Question becomes, where do we keep it. Obvious would be a new collection, with a fallback to session should the db be unavailable (so we can tell folk there's a problem)

**Comment by kylewm** [comment]
Could you explain why this is a bad thing? AFAIK, Flask (the python framework I'm familiar with) stores flashed messages in the session exactly like Known does.

**Comment by benwerd** [comment]
I actually don't think it is an issue now that Known stores sessions in the database.

**Comment by kylewm** [comment]
Power down robots!

**Comment by mapkyca** [comment]
It is less of an issue now, aye. That said, there are some edge cases with storing messages in the session when operating in a clustered/load balanced environment where sessions are shared and writes become expensive.
