### ISSUE TITLE
Consider using require.js

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#914]
I'm wondering whether it'd be worth loading resources via require.js instead of inserting them into the main template.

This would:
- Mean theme authors who do extensive mods wouldn't need to track changes on the page shell
- Load libraries when required instead of all at once
- Might resolve some of the jquery chicken and egg
##

**Comment by benwerd** [comment]
I don't know too much about it, but it might be a good idea. Take a look at the bootstrap3 branch if you haven't, btw.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/914" class="u-in-reply-to"></a>Tangentially related, there's an increasing amount of JS being including in the main template. Some or all of this could probably be shipped off to it's own library...

**Comment by mapkyca** [comment]
Going to close, not got to it yet, and having used require for a little while on other projects have decided that it's a headache I just don't need right now.
