### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by physcocode** [idno/Known#920]
How did you manage \Idno\Core\site()->config() insted of $site= new \Idno\Core\Idno; $site->config() ? I too tried doing same as done with $site in Idno\Core but end up with error \Mysite\Core\site() function does not exist !

**Comment by benwerd** [comment]
This is a PHP question, not a Known question. Answering it, but I'm going to close the ticket :)

site() is actually defined to return \Idno\Core\Idno::$site (a static variable containing an instance of \Idno\Core\Idno) by reference. See the definition on line 735 of Idno/Core/Idno.php.

Key concepts here being:

Passing by reference
Defining a function within a namespace
The static property of the class, containing an instantiated version of the object

**Comment by physcocode** [comment]
namespace Scrawler\Core;
 class Scrawler extends \Scrawler\Common\Component
 {
	 public static $site;
	 public $dispatcher;
	 public $filesystem;
	 public $template;
	 public $config;
	 public $session;
	 public $routes;
	 public $db;
	 
	 function init()
	 {
	   self::$site = $this; 
	   $this->dispacher = new \League\Event\Emitter();
	   $this->filesystem = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local(__DIR__.'/../../'));
	   $this->template= new \League\Plates\Engine(__DIR__.'/../../templates','sct');
	   $this->db = new Database();
	   $this->session= new Session();   
	   $this->config= new Config();
	   $this->routes = new Routes();
	   $this->db = new Database();
	   site()->session()->start_session('_s', false);
	 }
	 
	
	 
	 function &dispatch()
	 {
		 return $this->dispatcher;
	 }
	 
	 function &filesystem()
	 {
		 return $this->filesystem;
	 }
	 
	 function &template()
	 {
		 return $this->template;
	 }
	 
	 function &config()
	 {
		 return $this->config;
	 }
	 
	 function &session()
	 {
		 return $this->session;
	 }
	 
	 function &routes()
	 {
		 return $this->routes;
	 }
	 
	 function &db()
	 {
		 return $this->db;
	 }
	 
	  function &site()
     {
         return \Scrawler\Core\Scrawler::$site;
     }
 }

This code returns error : call to undefined function Scrawler\Core\site()
when we try \Scrawler\Core\site()->db()->somefunction()

**Comment by kylewm** [comment]
what is Scrawler?

**Comment by physcocode** [comment]
Thats the name of my new indie web project @kylewm  I just wanted a function like \Idno\Core\site() so I am trying to replicate one without success :'(

**Comment by kylewm** [comment]
Look at the Known source code, https://github.com/physcocode/Known/blob/master/Idno/Core/Idno.php#L715 is outside of the `class Idno` definition.

but this seems like an inapproriate place to ask for coding help unrelated to Known. Maybe come by the IRC channel?

**Comment by physcocode** [comment]
ok sorry and thanks @kylewm

**Comment by benwerd** [comment]
The IRC channel and the developer mailing list are much better places, yes!
GitHub issues are for bugs & feature requests, rather than questions.

On Saturday, June 6, 2015, Kyle Mahan <notifications@github.com> wrote:

> Look at the Known source code,
> https://github.com/physcocode/Known/blob/master/Idno/Core/Idno.php#L715
> is outside of the class Idno definition.
>
> but this seems like an inapproriate place to ask for coding help unrelated
> to Known. Maybe come by the IRC channel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/920#issuecomment-109610579>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
It's awesome that you're writing your own IndieWeb project. Kyle's right:
you should stop by #indiewebcamp on Freenode.

On Saturday, June 6, 2015, Ben Werdmuller <ben@benwerd.com> wrote:

>
> The IRC channel and the developer mailing list are much better places,
> yes! GitHub issues are for bugs & feature requests, rather than questions.
>
> On Saturday, June 6, 2015, Kyle Mahan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Look at the Known source code,
>> https://github.com/physcocode/Known/blob/master/Idno/Core/Idno.php#L715
>> is outside of the class Idno definition.
>>
>> but this seems like an inapproriate place to ask for coding help
>> unrelated to Known. Maybe come by the IRC channel?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/idno/Known/issues/920#issuecomment-109610579>.
>>
>
>
> --
> Ben Werdmuller
> <http://goog_1933028737>
> benwerd.com | werd.io
>
> +1 (312) 488-9373
>
>

-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by physcocode** [comment]
Roger that sir @benwerd !

**Comment by benwerd** [comment]
But even then, there may be a better place for generic PHP questions.

Free hint: if you want to mimic what I did with the helper functions in
Known, you need to define those functions outside of the class (here you've
defined them as class methods).

On Saturday, June 6, 2015, Pranjal Pandey <notifications@github.com> wrote:

> Roger that sir @benwerd <https://github.com/benwerd> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/920#issuecomment-109612231>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by physcocode** [comment]
Thank you very much Ben sir now this works as it should :)

**Comment by kylewm** [comment]
ditto, what Ben said, that's awesome! would love to hear about your project in #indiewebcamp :+1:
