### ISSUE TITLE
Posting (with international characters) does not really work on hosted version

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#923]
For the last couple of weeks trying to post anything to hosted version of Known usually resulted in cryptic broken-unicode messages, and it took three to five tries to get through (pictures, status updates, events - anything). Now a new status update already took me 20 attempts, and still counting, and all I get is:

���ao�0���wR�I�:>����*&&>0i�i�kåq�:Wʯ��1��6�����v^?i9��� ���:�����k� >Pcq<+�䕾z!f��`&��GЮ�����k�ظ�9<���L�-t���	t��	�d-�ӮT^NX�j���!P؁:꠴���!�cu�9R5T��y�͗�4����w�����M��&q9��`�}t-r�#�bJ�<.k��SXl�ߜ��ka���|ǖ7��:�<�9{t�!�t�s ��Xs�v�ż8Xw{X(�5�XU�������(�3���o�Cb��4^Oq=�j�>+�b�_V�$�W��ș6mk������=Y�̽j�[�4^�f��Dʾ��(�%�F,*A�%a��_�R,��~��(��%��K�vO�E>�>+>dE������� ͳ�~�K���So*L�!�_,�(��q"G�<�JW�/��H 

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/923" class="u-in-reply-to"></a>Can you reliably replicate this? For example, posts with certain characters?

If you have a sample that always does this, could you post it?

**Comment by nekr0z** [comment]
No, I don't. The trouble is, this occurres to me with every post (the message differs, but the vibe is the same), and after several F5s with "resend data" things suddenly work out and the update is posted. So the same content can either go through well or result in failure, depending on the current air humidity or whatever else.

**Comment by benwerd** [comment]
We're able to replicate and are treating about this as our highest priority.

**Comment by benwerd** [comment]
We've identified the issue - which is, unfortunately, with non-Latin characters in status updates. We're on it and I'll update this thread when it's fixed (hopefully in the next 20 mins).

**Comment by mapkyca** [comment]
Hosted related, right? Never been able to replicate...

**Comment by benwerd** [comment]
Correct: it's something to do with the hosted infrastructure. We can't replicate on self-hosted either.

**Comment by benwerd** [comment]
The issue has been pinned down to URL slug generation, which is choking on unicode characters.

**Comment by mapkyca** [comment]
Given it's intermittent, my bet would be one or two old rds nodes misbehaving.

**Comment by benwerd** [comment]
It's actually related to an older bug. Amazon is failing to update our servers with the latest version of Known, which is a larger and more serious infrastructure problem that we'll follow up with them on. Testing a fix now.

**Comment by benwerd** [comment]
Correction: it looks like on AWS, some strings with special characters are not reliably utf-8 encoded, and the system is dying on json_encode.

**Comment by nekr0z** [comment]
Still looks dead to me.

**Comment by benwerd** [comment]
I'm afraid we're still on it. It looks like there's a utf8 issue somewhere in the chain. We're also in conversation with Amazon, which hosts our infrastructure. Hoping to get it fixed today.

**Comment by mapkyca** [comment]
Interestingly, it works fine on my systems so it's got to be a configuration issue - mod missing, or mbstring misconciguration.

**Comment by benwerd** [comment]
We've finally fixed this in code, and are in the process of coaxing ElasticBeanstalk into updating across all deployed servers.

**Comment by benwerd** [comment]
New version is deployed. I'm closing this ticket - but please do reply if it's still a problem for you.

**Comment by nekr0z** [comment]
I confirm, looks fixed to me.
