### ISSUE TITLE
Logouts...

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#925]
I'm getting session timeouts... again...

**Comment by physcocode** [comment]
me to @mapkyca

**Comment by benwerd** [comment]
Still happening?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/925" class="u-in-reply-to"></a>As it happens, it just happened when I tried to reply to this. It seems to be intermittent, and possibly something else to do with sessions.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/925" class="u-in-reply-to"></a>Closing this, it doesn't happen often enough to be systemic. Rather I think the GC is timing out the sessions.

That said, I don't think we do "persistent" logins, so maybe we should look at cookie persistence.
