### ISSUE TITLE
Check-in : location doesn't update after altering address field

### ISSUE THREAD

**Issue by danito** [idno/Known#927]
When doing a check-in from my workstation the location it finds is not accurate. When I enter an address manually it doesn't update the map.
See http://nxd4n.nixekinder.be/2015/checked-into-parlement-europen where I checked-in in Strasbourg  with address "Avenue du Président Robert Schuman, 67000 Strasbourg, France" but it shows a map of Brussels.

**Comment by danito** [comment]
Nothing seems to trigger any ajax call to update the lon/lat or the address when user_address is modified.

**Comment by kylewm** [comment]
I believe it's intentional that the map doesn't update when you edit the address. You *can* drag the pointer around on the checkin map to move it to the right lat/long location, and then fine tune the address to say the correct thing.

**Comment by kylewm** [comment]
Closing as expected behavior. Right now you can edit the lat/long by dragging the pin around on the map. This updates the address, and then you can tweak the address to say whatever you want. I think this is the best we can do.

**Comment by danito** [comment]
Agree. But. When do a checkin from my workplace on a workstation, the location is not accurate and it puts me in other country, probably where the proxy servers' end points are. That's then a hassle to edit on the small map (ok I admit, it's a special case, as you would normally use your gps enabled phone to checkin)

**Comment by kylewm** [comment]
Do you have any thoughts on how you could support editing the lat/long *or* the address without creating a feedback loop? (lat/long changes the address, which changes the lat/long, which changes the address, etc.)

I always run into this kind of UX problem and don't know how to fix it well. I guess once you manually edit one or the other, that one could become the "primary" control and be sort of locked, such that edits to the other wouldn't propagate. Definitely open to ideas
