### ISSUE TITLE
Bookmarks : unicode are not re-encoded in titel

### ISSUE THREAD

**Issue by danito** [idno/Known#928]
when the bookmark plugin gets a page's title with unicode in it, it displays the code and when posting it, the code stays decoded.
This url : http://ostbelgiendirekt.be/bonjour-tristesse-wetzlarbad-eupen-trockenen-75118 gets this titel : Bonjour Tristesse im Wetzlarbad: Eupen sitzt weiter &#8220;auf dem Trockenen&#8221; [Fotogalerie] › Ostbelgien Direkt

**Comment by danito** [comment]
github does the job.
Took a picture : 
![2015-06-10 12_28_38-nxd4n s known](https://cloud.githubusercontent.com/assets/54977/8080450/eae7e7c4-0f6c-11e5-94d5-9d617c05d2de.png)

**Comment by danito** [comment]
for accents and umlaut it seems to work ok. It are the quotes that make trouble when trying to share a new bookmark.
I can't figure out how the $title is put into the Page title field with the modified quote.

**Comment by benwerd** [comment]
This should be fixed in the latest Known code, and will be in the next
release.

On Thu, Jun 25, 2015 at 7:50 AM, Daniel nix <notifications@github.com>
wrote:

> for accents and umlaut it seems to work ok. It are the quotes that make
> trouble when trying to share a new bookmark.
> I can't figure out how the $title is put into the Page title field with
> the modified quote.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/928#issuecomment-115282521>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by danito** [comment]
Seems to be fixed now. Don't forget to update the bookmarklet.

**Comment by danito** [comment]
to quick. Quotes are still not re-encoded.
