### ISSUE TITLE
Posts not displaying

### ISSUE THREAD

**Issue by davidmead** [idno/Known#929]
I've noticed recently some of my newer posts aren't showing up in the main timeline. Even after I've done a hard refresh, or logged completely out.

Here's the last post that shows when logged out, and when viewing the site in incognito mode...

![screen shot 2015-06-10 at 10 33 02 am](https://cloud.githubusercontent.com/assets/1266930/8085159/ac016842-0f5c-11e5-9d74-c4476ff90fe4.png)
![screen shot 2015-06-10 at 10 33 20 am](https://cloud.githubusercontent.com/assets/1266930/8085160/af645a80-0f5c-11e5-905d-6065634e1786.png)

But I actually posted more after that one. Those posts are accessible by following syndicated links from Twitter...

[http://blog.davidjohnmead.com/2015/have-you-tried-using-ifttt-with-amazonecho-yet-aaronpk-its](http://blog.davidjohnmead.com/2015/have-you-tried-using-ifttt-with-amazonecho-yet-aaronpk-its)
![screen shot 2015-06-10 at 10 34 06 am](https://cloud.githubusercontent.com/assets/1266930/8085209/eed8d22c-0f5c-11e5-91ba-8e7fde2231d3.png)

And if I click on the blog name in the top left, it takes me back to the top screenshot where that post isn't present. Clicking on the [profile link](http://blog.davidjohnmead.com/profile/davidmead) (whilst logged in) does show the posts.

Thoughts?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/929" class="u-in-reply-to"></a>In the later releases regular status messages and replies were split into two separate classes (so if you were a chatty user, these don't fill your timeline).

I notice you're using filtered content on your homepage. You will probably need to go into your homepage settings and enable the replies type, if you want them to appear on your front page.

**Comment by davidmead** [comment]
I didn't know that. Thanks @mapkyca :-)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/929" class="u-in-reply-to"></a>HTH :)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/929" class="u-in-reply-to"></a>@benwerd Can close...
