### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by davidmead** [idno/Known#930]
Don't seem to be able to generate an export file anymore.

Went to 'site config' -> 'export' and clicked the button. Saw the usual "come back later" message, but when I did it had reverted to it's click to export status.

Never got email notification that it ended.

Looked in the error log and found...

`[Wed Jun 10 07:45:16 2015] [error] [client 98.103.29.2] Premature end of script headers: php-latest, referer: http://blog.davidjohnmead.com/admin/export/`

Before that were several messages concerning different image files...

`...DEBUG - Couldn't get bytes from http://blog.davidjohnmead.com/file/345a5f354fcc5e7970e5e5e2f06cc179/igj6n1Jl.jpg...`

Any ideas?

**Comment by benwerd** [comment]
This sounds server-related, but we did just add some new export code. It may be worth trying again.

**Comment by davidmead** [comment]
I'll pull today and see if that makes a difference @benwerd.

**Comment by davidmead** [comment]
So now I get this error...

`Ooops! PharException
phar zip flush of "/var/tmp/blog_davidjohnmead_com.zip" failed: unable to write local file header of file "entities.json" to zip-based phar "/var/tmp/blog_davidjohnmead_com.zip"`

![screen shot 2015-06-15 at 3 39 30 pm](https://cloud.githubusercontent.com/assets/1266930/8169009/bdf2126a-1374-11e5-97e5-1399ea208e53.png)

**Comment by benwerd** [comment]
Sounds like your web server doesn't have permission to write to the
temporary folder. Interesting.

On Mon, Jun 15, 2015 at 12:39 PM, David Mead <notifications@github.com>
wrote:

> So now I get this error...
>
> Ooops! PharException
> phar zip flush of "/var/tmp/blog_davidjohnmead_com.zip" failed: unable to
> write local file header of file "entities.json" to zip-based phar
> "/var/tmp/blog_davidjohnmead_com.zip"
>
> [image: screen shot 2015-06-15 at 3 39 30 pm]
> <https://cloud.githubusercontent.com/assets/1266930/8169009/bdf2126a-1374-11e5-97e5-1399ea208e53.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/930#issuecomment-112183376>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by davidmead** [comment]
Hmm. I have been able to export in the past.  I'll reach out to Media Temple and see if anything changed on that end, though I hadn't heard of anything.

**Comment by misuba** [comment]
I'm having this problem as well. Any news?

**Comment by davidmead** [comment]
@misuba I pulled the latest down from GitHub yesterday and the export function seems to be working for me now. 

Now, I also looked at my host's (Media Temple) documentation and made a path change to the `uploadpath` in the `config.ini` file as well.

May have been a combo of the two.

**Comment by kylewm** [comment]
Sounds like this was resolved. Feel free to open if I misunderstood!
