### ISSUE TITLE
#hashtags starting with numbers are ignored

### ISSUE THREAD

**Issue by danito** [idno/Known#931]
When I tweet about our city, I often use the #1191be (our city's zip code), but Known seems to ignore this hashtag.
Example : http://nxd4n.nixekinder.be/2015/le-petit-train-vapeur-de-forest

**Comment by benwerd** [comment]
Unfortunately #1191be is also an HTML color code, and we explicitly don't convert those to hashtags so that people can paste HTML. We could probably look at being smarter about how to filter those.

**Comment by danito** [comment]
good point. Maybe something like ##... could force a hashtag to normally ignored sentence. Also tags are ended at a dash or a underscore, with ##under_score I could have a tag "under_score".

**Comment by markwaters** [comment]
I have noticed that #hashtags with a - (minus) or _ (underscore) are chopped , everything after these characters is not included , a problem in France for names like #marie-laure and vertueil-sur-charente

**Comment by kylewm** [comment]
Just a little slapdash research: Twitter recognizes underscore (#hash_tag) but not dash (#hash-tag).

It also recognizes tags that start with a number, as long as there is a letter somewhere in there (#123abc but not #123456)

**Comment by schiesbn** [comment]
It also ignores hashtags starting with German umlauts like 'Ä', 'Ü', 'Ö', something we can do about it?

**Comment by benwerd** [comment]
The latest code shouldn't be ignoring umlauts - just ran a successful test on my end.

**Comment by schiesbn** [comment]
@benwerd great, thanks a lot!
