### ISSUE TITLE
local development and some ideas

### ISSUE THREAD

**Issue by filtercake** [idno/Known#932]
Hey there.

so i have been trying known more actively for the past two weeks and I love it – so first of all THX A LOT for all the work you put into it! Being able to post pictures directly from the phone is the exact functionality I am missing from my Jekyll site.

I am a UX/Ix Designer and also doing UI development "good enough" for production. I would like to work on some ideas for Known and propose a PR here and there. The thing is that after staring at the dev docs I have zero idea how to get it running locally – I am not a dev.

Could somebody do some remote pairing until I have Known running? I really don't care if it runs Mongo or SQL, Docker or Vagrant or rkt or whatever. I need to see it at localhost so I can work and I need a one-command alias to get it up.

I would like to contribute back then a more step-by-step install tutorial for other Mac-based designers if possible.

The things I have on my list so far:

- enhance behaviour when added-to-homescreen
- make posting pictures to twitter post the link of the post, while still retaining a preview image (afaik that is going under "twitter cards" – but will not investigate further until there is chance to commit working code). Currently, a direct link to the image is posted to twitter, which makes reaching the post on the host known page impossible.

Cheers,
Fabian

**Comment by physcocode** [comment]
@filtercake  the best thing you can do it is download MAMP or AMPPS server for your mac and download the latest version of known from withknown.com after that just copy paste the content to www directory . you can now run localhost and rest of setup is very easy !

**Comment by filtercake** [comment]
@physcocode thx!! got it working and took [some notes](https://gist.github.com/filtercake/b6b4e9e2bb6fbbdc3e9f).

> rest of setup is very easy

nope, it wasn't :) will try to make a step by step guide later...

**Comment by benwerd** [comment]
Oof - I'm sorry to hear it wasn't easy. I'd love to read your notes.

**Comment by filtercake** [comment]
@benwerd no worries, see how it goes here https://gist.github.com/filtercake/b6b4e9e2bb6fbbdc3e9f and feel free to make suggestions!

**Comment by physcocode** [comment]
@benwerd the notes seems like setup of mamp and has nothing to do with known.

**Comment by filtercake** [comment]
@physcocode 

> the notes seems like setup of mamp and has nothing to do with known.

My point of view is: everything I need to do to run Known locally has to do with Known. "Not our problem" is not helpful to anybody who wants to contribute.

Not sure of course if contribution is Known's priority :)

**Comment by physcocode** [comment]
@filtercake i am sorry baut that ! @benwerd would decide where it should be included in the doc 
You can feel free to mail me at pranjaltech10@gmail.co if you encounter difficulty  while working locally you can even ping me at hangout !

**Comment by benwerd** [comment]
@filtercake It absolutely is our priority!

I think this is important. Getting a local development environment up and running is a pain - particularly if you're not a developer. I actually spent a good deal of time getting an environment set up on @erinjo's machine for this purpose.

Thank you for putting together these notes :) We're putting together some friendly guides at https://withknown.com/guides/ and I think this could fit well in that context.

**Comment by filtercake** [comment]
the guides look awesome!

I realized it's not necessary to create a new database. the default `mysql`/`root:root` works fine, it's just about letting people know that these are existing MAMP defaults Known can use. That leaves only setting default ports and pointing htdocs to the local Known checkout.

Related: What about maybe adding `.htaccess` to `.gitignore`? Currently the .htaccess changes produce a dirty git index. Needed changes to `.htaccess` could still be force-added.

**Comment by benwerd** [comment]
I think there's a lot of scope for that. The only thing is to make sure people copy the distribution version on installation - but actually, this would allow us to more easily automatically select the correct one according to Apache version.

**Comment by physcocode** [comment]
@filtercake just wrote this article http://www.wikihow.com/Setup-PHP-Development-Environment you should leave suggestions

**Comment by filtercake** [comment]
@physcocode cool thing! am just unsure about who intended audience is. who did you have in mind?

**Comment by physcocode** [comment]
@filtercake for anyone starting out with php or for any ui designer who wants to setup his own php devlopment environment..

**Comment by filtercake** [comment]
Guess I got together everything for the step-by-step guide: https://github.com/filtercake/orga/issues/46

@physcocode ah, I see, thx! :)
