### ISSUE TITLE
(selfhosted) known on Firefox 38 Ubuntu Linux

### ISSUE THREAD

**Issue by danito** [idno/Known#938]
Strange behaviour on my linux laptop (1280x800), Known displays like on a mobile device, having a hamburger menu in the title bar.

**Comment by benwerd** [comment]
Which browser?

**Comment by kylewm** [comment]
@benwerd it's in the title, silly

**Comment by benwerd** [comment]
@kylewm @danito Oops. It is. I'm going to refill my coffee, and then I'll take a look. That _is_ weird.

**Comment by kylewm** [comment]
@danito I'm running Firefox on Ubuntu too (1366x768), but I have to resize the window down to about 1000 px before it collapses the navbar. I wonder if you have a different DPI setting than me... what's the output of `xdpyinfo | grep dots`?

**Comment by danito** [comment]
silly me.
I'd zoomed in (probably with ctrl+trackpad). And it seems that FF keeps zoom level settings for same site even after a restart...
