### ISSUE TITLE
webmention without backlinks

### ISSUE THREAD

**Issue by danito** [idno/Known#939]
If I understand well, Bridgy/mf2 can add webmention to posts without a backlink as long that the complete h-entry is present on your homepage.
Could then the backlink be an option so that for quick status pushed to twitter we don't lose more characters with the url?

**Comment by kylewm** [comment]
on Site Configuration, turn off "Include Permalinks"

**Comment by danito** [comment]
Thanks, I found this, but I would like it to be config  per post.

**Comment by benwerd** [comment]
We're probably not going to add this as a per-post setting in core. Sounds like it could be an interesting plugin though?

**Comment by physcocode** [comment]
Or you can rather just turn it on or off before posting this way you can use it per post !

**Comment by danito** [comment]
is there a way to modify (addEventHook) just before a post is syndicated by adding the url before sending it to Twitter/FB... ?

**Comment by kylewm** [comment]
@danito why are you thinking you'd want to turn this on and off for different posts? It's not something I've heard anyone else in the indieweb community mention, so I'm wondering what the use case is, and whether it could be addressed in a different way

**Comment by danito** [comment]
In the case you make a reply to a site which you want also syndicate to twitter, if you have less than 140 char Known wont add the link and you will lose a bit of context.  so I want to be able to toggle this (and evetually replace this lnik by a personal url shortener)

**Comment by benwerd** [comment]
@danito Closing this here, but yes - you can hook into the 'syndicate' event.
