### ISSUE TITLE
hamburger menu is invisible

### ISSUE THREAD

**Issue by filtercake** [idno/Known#940]
![image](https://cloud.githubusercontent.com/assets/170145/8206654/d0ad8654-14fb-11e5-83f6-9d368d4c5cd7.png)

it's coming from the icon regex selector – if I turn that off, the menu looks right:

![image](https://cloud.githubusercontent.com/assets/170145/8206753/959751ca-14fc-11e5-8bac-d3733de6911a.png)

is that the expected look?

**Comment by kylewm** [comment]
It looks like this code was removed a couple days ago https://github.com/idno/Known/commit/02e81ba36eca99d2fddb2f396834776140f84c7e#diff-0f4d11f37f11d4c01d957b66708faaf5

Give it a pull! :)
