### ISSUE TITLE
Posting to multiple Known sites at the same time

### ISSUE THREAD

**Issue by herbsmn** [idno/Known#944]
Is it already possible to syndicate a post from one Known site to another Known site? If so, is there documentation for this somewhere? I have a personal Known site and one for my organization and when posting content that I'd like to have on both sites it'd be swell if I could make one post and have it syndicate to both of my self hosted Known sites. I'm assuming the same feature would be beneficial for students in a class who want to post their homework assignments to their own Known website as well as the class Known site. I'm sorry if this has already been discussed in another issue or elsewhere online. I tried finding information about it before making this post but perhaps I'm not aware of the correct vocabulary that describes this sort of feature.
##

**Comment by benwerd** [comment]
This is in process. Right now it's a part of the campus offering that we sell, but we're devolving it down to the core open source code. It'll land soon.

**Comment by herbsmn** [comment]
Great! This is extremely exciting news. Thanks for the update and extremely fast response. You guys are spectacular.

**Comment by jonto** [comment]
Thanks for the update. I've been waiting for Known to Know syndication as well. More specifically, will it be possible to syndicate between self hosted and hosted Known sites? I have one self hosted account and one Pro account. Thanks!!

**Comment by benwerd** [comment]
Yep.

**Comment by mapkyca** [comment]
Have a look at : https://github.com/mapkyca/KnownKnown

**Comment by herbsmn** [comment]
Sweet! Thanks for the heads up!

**Comment by mapkyca** [comment]
Closing, handled by plugin
