### ISSUE TITLE
Plugin that allows users to license all content.

### ISSUE THREAD

**Issue by herbsmn** [idno/Known#947]
I know that this has already been discussed on Twitter and elsewhere, but I just wanted to add this to the GitHub issues list since I didn't see it here already. People are already implimenting this by placing the licensing language in the footer section, but it'd be swell to have a proper plugin to add a Creative Commons license for all content on a user's Known site.

https://twitter.com/benwerd/status/505779791287427072

https://twitter.com/withknown/status/592789042888081408

**Comment by benwerd** [comment]
+1 to this.

**Comment by buzzworkers** [comment]
great idea !

**Comment by benwerd** [comment]
I'm going to close this as a core issue for now, but this doesn't negate its value as an idea.
