### ISSUE TITLE
Embeded youtube videos on post

### ISSUE THREAD

**Issue by danito** [idno/Known#948]
On a post, if you have more than YT links, they aren't embedded. 
Is this by design as a workaround would be to use the embed code?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/948" class="u-in-reply-to"></a>Not entirely sure what you mean... are you talking about embedding multiple youtube links, or links from other video services, or...?

**Comment by danito** [comment]
When pasting a YT/Vimeo/... link in a Status, the embed code is added automatically. 
When pasting a YT/Vimeo link in a Post it keeps the url as is, but you can use the embed code from their site if you still want the movie to be embedded.
I thought that a Post with with only one YT link the embed code would be added but I made a status update and not a Post.
See also http://stream.withknown.com/2015/nxd4n-if-you-include-a-link-to-a-youtube-video
