### ISSUE TITLE
Admin form for adding users directly

### ISSUE THREAD

**Issue by misuba** [idno/Known#949]
I serve a multi-user Known instance from a box on which I have no current interest in installing or running a mailer. My various attempts at configuring the server to use a mailer on some other box failed (I didn't try very hard, I admit). As a result, I've had to hack a way of directly creating User objects (short-circuiting the invitation process) into the User Admin page. Would there be any interest in adding this?
##

**Comment by benwerd** [comment]
Yep, makes sense. Similarly, the admin ability to change a user's password would probably be good, too.

**Comment by physcocode** [comment]
@benwerd i am intrested in working on this

**Comment by misuba** [comment]
I have a PR mostly ready for this but it doesn't include password editing.

**Comment by benwerd** [comment]
Oh wow! I wouldn't worry about holding it back for password editing. Thank you for writing it!

**Comment by misuba** [comment]
Looks like my PR is against bootstrap3, not master. What's the plan on merging those?

**Comment by benwerd** [comment]
bootstrap3 is actually fully merged in, but I haven't deleted it yet, which is my omission. Sorry about that.

**Comment by misuba** [comment]
Huh. Something else has gone funny, then. I can hopefully patch it up in the next day or so.

**Comment by mapkyca** [comment]
Looks like this has been handled by a PR
