### ISSUE TITLE
Work out some way to triage these issues

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#956]
Many are old, can be closed, etc...

**Comment by herbsmn** [comment]
It'd be more of a summer clean, but +1 on this idea.

**Comment by benwerd** [comment]
Working on it :) Please join me!

**Comment by mapkyca** [comment]
Can close off mine, but obvs. I can't moderate others!

**Comment by mapkyca** [comment]
Bumping again, since things are growing. If there's a way to grant moderator access to a repo / move comments to a coment repo I'm happy to help out.

**Comment by mapkyca** [comment]
Bump

**Comment by mapkyca** [comment]
Bumping again, issue list is getting a little crazy again...

**Comment by mapkyca** [comment]
Rewording the title, since the main problem is that @benwerd is forced to go through the list and close things off...

Unfortunately github's issue management features aren't great. For example, it's not possible to nominate folk as moderators, without giving them full write access to the repo (not great).

Some folk have handled this by setting up a separate issue-only repo which has no code, could this be worth considering?

Is it possible to enable folk to tag issues so we could create a 'close candidate' tag, so at the least Ben has a definitive list to work through.

Any other thoughts?

**Comment by kylewm** [comment]
Hmm, kind of a hack, but we could tag posts as candidates for closure by referencing this issue (#956). Then I think you'd see a list of issues below here that would turn red when closed.

> Unfortunately github's issue management features aren't great.

I find this annoying too, but you could e.g. give trusted people collaborator access but just make it clear if you don't want them to merge PR's or push to master. Of course "git push origin master" almost types itself, so it's easy to screw up if you aren't careful (maybe a good idea to rename the remote "upstream" or something else in that case)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/956" class="u-in-reply-to"></a>I can't speak officially, but I think there may be some irritating organisational structure issues in play, which is why the trusted collaborator approach hasn't been taken already.

The #956 might be a good stopgap... at least it'll give @benwerd a single place to look...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/956#issuecomment-177862272" class="u-in-reply-to"></a>Of course, the downside of using the #956 approach is I don't think it's possible to *undo* a delete candidate post... i.e. someone tags an issue, but @benwerd decides to not close it, or indeed if something is re-opened, it won't be able to be delete candidated again...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/956" class="u-in-reply-to"></a>I suspect the "trusted collaborator" approach might be the least worst approach... pushing to the main repo by accident shouldn't really be a problem since everyone is (or at least should be) working off their own forks anyway, and it'd be easy enough to revert anything accidentally committed.

As mentioned above, I suspect there are annoying legal / company structure issues preventing this, which is why it hasn't already been done, since it is by far the most obvious solution. I can't comment on this of course.

**Comment by kylewm** [comment]
> Of course, the downside of using the #956 approach is I don't think it's possible to undo a delete candidate post

ick, you're right. I deleted the comment referencing this issue, but the reference remains. In that case I think it's better to just keep a list somewhere off Github ... how about: http://etherpad.indiewebcamp.com/known-issue-tracking ... that might even be better because you can give some context to why you think an issue should be closed.

FWIW: I looked at HuBoard and waffle.io last night. They both let you drag issues around to organize them in categories like [backlog, ready, in-progress, review, complete]. BUT it looks like they don't workaround the permissions issues ... i.e. still only collaborators can tag issues. (I was hoping that the project admin could grant other users permission to tag issues using the admin's API credentials)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/956#issuecomment-178048885" class="u-in-reply-to"></a>I know that some other projects have worked around this by having a dummy project with no code in the repo, and do all issue tracking there... but that's hardly a solution since you can guarantee folk are going to report against the main repo, so that just means Ben's time is going to be spent moving and closing tickets.

**Comment by kylewm** [comment]
Yeah, that's Github's recommended solution even! Like you said I can't see that working out :)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/956#issuecomment-178051701" class="u-in-reply-to"></a>Hmm... I don't think I'd call that a "solution", and it's certainly not something I'd recommend...

**Comment by mapkyca** [comment]
Closing, as we have a solution of sorts ;)
