### ISSUE TITLE
Plugin list

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#957]
It's been suggested before, but it'd be handy to have a list of community plugins. People are starting to reinvent the wheel...

**Comment by benwerd** [comment]
Yes. Agree. In fact, I think it's time to stop worrying about creating
something perfect, and just get something up and running.

On Thu, Jul 2, 2015 at 10:45 AM, Marcus Povey <notifications@github.com>
wrote:

> It's been suggested before, but it'd be handy to have a list of community
> plugins. People are starting to reinvent the wheel...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/957>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Perfection comes later when there's time :)

**Comment by benwerd** [comment]
This is now present in the docs. Send PRs with plugins!
