### ISSUE TITLE
Automatically Put Cursor in Username Input Field on Sign In page.

### ISSUE THREAD

**Issue by herbsmn** [idno/Known#958]
I don't know of any unintended drawbacks that this might cause, but it'd be slick if the cursor automatically was placed in the "username / email address" field on the "Sign In" page. I'm always striving to reduce as many clicks as possible in my routine workflow and this would get rid of one of them.

**Comment by mapkyca** [comment]
It might be desirable to give focus to the first non toolbar form element in a page, for example when clicking on a post icon it might be handy to position the cursor inside the edit form (share already does this)
