### ISSUE TITLE
No ability to retry database connection on install.

### ISSUE THREAD

**Issue by tyson-nw** [idno/Known#963]
My install errored when I did not give it accurate database credentials.  Now I can't even go back and retry.  I can delete my config.ini and start again, but a way to back up and retry while doing the initial config would be useful.
##

**Comment by benwerd** [comment]
+1 to this.

On Mon, Jul 13, 2015 at 2:49 PM, Tyson of the Northwest <
notifications@github.com> wrote:

> My install errored when I did not give it accurate database credentials.
> Now I can't even go back and retry. I can delete my config.ini and start
> again, but a way to back up and retry while doing the initial config would
> be useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/963>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
#1050 might help, so after config save ping the endpoint and see if you get a 200 back before proceeding.

**Comment by mapkyca** [comment]
This still an issue? Pretty sure db credentials are checked these days...
