### ISSUE TITLE
RSS feeds?

### ISSUE THREAD

**Issue by schiesbn** [idno/Known#971]
I wonder if Known could replace my Weblog. Therefor I would need to generate RSS feeds for different content streams because my weblog is syndicated on various planets. Is this already possible or is it planed to add RSS/Atom feed to Known?

**Comment by benwerd** [comment]
Known has full RSS feeds, which should be auto-discoverable by feed readers.

You can add ?_t=rss to the end of any Known URL to get the RSS feed of that
page. This includes searches and filter pages.

On Thu, Jul 16, 2015 at 3:52 PM, Björn Schießle <notifications@github.com>
wrote:

> I wonder if Known could replace my Weblog. Therefor I would need to
> generate RSS feeds for different content streams because my weblog is
> syndicated on various planets. Is this already possible or is it planed to
> add RSS/Atom feed to Known?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/971>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by schiesbn** [comment]
Thanks, that's everything I looked for :smile:
