### ISSUE TITLE
Image Uploading is Broken

### ISSUE THREAD

**Issue by johnellison** [idno/Known#973]
I've just setup a self-hosted Known blog on Digital Ocean, and I can't seem to get image uploads to work. When I select a profile image it just appears blank, and when I try and post a photo it gives me the error 'image wasn't attached' (even though it was and I saw a preview).

I have gone through the secure server setup tutorials on Digital Ocean and have setup a basic firewall.

This is my basic server setup:

- Ubuntu 14.04
- Apache 2.4.7

I got all the requirements green-lighted during setup. I've installed a third party SSL certificate which has been verified and is working properly [http://90days.john-ellison.com](90days.john-ellison.com).

Still though I have this bizarre situation of not being able to upload images. I have given group write permission to the Uploads folder (775) yet there are no files in the folder...

Any thoughts would be greatly appreciated.

**Comment by benwerd** [comment]
First thing to check: is the uploads directory specified in config.ini the
full path?

Also, is there anything in your error log (and does your server have gd
installed)?

On Friday, July 17, 2015, John Ellison <notifications@github.com> wrote:

> I've just setup a self-hosted Known blog on Digital Ocean, and I can't
> seem to get image uploads to work. When I select a profile image it just
> appears blank, and when I try and post a photo it gives me the error 'image
> wasn't attached' (even though it was and I saw a preview).
>
> I have gone through the secure server setup tutorials on Digital Ocean and
> have setup a basic firewall.
>
> This is my basic server setup:
>
>    - Ubuntu 14.04
>    - Apache 2.4.7
>
> I got all the requirements green-lighted during setup. I've installed a
> third party SSL certificate which has been verified and is working properly
> http://90days.john-ellison.com.
>
> Still though I have this bizarre situation of not being able to upload
> images. I have given group write permission to the Uploads folder (yet
> there are no files in the folder...)
>
> Any thoughts would be greatly appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/973>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/973" class="u-in-reply-to"></a>Check ownership of the upload dir as well... 775 gives write to user & group, but oftentimes the upload user is not the same as the web server user.

Make sure the Upload directory is owned by the web server user (usually www-data)

**Comment by johnellison** [comment]
@mapkyca — it was owned by my user, not the www-data user. As soon as I ran `chown www-data Uploads` I had my image uploads working... Thanks a bunch. 

I'll create a PR for my Digital Ocean guide on Monday.
