### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#976]
Create a FAQ, populate with things like #973

**Comment by chrisaldrich** [comment]
And presumably https://github.com/idno/Known/issues/971:
>Add ?_t=rss to the end of any Known URL to get the RSS feed of that page. This includes searches and filter pages.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/976#issuecomment-124327482" class="u-in-reply-to"></a>Indeed :)

**Comment by benwerd** [comment]
A comprehensive "getting started" guide is in the works courtesy of @erinjo, which will take in a lot of this, in a more structured way than a FAQ.

**Comment by mapkyca** [comment]
^^^ like
