### ISSUE TITLE
Mongo and Mysql data sources have inconsistent behaviour

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#978]
getAnyRecord return Array in mongo, completed PHP object of correct class in MySQL

**Comment by benwerd** [comment]
This is odd. By my reading, MySQL getRecord should also return an array - it's just a wrapped call to PDO, with associative array specified. Could the issue have been something else?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/978#issuecomment-125421355" class="u-in-reply-to"></a>Check out the dataconcierge test class for an example of what I mean (had to put in an exception to handle it).

Also, for Mongo, getID returns an object which must be explicitly cast into a string to get a string value.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/978" class="u-in-reply-to"></a>Looking again I think I was wrong about getRecord, but getAnyRecord is definitely inconsistent:

On Mysql (and sqlite which reuses a lot of code), getAnyRecord passes the pdo row through rowToEntity. Mongo returns findOne, which returns an array.

**Comment by kylewm** [comment]
There are two issues:

**Comment by kylewm** [comment]
(Thank goodness for unit tests)

Started trying to fix this and discovered DataConcierge::getRecordByUUID, getRecords, getAnyRecord return exactly the array that was saved in saveRecord. MySQL::getRecord gets the columns of the DB instead. The array that was saved in saveArray is encoded as json in the 'contents' field:

```
array (size=7)
  'uuid' => string 'http://known.dev/profile/kylewm' (length=31)
  '_id' => string 'fad2bc72f24adfd7c8ade05cbe2d681c' (length=32)
  'owner' => string '' (length=0)
  'entity_subtype' => string 'Idno\Entities\User' (length=18)
  'created' => string '2016-01-29 18:27:46' (length=19)
  'contents' => string '{"access":"PUBLIC","owner":"","email":"kyle@kylewm.com",... (length=821)
  'search' => string 'kyle kylewm  ' (length=13)
```

I'd like to change these methods in MySQL (and friends) to return the same array DataConcierge returns. The cool thing there is I think I could get rid of their implementations of rowToEntity and just use the one in DataConcierge.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/978#issuecomment-180165232" class="u-in-reply-to"></a>That's why I wrote the unit tests ;)

The DataConcierge tests have saved my butt several times already...
