### ISSUE TITLE
upgrade last version failed

### ISSUE THREAD

**Issue by jpcaruana** [idno/Known#979]
Hi,

I tried to update my self hosted known installation, following this guide: http://docs.withknown.com/en/latest/install/upgrade/ 

Since then, the only working page is "/" : every other page leads to a 404 error (detail of a post, settings page, site configuration page...)

here is some apache log:

````
[22/Jul/2015:15:45:42 +0200] "GET /account/settings/ HTTP/1.1" 404 5299 "-" "user agent"
...
[22/Jul/2015:15:45:43 +0200] "GET /index.php/account/css/defaultb3.css?20150123 HTTP/1.1" 404 5321 "http://xxx.xxx.xxx/account/settings/" "user agent"
````

I rolled back to the previous version and it is working again.

What's wrong with my update ?

**Comment by benwerd** [comment]
When you say a 404 page, do you mean a server-provided one, or the Known page that it can't find the content?

Is there anything in your error log?

**Comment by jpcaruana** [comment]
the one that says "Ruh roh" (but broken since it can't find css)

I provided typical error logs from apache - what do you need exactly ? (I thought this would be what you need to understand the issue, so I am asking :) )

**Comment by benwerd** [comment]
Those look like _access_ log entries - the error logs are usually found in a different file.

My suspicion is that your Apache configuration doesn't like our new .htaccess rules. It might be worth rolling back to just the .htaccess file from the previous version to see if that fixes your issue.

**Comment by jpcaruana** [comment]
ok : where should I look for the logs ?

**Comment by jpcaruana** [comment]
in the zip file, there was not .htaccess file, so this file didn't change (I checked)

**Comment by benwerd** [comment]
Try renaming the htaccess.dist file to .htaccess.

Your error log _should_ be in a file called something like error.log in your server's logs folder.

**Comment by jpcaruana** [comment]
````bash
sudo cp htaccess-2.4.dist .htaccess 
````

I still have the issue
(I can't find this error file. The apache error log says nothing)

**Comment by jpcaruana** [comment]
````bash
$ sudo locate error.log                                                                                                                                                                                                        
/var/log/apache2/error.log
/var/log/apache2/error.log.1
/var/log/apache2/error.log.10.gz
/var/log/apache2/error.log.11.gz
/var/log/apache2/error.log.12.gz
/var/log/apache2/error.log.13.gz
/var/log/apache2/error.log.14.gz
/var/log/apache2/error.log.15.gz
/var/log/apache2/error.log.16.gz
/var/log/apache2/error.log.17.gz
/var/log/apache2/error.log.18.gz
/var/log/apache2/error.log.19.gz
/var/log/apache2/error.log.2.gz
/var/log/apache2/error.log.20.gz
/var/log/apache2/error.log.21.gz
/var/log/apache2/error.log.22.gz
/var/log/apache2/error.log.23.gz
/var/log/apache2/error.log.24.gz
/var/log/apache2/error.log.25.gz
/var/log/apache2/error.log.26.gz
/var/log/apache2/error.log.27.gz
/var/log/apache2/error.log.28.gz
/var/log/apache2/error.log.29.gz
/var/log/apache2/error.log.3.gz
/var/log/apache2/error.log.30.gz
/var/log/apache2/error.log.31.gz
/var/log/apache2/error.log.32.gz
/var/log/apache2/error.log.33.gz
/var/log/apache2/error.log.34.gz
/var/log/apache2/error.log.35.gz
/var/log/apache2/error.log.36.gz
/var/log/apache2/error.log.37.gz
/var/log/apache2/error.log.38.gz
/var/log/apache2/error.log.39.gz
/var/log/apache2/error.log.4.gz
/var/log/apache2/error.log.40.gz
/var/log/apache2/error.log.41.gz
/var/log/apache2/error.log.42.gz
/var/log/apache2/error.log.43.gz
/var/log/apache2/error.log.44.gz
/var/log/apache2/error.log.45.gz
/var/log/apache2/error.log.46.gz
/var/log/apache2/error.log.47.gz
/var/log/apache2/error.log.48.gz
/var/log/apache2/error.log.49.gz
/var/log/apache2/error.log.5.gz
/var/log/apache2/error.log.50.gz
/var/log/apache2/error.log.51.gz
/var/log/apache2/error.log.52.gz
/var/log/apache2/error.log.6.gz
/var/log/apache2/error.log.7.gz
/var/log/apache2/error.log.8.gz
/var/log/apache2/error.log.9.gz
````

**Comment by kylewm** [comment]
`/var/log/apache2/error.log` is the most recent, then `error.log.1.gz` and so on. if we're lucky the errors happened recently enough that they'll still be in the first file.

you can view the gzipped (archived) logs with zless/zgrep/zcat like you would use the uncompressed file with less/grep/cat.

**Comment by jpcaruana** [comment]
Hi @kylewm,

thanks for the input (I know all of this). It was just to show that the only error.log files on my server were apache's, and there is nothing more in it to help us understand what happens

**Comment by chrisaldrich** [comment]
Without looking at the logs, I seem to remember having a similar issue once upon a time (home page worked, but nothing else did). Double check two quick/hopefully easy things:
Make sure you keep your original "Uploads" folder and keep your config.ini file (or recreate it if necessary. If you recreate it, double check that the path for Uploads is correct. It may automatically default to the proper path name.)

I've written two brief update posts in the past which might be helpful as well. (You may have seen the first one.)
http://stream.boffosocko.com/2015/upgrading-withknown-on-ones-own-server
http://stream.boffosocko.com/2015/updating-withknown-past-077-and-keeping-social-media-integration

**Comment by MarkBeech** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/979" class="u-in-reply-to"></a>I had the same issue with 0.9.3.1, with the default .htaccess I would only get a 500 server error, and with the old file only the home page would work with all other pages returning the Know 404 error, with no errors being reported in the server error logs.

To get my site functioning I mangled the .htaccess file to include the rewrite code from the new file with all the other code from the old one. 

It seems to be working correctly now, but please let me know if I have done something terrible?

**Comment by jpcaruana** [comment]
Once again, I tried to upgrade my self hosted known installation, and I have the same issue: 

- front page is (almost) working 
- all other pages are 404

I kept my .htaccess file and Uploads folder safe

What's wrong ?

On my home page (http://jp.dune.io) , these are the 404 links:

````
jp.dune.io/:109 GET http://jp.dune.io/styles/site/ 
(index):284 GET http://jp.dune.io/file/6062c0ce9e6f9323f5d08ebbd5d03ee7/thumb.jpg 404 (Not Found)
(index):1309 GET http://jp.dune.io/file/071681060dc4940e6c83395e835bdc0a/ebillet.png 404 (Not Found)
(index):523 GET http://jp.dune.io/file/366533e75b5d27915529feed2dcd4eba/CQieGCsWwAAYeyV.png 404 (Not Found)
````

**Comment by kylewm** [comment]
@jpcaruana Did you roll back to the previous version? All those links look good to me right now.

I think .htaccess has changed since the earlier release, maybe try backing up your current .htaccess and replace it with htaccess.dist?

**Comment by jpcaruana** [comment]
yes I rolled back.

my .htaccess is the same as the htaccess.dist

**Comment by chrisaldrich** [comment]
If you haven't found your solution yet, make sure you kept your config.ini file safe too...  I think I had this issue once with the homepage showing, but 404s on all the rest as a result of overwriting it.

For self-hosting updates take a peek at: 
http://stream.boffosocko.com/2015/updating-withknown-past-077-and-keeping-social-media-integration and/or
http://stream.boffosocko.com/2015/upgrading-withknown-on-ones-own-server

**Comment by benwerd** [comment]
Worth saying that we updated the htaccess file again. It may be worth
trying again.

That said, the next monthly update to Known won't be too long from now, so
it may also be worth just waiting for 0.8.6.

On Sun, Nov 8, 2015 at 7:40 PM, Chris Aldrich <notifications@github.com>
wrote:

> If you haven't found your solution yet, make sure you kept your config.ini
> file safe too... I think I had this issue once with the homepage showing,
> but 404s on all the rest as a result of overwriting it.
>
> For self-hosting updates take a peek at:
>
> http://stream.boffosocko.com/2015/updating-withknown-past-077-and-keeping-social-media-integration
> and/or
> http://stream.boffosocko.com/2015/upgrading-withknown-on-ones-own-server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/979#issuecomment-154910788>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
Old, and no reply. Closing.
