### ISSUE TITLE
Editing Profile DESIGN No White Background Cherwell Theme

### ISSUE THREAD

**Issue by harsh5455555** [idno/Known#982]
![screen shot 2015-07-22 at 11 45 26 pm](https://cloud.githubusercontent.com/assets/6641645/8833502/aa83a944-30cc-11e5-8447-fe0e0f9543d0.png)

**Comment by erinjo** [comment]
It looks like you're missing the css file that theme. You may want to grab an update to make sure you have all of the files.  The CSS with the white background is in /Themes/Cherwell/css/default.css

**Comment by benwerd** [comment]
It looks a lot like not all the files were updated. eg, here's mine:

![screen shot 2015-07-22 at 11 31 17 am](https://cloud.githubusercontent.com/assets/624104/8833765/4ac10f72-3065-11e5-867a-805bb1fa070b.png)

**Comment by benwerd** [comment]
@erinjo beat me to it.

**Comment by harsh5455555** [comment]
@erinjo @benwerd I have all the files with me , Then also I will cross-check it once

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/982" class="u-in-reply-to"></a>It's also possible that CSS is being cached somewhere, so try a ctrl-f5

**Comment by benwerd** [comment]
(A hard refresh, anyway - key combination is different on different platforms)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/982" class="u-in-reply-to"></a>ctrl/command/cthulu-f5, whatever chord you have to play to get your browser to clear it's cache ;)

**Comment by benwerd** [comment]
Closing, but do reply if this reoccurs.
