### ISSUE TITLE
Known tries to play a video when posting link to a YouTube channel

### ISSUE THREAD

**Issue by trilliums** [idno/Known#987]
We posted a link to our YouTube channel and I'm assuming some rule in Known says that whenever there is a URL from YouTube that it must be a video, so it pulls up a video viewer. 
<img width="828" alt="screen shot 2015-07-27 at 10 01 18 pm" src="https://cloud.githubusercontent.com/assets/11913216/8922633/1c7a61aa-34ab-11e5-9936-726f710da69d.png">
<img width="849" alt="screen shot 2015-07-27 at 10 01 27 pm" src="https://cloud.githubusercontent.com/assets/11913216/8922634/21696472-34ab-11e5-9bea-a13b569bdb16.png">
Maybe a rule should be changed that says that when the link is YouTube.com/c or YouTube.com/channel Known shouldn't pull up an embedded video player.

**Comment by benwerd** [comment]
Just committed a fix for this and followed your suggestion. Nice catch!
