### ISSUE TITLE
Reorder pages and categories in StaticPages [$50]

### ISSUE THREAD

**Issue by benwerd** [idno/Known#989]
You should be able to re-order pages and categories using drag and drop from the StaticPages admin screen. This should then affect the display of links to these pages in the navigation bar.

**Comment by cleverdevil** [comment]
+1 for this feature! Was just asking about it in IRC today.

**Comment by benwerd** [comment]
Fixed by @enebe-nb! Thank you for your contribution!

**Comment by markwaters** [comment]
How do I reorder static pages ?
I cannot see any controls apart from 'Make Homepage'

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/989" class="u-in-reply-to"></a>You can drag and drop your pages to reorder them on the page management page

**Comment by markwaters** [comment]
Ahhaaa!
Got it!
Thanks @mapkyca , @benwerd and @enebe-nb
