### ISSUE TITLE
wrong webmention source link for bridgy wms

### ISSUE THREAD

**Issue by snarfed** [idno/Known#995]
looks like known is unhappy with bridgy's webmention source mf2 recently? the "on" link for bridgy webmentions now points to the site's own webmention endpoint. native webmentions are still fine. maybe a regression in 0.8?

examples:
* http://stream.withknown.com/2015/how-to-get-rss-feeds-for-your-favorite-services#comments
* https://updates.kip.pe/2015/ihr-so-wir-sind-der-staat-die-so-das-hier#comments
* http://werd.io/2015/an-interesting-perception-is-that-i-sit-and-write-a

**Comment by benwerd** [comment]
Yes. I'm seeing that too, and I don't know what's causing it. Hoping to fix this weekend. Thanks for registering the issue.

**Comment by benwerd** [comment]
Actually, there's a real chance it was fixed on Thursday. withknown.com sites are already updated; I'm updating werd.io to test.

**Comment by benwerd** [comment]
Confirmed fixed! http://werd.io/2015/coffee-rt-to-agree-star-to-agree

**Comment by snarfed** [comment]
awesome, thanks! "already fixed" is definitely my favorite way to triage bugs.
